import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0",STORE="M238";
const s=(v:unknown)=>String(v??"").trim(),up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
const iso=(v:unknown)=>{const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""};
type Tot={qty:number;value:number};type Detail={name:string;article:string;qty:number;value:number};
const SUPPLIERS:Record<string,Array<[string,string,string[]]>>={Hastag:[["KTS","Kate Spade",["KATESPADE","KATE SPADE"]],["MUUM","Mutuall",["MUTUALL","MUTURAL"]],["FLTFT","Flaunt",["FLAUNT"]]],Dino:[["AMN","A.ELEMENTS",["A.ELEMENTS","AELEMENTS"]],["GE4","Gear4",["GEAR4"]],["MOK","MICROPACK",["MICROPACK"]],["MPI","MOPHIE",["MOPHIE"]],["ZAG","ZAAG",["ZAAG","ZAGG"]],["IFG","Ifrog",["IFROG","IFROGZ"]],["VBT","Verbatim",["VERBATIM"]],["AAV","AVANA",["AVANA"]],["INC","INCASE",["INCASE"]],["INP","INCIPIO",["INCIPIO"]],["ITS","ITSKIN",["ITSKIN"]],["RIV","RIVACASE",["RIVACASE"]],["TCA","TUCANO",["TUCANO"]],["UAQ","UAG",["UAG"]],["CRR","Care",["CARE"]]],IGA:[["ADP","ADIDAS",["ADIDAS"]],["ECS","ELEMENCASE",["ELEMENCASE"]],["GSH","GOSH",["GOSH"]],["INT","INTELIAMOR",["INTELIAMOR"]],["LFP","LIFEPROOF",["LIFEPROOF"]],["MDN","Master Dynamic",["MASTER DYNAMIC"]],["NIP","PINIT",["PINIT"]],["OTB","OTTERBOX",["OTTERBOX"]],["RPC","Raptic",["RAPTIC"]],["SD0","Sudio",["SUDIO"]],["ST1","STM",["STM"]],["RSQ","Rollingsquare",["ROLLING SQUARE","ROLLINGSQUARE"]],["ARU","ARC Pulse",["ARC PULSE"]],["RAT","Kratos",["KRATOS"]]],IBacks:[["IBS","Ibacks",["IBACKS"]]],Handal:[["CTU","CASESTUDI",["CASESTUDI"]],["IUV","ILUV",["ILUV"]],["MHO","MACHINO",["MACHINO"]],["UNQ","UNIQ",["UNIQ"]]],Omega:[["LYC","Lycus",["LYCUS"]],["OMZ","Optimuz",["OPTIMUZ"]]],Torras:[["TORRAS","Torras",["TORRAS"]]]};
const fresh=():Tot=>({qty:0,value:0}),add=(t:Tot,q:number,v:number)=>{t.qty+=q;t.value+=v};
function vendorSupplier(vendor:string,brand:string){const v=up(vendor),b=up(brand);if(b.includes("TORRAS")||v.includes("TORRAS"))return"Torras";if(v.includes("HASTAG"))return"Hastag";if(v==="DINO"||v.includes(" DINO"))return"Dino";if(v==="IGA")return"IGA";if(v.includes("IBACKS"))return"IBacks";if(v.includes("HANDAL"))return"Handal";if(v.includes("OMEGA"))return"Omega";return""}
function brandMatch(article:string,brand:string,vendor:string){const supplier=vendorSupplier(vendor,brand);if(!supplier)return null;const a=up(article).replace(/[^A-Z0-9]/g,""),b=up(brand).replace(/[^A-Z0-9]/g,"");for(const[code,name,aliases]of SUPPLIERS[supplier]){if(supplier==="Torras"&&b.includes("TORRAS"))return{supplier,code,name};const c=code.toUpperCase().replace(/[^A-Z0-9]/g,"");if(!a.startsWith(c))continue;const ok=!b||aliases.some(x=>b===x.toUpperCase().replace(/[^A-Z0-9]/g,""));if(ok)return{supplier,code,name}}return null}
function weekOrder(label:string){const m=label.match(/Week\s*(\d+)\s*Q(\d+)/i);return m?Number(m[2])*100+Number(m[1]):-1}
function monthLabel(p:string){if(!/^\d{4}-\d{2}$/.test(p))return p;const[y,m]=p.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(Date.UTC(y,m-1,1)))}
function dateLabel(d:string){if(!d)return"";return new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${d}T00:00:00Z`))}
export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const[rows]=await getSheetRanges(ID,["'Data Copas'!A2:S50000"],email,key);const all=rows.filter(r=>up(r[15])===STORE&&s(r[18])==="2026");const availableWeeks=[...new Set(all.map(r=>s(r[14])).filter(v=>/Week\s*\d+\s*Q\d+/i.test(v)))].sort((a,b)=>weekOrder(a)-weekOrder(b)),availableMonths=[...new Set(all.map(r=>iso(r[0]).slice(0,7)).filter(v=>/^2026-\d{2}$/.test(v)))].sort();const mode=(req.nextUrl.searchParams.get("mode")||"week") as "week"|"month"|"range",requestedWeek=req.nextUrl.searchParams.get("week")||"",week=availableWeeks.includes(requestedWeek)?requestedWeek:(availableWeeks.at(-1)||""),requestedMonth=req.nextUrl.searchParams.get("month")||availableMonths.at(-1)||"2026-09",month=availableMonths.includes(requestedMonth)?requestedMonth:(availableMonths.at(-1)||requestedMonth),from=req.nextUrl.searchParams.get("from")||`${month}-01`,to=req.nextUrl.searchParams.get("to")||`${month}-31`;const selected=all.filter(r=>{if(mode==="week")return s(r[14])===week;const d=iso(r[0]);if(mode==="month")return d.startsWith(month);return d>=from&&d<=to}),periodLabel=mode==="week"?week:mode==="month"?monthLabel(month):`${dateLabel(from)} – ${dateLabel(to)}`;
const map=new Map<string,Map<string,{code:string;name:string;total:Tot;details:Map<string,Detail>;staff:Map<string,Tot>}>>();for(const r of selected){if(up(r[12])!=="ACCESSORIES")continue;const qty=n(r[7]),value=n(r[8]);if(qty===0&&value===0)continue;const article=s(r[4]),desc=s(r[5]),type=s(r[6]),brand=s(r[10]),vendor=s(r[13]),staff=s(r[2])||"Tanpa Nama",hit=brandMatch(article,brand,vendor);if(!hit)continue;if(!map.has(hit.supplier))map.set(hit.supplier,new Map());const brands=map.get(hit.supplier)!,rec=brands.get(hit.code)||{code:hit.code,name:hit.name,total:fresh(),details:new Map<string,Detail>(),staff:new Map<string,Tot>()},keyD=`${article}|${type||desc}`,d=rec.details.get(keyD)||{name:type||desc||article,article,qty:0,value:0};d.qty+=qty;d.value+=value;rec.details.set(keyD,d);add(rec.total,qty,value);const st=rec.staff.get(staff)||fresh();add(st,qty,value);rec.staff.set(staff,st);brands.set(hit.code,rec)}
const suppliers=Object.keys(SUPPLIERS).map(supplier=>{const brands=[...(map.get(supplier)?.values()||[])].map(r=>({code:r.code,name:r.name,qty:r.total.qty,value:r.total.value,details:[...r.details.values()].sort((a,b)=>b.qty-a.qty),staff:r.staff})),staff=new Map<string,Tot>();for(const b of brands)for(const[name,t]of b.staff){const x=staff.get(name)||fresh();add(x,t.qty,t.value);staff.set(name,x)}return{supplier,qty:brands.reduce((a,b)=>a+b.qty,0),value:brands.reduce((a,b)=>a+b.value,0),brands:brands.map(({staff:_,...rest})=>rest),staff:[...staff.entries()].map(([name,t])=>({name,...t})).sort((a,b)=>b.qty-a.qty)}});const total=suppliers.reduce((a,r)=>({qty:a.qty+r.qty,value:a.value+r.value}),fresh());return NextResponse.json({mode,periodLabel,week,month,from,to,availableWeeks,availableMonths,thirdParty:{suppliers,total}},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca Product Fokus 3PP"},{status:500})}}
