import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,clearAndWrite,getSheetRanges} from "@/lib/google-sheets";
import {buildSummaryFromRawValues,upsertDailySummaryRows} from "@/lib/m238-daily-summary-cache";
import {invalidateDailySummaryPeriod} from "@/lib/m238-daily-summary-v4";

const DASHBOARD_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const RAW_SHEET="Raw Salesperson";
const COPAS_SHEET="Data Copas";
const text=(v:unknown)=>String(v??"").trim();
function isoDate(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=text(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);const m=x.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""}
function normalized(v:unknown){if(v===null||v===undefined)return"";if(typeof v==="number")return Number.isFinite(v)?String(v):"";const s=text(v).replace(/\s+/g," "),d=isoDate(s);return d||s.toUpperCase()}
function signature(row:unknown[]){return JSON.stringify(Array.from({length:17},(_,i)=>normalized(row[i])))}function hasData(row:unknown[]){return row.some(v=>text(v)!=="")}function creds(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)throw new Error("Google Sheets belum dikonfigurasi");return{email,key}}
export async function GET(req:NextRequest){try{const invoice=text(req.nextUrl.searchParams.get("invoice"));if(!invoice)return NextResponse.json({error:"No Invoice wajib diisi"},{status:400});const{email,key}=creds(),[helper,noExchange]=await getSheetRanges(DASHBOARD_ID,[`'${RAW_SHEET}'!AB2:AR50000`,`'${RAW_SHEET}'!Y2:Y50000`],email,key),wanted=invoice.toUpperCase(),idx=(helper||[]).findIndex(r=>text(r[3]).toUpperCase()===wanted);if(idx<0)return NextResponse.json({error:"Invoice tidak ditemukan."},{status:404});const row=helper[idx]||[],existing=text(noExchange?.[idx]?.[0]);return NextResponse.json({found:true,rowNumber:idx+2,existingNoExchange:existing,preview:{date:isoDate(row[0]),staffId:text(row[1]),staff:text(row[2]),invoice:text(row[3]),article:text(row[4]),description:text(row[5]),qty:Number(row[7]??0)||0,amount:Number(row[8]??0)||0}},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal mencari invoice"},{status:500})}}
export async function POST(req:NextRequest){try{const body=await req.json(),action=text(body.action),{email,key}=creds();if(action==="cutoff"){const mode=body.mode==="month"?"month":"date",value=text(body.value);if(mode==="date"&&!/^\d{4}-\d{2}-\d{2}$/.test(value))return NextResponse.json({error:"Tanggal cut off tidak valid"},{status:400});if(mode==="month"&&!/^\d{4}-\d{2}$/.test(value))return NextResponse.json({error:"Periode cut off tidak valid"},{status:400});const[source,destination]=await getSheetRanges(DASHBOARD_ID,[`'${RAW_SHEET}'!AB2:AR50000`,`'${COPAS_SHEET}'!A2:Q50000`],email,key),selected=(source||[]).filter(r=>{if(!hasData(r))return false;const d=isoDate(r[0]);return mode==="date"?d===value:d.startsWith(value)}).map(r=>Array.from({length:17},(_,i)=>r[i]??""));if(!selected.length)return NextResponse.json({error:"Tidak ada data RAW Salesperson pada periode yang dipilih."},{status:404});const existing=new Set((destination||[]).filter(hasData).map(signature)),duplicateCount=selected.filter(r=>existing.has(signature(r))).length;if(duplicateCount>0)return NextResponse.json({error:"Cut Off Gagal — data ini sudah pernah tersalin ke Data Copas.",duplicateCount},{status:409});await appendSheetValues(DASHBOARD_ID,`'${COPAS_SHEET}'!A:Q`,selected,email,key);invalidateDailySummaryPeriod(value.slice(0,7));let cacheWarning="";try{const summary=await buildSummaryFromRawValues(selected,{email,key},"CUT_OFF");await upsertDailySummaryRows(summary,{email,key})}catch(error){cacheWarning=error instanceof Error?error.message:"Daily Summary cache gagal diperbarui";console.warn("M238_PERF",{op:"cutoff-summary-cache",error:cacheWarning})}return NextResponse.json({ok:true,rows:selected.length,dailySummaryCache:{ok:!cacheWarning,warning:cacheWarning||null},message:`Cut Off Berhasil — ${selected.length} baris ditambahkan.`})}if(action==="exchange"){const invoice=text(body.invoice),noExchange=text(body.noExchange);if(!invoice||!noExchange)return NextResponse.json({error:"No Invoice dan No Exchange wajib diisi"},{status:400});const[helper,noExchangeCol]=await getSheetRanges(DASHBOARD_ID,[`'${RAW_SHEET}'!AB2:AR50000`,`'${RAW_SHEET}'!Y2:Y50000`],email,key),wanted=invoice.toUpperCase(),idx=(helper||[]).findIndex(r=>text(r[3]).toUpperCase()===wanted);if(idx<0)return NextResponse.json({error:"Invoice tidak ditemukan."},{status:404});if(text(noExchangeCol?.[idx]?.[0]))return NextResponse.json({error:"No Exchange invoice ini sudah terisi."},{status:409});const rowNumber=idx+2;await clearAndWrite(DASHBOARD_ID,null,`'${RAW_SHEET}'!Y${rowNumber}:Y${rowNumber}`,[[noExchange]],email,key,"USER_ENTERED");return NextResponse.json({ok:true,message:"No Exchange berhasil disimpan."})}return NextResponse.json({error:"Action tidak dikenal"},{status:400})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Operasi gagal"},{status:500})}}
