import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SHEET_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
const s=(v:unknown)=>String(v??"").trim();
const up=(v:unknown)=>s(v).toUpperCase();
function iso(v:unknown){const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""}
type Row={date:string;id:string;invoice:string;description:string;type:string;qty:number;amount:number;category:string;brand:string;scheme:string;vendor:string;article:string};
function parse(r:unknown[]):Row{return{date:iso(r[0]),id:s(r[1]),invoice:s(r[3]),article:s(r[4]),description:s(r[5]),type:s(r[6]),qty:n(r[7]),amount:n(r[8]),category:up(r[9]),brand:up(r[10]),scheme:up(r[12]),vendor:up(r[13])}}
function valid(r:Row){return !!(r.id&&r.date)&&r.scheme!=="VOUCHER"&&!up(r.description).includes("VOUCHER")}
function kind(r:Row){const text=`${r.category} ${up(r.type)} ${up(r.description)}`;if(r.scheme==="VAS")return"vas";if(r.scheme==="ACCESSORIES")return"accessories";if(r.scheme==="DEVICES")return"device";if(/IPHONE|IPAD|MAC|APPLE WATCH|AIRPODS/.test(text))return"device";return"other"}
function product(r:Row){if(r.brand!=="APPLE")return"other";if(r.scheme==="ACCESSORIES")return r.category==="AIRPODS"?"airpods":"other";if(r.scheme!=="DEVICES")return"other";if(r.category==="IPHONE")return"iphone";if(r.category==="MAC")return"mac";if(r.category==="IPAD")return"ipad";if(r.category==="APPLE WATCH")return"watch";return"other"}

export async function GET(req:NextRequest){const period=req.nextUrl.searchParams.get("period")||"",staffId=req.nextUrl.searchParams.get("staffId")||"";if(!/^2026-(0[1-9]|1[0-2])$/.test(period)||!staffId)return NextResponse.json({error:"Filter tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({daily:[],accessoriesQty:0});try{const [dateRows]=await getSheetRanges(SHEET_ID,["'Data Copas'!A2:A50000"],email,key),idx:number[]=[];dateRows.forEach((r,i)=>{if(iso(r[0]).startsWith(period))idx.push(i+2)});if(!idx.length)return NextResponse.json({daily:[],accessoriesQty:0});const [raw]=await getSheetRanges(SHEET_ID,[`'Data Copas'!A${idx[0]}:S${idx.at(-1)}`],email,key),rows=raw.map(parse).filter(r=>valid(r)&&r.date.startsWith(period)&&r.id===staffId),[y,m]=period.split("-").map(Number),daysInMonth=new Date(y,m,0).getDate(),accessoriesQty=rows.filter(r=>kind(r)==="accessories").reduce((a,r)=>a+Math.max(0,r.qty),0),daily=Array.from({length:daysInMonth},(_,i)=>{const date=`${period}-${String(i+1).padStart(2,"0")}`,d=rows.filter(r=>r.date===date),invoices=new Set(d.map(r=>r.invoice).filter(Boolean)),sales=d.reduce((a,r)=>a+r.amount,0),qty=d.reduce((a,r)=>a+r.qty,0),device=d.filter(r=>["iphone","mac","ipad","watch"].includes(product(r))).reduce((a,r)=>a+r.qty,0),accessories=d.filter(r=>kind(r)==="accessories").reduce((a,r)=>a+r.amount,0),accessoriesQty=d.filter(r=>kind(r)==="accessories").reduce((a,r)=>a+Math.max(0,r.qty),0),vas=d.filter(r=>kind(r)==="vas").reduce((a,r)=>a+r.amount,0),trx=invoices.size;return{date,sales,trx,device,accessories,accessoriesQty,vas,qty,upt:trx?qty/trx:0,atv:trx?sales/trx:0}});return NextResponse.json({daily,accessoriesQty},{headers:{"Cache-Control":"private, max-age=60"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca detail staff"},{status:500})}}
