import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,clearAndWrite,ensureSheet,getSheetRanges} from "@/lib/google-sheets";

const SHEET_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const TAB="Dashboard Feedback";
const SUMMARY_TAB="Dashboard Feedback Summary";
const HEADERS=["Timestamp","Date","Staff ID","Name","Category","Raw Feedback","Professional Feedback"];
const SUMMARY_HEADERS=["Date","Staff Count","Professional Summary","Last Updated"];
const text=(v:unknown)=>String(v??"").trim();
function isoDate(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=text(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(x)){const[a,b,c]=x.split(/[/-]/);return`${c}-${b.padStart(2,"0")}-${a.padStart(2,"0")}`}return x;}
const labels:{[key:string]:string}={external:"Faktor eksternal",promo:"Promo yang berjalan",bnpl:"BNPL",performance:"Performa staff",stock:"Ketersediaan stok"};
const actions:{[key:string]:string}={external:"Lakukan follow-up terhadap calon pelanggan dan maksimalkan konversi pada setiap interaksi.",promo:"Pastikan seluruh staff menyampaikan promo aktif secara konsisten dan mengaitkannya dengan kebutuhan pelanggan.",bnpl:"Perkuat penawaran BNPL dengan simulasi cicilan yang jelas serta pilihan tenor yang relevan.",performance:"Lakukan coaching terarah dan pantau progres penjualan pada shift berikutnya.",stock:"Koordinasikan pengecekan stok, konsolidasi antar-store, dan tawarkan alternatif produk yang setara."};
function normalize(raw:string){const replacements:Array<[RegExp,string]>=[[/\bcust(?:omer)?\b/gi,"pelanggan"],[/\bhandle\b/gi,"melayani"],[/\b(?:lost|lose)\b/gi,"potensi penjualan yang belum terealisasi"],[/\bacc\b/gi,"aksesori"],[/\btrx\b/gi,"transaksi"],[/\b(?:achv|achive|achieve)\b/gi,"mencapai"],[/\b(?:ga|gak|nggak|blm)\b/gi,"belum"],[/\buda?h?\b/gi,"sudah"],[/\bkarna\b/gi,"karena"],[/\bdri\b/gi,"dari"],[/\bnomer\b/gi,"nomor"],[/\bdimaks?\b/gi,"dimaksimalkan"]];let clean=raw.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,"").replace(/\s+/g," ").trim();for(const[pattern,value]of replacements)clean=clean.replace(pattern,value);clean=clean.replace(/\s+([,.])/g,"$1").replace(/\.{2,}/g,".");return clean?clean.charAt(0).toUpperCase()+clean.slice(1).replace(/[.!?]?$/,"."):"Tidak ada detail tambahan."}
function professional(raw:string,category:string,name:string){return `${labels[category]??"Kondisi penjualan"} — ${name} melaporkan: ${normalize(raw)}`;}
const reasonRules:Array<{pattern:RegExp;reason:string}>=[
 {pattern:/traffic|trafic|sepi|minim.{0,20}(customer|cust|pelanggan)|hanya (lihat|liat)/i,reason:"Traffic dan jumlah pelanggan potensial masih terbatas sehingga peluang transaksi belum maksimal."},
 {pattern:/stok|stock|kosong|tidak tersedia/i,reason:"Ketersediaan beberapa produk atau varian yang dicari pelanggan belum mencukupi."},
 {pattern:/harga|budget|anggaran|mahal/i,reason:"Sebagian pelanggan menunda pembelian karena pertimbangan harga dan keterbatasan anggaran."},
 {pattern:/compare|banding|kompetitor|samsung|ibox/i,reason:"Terdapat pelanggan yang masih membandingkan produk atau penawaran dengan kompetitor."},
 {pattern:/follow.?up|\bfu\b|save kontak|simpan kontak|keep (nomor|nomer)|belum mau|esok|besok|nanti/i,reason:"Beberapa calon pelanggan belum melakukan transaksi dan masih dalam proses follow-up."},
 {pattern:/provider|\bvas\b|qoala|telkomsel|indosat|\bxl\b/i,reason:"Penawaran VAS atau layanan provider belum seluruhnya berhasil dikonversi."},
 {pattern:/bnpl|cicilan|paylater|kredivo|akulaku/i,reason:"Opsi BNPL atau cicilan belum optimal dalam mendorong keputusan pembelian pelanggan."},
 {pattern:/promo|diskon|potongan/i,reason:"Promo yang berjalan belum sepenuhnya mendorong keputusan pembelian pelanggan."},
 {pattern:/aksesori|accessor|\bacc\b|adapter|cable|keyboard/i,reason:"Komposisi transaksi lebih banyak berasal dari aksesori sehingga kontribusi nilai penjualan device terbatas."},
 {pattern:/kasir|operasional|administrasi|back office/i,reason:"Aktivitas operasional membatasi waktu sebagian tim untuk fokus pada proses penjualan."}
];
const fallbackReasons:{[key:string]:string}={external:"Kesiapan pembelian dan kualitas traffic pelanggan belum optimal.",promo:"Promo berjalan belum menghasilkan konversi sesuai potensi.",bnpl:"Penawaran BNPL belum menghasilkan konversi yang optimal.",performance:"Produktivitas penjualan pada shift berjalan belum optimal.",stock:"Ketersediaan produk yang dibutuhkan pelanggan menjadi kendala penjualan."};
function managementReasons(rows:Row[]){const combined=rows.map(row=>row.raw).join(" ");const reasons=reasonRules.filter(rule=>rule.pattern.test(combined)).map(rule=>rule.reason);if(!reasons.length)for(const category of new Set(rows.map(row=>row.category))){const fallback=fallbackReasons[category];if(fallback)reasons.push(fallback)}return[...new Set(reasons)]}
type Row={timestamp:string;date:string;staffId:string;name:string;category:string;raw:string;professional:string};
function mapRows(rows:unknown[][]):Row[]{return rows.map(r=>({timestamp:text(r[0]),date:isoDate(r[1]),staffId:text(r[2]),name:text(r[3]),category:text(r[4]),raw:text(r[5]),professional:text(r[6])})).filter(r=>r.date&&r.staffId)}
function summarize(rows:Row[]){const grouped=new Map<string,Row[]>();for(const r of rows){if(!grouped.has(r.date))grouped.set(r.date,[]);grouped.get(r.date)!.push(r)}return[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>{const unique=[...new Map(list.map(x=>[x.staffId,x])).values()],reasons=managementReasons(unique),categories=[...new Set(unique.map(x=>x.category))],followUps=[...new Set(categories.map(category=>actions[category]).filter(Boolean))].map((action,index)=>`${index+1}. ${action}`);const dateLabel=new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00Z`));const summary=`Reason Kendala Store M238 — ${dateLabel}\n\nKendala utama:\n• ${reasons.join("\n• ")}\n\nTindak lanjut store:\n${followUps.join("\n")}`;return[date,unique.length,summary,new Date().toISOString()]})}
async function syncSummary(all:Row[],email:string,key:string){await ensureSheet(SHEET_ID,SUMMARY_TAB,SUMMARY_HEADERS,email,key);const values=summarize(all);await clearAndWrite(SHEET_ID,`'${SUMMARY_TAB}'!A2:D5000`,`'${SUMMARY_TAB}'!A2`,values.length?values:[["","","",""]],email,key,"RAW")}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[],summary:""});try{await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[raw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),all=mapRows(raw);await syncSummary(all,email,key);const period=req.nextUrl.searchParams.get("period")||"",date=req.nextUrl.searchParams.get("date")||"",rows=all.filter(r=>(!period||r.date.startsWith(period))&&(!date||r.date===date));const unique=[...new Map(rows.map(x=>[`${x.date}:${x.staffId}`,x])).values()].map(r=>({...r,professional:professional(r.raw,r.category,r.name)}));const summary=summarize(unique).find(x=>x[0]===date)?.[2]||"";return NextResponse.json({rows:unique,summary});}catch(e){return NextResponse.json({rows:[],summary:"",error:e instanceof Error?e.message:"Gagal membaca feedback"});}}

export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum tersambung"},{status:500});try{const body=await req.json()as{date?:string;staffId?:string;name?:string;category?:string;feedback?:string};const date=isoDate(body.date),staffId=text(body.staffId),name=text(body.name),category=text(body.category),raw=text(body.feedback);if(!date||!staffId||!name||!category||!raw)return NextResponse.json({error:"Data feedback belum lengkap"},{status:400});await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[existingRaw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),existing=mapRows(existingRaw);if(existing.some(r=>r.date===date&&r.staffId===staffId))return NextResponse.json({error:"Feedback staff ini untuk tanggal tersebut sudah tersimpan dan tidak dapat diisi ulang.",alreadySubmitted:true},{status:409});const polished=professional(raw,category,name),timestamp=new Date().toISOString();await appendSheetValues(SHEET_ID,`'${TAB}'!A:G`,[[timestamp,date,staffId,name,category,raw,polished]],email,key);const saved={timestamp,date,staffId,name,category,raw,professional:polished};await syncSummary([...existing,saved],email,key);return NextResponse.json({ok:true,...saved});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal menyimpan feedback"},{status:500});}}
