import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,clearAndWrite,ensureSheet,getSheetRanges} from "@/lib/google-sheets";

const SHEET_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const TAB="Dashboard Feedback";
const SUMMARY_TAB="Dashboard Feedback Summary";
const HEADERS=["Timestamp","Date","Staff ID","Name","Category","Raw Feedback","Professional Feedback"];
const SUMMARY_HEADERS=["Date","Staff Count","Professional Summary","Last Updated"];
const text=(v:unknown)=>String(v??"").trim();
function isoDate(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=text(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(x)){const[a,b,c]=x.split(/[/-]/);return`${c}-${b.padStart(2,"0")}-${a.padStart(2,"0")}`}return x;}
const labels:{[key:string]:string}={external:"Faktor eksternal",promo:"Promo yang berjalan",performance:"Performa staff",stock:"Ketersediaan stok"};
function professional(raw:string,category:string,name:string){const clean=raw.replace(/\s+/g," ").trim();return `${labels[category]??"Kondisi penjualan"}: berdasarkan feedback ${name}, ${clean.charAt(0).toLowerCase()+clean.slice(1)}.`;}
type Row={timestamp:string;date:string;staffId:string;name:string;category:string;raw:string;professional:string};
function mapRows(rows:unknown[][]):Row[]{return rows.map(r=>({timestamp:text(r[0]),date:isoDate(r[1]),staffId:text(r[2]),name:text(r[3]),category:text(r[4]),raw:text(r[5]),professional:text(r[6])})).filter(r=>r.date&&r.staffId)}
function summarize(rows:Row[]){const grouped=new Map<string,Row[]>();for(const r of rows){if(!grouped.has(r.date))grouped.set(r.date,[]);grouped.get(r.date)!.push(r)}return[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>{const unique=[...new Map(list.map(x=>[x.staffId,x])).values()];const byCategory=new Map<string,Row[]>();for(const r of unique){if(!byCategory.has(r.category))byCategory.set(r.category,[]);byCategory.get(r.category)!.push(r)}const parts=[...byCategory.entries()].map(([cat,items])=>`${labels[cat]??cat}: ${items.map(x=>`${x.name} menyampaikan ${x.raw.replace(/\s+/g," ").trim()}`).join("; ")}.`);const summary=`Secara keseluruhan, terdapat ${unique.length} feedback staff pada ${new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00Z`))}. ${parts.join(" ")} Fokus tindak lanjut diarahkan pada faktor yang paling berpengaruh terhadap pencapaian harian serta peluang perbaikan yang dapat dikendalikan oleh tim store.`;return[date,unique.length,summary,new Date().toISOString()]})}
async function syncSummary(all:Row[],email:string,key:string){await ensureSheet(SHEET_ID,SUMMARY_TAB,SUMMARY_HEADERS,email,key);const values=summarize(all);await clearAndWrite(SHEET_ID,`'${SUMMARY_TAB}'!A2:D5000`,`'${SUMMARY_TAB}'!A2`,values.length?values:[["","","",""]],email,key,"RAW")}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[],summary:""});try{await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[raw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),all=mapRows(raw);await syncSummary(all,email,key);const period=req.nextUrl.searchParams.get("period")||"",date=req.nextUrl.searchParams.get("date")||"",rows=all.filter(r=>(!period||r.date.startsWith(period))&&(!date||r.date===date));const unique=[...new Map(rows.map(x=>[`${x.date}:${x.staffId}`,x])).values()];const summary=summarize(unique).find(x=>x[0]===date)?.[2]||"";return NextResponse.json({rows:unique,summary});}catch(e){return NextResponse.json({rows:[],summary:"",error:e instanceof Error?e.message:"Gagal membaca feedback"});}}

export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum tersambung"},{status:500});try{const body=await req.json()as{date?:string;staffId?:string;name?:string;category?:string;feedback?:string};const date=isoDate(body.date),staffId=text(body.staffId),name=text(body.name),category=text(body.category),raw=text(body.feedback);if(!date||!staffId||!name||!category||!raw)return NextResponse.json({error:"Data feedback belum lengkap"},{status:400});await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[existingRaw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),existing=mapRows(existingRaw);if(existing.some(r=>r.date===date&&r.staffId===staffId))return NextResponse.json({error:"Feedback staff ini untuk tanggal tersebut sudah tersimpan dan tidak dapat diisi ulang.",alreadySubmitted:true},{status:409});const polished=professional(raw,category,name),timestamp=new Date().toISOString();await appendSheetValues(SHEET_ID,`'${TAB}'!A:G`,[[timestamp,date,staffId,name,category,raw,polished]],email,key);const saved={timestamp,date,staffId,name,category,raw,professional:polished};await syncSummary([...existing,saved],email,key);return NextResponse.json({ok:true,...saved});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal menyimpan feedback"},{status:500});}}
