import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,clearAndWrite,ensureSheet,getSheetRanges} from "@/lib/google-sheets";

const SHEET_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const TAB="Dashboard Feedback";
const SUMMARY_TAB="Dashboard Feedback Summary";
const HEADERS=["Timestamp","Date","Staff ID","Name","Category","Raw Feedback","Professional Feedback"];
const SUMMARY_HEADERS=["Date","Staff Count","Professional Summary","Last Updated"];
const text=(v:unknown)=>String(v??"").trim();
function isoDate(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=text(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(x)){const[a,b,c]=x.split(/[/-]/);return`${c}-${b.padStart(2,"0")}-${a.padStart(2,"0")}`}return x;}
const labels:{[key:string]:string}={external:"Faktor eksternal",promo:"Promo yang berjalan",bnpl:"BNPL",performance:"Performa staff",stock:"Ketersediaan stok"};
const actions:{[key:string]:string}={external:"Lakukan follow-up terhadap calon pelanggan dan maksimalkan konversi pada setiap interaksi.",promo:"Pastikan seluruh staff menyampaikan promo aktif secara konsisten dan mengaitkannya dengan kebutuhan pelanggan.",bnpl:"Perkuat penawaran BNPL dengan simulasi cicilan yang jelas serta pilihan tenor yang relevan.",performance:"Lakukan coaching terarah dan pantau progres penjualan pada shift berikutnya.",stock:"Koordinasikan pengecekan stok, konsolidasi antar-store, dan tawarkan alternatif produk yang setara."};
function normalize(raw:string){const replacements:Array<[RegExp,string]>=[[/\bcust(?:omer)?\b/gi,"pelanggan"],[/\bhandle\b/gi,"melayani"],[/\b(?:lost|lose)\b/gi,"potensi penjualan yang belum terealisasi"],[/\bacc\b/gi,"aksesori"],[/\btrx\b/gi,"transaksi"],[/\b(?:achv|achive|achieve)\b/gi,"mencapai"],[/\b(?:ga|gak|nggak|blm)\b/gi,"belum"],[/\buda?h?\b/gi,"sudah"],[/\bkarna\b/gi,"karena"],[/\bdri\b/gi,"dari"],[/\bnomer\b/gi,"nomor"],[/\bdimaks?\b/gi,"dimaksimalkan"]];let clean=raw.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,"").replace(/\s+/g," ").trim();for(const[pattern,value]of replacements)clean=clean.replace(pattern,value);clean=clean.replace(/\s+([,.])/g,"$1").replace(/\.{2,}/g,".");return clean?clean.charAt(0).toUpperCase()+clean.slice(1).replace(/[.!?]?$/,"."):"Tidak ada detail tambahan."}
function professional(raw:string,category:string,name:string){return `${labels[category]??"Kondisi penjualan"} — ${name} melaporkan: ${normalize(raw)}`;}
type Row={timestamp:string;date:string;staffId:string;name:string;category:string;raw:string;professional:string};
function mapRows(rows:unknown[][]):Row[]{return rows.map(r=>({timestamp:text(r[0]),date:isoDate(r[1]),staffId:text(r[2]),name:text(r[3]),category:text(r[4]),raw:text(r[5]),professional:text(r[6])})).filter(r=>r.date&&r.staffId)}
function summarize(rows:Row[]){const grouped=new Map<string,Row[]>();for(const r of rows){if(!grouped.has(r.date))grouped.set(r.date,[]);grouped.get(r.date)!.push(r)}return[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,list])=>{const unique=[...new Map(list.map(x=>[x.staffId,x])).values()];const byCategory=new Map<string,Row[]>();for(const r of unique){if(!byCategory.has(r.category))byCategory.set(r.category,[]);byCategory.get(r.category)!.push(r)}const findings=[...byCategory.entries()].map(([cat,items])=>`• ${labels[cat]??cat}: ${items.map(x=>normalize(x.raw)).join(" ")}`);const followUps=[...new Set([...byCategory.keys()].map(cat=>actions[cat]).filter(Boolean))].map((action,index)=>`${index+1}. ${action}`);const dateLabel=new Intl.DateTimeFormat("id-ID",{dateStyle:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00Z`));const summary=`Ringkasan Feedback M238 — ${dateLabel}\n\nTemuan utama:\n${findings.join("\n")}\n\nPrioritas tindak lanjut:\n${followUps.join("\n")}`;return[date,unique.length,summary,new Date().toISOString()]})}
async function syncSummary(all:Row[],email:string,key:string){await ensureSheet(SHEET_ID,SUMMARY_TAB,SUMMARY_HEADERS,email,key);const values=summarize(all);await clearAndWrite(SHEET_ID,`'${SUMMARY_TAB}'!A2:D5000`,`'${SUMMARY_TAB}'!A2`,values.length?values:[["","","",""]],email,key,"RAW")}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[],summary:""});try{await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[raw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),all=mapRows(raw);await syncSummary(all,email,key);const period=req.nextUrl.searchParams.get("period")||"",date=req.nextUrl.searchParams.get("date")||"",rows=all.filter(r=>(!period||r.date.startsWith(period))&&(!date||r.date===date));const unique=[...new Map(rows.map(x=>[`${x.date}:${x.staffId}`,x])).values()].map(r=>({...r,professional:professional(r.raw,r.category,r.name)}));const summary=summarize(unique).find(x=>x[0]===date)?.[2]||"";return NextResponse.json({rows:unique,summary});}catch(e){return NextResponse.json({rows:[],summary:"",error:e instanceof Error?e.message:"Gagal membaca feedback"});}}

export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum tersambung"},{status:500});try{const body=await req.json()as{date?:string;staffId?:string;name?:string;category?:string;feedback?:string};const date=isoDate(body.date),staffId=text(body.staffId),name=text(body.name),category=text(body.category),raw=text(body.feedback);if(!date||!staffId||!name||!category||!raw)return NextResponse.json({error:"Data feedback belum lengkap"},{status:400});await ensureSheet(SHEET_ID,TAB,HEADERS,email,key);const[existingRaw]=await getSheetRanges(SHEET_ID,[`'${TAB}'!A2:G5000`],email,key),existing=mapRows(existingRaw);if(existing.some(r=>r.date===date&&r.staffId===staffId))return NextResponse.json({error:"Feedback staff ini untuk tanggal tersebut sudah tersimpan dan tidak dapat diisi ulang.",alreadySubmitted:true},{status:409});const polished=professional(raw,category,name),timestamp=new Date().toISOString();await appendSheetValues(SHEET_ID,`'${TAB}'!A:G`,[[timestamp,date,staffId,name,category,raw,polished]],email,key);const saved={timestamp,date,staffId,name,category,raw,professional:polished};await syncSummary([...existing,saved],email,key);return NextResponse.json({ok:true,...saved});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal menyimpan feedback"},{status:500});}}
