import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {createRequire} from "node:module";
import ts from "typescript";
const require=createRequire(import.meta.url);
function load(file){const source=fs.readFileSync(new URL(`../${file}`,import.meta.url),"utf8");const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;const mod={exports:{}};new Function("require","module","exports",code)(require,mod,mod.exports);return mod.exports}
const acc=load("lib/promo-board-accessory.ts");
const XLSX=require("xlsx");
function workbook(rows){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),"Sheet1");const out=XLSX.write(wb,{type:"buffer",bookType:"xlsx"});return out.buffer.slice(out.byteOffset,out.byteOffset+out.byteLength)}
const header=["Brand","SAP Article","Article Mapemall","SAP Description","Category","Reference SRP","Current SRP Cash","Repricing Cash","BR / Zoutn","Remarks"];
test("parses row-5 accessory headers, normalizes SAP and uses repricing as active price",()=>{const rows=[["Update 27 September 2026"],[],[],[],header,["INCASE"," INC 001 ","MAP1","Case iPhone","Case",1000000,900000,799000,"BR","Promo"]];const parsed=acc.parseAccessoryPriceWorkbook(workbook(rows),"acc.xlsx");assert.equal(parsed.priceListDate,"2026-09-27");assert.equal(parsed.totalSku,1);assert.equal(parsed.products[0].sapArticle,"INC001");assert.equal(parsed.products[0].activePrice,799000);assert.equal(parsed.totalBrand,1);assert.equal(parsed.totalCategory,1)});
test("duplicate price refresh keeps latest row but conflicting identity blocks activation",()=>{const rows=[["Update 27 September 2026"],[],[],[],header,["INCASE","INC001","","Case iPhone","Case",1000000,900000,0,"",""],["INCASE","INC001","","Case iPhone","Case",1000000,800000,0,"",""],["OTHER","INC001","","Different","Case",1000000,700000,0,"",""]];const parsed=acc.parseAccessoryPriceWorkbook(workbook(rows),"acc.xlsx");assert.equal(parsed.products[0].activePrice,800000);assert.ok(parsed.warnings.some(v=>v.includes("berulang")));assert.equal(parsed.blockingErrors,1)});
test("supplier mapping uses longest SAP brand-code prefix then exact brand fallback",()=>{const refs=acc.parseSupplierReferences([["Vendor Code","PT Name","Brand Code","Brand Name"],["1","DINO","INC","INCASE"],["2","OTHER","IN","OTHER"]]);const products=[{supplier:"",brand:"INCASE",sapArticle:"INC001",articleMapemall:"",sapDescription:"Case",category:"Case",referenceSrp:1,currentSrpCash:1,repricingCash:0,activePrice:1,brZout:"",remarks:""},{supplier:"",brand:"Unknown",sapArticle:"ZZZ001",articleMapemall:"",sapDescription:"X",category:"Case",referenceSrp:1,currentSrpCash:1,repricingCash:0,activePrice:1,brZout:"",remarks:""}];const mapped=acc.mapAccessorySuppliers(products,refs);assert.equal(mapped[0].supplier,"DINO");assert.equal(mapped[1].supplier,"Belum Terpetakan")});
test("comparison detects SKU and price changes by normalized SAP Article",()=>{const base={fileName:"a",sheetName:"s",priceListDate:null,totalRows:1,totalSku:1,totalBrand:1,totalCategory:1,warnings:[],issues:[],blockingErrors:0};const p={supplier:"DINO",brand:"INCASE",sapArticle:"INC001",articleMapemall:"",sapDescription:"Case",category:"Case",referenceSrp:100,currentSrpCash:100,repricingCash:0,activePrice:100,brZout:"",remarks:""};const before={...base,products:[p]},after={...base,products:[{...p,activePrice:80,currentSrpCash:80},{...p,sapArticle:"INC002",activePrice:50,currentSrpCash:50}]};const c=acc.compareAccessoryPriceLists(before,after);assert.equal(c.counts.PRICE_DOWN,1);assert.equal(c.counts.NEW_SKU,1)});
