import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,ensureSheet,getSheetRanges} from "@/lib/google-sheets";

const MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk";
const SOURCE_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const TAB="Dashboard Manual Target";
const HEADERS=["Scope","Period","Focus","Target","Updated At"];
const s=(v:unknown)=>String(v??"").trim();
const n=(v:unknown)=>typeof v==="number"?v:Number(s(v).replace(/%/g,"").replace(/,/g,"."))||0;
function share(v:unknown){let x=n(v);if(x>1)x/=100;return Math.max(0,x)}
function validScope(v:string){return v==="monthly"||v==="weekly"||v==="range"}
function validGroup(v:string){return ["lob-focus","product-focus","vas-focus"].includes(v)}
function safeKey(v:string){return v.replace(/[\r\n]/g," ").trim().slice(0,120)}
function storedKey(group:string,key:string){return `${group}::${safeKey(key)}`}
async function staffShares(email:string,key:string){const[rows]=await getSheetRanges(SOURCE_ID,["Config!H1:L120"],email,key);return rows.map(r=>({store:s(r[0]).toUpperCase(),id:s(r[1]),name:s(r[2]),position:s(r[3]),share:share(r[4])})).filter(r=>r.store==="M238"&&/^\d{6,10}$/.test(r.id)&&r.name&&r.share>0&&!/SUPERVISOR|\bSPV\b/i.test(r.position))}
export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});const scope=s(req.nextUrl.searchParams.get("scope")||"monthly"),period=s(req.nextUrl.searchParams.get("period")||""),group=s(req.nextUrl.searchParams.get("group")||"lob-focus");if(!validScope(scope)||!period||!validGroup(group))return NextResponse.json({error:"Scope/period/group tidak valid"},{status:400});try{await ensureSheet(MASTER_ID,TAB,HEADERS,email,key);const[rows]=await getSheetRanges(MASTER_ID,[`'${TAB}'!A2:E5000`],email,key),latest=new Map<string,{target:number;updatedAt:string}>();for(const r of rows){if(s(r[0])!==scope||s(r[1])!==period)continue;const focus=s(r[2]),prefix=`${group}::`;if(focus.startsWith(prefix))latest.set(focus.slice(prefix.length),{target:n(r[3]),updatedAt:s(r[4])});else if(group==="lob-focus"&&!focus.includes("::"))latest.set(focus,{target:n(r[3]),updatedAt:s(r[4])})}const staff=await staffShares(email,key);return NextResponse.json({scope,period,group,targets:Object.fromEntries(latest),staff},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca target"},{status:500})}}
export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const b=await req.json(),scope=s(b.scope),period=s(b.period),group=s(b.group||"lob-focus"),targets=(b.targets||{}) as Record<string,unknown>;if(!validScope(scope)||!period||!validGroup(group))return NextResponse.json({error:"Scope/period/group tidak valid"},{status:400});const ts=new Date().toISOString(),rows=Object.entries(targets).map(([k,v])=>[scope,period,storedKey(group,k),Math.max(0,n(v)),ts]).filter(r=>s(r[2]).length>group.length+2);if(!rows.length)return NextResponse.json({error:"Belum ada target yang diisi"},{status:400});await ensureSheet(MASTER_ID,TAB,HEADERS,email,key);await appendSheetValues(MASTER_ID,`'${TAB}'!A:E`,rows,email,key);const staff=await staffShares(email,key);return NextResponse.json({ok:true,scope,period,group,rows:rows.length,staff,message:"Target tersimpan dan otomatis dibagi sesuai %T staff."})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal menyimpan target"},{status:500})}}
