import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SALES_2025="1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0";
const SALES_2026="151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k";
const OPS="1BjLDXdi_5BgZCUUJAKba-xYRFf0RDmRTT0FW1be03WE";
const STORE_CODES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"] as const;
const STORE_NAMES:Record<string,string>={M117:"Digimap Plaza Senayan",M118:"Digimap Pondok Indah Mall 3",M124:"Digimap Pacific Place",M127:"Digimap Lotte Avenue",M217:"Digimap Blok M Plaza",M227:"Digimap AEON Tanjung Barat",M238:"Digimap Pondok Indah Mall 2",M255:"Digimap Antasari Place",M264:"Digimap Plaza Semanggi"};
const MONTHS=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];

type AnyRow=unknown[];
type StoreAgg={code:string;name:string;target:number;achievement:number;device:number;acc:number;vas:number;qty:number;transactions:number;traffic:number;cvr:number;upt:number;atv:number;nps:number|null;newMember:number;targetCvr:number};
let cache=new Map<string,{at:number,data:unknown}>();
const CACHE_MS=4*60*1000;

function n(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;const s=String(v??"").trim();if(!s)return 0;const cleaned=s.replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,"");const x=Number(cleaned);return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/]?(\d{2})[-/]?(\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function monthIndexFromRow(row:AnyRow){const d=dateKey(row[1]);if(d)return Number(d.slice(5,7))-1;const label=String(row[2]??"").toLowerCase();return MONTHS.findIndex(x=>x.toLowerCase()===label)}
function blankAgg(code:string):StoreAgg{return{code,name:STORE_NAMES[code]??code,target:0,achievement:0,device:0,acc:0,vas:0,qty:0,transactions:0,traffic:0,cvr:0,upt:0,atv:0,nps:null,newMember:0,targetCvr:30}}

function parseTargets(rows:AnyRow[],monthName:string){const out:Record<string,{total:number;device:number;acc:number;vas:number}>={};let active=false;for(const row of rows){const first=String(row[0]??"").trim();if(MONTHS.some(m=>m.toLowerCase()===first.toLowerCase())){active=first.toLowerCase()===monthName.toLowerCase();continue}if(!active)continue;if(first.toLowerCase()==="total")break;if(STORE_CODES.includes(first as typeof STORE_CODES[number]))out[first]={total:n(row[3]),device:n(row[4]),acc:n(row[5]),vas:n(row[6])}}return out}
function parseNps(rows:AnyRow[],monthIdx:number){const out:Record<string,number|null>={};for(const row of rows.slice(2)){const label=String(row[0]??"");const code=STORE_CODES.find(c=>label.includes(c));if(code){const raw=row[monthIdx+1];out[code]=raw===undefined||raw===null||raw===""?null:n(raw)}}return out}
function parseTraffic(rows:AnyRow[],period:string){const monthTraffic:Record<string,number>=Object.fromEntries(STORE_CODES.map(c=>[c,0]));const daily:Record<string,Record<string,number>>={};const header=rows[0]??[];const cols=STORE_CODES.map(code=>header.findIndex(v=>String(v??"").includes(code)));for(const row of rows.slice(1)){const d=dateKey(row[0]);if(!d||!d.startsWith(period))continue;daily[d]=daily[d]??{};STORE_CODES.forEach((code,i)=>{const value=cols[i]>=0?n(row[cols[i]]):0;monthTraffic[code]+=value;daily[d][code]=value})}return{monthTraffic,daily}}
function parseSoh(rows:AnyRow[]){const header=rows[7]??[];const cols:Record<string,number>={};STORE_CODES.forEach(c=>cols[c]=header.findIndex(v=>String(v??"").trim()===c));const totals:Record<string,number>=Object.fromEntries(STORE_CODES.map(c=>[c,0]));for(const row of rows.slice(8))STORE_CODES.forEach(c=>{if(cols[c]>=0)totals[c]+=n(row[cols[c]])});return totals}
function aggregateSales(ranges:AnyRow[][],period:string){const stores=Object.fromEntries(STORE_CODES.map(c=>[c,blankAgg(c)])) as Record<string,StoreAgg>;const txnSets:Record<string,Set<string>>=Object.fromEntries(STORE_CODES.map(c=>[c,new Set<string>()]));const daily:Record<string,{amount:number;device:number;acc:number;vas:number;qty:number;tx:Set<string>}>=Object.create(null);const lob:Record<string,{iphone:number;mac:number;ipad:number;watch:number;airpods:number}>=Object.fromEntries(STORE_CODES.map(c=>[c,{iphone:0,mac:0,ipad:0,watch:0,airpods:0}]));const weekly:Record<string,Record<string,{amount:number;qty:number}>>={};const monthly=Array.from({length:12},(_,i)=>({month:i+1,amount:0}));ranges.forEach((rows,idx)=>{const code=STORE_CODES[idx],agg=stores[code];for(const row of rows.slice(1)){const d=dateKey(row[1]);if(!d||!d.startsWith("2026-"))continue;const amount=n(row[13]),qty=n(row[11]),group=String(row[8]??"").toUpperCase(),cat=String(row[6]??"").toUpperCase(),week=String(row[3]??"").trim(),txn=String(row[14]??"").trim();const mi=monthIndexFromRow(row);if(mi>=0&&mi<12)monthly[mi].amount+=amount;if(!d.startsWith(period))continue;agg.achievement+=amount;agg.qty+=qty;if(txn)txnSets[code].add(`${code}|${txn}`);if(group==="DEVICES")agg.device+=amount;else if(group==="ACCESSORIES")agg.acc+=amount;else if(group==="VAS")agg.vas+=amount;if(cat.includes("IPHONE"))lob[code].iphone+=amount;else if(cat==="MAC"||cat.includes("MACBOOK"))lob[code].mac+=amount;else if(cat.includes("IPAD"))lob[code].ipad+=amount;else if(cat.includes("WATCH"))lob[code].watch+=amount;else if(cat.includes("AIRPODS"))lob[code].airpods+=amount;if(week){weekly[week]=weekly[week]??{};weekly[week][code]=weekly[week][code]??{amount:0,qty:0};weekly[week][code].amount+=amount;weekly[week][code].qty+=qty}const day=d;daily[day]=daily[day]??{amount:0,device:0,acc:0,vas:0,qty:0,tx:new Set<string>()};daily[day].amount+=amount;daily[day].qty+=qty;if(txn)daily[day].tx.add(`${code}|${txn}`);if(group==="DEVICES")daily[day].device+=amount;else if(group==="ACCESSORIES")daily[day].acc+=amount;else if(group==="VAS")daily[day].vas+=amount;}});STORE_CODES.forEach(code=>{const a=stores[code];a.transactions=txnSets[code].size;a.upt=a.transactions?a.qty/a.transactions:0;a.atv=a.transactions?a.achievement/a.transactions:0});return{stores,daily,lob,weekly,monthly}}
function annualFromRanges(ranges:AnyRow[][],year:number){const monthly=Array.from({length:12},()=>0);ranges.forEach(rows=>{for(const row of rows.slice(1)){const d=dateKey(row[1]);if(!d.startsWith(String(year)))continue;const mi=monthIndexFromRow(row);if(mi>=0&&mi<12)monthly[mi]+=n(row[13])}});return monthly}

export async function GET(req:NextRequest){
 const period=req.nextUrl.searchParams.get("period")||"2026-09";if(!/^2026-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});const cached=cache.get(period);if(cached&&Date.now()-cached.at<CACHE_MS)return NextResponse.json(cached.data,{headers:{"x-jakarta1-cache":"HIT"}});
 const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});
 try{
  const salesRanges=STORE_CODES.map(c=>`'${c}'!A:O`);const [sales26,sales25,ops]=await Promise.all([getSheetRanges(SALES_2026,salesRanges,email,key),getSheetRanges(SALES_2025,salesRanges,email,key),getSheetRanges(OPS,["'Data Traffic'!A:J","'Data Nps'!A:M","'Master Data'!Y1:AE180","'Soh Final'!A:Q"],email,key)]);
  const monthIdx=Number(period.slice(5,7))-1,monthName=MONTHS[monthIdx],targets=parseTargets(ops[2]??[],monthName),nps=parseNps(ops[1]??[],monthIdx),traffic=parseTraffic(ops[0]??[],period),soh=parseSoh(ops[3]??[]),sales=aggregateSales(sales26 as AnyRow[][],period),annual25=annualFromRanges(sales25 as AnyRow[][],2025),today=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  const stores=STORE_CODES.map(code=>{const a=sales.stores[code],t=targets[code];a.target=t?.total??0;a.traffic=traffic.monthTraffic[code]??0;a.cvr=a.traffic?a.transactions/a.traffic*100:0;a.nps=nps[code]??null;return{...a,targetDevice:t?.device??0,targetAcc:t?.acc??0,targetVas:t?.vas??0,soh:soh[code]??0}});
  const total=stores.reduce((a,s)=>({target:a.target+s.target,achievement:a.achievement+s.achievement,device:a.device+s.device,acc:a.acc+s.acc,vas:a.vas+s.vas,qty:a.qty+s.qty,transactions:a.transactions+s.transactions,traffic:a.traffic+s.traffic,soh:a.soh+s.soh}),{target:0,achievement:0,device:0,acc:0,vas:0,qty:0,transactions:0,traffic:0,soh:0});
  const validNps=stores.map(s=>s.nps).filter((x):x is number=>typeof x==="number"),areaNps=validNps.length?validNps.reduce((a,b)=>a+b,0)/validNps.length:null,daysInMonth=new Date(2026,monthIdx+1,0).getDate(),dailyTarget=total.target/daysInMonth;
  const trend=Object.keys(traffic.daily).sort().map(date=>{const tx=STORE_CODES.reduce((sum,c)=>{const storeRows=(sales26 as AnyRow[][])[STORE_CODES.indexOf(c)]??[];const set=new Set<string>();for(const row of storeRows.slice(1)){if(dateKey(row[1])===date){const txn=String(row[14]??"").trim();if(txn)set.add(`${c}|${txn}`)}}return sum+set.size},0);const tr=STORE_CODES.reduce((sum,c)=>sum+(traffic.daily[date]?.[c]??0),0);return{date,traffic:tr,transactions:tx,cvr:tr?tx/tr*100:0}});
  const d=sales.daily[today],todayTraffic=STORE_CODES.reduce((sum,c)=>sum+(traffic.daily[today]?.[c]??0),0),todayTx=d?.tx.size??0;
  const area={...total,achievementPct:total.target?total.achievement/total.target*100:0,cvr:total.traffic?total.transactions/total.traffic*100:0,upt:total.transactions?total.qty/total.transactions:0,atv:total.transactions?total.achievement/total.transactions:0,nps:areaNps,newMember:0};
  const result={period,monthName,stores,area,daily:{date:today,target:dailyTarget,achievement:d?.amount??0,device:d?.device??0,acc:d?.acc??0,vas:d?.vas??0,qty:d?.qty??0,transactions:todayTx,traffic:todayTraffic,cvr:todayTraffic?todayTx/todayTraffic*100:0,upt:todayTx?(d?.qty??0)/todayTx:0,atv:todayTx?(d?.amount??0)/todayTx:0},trend,lob:sales.lob,weekly:sales.weekly,revenue:{y2025:annual25,y2026:sales.monthly.map(x=>x.amount)},meta:{stores:STORE_CODES.length,cvrTargetSource:"fallback",cvrTarget:30,npsMethod:"simple-average",newMemberSource:"not-configured",sourceTimezone:"Asia/Jakarta",opsSpreadsheetTimezone:"Pacific/Auckland"}};
  cache.set(period,{at:Date.now(),data:result});return NextResponse.json(result,{headers:{"cache-control":"public, max-age=60, stale-while-revalidate=240","x-jakarta1-cache":"MISS"}})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca data Jakarta 1"},{status:500})}
}
