import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SALES:Record<string,string>={"2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0","2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"};
const STORE_CODES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"] as const;
type Row=unknown[];
function n(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;const x=Number(String(v??"").replace(/[^0-9.-]/g,""));return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function emptyFocus(){return{iphone17promax:0,iphone17pro:0,iphone17:0,iphone15:0,iphone16:0,iphoneAir:0,macbookAirM5:0,macbookNeo:0,ipad11:0,awSe3:0}}
function addFocus(f:ReturnType<typeof emptyFocus>,desc:string,qty:number){const q=Math.max(0,qty),d=desc.replace(/\s+/g," ");if(/IPHONE 17 PRO\s*MAX|IPHONE 17 PROMAX/.test(d))f.iphone17promax+=q;else if(/IPHONE 17 PRO/.test(d))f.iphone17pro+=q;else if(/IPHONE 17(?!\s*(PRO|AIR))/.test(d))f.iphone17+=q;if(/IPHONE 15/.test(d))f.iphone15+=q;if(/IPHONE 16/.test(d))f.iphone16+=q;if(/IPHONE\s+AIR/.test(d))f.iphoneAir+=q;if(/MACBOOK AIR/.test(d)&&/M5/.test(d))f.macbookAirM5+=q;if(/MACBOOK NEO/.test(d))f.macbookNeo+=q;if(/IPAD\s+11/.test(d))f.ipad11+=q;if(/(APPLE\s+WATCH|AW).*SE\s*3|WATCH\s+SE\s*3/.test(d))f.awSe3+=q}
function weekInfo(date:string){const d=new Date(`${date}T00:00:00Z`),anchor=new Date("2026-06-28T00:00:00Z"),days=Math.floor((d.getTime()-anchor.getTime())/86400000),weekIndex=Math.floor(days/7);let qIndex=Math.floor(weekIndex/13),w=((weekIndex%13)+13)%13+1;let q=4+qIndex;while(q<1)q+=4;while(q>4)q-=4;const start=new Date(anchor.getTime()+weekIndex*7*86400000),end=new Date(start.getTime()+6*86400000);return{key:start.toISOString().slice(0,10),label:`Week ${w} Q${q}`,start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}}

export async function GET(req:NextRequest){const year=req.nextUrl.searchParams.get("year")||"2026";if(!SALES[year])return NextResponse.json({error:"Tahun tidak valid"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const data=await getSheetRanges(SALES[year],STORE_CODES.map(c=>`'${c}'!A:O`),email,key);const map=new Map<string,{date:string;store:string;staffId:string;staffName:string;focus:ReturnType<typeof emptyFocus>}>,weekMap=new Map<string,ReturnType<typeof weekInfo>>();for(let i=0;i<STORE_CODES.length;i++){const code=STORE_CODES[i],rows=(data[i]??[]) as Row[];for(const row of rows.slice(1)){const d=dateKey(row[1]);if(!d.startsWith(`${year}-`))continue;const staffId=String(row[4]??"").replace(/\.0$/,"").trim(),staffName=String(row[5]??"").trim(),desc=String(row[10]??"").toUpperCase(),qty=n(row[11]);if(!staffName&&!staffId)continue;const f=emptyFocus();addFocus(f,desc,qty);if(Object.values(f).every(v=>v===0))continue;const k=`${d}|${code}|${staffId||staffName}`,x=map.get(k)??{date:d,store:code,staffId:staffId||`${code}|${staffName}`,staffName:staffName||staffId,focus:emptyFocus()};for(const p of Object.keys(f) as (keyof typeof f)[])x.focus[p]+=f[p];map.set(k,x);const wi=weekInfo(d);weekMap.set(wi.key,wi)}}return NextResponse.json({year,rows:[...map.values()],weeks:[...weekMap.values()].sort((a,b)=>a.start.localeCompare(b.start))},{headers:{"cache-control":"public, max-age=120, stale-while-revalidate=300"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca product focus"},{status:500})}}
