import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0",STORE="M238";
const s=(v:unknown)=>String(v??"").trim(),up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
const iso=(v:unknown)=>{const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""};
const FOCUS=["iPhone 17 Pro Max","iPhone 17 Pro","iPhone 17","iPhone Air","iPhone 16","iPhone 15","iPad 11","MacBook Neo","Watch SE 3","AirPods"] as const;
function productName(type:string,desc:string,category:string){const x=`${type} ${desc} ${category}`.toUpperCase().replace(/\s+/g," ");if(/AIRPODS/.test(x))return"AirPods";if(/IPHONE\s*17\s*PRO\s*MAX/.test(x))return"iPhone 17 Pro Max";if(/IPHONE\s*17\s*PRO/.test(x))return"iPhone 17 Pro";if(/IPHONE\s*17(?!\s*PRO)/.test(x))return"iPhone 17";if(/IPHONE\s*AIR/.test(x))return"iPhone Air";if(/IPHONE\s*16/.test(x))return"iPhone 16";if(/IPHONE\s*15/.test(x))return"iPhone 15";if(/\bIPAD\s*(?:11|11TH)\b/.test(x))return"iPad 11";if(/\bMBN\b|MACBOOK\s*NEO|MAC\s*NEO/.test(x))return"MacBook Neo";if(/\bAW\s*SE\s*3\b|APPLE\s*WATCH\s*SE\s*3|WATCH\s*SE\s*3/.test(x))return"Watch SE 3";return""}
function weekOrder(label:string){const m=label.match(/Week\s*(\d+)\s*Q(\d+)/i);return m?Number(m[2])*100+Number(m[1]):-1}
function monthLabel(p:string){if(!/^\d{4}-\d{2}$/.test(p))return p;const[y,m]=p.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(Date.UTC(y,m-1,1)))}
function dateLabel(d:string){return d?new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${d}T00:00:00Z`)):""}

type Tot={qty:number;value:number};type Staff={id:string;name:string;products:Record<string,Tot>;total:Tot;deviceTotal:Tot};
const fresh=():Tot=>({qty:0,value:0});
export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const[dataRows,configRows]=await getSheetRanges(ID,["'Data Copas'!A2:S50000","Config!A1:AZ120"],email,key);const all=dataRows.filter(r=>s(r[15]).toUpperCase()===STORE&&s(r[18])==="2026"),roster=configRows.slice(27,55).filter(r=>s(r[7])===STORE&&s(r[8])&&s(r[9])&&!/SUPERVISOR|ONLINE/i.test(s(r[10]))).map(r=>({id:s(r[8]),name:s(r[9])})),byId=new Map(roster.map(r=>[r.id,r])),byName=new Map(roster.map(r=>[up(r.name),r]));const availableWeeks=[...new Set(all.map(r=>s(r[14])).filter(v=>/Week\s*\d+\s*Q\d+/i.test(v)))].sort((a,b)=>weekOrder(a)-weekOrder(b)),availableMonths=[...new Set(all.map(r=>iso(r[0]).slice(0,7)).filter(v=>/^2026-\d{2}$/.test(v)))].sort();const mode=(req.nextUrl.searchParams.get("mode")||"week") as "week"|"month"|"range",requestedWeek=req.nextUrl.searchParams.get("week")||"",week=availableWeeks.includes(requestedWeek)?requestedWeek:(availableWeeks.at(-1)||""),requestedMonth=req.nextUrl.searchParams.get("month")||availableMonths.at(-1)||"2026-09",month=availableMonths.includes(requestedMonth)?requestedMonth:(availableMonths.at(-1)||requestedMonth),from=req.nextUrl.searchParams.get("from")||`${month}-01`,to=req.nextUrl.searchParams.get("to")||`${month}-31`,selected=all.filter(r=>{if(mode==="week")return s(r[14])===week;const d=iso(r[0]);return mode==="month"?d.startsWith(month):d>=from&&d<=to}),periodLabel=mode==="week"?week:mode==="month"?monthLabel(month):`${dateLabel(from)} – ${dateLabel(to)}`;
 const staff=new Map<string,Staff>();for(const r of roster)staff.set(r.id,{id:r.id,name:r.name,products:{},total:fresh(),deviceTotal:fresh()});const productTotals:Record<string,Tot>=Object.fromEntries(FOCUS.map(k=>[k,fresh()]));
 for(const row of selected){const rawId=s(row[1]),rawName=s(row[2]),person=byId.get(rawId)||byName.get(up(rawName)),staffId=person?.id||rawId||rawName,staffName=person?.name||rawName||"Tanpa Nama",desc=s(row[5]),type=s(row[6]),category=up(row[9]),brand=up(row[10]),scheme=up(row[12]),qty=n(row[7]);if(qty===0||brand!=="APPLE")continue;const p=productName(type,desc,category);if(!p)continue;const eligible=scheme==="DEVICES"||(scheme==="ACCESSORIES"&&p==="AirPods");if(!eligible)continue;const rec=staff.get(staffId)||{id:staffId,name:staffName,products:{},total:fresh(),deviceTotal:fresh()};rec.products[p]||=fresh();rec.products[p].qty+=qty;rec.total.qty+=qty;productTotals[p].qty+=qty;if(scheme==="DEVICES")rec.deviceTotal.qty+=qty;staff.set(staffId,rec)}
 const products=FOCUS.map(name=>({name,...productTotals[name]})),rows=[...staff.values()].sort((a,b)=>b.total.qty-a.total.qty||a.name.localeCompare(b.name)),total=products.reduce((a,r)=>({qty:a.qty+r.qty,value:0}),fresh());return NextResponse.json({mode,periodLabel,week,month,from,to,availableWeeks,availableMonths,lob:{products,staff:rows,total}},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca LOB Target Fokus"},{status:500})}}
