import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,ensureSheet,getSheetRanges} from "@/lib/google-sheets";
import * as XLSX from "xlsx";
import {createHash} from "crypto";

const MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk";
const LOG="Dashboard Schedule Upload Log";
const SCHEDULE="Dashboard Uploaded Schedule";
const SNAPSHOT="Dashboard Schedule Snapshot";
const SALES_SNAPSHOT="Dashboard Daily Sales Snapshot";
const s=(v:unknown)=>String(v??"").trim();
const up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
const excel=/\.xlsx?$/i;
function monthDays(period:string){const[y,m]=period.split("-").map(Number);return new Date(y,m,0).getDate()}
function text(v:unknown){return up(v).replace(/[^A-Z0-9]/g,"")}
function status(v:unknown){const x=up(v).replace(/\s+/g," ");if(!x)return"IN";if(/^D\d{3}$/.test(x))return x;if(/^(OFF|O)$/.test(x))return"OFF";if(/TRAIN/.test(x))return"TRAINING";if(/MEET/.test(x))return"MEETING";if(/CUTI|LEAVE/.test(x))return"CUTI";if(/^RO$|ROSTER OFF/.test(x))return"RO";if(/SAKIT|SICK/.test(x))return"SAKIT";if(/FULL/.test(x))return"FULL";if(/^(IN|P|PRESENT|SHIFT|M|S|PAGI|SIANG|MID|CLOSING|OPENING)$/.test(x))return"IN";return x}
function iso(v:unknown){const x=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}return""}
type Roster={id:string;name:string;position:string;share:number};
async function masterRoster(email:string,key:string):Promise<Roster[]>{
 await ensureSheet(MASTER_ID,SCHEDULE,["Date","Sales ID","Sales Name","Position","Share","Status","Uploaded At","Remark","Upload Key"],email,key);
 await ensureSheet(MASTER_ID,SNAPSHOT,["Date","Sales ID","Sales Name","Position","Share","Status","Created At"],email,key);
 await ensureSheet(MASTER_ID,SALES_SNAPSHOT,["Date","Sales ID","Sales Name","Position","Share","Status","Target Amount","Target Accessories","Target VAS","Achievement Amount","Accessories","VAS","Qty","Invoices","Updated At"],email,key);
 const [uploaded,snapshot,sales]=await getSheetRanges(MASTER_ID,[`'${SCHEDULE}'!A2:I10000`,`'${SNAPSHOT}'!A2:G5000`,`'${SALES_SNAPSHOT}'!A2:O5000`],email,key);
 const map=new Map<string,Roster>();
 const ingest=(rows:unknown[][])=>{for(const r of rows){const id=s(r[1]),name=s(r[2]);if(!/^\d{6,10}$/.test(id)||!name)continue;const prev=map.get(id),position=s(r[3])||prev?.position||"Sales Assistant",share=n(r[4])||prev?.share||1;map.set(id,{id,name,position,share})}};
 ingest(sales);ingest(snapshot);ingest(uploaded);
 return [...map.values()]
}
function findHeader(grid:unknown[][],period:string){let header=-1,dateCols=new Map<number,number>();for(let ri=0;ri<Math.min(grid.length,50);ri++){const map=new Map<number,number>();for(let ci=0;ci<(grid[ri]?.length||0);ci++){const raw=s(grid[ri][ci]),m=raw.match(/(?:^|\D)([1-9]|[12]\d|3[01])(?:\D|$)/),day=Number(m?.[1]||(/^\d{1,2}$/.test(raw)?raw:0));if(day>=1&&day<=monthDays(period))map.set(ci,day)}if(map.size>dateCols.size){header=ri;dateCols=map}}return{header,dateCols}}
function inferPerson(row:unknown[],headerRow:unknown[],known:Map<string,Roster>):Roster|null{let id="",idCol=-1;for(let i=0;i<row.length;i++){const v=s(row[i]).replace(/\.0$/,"");if(/^\d{8}$/.test(v)){id=v;idCol=i;break}}if(!id)return null;const k=known.get(id);const nameHeader=headerRow.findIndex(v=>/NAME|NAMA/i.test(s(v))),rankHeader=headerRow.findIndex(v=>/RANK|POSITION|JABATAN/i.test(s(v)));let name=nameHeader>=0?s(row[nameHeader]):"",position=rankHeader>=0?s(row[rankHeader]):"";if(!name&&idCol>=0)name=s(row[idCol+1]);if(!position&&idCol>=0)position=s(row[idCol+2]);name=name||k?.name||id;position=position||k?.position||"Sales Assistant";return{id,name,position,share:k?.share||1}}
export async function GET(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[],roster:[]});try{await ensureSheet(MASTER_ID,LOG,["Period","File Name","Uploaded At","Type","Remark","Parsed Rows","Status","Hash"],email,key);const[rows]=await getSheetRanges(MASTER_ID,[`'${LOG}'!A2:H1000`],email,key);const roster=await masterRoster(email,key);return NextResponse.json({rows:rows.filter(r=>s(r[0])).map(r=>({period:s(r[0]),fileName:s(r[1]),uploadedAt:s(r[2]),type:s(r[3]),remark:s(r[4]),parsedRows:n(r[5]),status:s(r[6]),applied:n(r[5])>0})).reverse(),roster},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca log",rows:[],roster:[]},{status:500})}}
export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Koneksi Google Sheets belum tersedia"},{status:503});try{const form=await req.formData(),file=form.get("file"),period=s(form.get("period")),remark=s(form.get("remark")),passcode=s(form.get("passcode"));const admin=process.env.ADMIN_PASSCODE;if(!admin)return NextResponse.json({error:"ADMIN_PASSCODE belum dipasang di Vercel"},{status:503});if(passcode!==admin)return NextResponse.json({error:"Passcode admin salah. Upload schedule hanya dapat dilakukan oleh admin."},{status:403});if(!(file instanceof File))return NextResponse.json({error:"Pilih file schedule terlebih dahulu."},{status:400});if(!/^20\d{2}-\d{2}$/.test(period))return NextResponse.json({error:"Pilih periode bulan schedule."},{status:400});if(!excel.test(file.name))return NextResponse.json({error:"Foto/PDF/HEIC harus dibaca dulu sampai muncul Preview Schedule. Setelah preview benar, tekan ‘Gunakan Hasil Ini untuk Upload Schedule’ agar otomatis dikonversi ke Excel, baru simpan ke MASTER DATA M238."},{status:422});
 await ensureSheet(MASTER_ID,LOG,["Period","File Name","Uploaded At","Type","Remark","Parsed Rows","Status","Hash"],email,key);await ensureSheet(MASTER_ID,SCHEDULE,["Date","Sales ID","Sales Name","Position","Share","Status","Uploaded At","Remark","Upload Key"],email,key);const[logs]=await getSheetRanges(MASTER_ID,[`'${LOG}'!A2:H1000`],email,key),existing=logs.find(r=>s(r[0])===period&&n(r[5])>0);if(existing)return NextResponse.json({error:`Schedule aktif ${period} sudah pernah di-upload pada ${s(existing[2])} (${s(existing[1])}). Data aktif tidak ditimpa.`,existing:{period,fileName:s(existing[1]),uploadedAt:s(existing[2]),status:s(existing[6])}},{status:409});
 const bytes=Buffer.from(await file.arrayBuffer()),hash=createHash("sha256").update(bytes).digest("hex"),uploadedAt=new Date().toISOString(),wb=XLSX.read(bytes,{type:"buffer",cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],grid=XLSX.utils.sheet_to_json<unknown[]>(ws,{header:1,defval:"",raw:false});const{header,dateCols}=findHeader(grid,period);if(header<0||dateCols.size===0)return NextResponse.json({error:"Kolom tanggal schedule tidak terbaca dari file hasil konversi."},{status:422});
 const known=new Map((await masterRoster(email,key)).map(r=>[r.id,r])),headerRow=grid[header]||[],parsedRows:unknown[][]=[];for(let ri=header+1;ri<grid.length;ri++){const person=inferPerson(grid[ri]||[],headerRow,known);if(!person)continue;for(const[ci,day]of dateCols){const st=status(grid[ri]?.[ci]),date=`${period}-${String(day).padStart(2,"0")}`;parsedRows.push([date,person.id,person.name,person.position,person.share,st,uploadedAt,remark,period])}}
 if(!parsedRows.length)return NextResponse.json({error:"Tidak ada baris staff yang terbaca. Pastikan preview menampilkan NIK, nama staff, tanggal, dan status sebelum disimpan."},{status:422});await appendSheetValues(MASTER_ID,`'${SCHEDULE}'!A:I`,parsedRows,email,key);await appendSheetValues(MASTER_ID,`'${LOG}'!A:H`,[[period,file.name,uploadedAt,"XLSX",remark,parsedRows.length,"AUTO_PARSED_MASTER",hash]],email,key);return NextResponse.json({ok:true,period,fileName:file.name,uploadedAt,parsedRows:parsedRows.length,status:"AUTO_PARSED_MASTER",appliedToDailySales:true,message:`${parsedRows.length} baris schedule berhasil disimpan langsung ke MASTER DATA M238 dan menjadi sumber Daily Sales.`},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Upload schedule gagal"},{status:500})}}
