import {NextRequest,NextResponse} from "next/server";
import {appendSheetValues,ensureSheet,getSheetRanges} from "@/lib/google-sheets";
import * as XLSX from "xlsx";
import {createHash} from "crypto";

const DASHBOARD_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0",MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk",STORE="M238",LOG="Dashboard Schedule Upload Log",SCHEDULE="Dashboard Uploaded Schedule";
const s=(v:unknown)=>String(v??"").trim(),up=(v:unknown)=>s(v).toUpperCase(),n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
const allowed=/\.(jpe?g|png|pdf|heic|xls|xlsx)$/i;
function monthDays(period:string){const[y,m]=period.split("-").map(Number);return new Date(y,m,0).getDate()}
function status(v:unknown){const x=up(v).replace(/\s+/g," ");if(/^(OFF|O)$/.test(x))return"OFF";if(/TRAIN/.test(x))return"TRAINING";if(/CUTI|LEAVE/.test(x))return"CUTI";if(/^RO$|ROSTER OFF/.test(x))return"RO";if(/SAKIT|SICK/.test(x))return"SAKIT";if(/^(IN|P|PRESENT|SHIFT|M|S|PAGI|SIANG|MID|CLOSING|OPENING)$/.test(x))return"IN";return x||"IN"}
function text(v:unknown){return up(v).replace(/[^A-Z0-9]/g,"")}
export async function GET(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({rows:[]});try{await ensureSheet(MASTER_ID,LOG,["Period","File Name","Uploaded At","Type","Remark","Parsed Rows","Status","Hash"],email,key);const[rows]=await getSheetRanges(MASTER_ID,[`'${LOG}'!A2:H1000`],email,key);return NextResponse.json({rows:rows.filter(r=>s(r[0])).map(r=>({period:s(r[0]),fileName:s(r[1]),uploadedAt:s(r[2]),type:s(r[3]),remark:s(r[4]),parsedRows:n(r[5]),status:s(r[6]),applied:n(r[5])>0})).reverse()},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca log"},{status:500})}}
export async function POST(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Koneksi Google Sheets belum tersedia"},{status:503});try{const form=await req.formData(),file=form.get("file"),period=s(form.get("period")),remark=s(form.get("remark"));if(!(file instanceof File))return NextResponse.json({error:"Pilih file schedule terlebih dahulu."},{status:400});if(!/^20\d{2}-\d{2}$/.test(period))return NextResponse.json({error:"Pilih periode bulan schedule."},{status:400});if(!allowed.test(file.name))return NextResponse.json({error:"Format schedule: JPG/JPEG, PNG, PDF, HEIC, XLS, atau XLSX."},{status:400});await ensureSheet(MASTER_ID,LOG,["Period","File Name","Uploaded At","Type","Remark","Parsed Rows","Status","Hash"],email,key);await ensureSheet(MASTER_ID,SCHEDULE,["Date","Sales ID","Sales Name","Position","Share","Status","Uploaded At","Remark","Upload Key"],email,key);const[logs]=await getSheetRanges(MASTER_ID,[`'${LOG}'!A2:H1000`],email,key),existing=logs.find(r=>s(r[0])===period&&(n(r[5])>0||/AUTO_PARSED/i.test(s(r[6]))));if(existing)return NextResponse.json({error:`Schedule aktif ${period} sudah pernah di-upload pada ${s(existing[2])} (${s(existing[1])}). Data aktif tidak ditimpa.`,existing:{period,fileName:s(existing[1]),uploadedAt:s(existing[2]),status:s(existing[6])}},{status:409});const bytes=Buffer.from(await file.arrayBuffer()),hash=createHash("sha256").update(bytes).digest("hex"),uploadedAt=new Date().toISOString(),ext=(file.name.split(".").pop()||"").toLowerCase();let parsedRows:unknown[][]=[],mode="REFERENCE_ONLY";
 if(/xlsx?/.test(ext)){const wb=XLSX.read(bytes,{type:"buffer",cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],grid=XLSX.utils.sheet_to_json<unknown[]>(ws,{header:1,defval:"",raw:false});const[config]=await getSheetRanges(DASHBOARD_ID,["Config!A1:AZ120"],email,key),roster=config.slice(27,55).filter(r=>s(r[7])===STORE&&s(r[8])&&s(r[9])&&!/SUPERVISOR|ONLINE/i.test(s(r[10]))).map(r=>({id:s(r[8]),name:s(r[9]),position:s(r[10]),share:n(r[11])}));let header=-1,dateCols=new Map<number,number>();for(let ri=0;ri<Math.min(grid.length,40);ri++){const map=new Map<number,number>();for(let ci=0;ci<(grid[ri]?.length||0);ci++){const raw=s(grid[ri][ci]),day=Number(raw.match(/(?:^|\D)([1-9]|[12]\d|3[01])(?:\D|$)/)?.[1]||raw);if(day>=1&&day<=monthDays(period))map.set(ci,day)}if(map.size>dateCols.size){header=ri;dateCols=map}}if(header>=0&&dateCols.size){for(const person of roster){const keys=[text(person.id),text(person.name)],ri=grid.findIndex((row,i)=>i>header&&row.some(c=>keys.includes(text(c))));if(ri<0)continue;for(const[ci,day]of dateCols){const st=status(grid[ri]?.[ci]);const date=`${period}-${String(day).padStart(2,"0")}`;parsedRows.push([date,person.id,person.name,person.position,person.share,st,uploadedAt,remark,period])}}if(parsedRows.length){await appendSheetValues(MASTER_ID,`'${SCHEDULE}'!A:I`,parsedRows,email,key);mode="AUTO_PARSED_EXCEL"}}
 }
 await appendSheetValues(MASTER_ID,`'${LOG}'!A:H`,[[period,file.name,uploadedAt,ext.toUpperCase(),remark,parsedRows.length,mode,hash]],email,key);const applied=parsedRows.length>0;return NextResponse.json({ok:true,period,fileName:file.name,uploadedAt,parsedRows:parsedRows.length,status:mode,appliedToDailySales:applied,message:applied?`${parsedRows.length} baris schedule terbaca, tersimpan di MASTER DATA M238, dan langsung dipakai Daily Sales.`:"File berhasil dicatat sebagai referensi, tetapi belum mengubah target Daily Sales. Gambar/PDF/HEIC belum dapat dipetakan otomatis ke status staff; upload XLS/XLSX untuk schedule aktif.`".replace(/`$/,'')},{headers:{"cache-control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Upload schedule gagal"},{status:500})}}
