"use client";
import {useEffect,useMemo,useState} from "react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const input="h-11 rounded-xl border bg-white px-3 dark:bg-slate-900";
const bnpl=["HCI","Indodana","Kredivo","Akulaku","SPayLater"];
const trade=["Laku6 Master Device","OnePulse"];
const all=[...bnpl,...trade];
type Category="BNPL"|"Trade-In";
type Row={id:string;date:string;category:Category;provider:string;qty:number;amount:number;notes:string;updatedBy:string;updatedAt:string};
type Summary={provider:string;category:Category;qty:number;amount:number};
type Payload={rows:Row[];providerSummary:Summary[];total:{qty:number;amount:number};bnpl:{qty:number;amount:number};tradeIn:{qty:number;amount:number};error?:string};
type EditState={id:string;date:string;category:Category;provider:string;qty:number;amount:number;notes:string};
const emptyPayload:Payload={rows:[],providerSummary:[],total:{qty:0,amount:0},bnpl:{qty:0,amount:0},tradeIn:{qty:0,amount:0}};
const displayDate=(v:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return v;return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${v}T00:00:00Z`))};
const day=(v:string)=>new Intl.DateTimeFormat("id-ID",{weekday:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${v}T00:00:00Z`));
const updatedBy=()=>{try{return localStorage.getItem("m238-user-name")||localStorage.getItem("m238-user")||"Dashboard User"}catch{return"Dashboard User"}};

export default function BnplTrackingPage(){
 const[d,setD]=useState(today()),[period,setPeriod]=useState(today().slice(0,7)),[category,setCategory]=useState<Category>("BNPL"),[provider,setProvider]=useState("HCI"),[qty,setQty]=useState(1),[amount,setAmount]=useState(0),[notes,setNotes]=useState(""),[data,setData]=useState<Payload>(emptyPayload),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[edit,setEdit]=useState<EditState|null>(null);
 const load=async(p=period,signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch(`/api/bnpl?period=${encodeURIComponent(p)}`,{cache:"no-store",signal}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal membaca data BNPL & Trade-In");setData(j);setMsg("")}catch(e){if((e as Error)?.name!=="AbortError")setMsg(e instanceof Error?e.message:"Gagal membaca data BNPL & Trade-In")}finally{if(!signal?.aborted)setLoading(false)}};
 useEffect(()=>{const c=new AbortController();void load(period,c.signal);return()=>c.abort()},[period]);
 useEffect(()=>setProvider(category==="BNPL"?"HCI":"Laku6 Master Device"),[category]);
 const save=async()=>{if(!d||!provider||!Number.isFinite(qty)||qty<0||!Number.isFinite(amount)||amount<0){setMsg("Periksa tanggal, provider, Qty, dan Amount.");return}setBusy(true);setMsg("");try{const r=await fetch("/api/bnpl",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date:d,category,provider,qty,amount,notes,updatedBy:updatedBy()})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal menyimpan data.");const next=d.slice(0,7);setAmount(0);setQty(1);setNotes("");if(next!==period)setPeriod(next);else await load(next);setMsg("Data berhasil disimpan.")}catch(e){setMsg(e instanceof Error?e.message:"Gagal menyimpan data.")}finally{setBusy(false)}};
 const saveEdit=async()=>{if(!edit)return;if(!edit.date||!edit.provider||!Number.isFinite(edit.qty)||edit.qty<0||!Number.isFinite(edit.amount)||edit.amount<0){setMsg("Periksa data yang akan diubah.");return}setBusy(true);setMsg("");try{const r=await fetch("/api/bnpl",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...edit,updatedBy:updatedBy()})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal menyimpan perubahan.");setEdit(null);await load(period);setMsg("Perubahan berhasil disimpan.")}catch(e){setMsg(e instanceof Error?e.message:"Gagal menyimpan perubahan.")}finally{setBusy(false)}};
 const remove=async(row:Row)=>{if(!window.confirm(`Yakin ingin menghapus data ${row.provider} tanggal ${displayDate(row.date)}?`))return;setBusy(true);setMsg("");try{const r=await fetch("/api/bnpl",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal menghapus data.");await load(period);setMsg("Data berhasil dihapus.")}catch(e){setMsg(e instanceof Error?e.message:"Gagal menghapus data.")}finally{setBusy(false)}};
 const matrix=useMemo(()=>{const map=new Map<string,{date:string;day:string;cells:Record<string,{qty:number;amount:number}>}>();for(const r of data.rows){const v=map.get(r.date)||{date:r.date,day:day(r.date),cells:{}};const c=v.cells[r.provider]||{qty:0,amount:0};c.qty+=Number(r.qty)||0;c.amount+=Number(r.amount)||0;v.cells[r.provider]=c;map.set(r.date,v)}return[...map.values()].sort((a,b)=>a.date.localeCompare(b.date))},[data.rows]);
 const total=(name:string)=>data.providerSummary.find(x=>x.provider===name)||{qty:0,amount:0};
 const editProviders=edit?.category==="Trade-In"?trade:bnpl;
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-950 dark:bg-slate-900 dark:text-slate-100 sm:p-8"><a href="/" className="font-bold text-blue-600">← Dashboard</a><div className="mx-auto mt-6 max-w-[1500px] space-y-5"><div><h1 className="text-3xl font-black">BNPL & Trade-In</h1><p className="mt-1 text-slate-500">Daily tracking dibuat seperti lembar kerja: provider menjadi kolom agar lebih cepat dibaca.</p></div>
 <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="grid gap-3 md:grid-cols-7"><input className={input} type="date" value={d} onChange={e=>setD(e.target.value)}/><select className={input} value={category} onChange={e=>setCategory(e.target.value as Category)}><option value="BNPL">BNPL</option><option value="Trade-In">TRADE IN</option></select><select className={input} value={provider} onChange={e=>setProvider(e.target.value)}>{(category==="BNPL"?bnpl:trade).map(x=><option key={x}>{x}</option>)}</select><input className={input} type="number" min={0} value={qty} onChange={e=>setQty(Number(e.target.value))}/><input className={input} type="number" min={0} value={amount} onChange={e=>setAmount(Number(e.target.value))}/><input className={input} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional)"/><button disabled={busy} onClick={save} className="rounded-xl bg-blue-600 px-4 font-black text-white disabled:opacity-50">{busy?"Menyimpan...":"Simpan"}</button></div>{msg&&<p className="mt-3 text-sm font-bold">{msg}</p>}</section>
 <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Monthly Summary</h2><p className="text-sm text-slate-500">Qty dan Amount mengikuti bulan aktif.</p></div><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Bulan</span><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className={input}/></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{all.map(name=>{const t=total(name);return <div key={name} className="rounded-xl border bg-slate-50/60 p-3 dark:bg-slate-900"><p className="text-xs font-bold text-slate-500">{name}</p><p className="mt-1 text-lg font-black">{num.format(t.qty)} qty</p><p className="mt-1 text-sm font-semibold">{money.format(t.amount)}</p></div>})}</div><div className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Total BNPL</p><b>{num.format(data.bnpl.qty)} qty · {money.format(data.bnpl.amount)}</b></div><div><p className="text-xs text-slate-400">Total Trade-In</p><b>{num.format(data.tradeIn.qty)} qty · {money.format(data.tradeIn.amount)}</b></div><div><p className="text-xs text-slate-400">Total Keseluruhan</p><b>{num.format(data.total.qty)} qty · {money.format(data.total.amount)}</b></div></div></section>
 <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b p-5"><h2 className="text-xl font-black">Daily Tracking</h2><p className="text-sm text-slate-500">Qty dan Amount per provider dalam satu baris tanggal.</p></div><div className="overflow-x-auto"><table className="min-w-[1550px] w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th rowSpan={2} className="p-3 text-left">Tanggal</th><th rowSpan={2} className="p-3 text-left">Hari</th>{bnpl.map(x=><th key={x} colSpan={2} className="border-l p-3 text-center">{x}</th>)}{trade.map(x=><th key={x} colSpan={2} className="border-l bg-emerald-50 p-3 text-center text-emerald-800">{x}</th>)}</tr><tr>{all.flatMap(x=>[<th key={`${x}-q`} className="border-l p-2 text-right">Qty</th>,<th key={`${x}-a`} className="p-2 text-right">Amount</th>])}</tr></thead><tbody>{loading?<tr><td colSpan={16} className="p-8 text-center text-slate-400">Memuat data…</td></tr>:matrix.length?matrix.map(r=><tr className="border-t" key={r.date}><td className="p-3 font-bold">{displayDate(r.date)}</td><td className="p-3">{r.day}</td>{all.flatMap(x=>{const c=r.cells[x]||{qty:0,amount:0};return[<td key={`${r.date}-${x}-q`} className="border-l p-3 text-right font-black">{c.qty||"-"}</td>,<td key={`${r.date}-${x}-a`} className="p-3 text-right">{c.amount?money.format(c.amount):"-"}</td>]})}</tr>):<tr><td colSpan={16} className="p-8 text-center text-slate-400">Belum ada data BNPL & Trade-In pada bulan ini</td></tr>}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-black dark:bg-slate-900"><td className="p-3" colSpan={2}>TOTAL</td>{all.flatMap(x=>{const t=total(x);return[<td key={`${x}-tq`} className="border-l p-3 text-right">{t.qty}</td>,<td key={`${x}-ta`} className="p-3 text-right">{money.format(t.amount)}</td>]})}</tr></tfoot></table></div></section>
 <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b p-5"><h2 className="text-xl font-black">Record Detail</h2><p className="text-sm text-slate-500">Edit atau hapus record berdasarkan ID tanpa membuat duplikat.</p></div><div className="overflow-x-auto"><table className="min-w-[1150px] w-full text-sm"><thead className="bg-slate-50 dark:bg-slate-900"><tr>{["Tanggal","Category","Provider","Qty","Amount","Notes","Updated By","Updated At","Action"].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{data.rows.length?data.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-semibold">{displayDate(r.date)}</td><td className="p-3">{r.category}</td><td className="p-3 font-bold">{r.provider}</td><td className="p-3">{num.format(r.qty)}</td><td className="p-3">{money.format(r.amount)}</td><td className="p-3 text-slate-500">{r.notes||"—"}</td><td className="p-3">{r.updatedBy||"—"}</td><td className="p-3 text-xs text-slate-500">{r.updatedAt?new Date(r.updatedAt).toLocaleString("id-ID"):"—"}</td><td className="p-3"><div className="flex gap-2"><button onClick={()=>setEdit({id:r.id,date:r.date,category:r.category,provider:r.provider,qty:r.qty,amount:r.amount,notes:r.notes})} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Edit</button><button disabled={busy} onClick={()=>void remove(r)} className="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-bold text-rose-600">Hapus</button></div></td></tr>):<tr><td colSpan={9} className="p-8 text-center text-slate-400">Belum ada record pada bulan ini.</td></tr>}</tbody></table></div></section>
 </div>{edit&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-950"><div><h2 className="text-xl font-black">Edit BNPL & Trade-In</h2><p className="mt-1 text-xs text-slate-400">ID {edit.id}</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-slate-400">Tanggal</span><input type="date" className={`${input} w-full`} value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Category</span><select className={`${input} w-full`} value={edit.category} onChange={e=>{const c=e.target.value as Category;setEdit({...edit,category:c,provider:c==="BNPL"?"HCI":"Laku6 Master Device"})}}><option value="BNPL">BNPL</option><option value="Trade-In">TRADE IN</option></select></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Provider</span><select className={`${input} w-full`} value={edit.provider} onChange={e=>setEdit({...edit,provider:e.target.value})}>{editProviders.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Qty</span><input type="number" min={0} className={`${input} w-full`} value={edit.qty} onChange={e=>setEdit({...edit,qty:Number(e.target.value)})}/></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Amount</span><input type="number" min={0} className={`${input} w-full`} value={edit.amount} onChange={e=>setEdit({...edit,amount:Number(e.target.value)})}/></label><label><span className="mb-1 block text-xs font-bold text-slate-400">Notes</span><input className={`${input} w-full`} value={edit.notes} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label></div><div className="mt-5 flex justify-end gap-2"><button disabled={busy} onClick={()=>setEdit(null)} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button disabled={busy} onClick={()=>void saveEdit()} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{busy?"Menyimpan…":"Simpan Perubahan"}</button></div></div></div>}</main>
}
