"use client";
import {useEffect,useMemo,useState} from "react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const input="h-11 rounded-xl border bg-white px-3 dark:bg-slate-900";
const bnpl=["HCI","Indodana","Kredivo","Akulaku","SPaylater"];
const trade=["Laku6 Master Device","OnePulse"];
const all=[...bnpl,...trade];
type Row={date:string;day:string;group:string;type:string;qty:number;amount:number};

export default function BnplTrackingPage(){
 const[d,setD]=useState(today()),[period,setPeriod]=useState(today().slice(0,7)),[group,setGroup]=useState("BNPL"),[type,setType]=useState("HCI"),[qty,setQty]=useState(1),[amount,setAmount]=useState(0),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>setRows((await(await fetch(`/api/bnpl?period=${period}`,{cache:"no-store"})).json()).rows||[]);
 useEffect(()=>{void load()},[period]);
 useEffect(()=>setType(group==="BNPL"?"HCI":"Laku6 Master Device"),[group]);
 const save=async()=>{setBusy(true);setMsg("");try{const r=await fetch("/api/bnpl",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date:d,group,type,qty,amount})}),j=await r.json();setMsg(r.ok?"Data berhasil disimpan.":j.error||"Gagal menyimpan data.");if(r.ok){setAmount(0);setQty(1);setPeriod(d.slice(0,7));await load()}}finally{setBusy(false)}};
 const matrix=useMemo(()=>{const map=new Map<string,{date:string;day:string;cells:Record<string,{qty:number;amount:number}>}>();for(const r of rows){const v=map.get(r.date)||{date:r.date,day:r.day,cells:{}};const c=v.cells[r.type]||{qty:0,amount:0};c.qty+=Number(r.qty)||0;c.amount+=Number(r.amount)||0;v.cells[r.type]=c;map.set(r.date,v)}return[...map.values()].sort((a,b)=>a.date.localeCompare(b.date))},[rows]);
 const total=(name:string)=>rows.filter(r=>r.type===name).reduce((a,r)=>({qty:a.qty+(Number(r.qty)||0),amount:a.amount+(Number(r.amount)||0)}),{qty:0,amount:0});
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-950 dark:bg-slate-900 dark:text-slate-100 sm:p-8"><a href="/" className="font-bold text-blue-600">← Dashboard</a><div className="mx-auto mt-6 max-w-[1500px] space-y-5"><div><h1 className="text-3xl font-black">BNPL & Trade-In</h1><p className="mt-1 text-slate-500">Daily tracking dibuat seperti lembar kerja: provider menjadi kolom agar lebih cepat dibaca.</p></div>
 <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="grid gap-3 md:grid-cols-6"><input className={input} type="date" value={d} onChange={e=>setD(e.target.value)}/><select className={input} value={group} onChange={e=>setGroup(e.target.value)}><option>BNPL</option><option value="TRADE_IN">TRADE IN</option></select><select className={input} value={type} onChange={e=>setType(e.target.value)}>{(group==="BNPL"?bnpl:trade).map(x=><option key={x}>{x}</option>)}</select><input className={input} type="number" min={0} value={qty} onChange={e=>setQty(+e.target.value)}/><input className={input} type="number" min={0} value={amount} onChange={e=>setAmount(+e.target.value)}/><button disabled={busy} onClick={save} className="rounded-xl bg-blue-600 px-4 font-black text-white disabled:opacity-50">{busy?"Menyimpan...":"Simpan"}</button></div>{msg&&<p className="mt-3 text-sm font-bold">{msg}</p>}</section>
 <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-end justify-between gap-3 border-b p-5"><div><h2 className="text-xl font-black">Daily Tracking</h2><p className="text-sm text-slate-500">Qty dan Amount per provider dalam satu baris tanggal.</p></div><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Bulan</span><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className={input}/></label></div><div className="overflow-x-auto"><table className="min-w-[1550px] w-full text-xs"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th rowSpan={2} className="p-3 text-left">Tanggal</th><th rowSpan={2} className="p-3 text-left">Hari</th>{bnpl.map(x=><th key={x} colSpan={2} className="border-l p-3 text-center">{x}</th>)}{trade.map(x=><th key={x} colSpan={2} className="border-l bg-emerald-50 p-3 text-center text-emerald-800">{x}</th>)}</tr><tr>{all.flatMap(x=>[<th key={`${x}-q`} className="border-l p-2 text-right">Qty</th>,<th key={`${x}-a`} className="p-2 text-right">Amount</th>])}</tr></thead><tbody>{matrix.length?matrix.map(r=><tr className="border-t" key={r.date}><td className="p-3 font-bold">{r.date}</td><td className="p-3">{r.day}</td>{all.flatMap(x=>{const c=r.cells[x]||{qty:0,amount:0};return[<td key={`${r.date}-${x}-q`} className="border-l p-3 text-right font-black">{c.qty||"-"}</td>,<td key={`${r.date}-${x}-a`} className="p-3 text-right">{c.amount?money.format(c.amount):"-"}</td>]})}</tr>):<tr><td colSpan={16} className="p-8 text-center text-slate-400">Belum ada data bulan ini.</td></tr>}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-black dark:bg-slate-900"><td className="p-3" colSpan={2}>TOTAL</td>{all.flatMap(x=>{const t=total(x);return[<td key={`${x}-tq`} className="border-l p-3 text-right">{t.qty}</td>,<td key={`${x}-ta`} className="p-3 text-right">{money.format(t.amount)}</td>]})}</tr></tfoot></table></div></section>
 </div></main>
}
