"use client";
import {useEffect} from "react";

type LiveRow={name:string;liveStatus?:string;statusTone?:string;shiftStart?:string;shiftEnd?:string;shiftProgress?:number;paceTarget?:number};
type DailyStaff={id:string;name:string;position:string;status:string;amount:number;accessories:number;vas:number;qty:number;invoices:number;upt:number;atv:number;targets:{amount:number;accessories:number;vas:number}};
type DailyPayload={date:string;staff:DailyStaff[];total:{amount:number;target:number;accessories:number;accTarget:number;vas:number;vasTarget:number;qty:number;invoices:number;upt:number};error?:string};
const norm=(v:string)=>v.trim().toUpperCase().replace(/\s+/g," ");
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number.isFinite(v)?v:0);
const num=(v:number)=>new Intl.NumberFormat("id-ID").format(Number.isFinite(v)?v:0);
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const ach=(v:number,t:number)=>t?v/t*100:0;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const shareTime=()=>new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Jakarta"}).format(new Date()).replace(":",".");
function rr(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function clip(ctx:CanvasRenderingContext2D,text:string,max:number){if(ctx.measureText(text).width<=max)return text;let s=text;while(s.length>2&&ctx.measureText(s+"…").width>max)s=s.slice(0,-1);return s+"…"}
async function fetchDaily():Promise<DailyPayload>{const d=today(),r=await fetch(`/api/daily?date=${d}&t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(!r.ok||j?.error)throw new Error(j?.error||"Gagal membaca Daily Sales");return j}
async function makePicture(data:DailyPayload){
 const rows=data.staff||[],t=data.total,W=1800,p=58,g=20,cw=(W-p*2-g*3)/4,rh=72,hy=516,hh=64,H=Math.max(1050,hy+hh+rh*(rows.length+1)+100),c=document.createElement("canvas");c.width=W;c.height=H;const x=c.getContext("2d");if(!x)throw new Error("Canvas tidak tersedia");
 x.fillStyle="#f8fafc";x.fillRect(0,0,W,H);x.fillStyle="#fff";rr(x,28,28,W-56,H-56,28);x.fill();x.fillStyle="#2563eb";x.font="800 22px Arial";x.fillText("M238 • DAILY SALES",p,78);x.fillStyle="#0f172a";x.font="800 42px Arial";x.fillText("Digimap PIM 2",p,130);x.fillStyle="#64748b";x.font="600 24px Arial";x.fillText(new Intl.DateTimeFormat("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date()),p,170);x.textAlign="right";x.fillStyle="#94a3b8";x.font="500 18px Arial";x.fillText("Generated from M238 Dashboard",W-p,82);x.textAlign="left";
 const cards=[{a:"Target vs Achievement",b:`${money(t.amount)} / ${money(t.target)}`,c:pct(ach(t.amount,t.target)),d:"#2563eb"},{a:"VAS vs Achievement",b:`${money(t.vas)} / ${money(t.vasTarget)}`,c:pct(ach(t.vas,t.vasTarget)),d:"#059669"},{a:"ACC vs Achievement",b:`${money(t.accessories)} / ${money(t.accTarget)}`,c:pct(ach(t.accessories,t.accTarget)),d:"#7c3aed"},{a:"UPT",b:(t.upt||0).toFixed(1),c:`${num(t.qty)} unit / ${num(t.invoices)} transaksi`,d:"#d97706"}];
 cards.forEach((z,i)=>{const xx=p+i*(cw+g),y=215;x.fillStyle="#fff";x.strokeStyle="#e2e8f0";x.lineWidth=2;rr(x,xx,y,cw,160,20);x.fill();x.stroke();x.fillStyle=z.d;rr(x,xx+20,y+20,44,44,12);x.fill();x.fillStyle="#475569";x.font="700 20px Arial";x.fillText(z.a,xx+78,y+49);x.fillStyle="#0f172a";x.font="800 26px Arial";x.fillText(clip(x,z.b,cw-40),xx+20,y+102);x.fillStyle="#64748b";x.font="700 20px Arial";x.fillText(z.c,xx+20,y+137)});
 x.fillStyle="#0f172a";x.font="800 30px Arial";x.fillText("Daily Sales Staff",p,454);x.fillStyle="#64748b";x.font="500 19px Arial";x.fillText("Staff in-charge sesuai schedule hari berjalan",p,487);
 const cols=[{l:"Nama",w:360,a:"left"},{l:"Status",w:150,a:"left"},{l:"Target",w:205,a:"right"},{l:"ACC",w:170,a:"right"},{l:"VAS",w:170,a:"right"},{l:"Achievement",w:220,a:"right"},{l:"%",w:100,a:"right"},{l:"UPT",w:95,a:"right"},{l:"ATV",w:220,a:"right"}] as const;let xx=p;x.fillStyle="#f8fafc";x.fillRect(p,hy,W-p*2,hh);x.strokeStyle="#e2e8f0";x.strokeRect(p,hy,W-p*2,hh);x.font="800 18px Arial";x.fillStyle="#334155";for(const col of cols){x.textAlign=col.a==="right"?"right":"left";x.fillText(col.l,col.a==="right"?xx+col.w-14:xx+14,hy+39);xx+=col.w}x.textAlign="left";
 const row=(r:DailyStaff|undefined,i:number,total=false)=>{const y=hy+hh+i*rh;x.fillStyle=total?"#f1f5f9":i%2?"#fbfdff":"#fff";x.fillRect(p,y,W-p*2,rh);x.strokeStyle="#e2e8f0";x.beginPath();x.moveTo(p,y+rh);x.lineTo(W-p,y+rh);x.stroke();const v=total?["TOTAL","—",money(t.target),money(t.accessories),money(t.vas),money(t.amount),pct(ach(t.amount,t.target)),(t.upt||0).toFixed(1),money(t.invoices?t.amount/t.invoices:0)]:[r!.name,r!.status,money(r!.targets.amount),money(r!.accessories),money(r!.vas),money(r!.amount),pct(ach(r!.amount,r!.targets.amount)),r!.upt.toFixed(1),money(r!.atv)];let rx=p;cols.forEach((col,j)=>{x.textAlign=col.a==="right"?"right":"left";x.fillStyle="#0f172a";x.font=`${total?"800":"700"} ${j===0?19:18}px Arial`;const tx=col.a==="right"?rx+col.w-14:rx+14;x.fillText(clip(x,v[j],col.w-28),tx,y+(total?43:30));if(!total&&j===0){x.fillStyle="#94a3b8";x.font="500 15px Arial";x.fillText(clip(x,r!.position||"Sales Advisor",col.w-28),tx,y+54)}rx+=col.w});x.textAlign="left"};rows.forEach((r,i)=>row(r,i));row(undefined,rows.length,true);x.fillStyle="#94a3b8";x.font="500 17px Arial";x.fillText("Daily sales report • M238 PIM 2",p,H-45);return new Promise<Blob>((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error("Gagal membuat PNG")),"image/png",1))
}
export default function DailySalesAlerts(){
 useEffect(()=>{
  let stopped=false,lastFetch=0,data:{staff?:LiveRow[]}|null=null;
  const findTable=()=>{const section=Array.from(document.querySelectorAll("section")).find(x=>x.textContent?.includes("Daily Sales Staff"));return section?.querySelector("table")||null};
  const apply=()=>{const table=findTable();if(!table||!data?.staff)return;const head=Array.from(table.querySelectorAll("thead th")).map(x=>(x.textContent||"").trim().toLowerCase()),idx=head.findIndex(x=>x==="status");if(idx<0)return;const byName=new Map(data.staff.map(x=>[norm(x.name),x]));for(const tr of Array.from(table.querySelectorAll("tbody tr"))){const cells=Array.from(tr.querySelectorAll("td"));if(!cells.length||cells[0]?.textContent?.trim()==="TOTAL")continue;const meta=byName.get(norm(cells[0]?.querySelector("b")?.textContent||cells[0]?.textContent||""));if(meta&&cells[idx])cells[idx].textContent=meta.liveStatus||"—"}};
  const refresh=async()=>{if(!findTable())return;const now=Date.now();if(data&&now-lastFetch<55000){apply();return}lastFetch=now;try{const r=await fetch(`/api/daily?date=${today()}&t=${now}`,{cache:"no-store"}),j=await r.json();if(!stopped&&r.ok){data=j;apply()}}catch{}};
  const inject=()=>{const h=Array.from(document.querySelectorAll("h1")).find(x=>(x.textContent||"").trim()==="Daily Sales") as HTMLElement|undefined;if(!h)return;const root=h.closest("div.space-y-5") as HTMLElement|null;if(!root||root.querySelector("[data-daily-share]"))return;const box=document.createElement("div");box.dataset.dailyShare="1";box.className="export-hide rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950";box.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><p class="font-black">Share Report</p><p class="mt-1 text-xs text-slate-500">Daily Sales landscape • siap update ke WhatsApp</p></div><div class="flex flex-wrap gap-2"><button data-pic class="rounded-xl border px-4 py-2 text-sm font-black">Picture Screenshot</button><button data-share class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">Share WhatsApp</button></div></div><p data-note class="mt-2 text-xs font-semibold text-slate-500"></p>';const header=h.parentElement?.parentElement;if(header?.nextSibling)root.insertBefore(box,header.nextSibling);else root.prepend(box);const note=box.querySelector("[data-note]") as HTMLElement;const build=async()=>{const d=await fetchDaily(),b=await makePicture(d),stamp=shareTime(),file=new File([b],`M238-Daily-Sales-${d.date}-${stamp}.png`,{type:"image/png"});return{file,stamp}};(box.querySelector("[data-pic]") as HTMLButtonElement).onclick=async()=>{try{note.textContent="Membuat picture…";const{file}=await build(),u=URL.createObjectURL(file),a=document.createElement("a");a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);note.textContent="Picture Daily Sales berhasil dibuat."}catch(e){note.textContent=e instanceof Error?e.message:"Gagal membuat picture"}};(box.querySelector("[data-share]") as HTMLButtonElement).onclick=async()=>{try{note.textContent="Menyiapkan share…";const{file,stamp}=await build(),text=`M238 PIM 2\nUpdate sales jam ${stamp} WIB`;if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:"M238 Daily Sales",text});note.textContent=`Update sales jam ${stamp} WIB`}else{note.textContent="Share foto belum didukung browser ini."}}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))note.textContent=e instanceof Error?e.message:"Gagal share"}}};
  inject();void refresh();const timer=setInterval(()=>{inject();void refresh()},2000);return()=>{stopped=true;clearInterval(timer)};
 },[]);
 return null;
}
