"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {Clock3,TrendingDown,TrendingUp,Users} from "lucide-react";

type AnnualRow={period:string;label:string;amount:number};
type AnnualData={lastYear:AnnualRow[];thisYear:AnnualRow[];lastYearTotal:number;thisYearTotal:number};
type OverviewData={target:{amount:number;device:number;accessories:number;vas:number};summary:{amount:number;device:number;accessories:number;vas:number;upt:number;atv:number;point:number};annual:AnnualData};
type CompareData={period:string;cutoffDay:number;current:number;mtm:number;lfl:number;mtmGrowth:number;lflGrowth:number;previousPeriod:string;lastYearPeriod:string};
type DailyRow={id:string;name:string;accessories:number;vas:number};
type DailyData={staff:DailyRow[];total:{accessories:number;vas:number}};
type UploadInfo={timestamp:string;fileName:string;rows:number}|null;
type LoginRow={nik:string;name:string;count:number;lastLogin:string};
type LoginData={date:string;rows:LoginRow[];totalUsers:number;totalLogins:number;summary:string};

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=new Intl.NumberFormat("id-ID",{maximumFractionDigits:1});
const achievement=(v:number,t:number)=>t?v/t*100:0;
const currentPeriod=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const jakartaDateTime=(v:string)=>v?new Intl.DateTimeFormat("id-ID",{timeZone:"Asia/Jakarta",day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date(v)).replaceAll(".",":"):"—";

function Growth({value}:{value:number}){const good=value>=0;return <span className={`inline-flex items-center gap-1 font-black ${good?"text-emerald-600":"text-rose-600"}`}>{good?<TrendingUp className="size-4"/>:<TrendingDown className="size-4"/>}{good?"+":""}{pct.format(value)}%</span>}
function CompareCard({label,current,base,growth,sub}:{label:string;current:number;base:number;growth:number;sub:string}){const diff=current-base;return <div className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><p className="text-sm font-extrabold">{label}</p><div className="mt-3 grid grid-cols-2 gap-3"><div><p className="text-[11px] text-slate-400">This Month</p><b className="text-sm">{money.format(current)}</b></div><div><p className="text-[11px] text-slate-400">Compare</p><b className="text-sm">{money.format(base)}</b></div></div><div className="mt-3 flex items-center justify-between gap-3 border-t pt-3 text-xs"><span className={diff>=0?"text-emerald-600":"text-rose-600"}>{diff>=0?"+":""}{money.format(diff)}</span><Growth value={growth}/></div><p className="mt-2 text-[11px] text-slate-400">{sub}</p></div>}
function OverviewTargetCard({label,value,target}:{label:string;value:number;target:number}){const a=achievement(value,target),gap=a-100;return <div className="min-w-0 rounded-2xl border border-white/20 bg-white/10 p-3"><p className="text-[11px] text-blue-100">{label}</p><p className="mt-1 break-words text-base font-black sm:text-lg">{money.format(value)}</p><div className="mt-2 border-t border-white/15 pt-2 text-[11px]"><div className="flex items-center justify-between gap-2 text-blue-100"><span>Target {money.format(target)}</span><b className="text-white">{pct.format(a)}%</b></div><div className={`mt-1 font-black ${gap>=0?"text-emerald-200":"text-rose-200"}`}>{gap>=0?"+":""}{pct.format(gap)}% vs target</div></div></div>}
function ProductivityCard({upt,atv}:{upt:number;atv:number}){return <div className="min-w-0 rounded-2xl border border-white/20 bg-white/10 p-3"><p className="text-[11px] text-blue-100">UPT / ATV</p><div className="mt-2 grid grid-cols-2 gap-2"><div><span className="text-[10px] text-blue-100">UPT</span><b className="block text-lg">{upt.toFixed(1)}</b></div><div><span className="text-[10px] text-blue-100">ATV</span><b className="block break-words text-sm">{money.format(atv)}</b></div></div></div>}

export default function DashboardEnhancements(){
 const[period,setPeriod]=useState(currentPeriod());
 const[salesOverviewTarget,setSalesOverviewTarget]=useState<HTMLElement|null>(null),[revenueTarget,setRevenueTarget]=useState<HTMLElement|null>(null),[yearTarget,setYearTarget]=useState<HTMLElement|null>(null),[salesTarget,setSalesTarget]=useState<HTMLElement|null>(null),[settingsTarget,setSettingsTarget]=useState<HTMLElement|null>(null);
 const[overview,setOverview]=useState<OverviewData|null>(null),[compare,setCompare]=useState<CompareData|null>(null),[spwUpload,setSpwUpload]=useState<UploadInfo>(null),[dailyDetail,setDailyDetail]=useState<DailyData|null>(null),[loginData,setLoginData]=useState<LoginData|null>(null);

 useEffect(()=>{const load=()=>fetch(`/api/daily?date=${today()}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(setDailyDetail).catch(()=>{});void load();const id=setInterval(load,60000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const load=()=>fetch("/api/upload-status",{cache:"no-store"}).then(r=>r.json()).then(j=>setSpwUpload(j.spw||null)).catch(()=>{});void load();const id=setInterval(load,60000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const load=()=>fetch(`/api/login-activity?date=${today()}`,{cache:"no-store"}).then(r=>r.json()).then(setLoginData).catch(()=>{});void load();const id=setInterval(load,60000);return()=>clearInterval(id)},[]);

 useEffect(()=>{
  const sync=()=>{
   const labels=[...document.querySelectorAll("label")],monthLabel=labels.find(x=>x.querySelector("span")?.textContent?.trim()==="Filter Bulan"),select=monthLabel?.querySelector("select") as HTMLSelectElement|null;
   if(select&&select.value&&select.value!==period)setPeriod(select.value);
   if(select&&!select.dataset.m238EnhanceBound){select.dataset.m238EnhanceBound="1";select.addEventListener("change",()=>setPeriod(select.value))}

   const h=[...document.querySelectorAll("h2")].find(x=>x.textContent?.trim()==="M238 Sales Overview");
   if(h){const hero=h.closest("section") as HTMLElement|null,grid=hero?.querySelector(".grid.grid-cols-2.gap-2\\.5") as HTMLElement|null;if(grid){[...grid.children].forEach(c=>{if(c instanceof HTMLElement&&!c.dataset.salesOverviewPortal)c.style.display="none"});let host=grid.querySelector("[data-sales-overview-portal]") as HTMLElement|null;if(!host){host=document.createElement("div");host.dataset.salesOverviewPortal="1";host.className="contents";grid.appendChild(host)}if(host!==salesOverviewTarget)setSalesOverviewTarget(host)}const next=hero?.nextElementSibling as HTMLElement|null;if(next&&next.matches("section.grid"))next.style.display="none"}

   const revenue=[...document.querySelectorAll("h2")].find(x=>x.textContent?.trim()==="Revenue Analytics");
   if(revenue){const card=revenue.closest(".rounded-2xl"),content=card?.querySelector(":scope > .space-y-6") as HTMLElement|null;if(content){const first=content.firstElementChild as HTMLElement|null;if(first?.className.includes("sm:grid-cols-3"))first.style.display="none";let rh=content.querySelector("[data-revenue-compare]") as HTMLElement|null;if(!rh){rh=document.createElement("div");rh.dataset.revenueCompare="1";content.prepend(rh)}if(rh!==revenueTarget)setRevenueTarget(rh);let yh=content.querySelector("[data-year-compare]") as HTMLElement|null;if(!yh){yh=document.createElement("div");yh.dataset.yearCompare="1";content.appendChild(yh)}if(yh!==yearTarget)setYearTarget(yh)}}

   const dh=[...document.querySelectorAll("h1")].find(x=>x.textContent?.trim()==="Daily Sales");
   if(dh){const parent=dh.parentElement as HTMLElement|null;if(parent){let host=parent.querySelector("[data-sales-update]") as HTMLElement|null;if(!host){host=document.createElement("div");host.dataset.salesUpdate="1";host.className="mt-2";parent.appendChild(host)}if(host!==salesTarget)setSalesTarget(host)}}

   const sh=[...document.querySelectorAll("h1")].find(x=>x.textContent?.trim()==="Settings");
   if(sh){const root=sh.parentElement?.parentElement as HTMLElement|null;if(root){let host=root.querySelector("[data-login-activity]") as HTMLElement|null;if(!host){host=document.createElement("div");host.dataset.loginActivity="1";root.appendChild(host)}if(host!==settingsTarget)setSettingsTarget(host)}}

   const dsh=[...document.querySelectorAll("h2")].find(x=>x.textContent?.trim()==="Daily Sales Staff"),sec=dsh?.closest("section") as HTMLElement|null;
   if(sec&&dailyDetail){const header=sec.querySelector("thead tr"),targetTh=[...sec.querySelectorAll("thead th")].find(x=>x.textContent?.trim()==="Target");if(header&&targetTh&&!header.querySelector("[data-daily-acc]")){const acc=document.createElement("th");acc.dataset.dailyAcc="1";acc.className="h-10 px-2 text-right align-middle font-medium text-muted-foreground";acc.textContent="ACC";const vas=document.createElement("th");vas.dataset.dailyVas="1";vas.className=acc.className;vas.textContent="VAS";targetTh.insertAdjacentElement("afterend",vas);targetTh.insertAdjacentElement("afterend",acc)}const byName=new Map((dailyDetail.staff||[]).map(r=>[r.name.trim(),r]));for(const tr of sec.querySelectorAll("tbody tr")){if(tr.querySelector("[data-daily-acc-cell]"))continue;const cells=tr.querySelectorAll("td");if(cells.length<3)continue;const name=(cells[0].querySelector("b")?.textContent||cells[0].textContent||"").trim(),row=byName.get(name),isTotal=name==="TOTAL";if(!row&&!isTotal)continue;const a=isTotal?(dailyDetail.total?.accessories||0):(row?.accessories||0),v=isTotal?(dailyDetail.total?.vas||0):(row?.vas||0),anchor=cells[2],acc=document.createElement("td"),vas=document.createElement("td");acc.dataset.dailyAccCell="1";acc.className="p-2 align-middle text-right";acc.textContent=money.format(a);vas.className=acc.className;vas.textContent=money.format(v);anchor.insertAdjacentElement("afterend",vas);anchor.insertAdjacentElement("afterend",acc)}}
  };
  sync();const obs=new MutationObserver(sync);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect();
 },[salesOverviewTarget,revenueTarget,yearTarget,salesTarget,settingsTarget,period,dailyDetail]);

 useEffect(()=>{let alive=true;Promise.all([fetch(`/api/data?period=${period}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/overview-compare?period=${period}`,{cache:"no-store"}).then(r=>r.json())]).then(([d,c])=>{if(alive){setOverview(d);setCompare(c)}}).catch(()=>{});return()=>{alive=false}},[period]);

 const annual=overview?.annual||null;
 const pairs=useMemo(()=>{if(!annual)return[];const last=new Map(annual.lastYear.map(x=>[x.period.slice(5,7),x]));return annual.thisYear.map(y=>{const x=last.get(y.period.slice(5,7)),v25=x?.amount??0,v26=y.amount??0;return{label:y.label,v25,v26,diff:v26-v25,growth:v25?(v26-v25)/v25*100:0}})},[annual]);
 const totalGrowth=annual?.lastYearTotal?((annual.thisYearTotal-annual.lastYearTotal)/annual.lastYearTotal)*100:0,totalDiff=(annual?.thisYearTotal??0)-(annual?.lastYearTotal??0),s=overview?.summary,t=overview?.target;

 return <>
  {salesTarget&&createPortal(<div className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-sm dark:bg-slate-950 dark:text-slate-300"><Clock3 className="size-4 text-blue-600"/><span>Update sales terakhir: <b>{spwUpload?`${jakartaDateTime(spwUpload.timestamp)} WIB`:"Belum ada log upload SPW"}</b>{spwUpload?.fileName?` • ${spwUpload.fileName}`:""}</span></div>,salesTarget)}

  {salesOverviewTarget&&createPortal(<><OverviewTargetCard label="MTD Sales" value={s?.amount??0} target={t?.amount??0}/><OverviewTargetCard label="Device" value={s?.device??0} target={t?.device??0}/><OverviewTargetCard label="Accessories" value={s?.accessories??0} target={t?.accessories??0}/><OverviewTargetCard label="VAS" value={s?.vas??0} target={t?.vas??0}/><ProductivityCard upt={s?.upt??0} atv={s?.atv??0}/><div className="col-span-2 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-xs text-blue-100 sm:col-span-1"><span>Store Point</span><b className="ml-2 text-white">{pct.format(s?.point??0)}%</b><span className="ml-2 text-blue-200">• gabungan Device + ACC + VAS</span></div></>,salesOverviewTarget)}

  {revenueTarget&&compare&&createPortal(<div><h3 className="font-extrabold">Revenue Analytics H-1</h3><p className="mt-1 text-sm text-slate-500">This Month dibanding MTM dan LFL sampai H-1.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><CompareCard label="This Month vs MTM" current={compare.current} base={compare.mtm} growth={compare.mtmGrowth} sub={`s/d tanggal ${compare.cutoffDay} • ${compare.previousPeriod}`}/><CompareCard label="This Month vs Last Year" current={compare.current} base={compare.lfl} growth={compare.lflGrowth} sub={`s/d tanggal ${compare.cutoffDay} • ${compare.lastYearPeriod}`}/></div></div>,revenueTarget)}

  {yearTarget&&createPortal(<div className="space-y-4"><div><h3 className="font-extrabold">2025 vs 2026</h3><p className="mt-1 text-sm text-slate-500">Perbandingan revenue per bulan terhadap periode yang sama tahun sebelumnya.</p></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 dark:bg-slate-900"><tr><th className="px-3 py-3 text-left">Bulan</th><th className="px-3 py-3 text-right">2025</th><th className="px-3 py-3 text-right">2026</th><th className="px-3 py-3 text-right">Selisih</th><th className="px-3 py-3 text-right">Growth</th></tr></thead><tbody>{pairs.map(r=><tr key={r.label} className="border-t"><td className="px-3 py-3 font-bold">{r.label}</td><td className="px-3 py-3 text-right">{money.format(r.v25)}</td><td className="px-3 py-3 text-right font-bold">{money.format(r.v26)}</td><td className={`px-3 py-3 text-right font-semibold ${r.diff>=0?"text-emerald-600":"text-rose-600"}`}>{r.diff>=0?"+":""}{money.format(r.diff)}</td><td className="px-3 py-3 text-right"><Growth value={r.growth}/></td></tr>)}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-black dark:bg-slate-900"><td className="px-3 py-3">TOTAL</td><td className="px-3 py-3 text-right">{money.format(annual?.lastYearTotal??0)}</td><td className="px-3 py-3 text-right">{money.format(annual?.thisYearTotal??0)}</td><td className={`px-3 py-3 text-right ${totalDiff>=0?"text-emerald-600":"text-rose-600"}`}>{totalDiff>=0?"+":""}{money.format(totalDiff)}</td><td className="px-3 py-3 text-right"><Growth value={totalGrowth}/></td></tr></tfoot></table></div></div>,yearTarget)}

  {settingsTarget&&createPortal(<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex items-start gap-3"><span className="rounded-2xl bg-blue-50 p-3 text-blue-600"><Users className="size-6"/></span><div className="min-w-0 flex-1"><h3 className="font-extrabold">Team Login Activity</h3><p className="mt-1 text-sm text-slate-500">Keaktifan team berdasarkan login NIK hari ini.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-xs text-slate-400">Staff Aktif</span><b className="mt-1 block text-xl">{loginData?.totalUsers??0}</b></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-xs text-slate-400">Total Login Hari Ini</span><b className="mt-1 block text-xl">{loginData?.totalLogins??0}</b></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead><tr><th className="p-2 text-left">NIK</th><th className="p-2 text-left">Nama</th><th className="p-2 text-right">Login</th><th className="p-2 text-right">Terakhir</th></tr></thead><tbody>{(loginData?.rows||[]).map(r=><tr key={r.nik} className="border-t"><td className="p-2 font-mono text-xs">{r.nik}</td><td className="p-2 font-bold">{r.name}</td><td className="p-2 text-right font-black">{r.count}x</td><td className="p-2 text-right text-xs">{jakartaDateTime(r.lastLogin)}</td></tr>)}</tbody></table></div>{loginData?.summary&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs font-semibold text-blue-700">{loginData.summary}</p>}</div></div></section>,settingsTarget)}
 </>;
}
