"use client"
import {useEffect,useMemo,useState} from "react"
import {createPortal} from "react-dom"
import type {M238Payload,StaffMetric} from "@/lib/m238-types"

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0})
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`
const ach=(v:number,t:number)=>t?v/t*100:0
const currentPeriod=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date())

function Row({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="grid gap-1 border-b px-4 py-3 last:border-b-0 sm:grid-cols-[220px_1fr] sm:items-center"><div className="text-sm font-bold text-slate-500">{label}</div><div><div className="font-black text-slate-950 dark:text-slate-100">{value}</div>{sub&&<div className="text-xs text-slate-400">{sub}</div>}</div></div>}

export default function DashboardStaffInline(){
 const[target,setTarget]=useState<HTMLElement|null>(null),[visible,setVisible]=useState(false),[period,setPeriod]=useState(currentPeriod()),[staff,setStaff]=useState("ALL"),[data,setData]=useState<M238Payload|null>(null),[loading,setLoading]=useState(false)
 useEffect(()=>{const sync=()=>{const main=document.querySelector("main");const host=main?.querySelector(":scope > div.px-4") as HTMLElement|null;const crumb=main?.querySelector("header b")?.textContent?.trim();setTarget(host);setVisible(crumb==="Dashboard");if(host){const select=[...host.querySelectorAll("select")].find(x=>/^2026-(0[1-9]|1[0-2])$/.test((x as HTMLSelectElement).value)) as HTMLSelectElement|undefined;if(select&&select.value!==period)setPeriod(select.value)}};sync();const id=setInterval(sync,500);return()=>clearInterval(id)},[period])
 useEffect(()=>{if(!visible)return;setLoading(true);fetch(`/api/data?period=${period}`).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[period,visible])
 const rows=data?.monthlyStaff??[],selected=useMemo(()=>rows.find(x=>x.id===staff)||null,[rows,staff])
 if(!target||!visible)return null
 return createPortal(<section className="mt-5 space-y-4 rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div><h2 className="text-xl font-black">Produktivitas Staff</h2><p className="mt-1 text-sm text-slate-500">Pilih nama staff untuk melihat seluruh produktivitas bulan yang sedang dipilih di Dashboard.</p></div><label className="block max-w-md"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[.12em] text-slate-400">Filter Staff</span><select value={staff} onChange={e=>setStaff(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 text-sm font-semibold text-slate-700 dark:bg-slate-900 dark:text-slate-100"><option value="ALL">Pilih Staff</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{loading?<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-400 dark:bg-slate-900">Memuat produktivitas staff…</div>:selected?<StaffDetail r={selected}/>:<div className="rounded-xl bg-slate-50 p-4 text-sm text-slate-400 dark:bg-slate-900">Pilih salah satu staff untuk menampilkan seluruh rekap produktivitas.</div>}</section>,target)
}

function StaffDetail({r}:{r:StaffMetric}){const totalAch=ach(r.amount,r.targets.amount),deviceAch=ach(r.device,r.targets.device),accAch=ach(r.accessories,r.targets.accessories),vasAch=ach(r.vas,r.targets.vas);return <div className="space-y-4"><section className="rounded-2xl bg-gradient-to-br from-[#0872b9] to-[#075b97] p-5 text-white"><p className="text-sm text-blue-100">Detail Produktivitas Staff</p><h3 className="mt-1 text-2xl font-black">{r.name}</h3><p className="text-sm text-blue-100">{r.position||"Staff M238"}</p></section><div className="overflow-hidden rounded-2xl border bg-white dark:bg-slate-950"><Row label="Target vs Achievement" value={`${money.format(r.targets.amount)} / ${money.format(r.amount)}`} sub={pct(totalAch)}/><Row label="Device" value={`${money.format(r.device)} / ${money.format(r.targets.device)}`} sub={pct(deviceAch)}/><Row label="Accessories" value={`${money.format(r.accessories)} / ${money.format(r.targets.accessories)}`} sub={pct(accAch)}/><Row label="VAS" value={`${money.format(r.vas)} / ${money.format(r.targets.vas)}`} sub={pct(vasAch)}/><Row label="UPT" value={r.upt.toFixed(1)} sub={`${r.qty} unit / ${r.invoices} transaksi`}/><Row label="ATV" value={money.format(r.atv)}/><Row label="iPhone" value={`${r.lob.iphone} unit`}/><Row label="MacBook" value={`${r.lob.mac} unit`}/><Row label="iPad" value={`${r.lob.ipad} unit`}/><Row label="Apple Watch" value={`${r.lob.watch} unit`}/><Row label="AirPods" value={`${r.lob.airpods} unit`}/><Row label="Qoala" value={`${r.vasDetail.qoala.qty} qty • ${money.format(r.vasDetail.qoala.value)}`}/><Row label="Telkomsel" value={`${r.vasDetail.telkomsel.qty} qty • ${money.format(r.vasDetail.telkomsel.value)}`}/><Row label="XL" value={`${r.vasDetail.xl.qty} qty • ${money.format(r.vasDetail.xl.value)}`}/><Row label="Indosat" value={`${r.vasDetail.indosat.qty} qty • ${money.format(r.vasDetail.indosat.value)}`}/><Row label="Estimasi Incentive" value={money.format(r.incentive.total)} sub={`Device ${money.format(r.incentive.mac+r.incentive.iphone+r.incentive.ipad+r.incentive.watch)} • ACC ${money.format(r.incentive.accessories)} • Qoala ${money.format(r.incentive.qoala)}`}/></div></div>}
