"use client"

import {useCallback,useEffect,useMemo,useRef,useState} from "react"
import {BarChart3,Cloud,Database,FileSpreadsheet,Gauge,LayoutDashboard,Moon,RefreshCw,Sun,Target,TrendingUp,Upload,Users,WalletCards} from "lucide-react"
import {Progress} from "@/components/ui/progress"
import {Tabs,TabsContent} from "@/components/ui/tabs"
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table"
import type {M238Payload,StaffMetric} from "@/lib/m238-types"

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0})
const number=new Intl.NumberFormat("id-ID")
const one=new Intl.NumberFormat("id-ID",{maximumFractionDigits:1})
const pct=(v:number)=>`${one.format(v)}%`
const defaultPeriod=new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date())
const currentYear=Number(defaultPeriod.slice(0,4))
const months=Array.from({length:(currentYear+1-2025+1)*12},(_,i)=>{const year=2025+Math.floor(i/12),month=i%12+1;return`${year}-${String(month).padStart(2,"0")}`})
const monthName=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${v}-01T00:00:00Z`))
const ach=(value:number,target:number)=>target?value/target*100:0
const clamp=(v:number)=>Math.max(0,Math.min(100,v))
const shiftPeriod=(period:string,monthsDelta:number)=>{const d=new Date(`${period}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+monthsDelta);return d.toISOString().slice(0,7)}
const yearAgo=(period:string)=>`${Number(period.slice(0,4))-1}-${period.slice(5,7)}`
const dayOf=(date:string)=>Number(date.slice(8,10))||0
const alignedSales=(payload:M238Payload|null|undefined,day:number)=>payload?.daily.filter(x=>dayOf(x.date)<=day).reduce((a,x)=>a+x.amount,0)??0
const deltaPct=(value:number,base:number)=>base?(value-base)/base*100:null

function Select({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="block min-w-0"><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border bg-white px-3 text-sm font-semibold text-slate-700 outline-none focus:ring-2 focus:ring-blue-200">{children}</select></label>}
function Panel({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border bg-white shadow-[0_2px_3px_rgba(16,32,56,.04)] ${className}`}>{children}</section>}
function SectionTitle({title,sub,right}:{title:string;sub?:string;right?:React.ReactNode}){return <div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="font-extrabold text-slate-950">{title}</h2>{sub&&<p className="mt-1 text-sm text-slate-500">{sub}</p>}</div>{right}</div>}
function StatCard({label,value,sub}:{label:string;value:string;sub:string}){return <article className="rounded-2xl border bg-white p-4 shadow-[0_2px_3px_rgba(16,32,56,.04)]"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black tracking-[-.04em] text-slate-950">{value}</p><p className="mt-1.5 text-xs text-slate-400">{sub}</p></article>}
function StatusBadge({value}:{value:number}){const label=value>=100?"Achieved":value>=90?"On Track":value>=80?"Need Push":"Need Attention",style=value>=100?"bg-emerald-50 text-emerald-700":value>=90?"bg-blue-50 text-blue-700":value>=80?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${style}`}>{label}</span>}
function Empty(){return <TableRow><TableCell colSpan={20} className="h-28 text-center text-slate-400">Belum ada data pada periode ini.</TableCell></TableRow>}

export default function Dashboard(){
  const[tab,setTab]=useState("overview"),[period,setPeriod]=useState(defaultPeriod),[staff,setStaff]=useState("ALL"),[selectedStaff,setSelectedStaff]=useState<string|null>(null)
  const[data,setData]=useState<M238Payload|null>(null),[prevMonth,setPrevMonth]=useState<M238Payload|null>(null),[prevYear,setPrevYear]=useState<M238Payload|null>(null)
  const[loading,setLoading]=useState(true),[compareLoading,setCompareLoading]=useState(false),[error,setError]=useState("")
  const[message,setMessage]=useState(""),[invoice,setInvoice]=useState(""),[saving,setSaving]=useState(false),[uploadStatus,setUploadStatus]=useState(""),[dark,setDark]=useState(false)
  const uploadingRef=useRef(false),fileRef=useRef<HTMLInputElement>(null)

  useEffect(()=>{const saved=localStorage.getItem("m238-theme"),enabled=saved?saved==="dark":window.matchMedia("(prefers-color-scheme: dark)").matches;document.documentElement.classList.toggle("dark",enabled);setDark(enabled)},[])
  const toggleTheme=()=>{const next=!dark;setDark(next);document.documentElement.classList.toggle("dark",next);localStorage.setItem("m238-theme",next?"dark":"light")}
  const load=useCallback(async(force=false)=>{setLoading(true);setError("");try{const suffix=force?`&refresh=1&t=${Date.now()}`:"",r=await fetch(`/api/data?period=${period}${suffix}`,force?{cache:"no-store"}:undefined);if(!r.ok)throw new Error(`HTTP ${r.status}`);const payload=await r.json() as M238Payload;setData(payload);if(payload.mode==="live")localStorage.setItem(`m238-dashboard:${period}`,JSON.stringify(payload))}catch(e){setError(e instanceof Error?e.message:"Gagal memuat dashboard")}finally{setLoading(false)}},[period])
  const loadComparisons=useCallback(async()=>{setCompareLoading(true);try{const[pMonth,pYear]=await Promise.all([fetch(`/api/data?period=${shiftPeriod(period,-1)}`).then(r=>r.json() as Promise<M238Payload>),fetch(`/api/data?period=${yearAgo(period)}`).then(r=>r.json() as Promise<M238Payload>)]);setPrevMonth(pMonth);setPrevYear(pYear)}catch{setPrevMonth(null);setPrevYear(null)}finally{setCompareLoading(false)}},[period])

  useEffect(()=>{try{const cached=localStorage.getItem(`m238-dashboard:${period}`);if(cached){const payload=JSON.parse(cached)as M238Payload,age=Date.now()-new Date(payload.generatedAt).getTime();if(age<5*60*1000)setData(payload)}}catch{}void load();void loadComparisons();const timer=window.setInterval(()=>{if(!uploadingRef.current)void load()},60*1000);return()=>window.clearInterval(timer)},[period,load,loadComparisons])

  const changePeriod=(value:string)=>{setPeriod(value);setStaff("ALL");setSelectedStaff(null)}
  const monthlyStaff=useMemo(()=>data?.monthlyStaff.filter(x=>staff==="ALL"||x.id===staff)??[],[data,staff])
  const selected=useMemo(()=>data?.monthlyStaff.find(x=>x.id===selectedStaff)??null,[data,selectedStaff])
  const updated=data?new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(new Date(data.generatedAt)):"—"

  const upload=async()=>{const file=fileRef.current?.files?.[0];if(!file)return setMessage("Pilih file Excel SPW terlebih dahulu.");setSaving(true);uploadingRef.current=true;setUploadStatus("Mengunggah file SPW…");setMessage("");try{const body=new FormData();body.append("file",file);const r=await fetch("/api/upload-spw",{method:"POST",body}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload gagal");setMessage(`Upload ${number.format(j.rows)} baris berhasil.`);if(fileRef.current)fileRef.current.value="";setUploadStatus("Memperbarui data dashboard…");window.setTimeout(()=>{void load(true).finally(()=>setUploadStatus(""))},2500)}catch(e){setMessage(e instanceof Error?e.message:"Upload gagal");setUploadStatus("")}finally{setSaving(false);uploadingRef.current=false}}
  const saveInvoice=async()=>{if(!invoice.trim())return;setSaving(true);setMessage("");try{const r=await fetch("/api/exchange",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoice:invoice.trim()})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Penyimpanan gagal");setMessage(`Invoice ${j.invoice} berhasil disimpan.`);setInvoice("");await load(true)}catch(e){setMessage(e instanceof Error?e.message:"Penyimpanan gagal")}finally{setSaving(false)}}

  return <div className="min-h-screen lg:grid lg:grid-cols-[238px_minmax(0,1fr)]">
    <aside className="border-b bg-white lg:sticky lg:top-0 lg:h-screen lg:border-r lg:border-b-0"><div className="flex h-full flex-col p-4 lg:p-5"><div className="flex items-center gap-3 border-b pb-5"><div className="grid size-10 place-items-center rounded-xl bg-blue-600 text-sm font-black text-white">M238</div><div><p className="font-extrabold text-slate-950">Digimap PIM 2</p><p className="text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Performance Hub</p></div></div><nav className="mt-4 grid grid-cols-4 gap-2 lg:mt-6 lg:block lg:space-y-1.5"><Nav active={tab==="overview"} onClick={()=>setTab("overview")} icon={LayoutDashboard}>Pencapaian</Nav><Nav active={tab==="daily"} onClick={()=>setTab("daily")} icon={BarChart3}>Daily Store</Nav><Nav active={tab==="staff"} onClick={()=>setTab("staff")} icon={Users}>Staff</Nav><Nav active={tab==="admin"} onClick={()=>setTab("admin")} icon={Database}>Data</Nav></nav><div className="mt-auto hidden rounded-2xl border border-blue-100 bg-blue-50/70 p-4 lg:block"><div className="flex items-center gap-2 text-xs font-extrabold text-blue-700"><Cloud className="size-4"/>{data?.mode==="live"?"Master Sheet aktif":"Mode demonstrasi"}</div><p className="mt-2 text-xs leading-5 text-slate-500">Auto refresh 1 menit<br/><b className="text-slate-700">{updated}</b></p></div></div></aside>
    <main className="min-w-0 pb-10"><header className="sticky top-0 z-20 border-b bg-white/90 backdrop-blur-xl"><div className="flex items-center justify-between gap-3 px-4 py-3 sm:px-7"><div><p className="text-xs font-bold text-slate-400">M238 Dashboard</p><p className="text-sm font-extrabold text-slate-950">Pondok Indah Mall 2</p></div><div className="flex items-center gap-2"><button onClick={toggleTheme} className="rounded-xl border bg-white p-2.5 text-slate-600" aria-label="Ganti tema">{dark?<Sun className="size-4"/>:<Moon className="size-4"/>}</button><button onClick={()=>void load(true)} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-semibold text-slate-700"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/><span className="hidden sm:inline">Perbarui</span></button></div></div></header>
      <div className="px-4 pt-6 sm:px-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-slate-400">Digimap Pondok Indah Mall 2</p><h1 className="mt-1 text-2xl font-black tracking-[-.035em] text-slate-950 sm:text-3xl">{tab==="overview"?"Pencapaian Store":tab==="daily"?"Daily Store":tab==="staff"?"Staff Performance":"Data & Admin"}</h1></div><div className="w-full sm:w-56"><Select label="Periode" value={period} onChange={changePeriod}>{months.map(x=><option key={x} value={x}>{monthName(x)}</option>)}</Select></div></div>{error&&<div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">Gagal memuat data: {error}</div>}</div>
      <Tabs value={tab} className="mt-5 px-4 sm:px-7">
        <TabsContent value="overview"><Overview data={data} prevMonth={prevMonth} prevYear={prevYear} compareLoading={compareLoading}/></TabsContent>
        <TabsContent value="daily"><DailyStore data={data}/></TabsContent>
        <TabsContent value="staff"><StaffPerformance rows={monthlyStaff} allRows={data?.monthlyStaff??[]} staff={staff} setStaff={v=>{setStaff(v);setSelectedStaff(v==="ALL"?null:v)}} selected={selected} setSelectedStaff={setSelectedStaff}/></TabsContent>
        <TabsContent value="admin"><AdminPanel upload={upload} saveInvoice={saveInvoice} fileRef={fileRef} invoice={invoice} setInvoice={setInvoice} saving={saving} uploadStatus={uploadStatus} message={message}/></TabsContent>
      </Tabs>
    </main>
  </div>
}

function Nav({active,onClick,icon:Icon,children}:{active:boolean;onClick:()=>void;icon:typeof Users;children:React.ReactNode}){return <button onClick={onClick} className={`flex items-center justify-center gap-2 rounded-xl px-2 py-2.5 text-[11px] font-bold transition lg:w-full lg:justify-start lg:px-3 lg:text-sm ${active?"bg-blue-50 text-blue-600 ring-1 ring-blue-100":"text-slate-500 hover:bg-slate-50"}`}><Icon className="size-4"/>{children}</button>}

function Overview({data,prevMonth,prevYear,compareLoading}:{data:M238Payload|null;prevMonth:M238Payload|null;prevYear:M238Payload|null;compareLoading:boolean}){
  if(!data)return <LoadingBlock/>
  const s=data.summary,t=data.target,achievement=ach(s.amount,t.amount),gap=Math.max(0,t.amount-s.amount),lastDay=Math.max(1,...data.daily.map(x=>dayOf(x.date))),daysInMonth=new Date(Number(data.period.slice(0,4)),Number(data.period.slice(5,7)),0).getDate(),remaining=Math.max(0,daysInMonth-lastDay),need=remaining?gap/remaining:0
  const currentAligned=alignedSales(data,lastDay),mtm=deltaPct(currentAligned,alignedSales(prevMonth,lastDay)),lfl=deltaPct(currentAligned,alignedSales(prevYear,lastDay))
  const progress=[{label:"Total Sales",value:s.amount,target:t.amount},{label:"Device",value:s.device,target:t.device},{label:"Accessories",value:s.accessories,target:t.accessories},{label:"VAS",value:s.vas,target:t.vas}]
  const lowest=[{label:"Device",v:ach(s.device,t.device)},{label:"Accessories",v:ach(s.accessories,t.accessories)},{label:"VAS",v:ach(s.vas,t.vas)}].sort((a,b)=>a.v-b.v)[0]
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Sales Achievement" value={pct(achievement)} sub={`${money.format(s.amount)} / ${money.format(t.amount)}`}/><StatCard label="Sisa Target" value={money.format(gap)} sub={gap?"Masih perlu dikejar":"Target sudah tercapai"}/><StatCard label="Sisa Hari" value={`${remaining} Hari`} sub={`Data terakhir tanggal ${lastDay}`}/><StatCard label="Need / Day" value={money.format(need)} sub={remaining?"Rata-rata kebutuhan per hari":"Periode selesai"}/></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Panel><SectionTitle title="Progress Target" sub="Actual terhadap target periode"/><div className="space-y-5 p-5">{progress.map(x=>{const p=ach(x.value,x.target);return <div key={x.label}><div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-sm font-bold text-slate-700">{x.label}</p><p className="text-xs text-slate-400">{money.format(x.value)} / {money.format(x.target)}</p></div><b className={p>=100?"text-emerald-600":"text-slate-950"}>{pct(p)}</b></div><Progress value={clamp(p)}/></div>})}</div></Panel>
      <Panel><SectionTitle title="KPI Store" sub="Indikator utama store"/><div className="grid grid-cols-2 gap-px bg-slate-100 sm:grid-cols-5 xl:grid-cols-2"><Kpi label="LFL" value={compareLoading?"…":lfl===null?"—":`${lfl>=0?"+":""}${pct(lfl)}`} sub="vs periode sama tahun lalu" tone={lfl}/><Kpi label="MTM" value={compareLoading?"…":mtm===null?"—":`${mtm>=0?"+":""}${pct(mtm)}`} sub="vs bulan sebelumnya" tone={mtm}/><Kpi label="CVR" value="—" sub="Traffic belum tersedia"/><Kpi label="UPT" value={one.format(s.upt)} sub={`${number.format(s.qty)} item / ${number.format(s.invoices)} invoice`}/><Kpi label="ATV" value={money.format(s.atv)} sub="Rata-rata per invoice"/></div></Panel></div>
    <Panel><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-400">Store Insight</p><p className="mt-2 text-sm leading-6 text-slate-700">{lowest.v<100?`${lowest.label} saat ini paling tertinggal di ${pct(lowest.v)}. ${remaining?`Untuk total sales, store membutuhkan rata-rata ${money.format(need)} per hari selama ${remaining} hari tersisa.`:"Periode sudah selesai."}`:`Seluruh kategori utama sudah mencapai target. Total store berada di ${pct(achievement)}.`}</p></div><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">Point {one.format(s.point)}</span></div></Panel>
  </div>
}

function Kpi({label,value,sub,tone}:{label:string;value:string;sub:string;tone?:number|null}){const c=tone===undefined||tone===null?"text-slate-950":tone>=0?"text-emerald-600":"text-rose-600";return <div className="bg-white p-4"><p className="text-xs font-semibold text-slate-400">{label}</p><p className={`mt-1.5 text-xl font-black ${c}`}>{value}</p><p className="mt-1 text-[11px] leading-4 text-slate-400">{sub}</p></div>}

function DailyStore({data}:{data:M238Payload|null}){
  if(!data)return <LoadingBlock/>
  const s=data.summary,t=data.target
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Sales" value={money.format(s.amount)} sub={`${number.format(s.invoices)} invoice · ${number.format(s.qty)} item`}/><StatCard label="Achievement" value={pct(ach(s.amount,t.amount))} sub={`Target ${money.format(t.amount)}`}/><StatCard label="UPT" value={one.format(s.upt)} sub="Unit per transaction"/><StatCard label="ATV" value={money.format(s.atv)} sub="Average transaction value"/></div>
    <Panel><div className="grid divide-y sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Mini label="Device" value={money.format(s.device)} sub={pct(ach(s.device,t.device))}/><Mini label="Accessories" value={money.format(s.accessories)} sub={pct(ach(s.accessories,t.accessories))}/><Mini label="VAS" value={money.format(s.vas)} sub={pct(ach(s.vas,t.vas))}/></div></Panel>
    <Panel><SectionTitle title="Daily Sales" sub={`${monthName(data.period)} · ${data.daily.length} hari transaksi`}/><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Tanggal</TableHead><TableHead className="text-right">Sales</TableHead><TableHead className="text-right">Device</TableHead><TableHead className="text-right">Accessories</TableHead><TableHead className="text-right">VAS</TableHead><TableHead className="text-right">Invoice</TableHead><TableHead className="text-right">Qty</TableHead><TableHead className="text-right">UPT</TableHead><TableHead className="text-right">ATV</TableHead></TableRow></TableHeader><TableBody>{data.daily.length?data.daily.map(d=><TableRow key={d.date}><TableCell><b>{new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short"}).format(new Date(`${d.date}T00:00:00`))}</b><span className="ml-2 text-xs text-slate-400">{new Intl.DateTimeFormat("id-ID",{weekday:"short"}).format(new Date(`${d.date}T00:00:00`))}</span></TableCell><TableCell className="text-right font-extrabold">{money.format(d.amount)}</TableCell><TableCell className="text-right">{money.format(d.device)}</TableCell><TableCell className="text-right">{money.format(d.accessories)}</TableCell><TableCell className="text-right">{money.format(d.vas)}</TableCell><TableCell className="text-right">{number.format(d.invoices)}</TableCell><TableCell className="text-right">{number.format(d.qty)}</TableCell><TableCell className="text-right">{one.format(d.upt)}</TableCell><TableCell className="text-right">{money.format(d.atv)}</TableCell></TableRow>):<Empty/>}</TableBody></Table></Panel>
  </div>
}

function Mini({label,value,sub}:{label:string;value:string;sub:string}){return <div className="p-4"><p className="text-xs font-semibold text-slate-400">{label}</p><div className="mt-1 flex items-baseline justify-between gap-3"><b className="text-lg text-slate-950">{value}</b><span className="text-xs font-bold text-blue-600">{sub}</span></div></div>}

function StaffPerformance({rows,allRows,staff,setStaff,selected,setSelectedStaff}:{rows:StaffMetric[];allRows:StaffMetric[];staff:string;setStaff:(v:string)=>void;selected:StaffMetric|null;setSelectedStaff:(v:string|null)=>void}){
  const sorted=[...rows].sort((a,b)=>ach(b.amount,b.targets.amount)-ach(a.amount,a.targets.amount)),allSorted=[...allRows].sort((a,b)=>ach(b.amount,b.targets.amount)-ach(a.amount,a.targets.amount)),top=allSorted[0],avgAch=allRows.length?allRows.reduce((a,r)=>a+ach(r.amount,r.targets.amount),0)/allRows.length:0,avgUpt=allRows.length?allRows.reduce((a,r)=>a+r.upt,0)/allRows.length:0,avgAtv=allRows.length?allRows.reduce((a,r)=>a+r.atv,0)/allRows.length:0,attention=allRows.filter(r=>ach(r.amount,r.targets.amount)<80).length
  return <div className="space-y-4"><Panel className="p-4"><div className="max-w-sm"><Select label="Filter Staff" value={staff} onChange={setStaff}><option value="ALL">Semua Staff</option>{allRows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></div></Panel>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Top Performer" value={top?.name??"—"} sub={top?pct(ach(top.amount,top.targets.amount)):"Belum ada data"}/><StatCard label="Avg Achievement" value={pct(avgAch)} sub="Rata-rata seluruh staff"/><StatCard label="Avg UPT" value={one.format(avgUpt)} sub="Rata-rata seluruh staff"/><StatCard label="Avg ATV" value={money.format(avgAtv)} sub="Rata-rata seluruh staff"/><StatCard label="Need Attention" value={`${attention} Staff`} sub="Achievement di bawah 80%"/></div>
    <Panel><SectionTitle title="Staff Ranking" sub="Klik nama staff untuk melihat detail"/><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>#</TableHead><TableHead>Staff</TableHead><TableHead className="text-right">Sales</TableHead><TableHead className="text-right">Target</TableHead><TableHead className="text-right">Ach</TableHead><TableHead className="text-right">Accessories</TableHead><TableHead className="text-right">VAS</TableHead><TableHead className="text-right">UPT</TableHead><TableHead className="text-right">ATV</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{sorted.length?sorted.map((r,i)=>{const a=ach(r.amount,r.targets.amount);return <TableRow key={r.id} className="cursor-pointer" onClick={()=>setSelectedStaff(r.id)}><TableCell className="font-bold text-slate-400">{i+1}</TableCell><TableCell><b className="text-slate-950">{r.name}</b><div className="text-xs text-slate-400">{pct(r.share*100)} target share</div></TableCell><TableCell className="text-right font-extrabold">{money.format(r.amount)}</TableCell><TableCell className="text-right">{money.format(r.targets.amount)}</TableCell><TableCell className={`text-right font-black ${a>=100?"text-emerald-600":a<80?"text-rose-600":"text-slate-950"}`}>{pct(a)}</TableCell><TableCell className="text-right">{money.format(r.accessories)}</TableCell><TableCell className="text-right">{money.format(r.vas)}</TableCell><TableCell className="text-right">{one.format(r.upt)}</TableCell><TableCell className="text-right">{money.format(r.atv)}</TableCell><TableCell><StatusBadge value={a}/></TableCell></TableRow>}):<Empty/>}</TableBody></Table></Panel>
    {selected&&<Panel><SectionTitle title={selected.name} sub="Detail performance staff" right={<button onClick={()=>setSelectedStaff(null)} className="rounded-lg border px-3 py-1.5 text-xs font-bold text-slate-500">Tutup</button>}/><div className="grid gap-3 p-5 sm:grid-cols-2 xl:grid-cols-4"><Mini label="Sales" value={money.format(selected.amount)} sub={pct(ach(selected.amount,selected.targets.amount))}/><Mini label="Accessories" value={money.format(selected.accessories)} sub={pct(ach(selected.accessories,selected.targets.accessories))}/><Mini label="VAS" value={money.format(selected.vas)} sub={pct(ach(selected.vas,selected.targets.vas))}/><Mini label="UPT / ATV" value={`${one.format(selected.upt)} / ${money.format(selected.atv)}`} sub={`${number.format(selected.invoices)} invoice`}/></div><div className="border-t p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Estimasi Incentive</p><div className="mt-3 grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(selected.incentive).filter(([k])=>k!=="total").map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">{k}</p><p className="mt-1 text-sm font-extrabold text-slate-950">{money.format(v)}</p></div>)}</div><p className="mt-4 text-sm font-bold text-slate-700">Total: <span className="text-blue-600">{money.format(selected.incentive.total)}</span></p></div></Panel>}
  </div>
}

function AdminPanel({upload,saveInvoice,fileRef,invoice,setInvoice,saving,uploadStatus,message}:{upload:()=>void;saveInvoice:()=>void;fileRef:React.RefObject<HTMLInputElement|null>;invoice:string;setInvoice:(v:string)=>void;saving:boolean;uploadStatus:string;message:string}){return <div className="grid gap-4 xl:grid-cols-2"><Panel><SectionTitle title="Upload SPW" sub="Perbarui data RAW SalesPerson dari file Excel"/><div className="space-y-4 p-5"><input ref={fileRef} type="file" accept=".xlsx,.xls" className="block w-full rounded-xl border bg-white p-3 text-sm text-slate-600"/><button onClick={upload} disabled={saving} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Upload className="size-4"/>{saving?"Memproses…":"Upload SPW"}</button>{uploadStatus&&<p className="text-sm font-semibold text-blue-600">{uploadStatus}</p>}</div></Panel><Panel><SectionTitle title="Invoice Exchange" sub="Tambahkan invoice ke daftar exchange"/><div className="space-y-4 p-5"><input value={invoice} onChange={e=>setInvoice(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")saveInvoice()}} placeholder="Masukkan nomor invoice" className="h-11 w-full rounded-xl border bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-blue-200"/><button onClick={saveInvoice} disabled={saving||!invoice.trim()} className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><FileSpreadsheet className="size-4"/>Simpan Invoice</button></div></Panel>{message&&<div className="xl:col-span-2 rounded-xl border bg-white px-4 py-3 text-sm font-semibold text-slate-700">{message}</div>}</div>}

function LoadingBlock(){return <div className="grid min-h-56 place-items-center rounded-2xl border bg-white"><div className="flex items-center gap-2 text-sm font-semibold text-slate-400"><RefreshCw className="size-4 animate-spin"/>Memuat data…</div></div>}
