"use client";
import {useState,type RefObject} from "react";
import {ChevronDown,Download,FileImage,FileSpreadsheet,FileText,LoaderCircle,Share2} from "lucide-react";

export function ExportMenu({onXls,onPdf,onPicture}:{onXls:()=>Promise<void>;onPdf:()=>Promise<void>;onPicture:()=>Promise<void>}){
 const[open,setOpen]=useState(false),[busy,setBusy]=useState("");
 const run=async(label:string,fn:()=>Promise<void>)=>{setBusy(label);setOpen(false);try{await fn()}catch(e){alert(e instanceof Error?e.message:"File gagal dibuat") }finally{setBusy("")}};
 const items=[{label:"XLS",icon:FileSpreadsheet,fn:onXls},{label:"PDF",icon:FileText,fn:onPdf},{label:"Picture Screenshot",icon:FileImage,fn:onPicture}];
 return <div className="export-hide relative z-30"><button type="button" disabled={!!busy} onClick={()=>setOpen(v=>!v)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-black text-white">{busy?<LoaderCircle className="size-4 animate-spin"/>:<Download className="size-4"/>}{busy?`Membuat ${busy}...`:"Unduh"}{!busy&&<ChevronDown className="size-4"/>}</button>{open&&<div className="absolute right-0 mt-2 w-56 rounded-xl border bg-white p-1.5 shadow-xl dark:bg-slate-950">{items.map(x=>{const I=x.icon;return <button key={x.label} onClick={()=>void run(x.label,x.fn)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-bold"><I className="size-4 text-blue-600"/>{x.label}</button>})}</div>}</div>
}

const bad=/(lab\(|oklab\(|lch\(|oklch\(|color\()/i;
function safe(prop:string,value:string){if(!bad.test(value))return value;prop=prop.toLowerCase();if(prop.includes("shadow")||prop==="background-image")return"none";if(prop.includes("background"))return"#ffffff";if(prop.includes("border")&&prop.includes("color"))return"#e2e8f0";if(prop.includes("color")||prop==="fill"||prop==="stroke")return"#0f172a";return"initial"}
function cloneInline(node:HTMLElement){const c=node.cloneNode(true) as HTMLElement,aa=[node,...Array.from(node.querySelectorAll<HTMLElement>("*"))],bb=[c,...Array.from(c.querySelectorAll<HTMLElement>("*"))];for(let i=0;i<Math.min(aa.length,bb.length);i++){const cs=getComputedStyle(aa[i]),el=bb[i];el.removeAttribute("class");el.removeAttribute("style");for(let j=0;j<cs.length;j++){const p=cs.item(j);if(!p||p.startsWith("--"))continue;try{el.style.setProperty(p,safe(p,cs.getPropertyValue(p)))}catch{}}}c.style.width=`${Math.ceil(node.getBoundingClientRect().width||720)}px`;c.style.maxWidth="none";c.style.background="#fff";c.style.color="#0f172a";return c}
function toBlob(canvas:HTMLCanvasElement){return new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("Gagal membuat PNG")),"image/png"))}
function load(url:string){return new Promise<HTMLImageElement>((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Renderer tidak didukung"));i.src=url})}
async function svgRender(node:HTMLElement){const c=cloneInline(node);document.body.appendChild(c);c.style.position="fixed";c.style.left="-100000px";await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const w=Math.max(c.scrollWidth,c.clientWidth,320),h=Math.max(c.scrollHeight,c.clientHeight,240);c.style.position="relative";c.style.left="0";const html=new XMLSerializer().serializeToString(c);c.remove();const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml" style="background:#fff;width:${w}px;min-height:${h}px">${html}</div></foreignObject></svg>`;const u=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));try{const img=await load(u),s=Math.min(2,devicePixelRatio||1),cv=document.createElement("canvas");cv.width=w*s;cv.height=h*s;const x=cv.getContext("2d");if(!x)throw new Error("Canvas tidak tersedia");x.scale(s,s);x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(img,0,0,w,h);return await toBlob(cv)}finally{URL.revokeObjectURL(u)}}
async function textRender(node:HTMLElement){const lines=(node.innerText||"Report M238").split("\n").map(x=>x.trim()).filter(Boolean),cv=document.createElement("canvas");cv.width=1080;cv.height=Math.max(500,140+lines.length*52);const x=cv.getContext("2d");if(!x)throw new Error("Canvas tidak tersedia");x.fillStyle="#fff";x.fillRect(0,0,cv.width,cv.height);x.fillStyle="#0f172a";x.font="600 34px Arial";lines.forEach((l,i)=>x.fillText(l.slice(0,60),70,80+i*52));return toBlob(cv)}
async function render(node:HTMLElement){try{return await svgRender(node)}catch{return await textRender(node)}}

export function PictureShareActions({targetRef,filename,shareText}:{targetRef:RefObject<HTMLElement|null>;filename:string;shareText:string}){
 const[busy,setBusy]=useState<"picture"|"share"|"">(""),[notice,setNotice]=useState("");
 const file=async()=>{if(!targetRef.current)throw new Error("Area report belum siap");const b=await render(targetRef.current);return new File([b],`${filename.replace(/[^a-zA-Z0-9._-]+/g,"-")}.png`,{type:"image/png"})};
 const download=async()=>{setBusy("picture");setNotice("");try{const f=await file(),u=URL.createObjectURL(f),a=document.createElement("a");a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);setNotice("Picture PNG berhasil dibuat.")}catch(e){setNotice(e instanceof Error?e.message:"Gagal membuat picture")}finally{setBusy("")}};
 const share=async()=>{setBusy("share");setNotice("");try{const f=await file();if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){await navigator.share({files:[f],title:shareText,text:shareText});setNotice("Picture siap dibagikan.")}else{const u=URL.createObjectURL(f),a=document.createElement("a");a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);setNotice("PNG dibuat. Browser belum mendukung share file.")}}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setNotice(e instanceof Error?e.message:"Gagal membagikan picture")}finally{setBusy("")}};
 return <div className="export-hide"><div className="flex flex-wrap gap-2"><button disabled={!!busy} onClick={()=>void download()} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-black">{busy==="picture"?<LoaderCircle className="size-4 animate-spin"/>:<FileImage className="size-4"/>}Picture Screenshot</button><button disabled={!!busy} onClick={()=>void share()} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">{busy==="share"?<LoaderCircle className="size-4 animate-spin"/>:<Share2 className="size-4"/>}Share WhatsApp</button></div>{notice&&<p className="mt-2 text-xs font-semibold text-slate-500">{notice}</p>}</div>
}
