"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Download,X} from "lucide-react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=new Intl.NumberFormat("id-ID",{maximumFractionDigits:1});
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const addDays=(date:string,days:number)=>{const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
const diffDays=(a:string,b:string)=>Math.round((new Date(`${b}T00:00:00Z`).getTime()-new Date(`${a}T00:00:00Z`).getTime())/86400000)+1;
const displayDate=(v:string)=>new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${v}T00:00:00Z`));
type Inc={mac:number;iphone:number;ipad:number;watch:number;accessories:number;qoala:number;total:number};
type Qty={mac:number;iphone:number;ipad:number;watch:number;accessories:number;qoala:number};
type Row={id:string;name:string;incentive:Inc;qty:Qty;activeDays:number;rates:{accessories:Record<string,number>;qoala:Record<string,number>}};
type Payload={from:string;to:string;rows:Row[];total:number;error?:string};
const categories:[keyof Omit<Inc,"total">,string][]=[["mac","MacBook"],["iphone","iPhone"],["ipad","iPad"],["watch","Apple Watch"],["accessories","Accessories"],["qoala","Qoala"]];
function rateDetail(r:Row,key:keyof Omit<Inc,"total">){if(key==="accessories"||key==="qoala"){const parts=Object.entries(r.rates[key]).sort((a,b)=>Number(a[0])-Number(b[0])).map(([rate,q])=>`${num.format(q)} eligible × ${money.format(Number(rate))}`);return parts.length?`${parts.join(" + ")} = ${money.format(r.incentive[key])}`:`0 eligible = ${money.format(0)}`;}return `${num.format(r.qty[key])} unit eligible = ${money.format(r.incentive[key])}`}
export default function IncentiveRangePage(){
 const now=today(),[from,setFrom]=useState(`${now.slice(0,7)}-01`),[to,setTo]=useState(now),[staff,setStaff]=useState("all"),[data,setData]=useState<Payload|null>(null),[previous,setPrevious]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[detail,setDetail]=useState<Row|null>(null),[exportOpen,setExportOpen]=useState(false);const exportRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!from||!to||from>to)return;let alive=true;setLoading(true);const days=diffDays(from,to),prevTo=addDays(from,-1),prevFrom=addDays(prevTo,-days+1);Promise.all([fetch(`/api/incentive-range?from=${from}&to=${to}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/incentive-range?from=${prevFrom}&to=${prevTo}`,{cache:"no-store"}).then(r=>r.json()).catch(()=>null)]).then(([j,p])=>{if(!alive)return;setData(j);setPrevious(p?.error?null:p)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[from,to]);
 const teamRows=data?.rows||[],filtered=staff==="all"?teamRows:teamRows.filter(r=>r.id===staff),teamTotal=data?.total||0,total=filtered.reduce((a,r)=>a+r.incentive.total,0),device=filtered.reduce((a,r)=>a+r.incentive.mac+r.incentive.iphone+r.incentive.ipad+r.incentive.watch,0),accessories=filtered.reduce((a,r)=>a+r.incentive.accessories,0),qoala=filtered.reduce((a,r)=>a+r.incentive.qoala,0),activeStaff=teamRows.filter(r=>r.incentive.total>0).length,top=teamRows[0]||null,avgStaff=activeStaff?teamTotal/activeStaff:0,selected=staff==="all"?null:teamRows.find(r=>r.id===staff)||null;
 const highest=useMemo(()=>{const source=selected?[selected]:teamRows;return categories.map(([key,label])=>({key,label,value:source.reduce((a,r)=>a+r.incentive[key],0)})).sort((a,b)=>b.value-a.value)[0]||{key:"mac",label:"MacBook",value:0}},[selected,teamRows]);
 const prevTeam=previous?.total||0,prevSelected=selected?previous?.rows?.find(r=>r.id===selected.id)?.incentive.total||0:prevTeam,compareBase=selected?prevSelected:prevTeam,compare=compareBase?total-compareBase:null;
 const doXls=async()=>{const XLSX=await import("xlsx");const rows=filtered.map((r,i)=>({Rank:teamRows.findIndex(x=>x.id===r.id)+1,Nama:r.name,MacBook:r.incentive.mac,iPhone:r.incentive.iphone,iPad:r.incentive.ipad,"Apple Watch":r.incentive.watch,Accessories:r.incentive.accessories,Qoala:r.incentive.qoala,Contribution:teamTotal?r.incentive.total/teamTotal:0,Total:r.incentive.total}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,"Incentive");XLSX.writeFile(wb,`M238_Incentive_${from}_${to}.xlsx`);setExportOpen(false)};
 const capture=async(mode:"pdf"|"png")=>{if(!exportRef.current)return;const html2canvas=(await import("html2canvas")).default,canvas=await html2canvas(exportRef.current,{scale:2,backgroundColor:"#ffffff"});if(mode==="png"){const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`M238_Incentive_${from}_${to}.png`;a.click()}else{const{jsPDF}=await import("jspdf"),pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"}),img=canvas.toDataURL("image/png"),w=277,h=canvas.height*w/canvas.width;pdf.addImage(img,"PNG",10,10,w,Math.min(h,190));pdf.save(`M238_Incentive_${from}_${to}.pdf`)}setExportOpen(false)};
 if(loading)return <div className="m238-soft-card p-8 text-center text-slate-500">Memuat incentive…</div>;
 if(data?.error)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{data.error}</div>;
 return <div className="space-y-5" ref={exportRef}><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238</p><h2 className="mt-1 text-3xl font-black">Estimasi Incentive</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Default tanggal 1 bulan berjalan sampai hari ini. Range bebas lintas bulan.</p></div>
 <section className="m238-soft-card p-4"><div className="grid gap-3 sm:grid-cols-3"><label><span className="mb-1 block text-xs font-bold text-slate-500">Dari Tanggal</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><label><span className="mb-1 block text-xs font-bold text-slate-500">Sampai Tanggal</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><label><span className="mb-1 block text-xs font-bold text-slate-500">Staff</span><select value={staff} onChange={e=>setStaff(e.target.value)} className="h-11 w-full rounded-xl border px-3"><option value="all">Semua Staff</option>{teamRows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></div>{from>to&&<p className="mt-3 text-sm font-bold text-rose-600">Tanggal awal tidak boleh melebihi tanggal akhir.</p>}</section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="m238-soft-card p-4"><p className="text-xs font-bold text-slate-500">TOTAL EST. INCENTIVE</p><p className="mt-2 text-2xl font-black">{money.format(total)}</p><p className="mt-1 text-xs text-slate-400">{displayDate(from)} – {displayDate(to)}</p></div>{[["Device",device],["Accessories",accessories],["Qoala",qoala]].map(([label,val])=><div key={String(label)} className="m238-soft-card p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{money.format(Number(val))}</p></div>)}</section>
 <section className="m238-soft-card p-4"><div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm">{selected?<><span><b>Contribution to Total Team:</b> {pct.format(teamTotal?selected.incentive.total/teamTotal*100:0)}%</span><span><b>Avg Incentive / Active Day:</b> {money.format(selected.activeDays?selected.incentive.total/selected.activeDays:0)}</span><span><b>Highest Category:</b> {highest.label} — {money.format(highest.value)}</span></>:<><span><b>Top Staff:</b> {top?`${top.name} — ${money.format(top.incentive.total)}`:"—"}</span><span><b>Avg/Staff:</b> {money.format(avgStaff)}</span><span><b>Active Staff:</b> {activeStaff}</span><span><b>Highest Category:</b> {highest.label} — {money.format(highest.value)}</span></>}<span><b>vs Previous:</b> {compare===null?"No comparison data":`${compare>=0?"▲":"▼"} ${money.format(Math.abs(compare))} (${pct.format(compareBase?Math.abs(compare)/compareBase*100:0)}%)`}</span><div className="relative ml-auto"><button onClick={()=>setExportOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 font-bold"><Download className="size-4"/>Unduh</button>{exportOpen&&<div className="absolute right-0 top-11 z-20 w-48 rounded-xl border bg-white p-1 shadow-lg"><button onClick={doXls} className="w-full rounded-lg px-3 py-2 text-left hover:bg-slate-50">XLS</button><button onClick={()=>void capture("pdf")} className="w-full rounded-lg px-3 py-2 text-left hover:bg-slate-50">PDF</button><button onClick={()=>void capture("png")} className="w-full rounded-lg px-3 py-2 text-left hover:bg-slate-50">Picture / Screenshot</button></div>}</div></div></section>
 <section className="m238-soft-card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead><tr><th className="px-3 py-3 text-center">#</th><th className="px-4 py-3 text-left">Nama</th>{categories.map(([,label])=><th key={label} className="px-3 py-3 text-right">{label}</th>)}<th className="px-3 py-3 text-right">Contribution</th><th className="px-3 py-3 text-right">Total</th></tr></thead><tbody>{filtered.map(r=>{const rank=teamRows.findIndex(x=>x.id===r.id)+1;return <tr key={r.id} className="border-t"><td className="px-3 py-3 text-center font-bold">{rank}</td><td className="px-4 py-3"><button onClick={()=>setDetail(r)} className="font-bold text-blue-600 hover:underline">{r.name}</button></td>{categories.map(([key])=><td key={key} className="px-3 py-3 text-right"><button title={rateDetail(r,key)} className="cursor-help underline decoration-dotted underline-offset-4">{money.format(r.incentive[key])}</button></td>)}<td className="px-3 py-3 text-right">{pct.format(teamTotal?r.incentive.total/teamTotal*100:0)}%</td><td className="px-3 py-3 text-right font-black">{money.format(r.incentive.total)}</td></tr>})}</tbody></table></div></section>
 {detail&&<div className="fixed inset-0 z-[100] flex justify-end bg-black/25" onClick={()=>setDetail(null)}><aside className="h-full w-full max-w-md overflow-y-auto bg-white p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-blue-600">Incentive Detail</p><h3 className="mt-1 text-xl font-black">{detail.name}</h3><p className="text-sm text-slate-500">{displayDate(from)} – {displayDate(to)}</p></div><button onClick={()=>setDetail(null)} className="rounded-lg border p-2"><X className="size-4"/></button></div><div className="mt-5 space-y-2">{categories.map(([key,label])=><div key={key} className="rounded-xl border p-3"><div className="flex justify-between gap-4"><span className="font-bold">{label}</span><span className="font-black">{money.format(detail.incentive[key])}</span></div><p className="mt-1 text-xs text-slate-500">{rateDetail(detail,key)}</p></div>)}</div><div className="mt-5 border-t pt-4"><div className="flex justify-between text-lg font-black"><span>Total Estimated Incentive</span><span>{money.format(detail.incentive.total)}</span></div><div className="mt-3 flex justify-between text-sm"><span>Avg Incentive / Active Day</span><b>{money.format(detail.activeDays?detail.incentive.total/detail.activeDays:0)}</b></div><div className="mt-2 flex justify-between text-sm"><span>Contribution to Team</span><b>{pct.format(teamTotal?detail.incentive.total/teamTotal*100:0)}%</b></div></div></aside></div>}</div>
}
