"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";
import DailySummaryPage from "@/components/daily-summary-page";
import BnplTrackingPage from "@/components/bnpl-tracking-page";
import SohTabsPage from "@/components/soh-tabs-page";
import OperationsPage from "@/components/operations-page";
import WeeklyCopyEnhancer from "@/components/weekly-copy-enhancer";
import WeeklyReasonPage from "@/components/weekly-reason-live-page";
import TargetFocusPage from "@/components/target-focus-page";
import MadingPage from "@/components/mading-page";
import CxPage from "@/app/cx/page";
import DataToolsPage from "@/app/data-tools/page";

type ViewKey="daily-summary"|"bnpl"|"soh"|"weekly"|"weekly-reason"|"cx"|"lob-focus"|"product-focus"|"vas-focus"|"data-upload"|"mading";
const routes:Record<string,ViewKey>={"Daily Summary":"daily-summary","BNPL & Trade-In":"bnpl","SOH":"soh","Weekly Report":"weekly","Weekly Reason":"weekly-reason","NPS/CX & Member":"cx","LOB Target Fokus":"lob-focus","Product Fokus 3PP":"product-focus","VAS Fokus":"vas-focus","Data Upload":"data-upload","Mading":"mading"};
const nativeDashboardItems=new Set(["Overview","Daily Sales","Staff Performance","Est. Incentive","Feedback","Settings"]);
function NativeView({view}:{view:ViewKey}){if(view==="daily-summary")return <DailySummaryPage/>;if(view==="bnpl")return <BnplTrackingPage/>;if(view==="soh")return <SohTabsPage/>;if(view==="cx")return <CxPage/>;if(view==="weekly-reason")return <WeeklyReasonPage/>;if(view==="mading")return <MadingPage/>;if(view==="lob-focus"||view==="product-focus"||view==="vas-focus")return <TargetFocusPage mode={view}/>;if(view==="data-upload")return <DataToolsPage/>;return <><OperationsPage mode="weekly"/><WeeklyCopyEnhancer/></>}
function buttonLabel(button:HTMLButtonElement){return(button.dataset.menuLabel||button.querySelector("span:last-child")?.textContent||button.textContent||"").trim()}
function menuButton(label:string,icon:string){const b=document.createElement("button");b.dataset.menuLabel=label;b.className="flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-bold lg:pl-7";b.innerHTML=`<span aria-hidden="true">${icon}</span><span>${label}</span>`;return b}
function syncNavigation(label:string|null){const main=document.querySelector("main.min-w-0"),breadcrumb=main?.querySelector("header b") as HTMLElement|null;if(breadcrumb&&label)breadcrumb.textContent=label;for(const button of Array.from(document.querySelectorAll<HTMLButtonElement>("aside nav button"))){const current=buttonLabel(button),isItem=Object.prototype.hasOwnProperty.call(routes,current)||nativeDashboardItems.has(current);if(!isItem)continue;if(!label){button.style.removeProperty("background-color");button.style.removeProperty("box-shadow");button.style.removeProperty("color");button.removeAttribute("aria-current");continue}const selected=current===label;button.style.backgroundColor=selected?"rgba(0,113,227,.10)":"transparent";button.style.boxShadow=selected?"inset 0 0 0 1px rgba(0,113,227,.08)":"none";button.style.color=selected?"#0071e3":"";if(selected)button.setAttribute("aria-current","page");else button.removeAttribute("aria-current")}}
function injectGroup(nav:Element,label:string,items:Array<[string,string]>,marker:string,before?:Element|null){if(nav.querySelector(`[data-${marker}]`))return;const group=document.createElement("div");group.dataset[marker.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]="1";group.className="rounded-xl bg-white/5 p-1";const head=document.createElement("button");head.type="button";head.className="flex w-full items-center gap-2 rounded-lg px-3 py-3 text-sm font-black hover:bg-white/10";head.innerHTML=`<span class="inline-grid size-4 place-items-center" aria-hidden="true">▦</span><span class="flex-1 text-left">${label}</span><span aria-hidden="true">⌄</span>`;const list=document.createElement("div");list.className="mt-1 lg:space-y-1";for(const [name,icon] of items)list.appendChild(menuButton(name,icon));head.onclick=()=>list.classList.toggle("hidden");group.append(head,list);if(before)nav.insertBefore(group,before);else nav.appendChild(group)}
export default function InlineDashboardViews(){const[active,setActive]=useState<{key:ViewKey;label:string}|null>(null),[host,setHost]=useState<HTMLElement|null>(null);
 useEffect(()=>{const inject=()=>{const nav=document.querySelector("aside nav");if(!nav)return;const children=Array.from(nav.children),reporting=children.find(el=>el.textContent?.includes("Reporting"))||null;injectGroup(nav,"M238 Dashboard",[["Mading","▣"],["Daily Summary","▤"]],"m238-dashboard-group",reporting);if(!nav.querySelector("[data-target-focus-group]"))injectGroup(nav,"Target Fokus",[["LOB Target Fokus","◉"],["Product Fokus 3PP","◫"],["VAS Fokus","◇"]],"target-focus-group",reporting);if(!document.querySelector("[data-weekly-reason-menu]")){const repButton=Array.from(document.querySelectorAll<HTMLButtonElement>("aside nav button")).find(b=>buttonLabel(b)==="Reporting"),list=repButton?.parentElement?.querySelector(".mt-1") as HTMLElement|null;if(list){const b=menuButton("Weekly Reason","↳");b.dataset.weeklyReasonMenu="1";list.appendChild(b)}}if(!nav.querySelector("[data-administration-group]")){injectGroup(nav,"Administrasi",[["Data Upload","⇧"]],"administration-group");const settings=Array.from(nav.querySelectorAll<HTMLButtonElement>("button")).find(b=>buttonLabel(b)==="Settings");const admin=nav.querySelector("[data-administration-group] div.mt-1");if(settings&&admin&&!settings.closest("[data-administration-group]")){settings.dataset.menuLabel="Settings";admin.appendChild(settings)}}};inject();const obs=new MutationObserver(inject);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 useEffect(()=>{const click=(event:MouseEvent)=>{const button=(event.target as Element|null)?.closest("button") as HTMLButtonElement|null;if(!button||!button.closest("aside nav"))return;const label=buttonLabel(button),key=routes[label];if(key){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();syncNavigation(label);setActive({key,label});return}if(nativeDashboardItems.has(label)&&active){syncNavigation(null);setActive(null)}};document.addEventListener("click",click,true);return()=>document.removeEventListener("click",click,true)},[active]);
 useEffect(()=>{const root=document.querySelector("main.min-w-0 > div.px-4.pt-6") as HTMLElement|null;if(!root)return;let h=root.querySelector("[data-inline-view-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.inlineViewHost="1";h.className="min-w-0 w-full";root.appendChild(h)}setHost(h);const apply=()=>{for(const child of Array.from(root.children)){if(child===h)continue;(child as HTMLElement).style.display=active?"none":""}h!.style.display=active?"block":"none"};apply();const obs=new MutationObserver(apply);obs.observe(root,{childList:true});return()=>{obs.disconnect();for(const child of Array.from(root.children)){if(child!==h)(child as HTMLElement).style.display=""}}},[active]);
 useEffect(()=>{if(active)syncNavigation(active.label);return()=>{if(!active)syncNavigation(null)}},[active]);if(!host||!active)return null;return createPortal(<div data-inline-native className="w-full min-w-0 space-y-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238</p><h1 className="mt-1 text-3xl font-black text-slate-900 dark:text-slate-100">{active.label}</h1></div><div className="m238-native-view w-full min-w-0"><NativeView view={active.key}/></div></div>,host)}
