"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Activity,BarChart3,Boxes,Building2,ChevronRight,Gauge,LayoutDashboard,MessageSquare,Moon,RefreshCw,Settings,Sun,TrendingUp,Users} from "lucide-react";
import {LineChart,Line,ResponsiveContainer,XAxis,YAxis,Tooltip,CartesianGrid,BarChart,Bar} from "recharts";

type Store={code:string;name:string;target:number;achievement:number;device:number;acc:number;vas:number;qty:number;transactions:number;traffic:number;cvr:number;upt:number;atv:number;nps:number|null;newMember:number;targetCvr:number;soh:number};
type Payload={period:string;monthName:string;stores:Store[];area:{target:number;achievement:number;achievementPct:number;device:number;acc:number;vas:number;qty:number;transactions:number;traffic:number;cvr:number;upt:number;atv:number;nps:number|null;newMember:number;soh:number};daily:{date:string;target:number;achievement:number;device:number;acc:number;vas:number;qty:number;transactions:number;traffic:number;cvr:number;upt:number;atv:number};trend:Array<{date:string;traffic:number;transactions:number;cvr:number}>;lob:Record<string,{iphone:number;mac:number;ipad:number;watch:number;airpods:number}>;weekly:Record<string,Record<string,{amount:number;qty:number}>>;revenue:{y2025:number[];y2026:number[]};meta:{stores:number;cvrTargetSource:string;cvrTarget:number;npsMethod:string;newMemberSource:string;sourceTimezone:string;opsSpreadsheetTimezone:string};error?:string};
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}),num=new Intl.NumberFormat("id-ID"),pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`),monthLabel=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`));
type VisualTheme="professional"|"hero"|"anime"|"pirate"|"spider";
const themes:Record<VisualTheme,{shell:string;side:string;hero:string;accent:string}>={professional:{shell:"bg-slate-100 dark:bg-slate-950",side:"bg-gradient-to-b from-slate-900 to-blue-950",hero:"from-blue-700 to-cyan-600",accent:"text-blue-600"},hero:{shell:"bg-zinc-100 dark:bg-zinc-950",side:"bg-gradient-to-b from-zinc-950 via-red-950 to-blue-950",hero:"from-red-700 via-zinc-950 to-blue-700",accent:"text-red-600"},anime:{shell:"bg-violet-50 dark:bg-[#10091c]",side:"bg-gradient-to-b from-violet-700 via-fuchsia-600 to-cyan-600",hero:"from-violet-600 via-fuchsia-500 to-cyan-500",accent:"text-violet-600"},pirate:{shell:"bg-amber-50 dark:bg-stone-950",side:"bg-gradient-to-b from-amber-900 via-stone-950 to-sky-950",hero:"from-amber-700 via-orange-600 to-sky-700",accent:"text-amber-700"},spider:{shell:"bg-slate-100 dark:bg-slate-950",side:"bg-gradient-to-b from-red-700 via-slate-950 to-blue-800",hero:"from-red-600 via-slate-950 to-blue-700",accent:"text-red-600"}};
function Card({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-2xl border border-black/5 bg-white/90 p-4 shadow-sm backdrop-blur dark:border-white/10 dark:bg-slate-900/90"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 break-words text-xl font-black tracking-tight sm:text-2xl">{value}</p>{sub&&<p className="mt-2 text-xs text-slate-500">{sub}</p>}</div>}
function CvrBadge({value,target=30}:{value:number;target?:number}){const cls=value>=target?"bg-emerald-100 text-emerald-700":value>=target-5?"bg-amber-100 text-amber-700":"bg-rose-100 text-rose-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-black ${cls}`}>{pct(value)}</span>}
function TableWrap({children}:{children:React.ReactNode}){return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-900">{children}</div>}
const th="whitespace-nowrap px-3 py-3 text-left text-[11px] font-black uppercase tracking-wide text-slate-400",td="whitespace-nowrap px-3 py-3 text-sm";

export default function Jakarta1Dashboard(){
 const[tab,setTab]=useState("dashboard"),[period,setPeriod]=useState("2026-09"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[dark,setDark]=useState(false),[visual,setVisual]=useState<VisualTheme>("professional"),busy=useRef(false);
 useEffect(()=>{const d=localStorage.getItem("j1-dark")==="1";setDark(d);document.documentElement.classList.toggle("dark",d);const v=(localStorage.getItem("j1-theme")||"professional") as VisualTheme;if(v in themes)setVisual(v)},[]);
 const load=useCallback(async(manual=false)=>{if(busy.current)return;busy.current=true;manual?setRefreshing(true):setLoading(!data);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(`/api/jakarta1?period=${period}${manual?`&t=${Date.now()}`:""}`,{cache:manual?"no-store":"default",signal:controller.signal});const j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memuat data");setData(j)}catch(e){if(!data)console.error(e)}finally{clearTimeout(timer);busy.current=false;setLoading(false);setRefreshing(false)}},[period,data]);
 useEffect(()=>{void load();const t=setInterval(()=>{if(document.visibilityState==="visible")void load(false)},120000);return()=>clearInterval(t)},[load]);
 const toggleDark=()=>{const v=!dark;setDark(v);document.documentElement.classList.toggle("dark",v);localStorage.setItem("j1-dark",v?"1":"0")},setTheme=(v:VisualTheme)=>{setVisual(v);localStorage.setItem("j1-theme",v)};
 const nav=[['dashboard','Dashboard',LayoutDashboard],['daily','Daily Performance',Activity],['stores','Store Performance',Building2],['lob','LOB Performance',BarChart3],['weekly','Weekly Report',TrendingUp],['soh','SOH',Boxes],['nps','NPS/CX & Member',Gauge],['feedback','Feedback',MessageSquare],['settings','Settings',Settings]] as const,t=themes[visual];
 const ranking=useMemo(()=>{const s=[...(data?.stores??[])];return{high:[...s].sort((a,b)=>b.cvr-a.cvr)[0],low:[...s].sort((a,b)=>a.cvr-b.cvr)[0],traffic:[...s].sort((a,b)=>b.traffic-a.traffic)[0],gap:[...s].sort((a,b)=>(a.cvr-a.targetCvr)-(b.cvr-b.targetCvr))[0]}},[data]);
 if(loading&&!data)return <div className="grid min-h-screen place-items-center bg-slate-950 text-white"><div className="text-center"><RefreshCw className="mx-auto size-8 animate-spin"/><p className="mt-3 font-bold">Memuat Jakarta 1 Dashboard…</p></div></div>;
 return <div className={`min-h-screen ${t.shell} text-slate-950 dark:text-white lg:grid lg:grid-cols-[240px_minmax(0,1fr)]`}>
  <aside className={`${t.side} text-white lg:sticky lg:top-0 lg:h-screen`}><div className="p-5"><div className="rounded-2xl border border-white/15 bg-white/10 p-4"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/65">Area Dashboard</p><h1 className="mt-2 text-2xl font-black">Jakarta 1</h1><p className="mt-1 text-xs text-white/70">9 Stores Performance Hub</p></div></div><nav className="grid grid-cols-3 gap-1 px-3 pb-4 lg:block lg:space-y-1">{nav.map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex items-center justify-center gap-2 rounded-xl px-3 py-3 text-xs font-bold lg:w-full lg:justify-start lg:text-sm ${tab===k?"bg-white/20":"text-white/80 hover:bg-white/10"}`}><I className="size-4"/><span className="hidden sm:inline">{l}</span></button>)}</nav></aside>
  <main className="min-w-0"><header className="sticky top-0 z-40 border-b bg-white/90 backdrop-blur-xl dark:bg-slate-950/90"><div className="flex items-center justify-between gap-3 px-4 py-3 sm:px-7"><div className="flex items-center gap-2 text-sm"><span className="text-slate-400">Jakarta 1</span><ChevronRight className="size-4"/><b>{nav.find(x=>x[0]===tab)?.[1]}</b></div><div className="flex gap-2"><button onClick={toggleDark} className="rounded-xl border bg-white p-2.5 dark:bg-slate-900">{dark?<Sun className="size-4"/>:<Moon className="size-4"/>}</button><button onClick={()=>void load(true)} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-bold dark:bg-slate-900"><RefreshCw className={`size-4 ${refreshing?"animate-spin":""}`}/>Perbarui</button></div></div></header>
  <div className="space-y-5 p-4 sm:p-7"><div className="max-w-xs"><label className="text-xs font-black uppercase tracking-wide text-slate-400">Periode</label><select value={period} onChange={e=>setPeriod(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-white px-3 font-bold dark:bg-slate-900">{months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select></div>
   {tab==="dashboard"&&<Overview data={data} t={t.hero} ranking={ranking}/>} {tab==="daily"&&<Daily data={data}/>} {tab==="stores"&&<Stores data={data}/>} {tab==="lob"&&<Lob data={data}/>} {tab==="weekly"&&<Weekly data={data}/>} {tab==="soh"&&<SOH data={data}/>} {tab==="nps"&&<Nps data={data}/>} {tab==="feedback"&&<Feedback/>} {tab==="settings"&&<SettingsPanel visual={visual} setVisual={setTheme} dark={dark} toggleDark={toggleDark} meta={data?.meta}/>} 
  </div></main>
 </div>}
function Overview({data,t,ranking}:{data:Payload|null;t:string;ranking:{high?:Store;low?:Store;traffic?:Store;gap?:Store}}){const a=data?.area;return <div className="space-y-5"><section className={`rounded-3xl bg-gradient-to-br ${t} p-5 text-white shadow-xl`}><p className="text-sm text-white/70">Area Jakarta 1 • {data?.monthName} 2026</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-white/65">Target Area</p><b className="text-2xl">{money.format(a?.target??0)}</b></div><div><p className="text-xs text-white/65">Achievement</p><b className="text-2xl">{money.format(a?.achievement??0)}</b></div><div><p className="text-xs text-white/65">Achievement %</p><b className="text-2xl">{pct(a?.achievementPct??0)}</b></div><div><p className="text-xs text-white/65">CVR Area</p><b className="text-2xl">{pct(a?.cvr??0)}</b></div></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Device" value={money.format(a?.device??0)}/><Card label="Accessories" value={money.format(a?.acc??0)}/><Card label="VAS" value={money.format(a?.vas??0)}/><Card label="NPS / CX" value={a?.nps==null?"—":pct(a.nps)} sub="Rata-rata 9 store dari data NPS"/></section><section className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-900"><div className="mb-4"><h2 className="font-black">Traffic & CVR Area</h2><p className="text-xs text-slate-500">CVR = total transaksi ÷ total traffic 9 store.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Card label="Traffic" value={num.format(a?.traffic??0)}/><Card label="Transaction" value={num.format(a?.transactions??0)}/><Card label="CVR" value={pct(a?.cvr??0)}/><Card label="UPT / ATV" value={`${(a?.upt??0).toFixed(1)} / ${money.format(a?.atv??0)}`}/></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data?.trend??[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey="cvr" stroke="currentColor" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></div><div className="space-y-3"><Card label="Highest CVR" value={ranking.high?`${ranking.high.code} • ${pct(ranking.high.cvr)}`:"—"}/><Card label="Lowest CVR" value={ranking.low?`${ranking.low.code} • ${pct(ranking.low.cvr)}`:"—"}/><Card label="Highest Traffic" value={ranking.traffic?`${ranking.traffic.code} • ${num.format(ranking.traffic.traffic)}`:"—"}/><Card label="Largest CVR Gap" value={ranking.gap?`${ranking.gap.code} • ${pct(ranking.gap.cvr-ranking.gap.targetCvr)}`:"—"}/></div></section><Stores data={data}/><Revenue data={data}/></div>}
function Stores({data}:{data:Payload|null}){const total=data?.area;return <section><div className="mb-3"><h2 className="text-xl font-black">Performance 9 Store</h2><p className="text-sm text-slate-500">Mapping berdasarkan Store Code.</p></div><TableWrap><table className="w-full"><thead><tr>{["Store","Target","Achievement","Ach %","Traffic","Transaction","CVR","Device","ACC","VAS","UPT","ATV"].map(x=><th key={x} className={th}>{x}</th>)}</tr></thead><tbody>{data?.stores.map(s=><tr key={s.code} className="border-t"><td className={td}><b>{s.code}</b><div className="text-xs text-slate-400">{s.name}</div></td><td className={td}>{money.format(s.target)}</td><td className={`${td} font-bold`}>{money.format(s.achievement)}</td><td className={td}>{pct(s.target?s.achievement/s.target*100:0)}</td><td className={td}>{num.format(s.traffic)}</td><td className={td}>{num.format(s.transactions)}</td><td className={td}><CvrBadge value={s.cvr} target={s.targetCvr}/></td><td className={td}>{money.format(s.device)}</td><td className={td}>{money.format(s.acc)}</td><td className={td}>{money.format(s.vas)}</td><td className={td}>{s.upt.toFixed(1)}</td><td className={td}>{money.format(s.atv)}</td></tr>)}<tr className="border-t bg-slate-50 font-black dark:bg-slate-800"><td className={td}>TOTAL AREA</td><td className={td}>{money.format(total?.target??0)}</td><td className={td}>{money.format(total?.achievement??0)}</td><td className={td}>{pct(total?.achievementPct??0)}</td><td className={td}>{num.format(total?.traffic??0)}</td><td className={td}>{num.format(total?.transactions??0)}</td><td className={td}><CvrBadge value={total?.cvr??0}/></td><td className={td}>{money.format(total?.device??0)}</td><td className={td}>{money.format(total?.acc??0)}</td><td className={td}>{money.format(total?.vas??0)}</td><td className={td}>{(total?.upt??0).toFixed(1)}</td><td className={td}>{money.format(total?.atv??0)}</td></tr></tbody></table></TableWrap></section>}
function Daily({data}:{data:Payload|null}){const d=data?.daily;return <div className="space-y-5"><div><h2 className="text-2xl font-black">Daily Area Performance</h2><p className="text-sm text-slate-500">Hari berjalan: {d?.date||"—"}</p></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card label="Daily Target Area" value={money.format(d?.target??0)} sub="Sementara: target bulanan ÷ jumlah hari bulan"/><Card label="Achievement" value={money.format(d?.achievement??0)} sub={pct((d?.target??0)?(d?.achievement??0)/(d?.target??1)*100:0)}/><Card label="Traffic / Transaction" value={`${num.format(d?.traffic??0)} / ${num.format(d?.transactions??0)}`}/><Card label="CVR Hari Ini" value={pct(d?.cvr??0)}/><Card label="Device" value={money.format(d?.device??0)}/><Card label="Accessories" value={money.format(d?.acc??0)}/><Card label="VAS" value={money.format(d?.vas??0)}/><Card label="UPT / ATV" value={`${(d?.upt??0).toFixed(1)} / ${money.format(d?.atv??0)}`}/></section><p className="text-sm text-slate-500">Detail harian per store akan kita revisi setelah struktur target harian store disepakati.</p></div>}
function Lob({data}:{data:Payload|null}){return <div><h2 className="mb-3 text-2xl font-black">LOB Performance</h2><TableWrap><table className="w-full"><thead><tr>{["Store","iPhone","MacBook","iPad","Watch","AirPods"].map(x=><th key={x} className={th}>{x}</th>)}</tr></thead><tbody>{data?.stores.map(s=>{const l=data.lob[s.code];return <tr key={s.code} className="border-t"><td className={`${td} font-black`}>{s.code}</td><td className={td}>{money.format(l?.iphone??0)}</td><td className={td}>{money.format(l?.mac??0)}</td><td className={td}>{money.format(l?.ipad??0)}</td><td className={td}>{money.format(l?.watch??0)}</td><td className={td}>{money.format(l?.airpods??0)}</td></tr>})}</tbody></table></TableWrap></div>}
function Weekly({data}:{data:Payload|null}){const weeks=Object.keys(data?.weekly??{}).sort();return <div><h2 className="mb-3 text-2xl font-black">Weekly Report</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{weeks.map(w=>{const entries=Object.values(data?.weekly[w]??{}),amount=entries.reduce((a,b)=>a+b.amount,0),qty=entries.reduce((a,b)=>a+b.qty,0);return <Card key={w} label={w} value={money.format(amount)} sub={`${num.format(qty)} unit`}/>})}</div></div>}
function SOH({data}:{data:Payload|null}){return <div><h2 className="mb-3 text-2xl font-black">SOH Area</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.stores.map(s=><Card key={s.code} label={`${s.code} • ${s.name}`} value={`${num.format(s.soh)} unit`}/>)}</div></div>}
function Nps({data}:{data:Payload|null}){return <div className="space-y-4"><div><h2 className="text-2xl font-black">NPS / CX & Member</h2><p className="text-sm text-slate-500">NPS dibaca dari sheet Data Nps. New Member belum memiliki source yang terdeteksi.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data?.stores.map(s=><Card key={s.code} label={`${s.code} • NPS`} value={s.nps==null?"—":pct(s.nps)}/>)}</div></div>}
function Feedback(){return <div className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-900"><h2 className="text-2xl font-black">Feedback</h2><p className="mt-2 text-sm text-slate-500">Bagian feedback Area disiapkan sebagai modul berikutnya supaya sumber input dan struktur reason/action plan bisa kita sepakati tanpa mengubah data utama.</p></div>}
function Revenue({data}:{data:Payload|null}){const chart=Array.from({length:12},(_,i)=>({month:String(i+1).padStart(2,"0"),y2025:data?.revenue.y2025[i]??0,y2026:data?.revenue.y2026[i]??0}));return <div className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-900"><h2 className="font-black">Revenue Analytics</h2><p className="mb-4 text-xs text-slate-500">Perbandingan 2025 vs 2026 dari Data Compile.</p><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis tick={{fontSize:10}}/><Tooltip formatter={(v)=>money.format(Number(v))}/><Bar dataKey="y2025" fill="currentColor" opacity={.35}/><Bar dataKey="y2026" fill="currentColor"/></BarChart></ResponsiveContainer></div></div>}
function SettingsPanel({visual,setVisual,dark,toggleDark,meta}:{visual:VisualTheme;setVisual:(v:VisualTheme)=>void;dark:boolean;toggleDark:()=>void;meta?:Payload["meta"]}){const labels:Record<VisualTheme,string>={professional:"Professional",hero:"Hero Comic",anime:"Anime Neon",pirate:"Pirate Adventure",spider:"Spider Hero"};return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-900"><h2 className="text-xl font-black">Tampilan Dashboard</h2><p className="mt-1 text-sm text-slate-500">Tema memengaruhi sidebar, hero, card feel, accent dan keseluruhan dashboard.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(Object.keys(labels) as VisualTheme[]).map(v=><button key={v} onClick={()=>setVisual(v)} className={`rounded-2xl border p-3 text-left ${visual===v?"ring-2 ring-blue-400":""}`}><div className={`h-14 rounded-xl bg-gradient-to-br ${themes[v].hero}`}/><b className="mt-2 block text-sm">{labels[v]}</b></button>)}</div><button onClick={toggleDark} className="mt-4 rounded-xl border px-4 py-2 text-sm font-bold">{dark?"Gunakan Light Mode":"Gunakan Dark Mode"}</button></section><section className="rounded-2xl border bg-white p-5 text-sm shadow-sm dark:bg-slate-900"><h3 className="font-black">Status Source</h3><p className="mt-2 text-slate-500">CVR target: {meta?.cvrTargetSource==="fallback"?`sementara ${meta.cvrTarget}% karena source target CVR belum ditemukan di Google Sheet`:`${meta?.cvrTarget}%`}. NPS menggunakan {meta?.npsMethod}. Timezone source sales: {meta?.sourceTimezone}. File SPW & SOH saat ini terdeteksi memakai timezone {meta?.opsSpreadsheetTimezone}.</p></section></div>}
