"use client";
import {useEffect,useMemo,useState} from "react";
import {RefreshCw,X} from "lucide-react";
import {createPortal} from "react-dom";

type SummaryRow={
 key:string;id:string;name:string;store:string;
 qty:{iphone:number;macbook:number;ipad:number;watch:number;accessories:number;qoala:number};
 incentive:{iphone:number;macbook:number;ipad:number;watch:number;accessories:number;qoala:number;total:number};
 invalidAccessoryRows:number;invalidAccessoryQty:number;invalidQoalaRows:number;
 totalSoldQty:number;totalTransactions:number;duplicateRowsSkipped:number;sanityWarning:boolean;
};
type Payload={period:string;stores:string[];rows:SummaryRow[];error?:string};
type Detail=SummaryRow&{
 accessoryTiers:Record<string,{qty:number;rate:number;incentive:number}>;
 qoalaTiers:{low:{qty:number;rate:number;incentive:number};high:{qty:number;rate:number;incentive:number}};
};
type DeviceLine={product:string;article:string;description:string;qty:number;rate:number;incentive:number;transaction:string};
type AccessoryLine={article:string;description:string;qty:number;unitPrice:number;tier:string;rate:number;incentive:number;transaction:string};
type QoalaLine={article:string;description:string;qty:number;unitPrice:number;bucket:string;rate:number;incentive:number;transaction:string};
type Section="device"|"accessories"|"qoala";
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const months=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const nowPeriod=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);
const th="whitespace-nowrap px-3 py-3 text-left text-[11px] font-black uppercase tracking-wide text-slate-400";
const td="whitespace-nowrap px-3 py-3 text-sm";

export default function Jakarta1IncentiveAudit(){
 const[nav,setNav]=useState<HTMLElement|null>(null),[main,setMain]=useState<HTMLElement|null>(null),[host,setHost]=useState<HTMLElement|null>(null),[active,setActive]=useState(false);
 useEffect(()=>{let timer=0,cancel=false;const find=()=>{if(cancel)return;const n=document.querySelector('aside nav') as HTMLElement|null,m=document.querySelector('main.min-w-0') as HTMLElement|null;if(!n||!m)return;setNav(n);setMain(m);let h=document.querySelector('[data-j1-inc-audit-host="1"]') as HTMLElement|null;if(!h){h=document.createElement('div');h.dataset.j1IncAuditHost='1';m.appendChild(h)}setHost(h);if(timer)window.clearInterval(timer)};timer=window.setInterval(find,250);find();return()=>{cancel=true;if(timer)window.clearInterval(timer);document.querySelector('[data-j1-inc-audit-host="1"]')?.remove()}},[]);
 useEffect(()=>{if(!nav)return;const click=(e:Event)=>{const b=(e.target as HTMLElement).closest('button');if(!b)return;setActive((b.textContent||'').toLowerCase().includes('est incentive'))};nav.addEventListener('click',click,true);return()=>nav.removeEventListener('click',click,true)},[nav]);
 useEffect(()=>{if(!main)return;const children=[...main.children] as HTMLElement[];children.forEach(el=>{if(el.dataset.j1IncAuditHost==='1')return;if(active){el.dataset.j1IncAuditPrev=el.style.display;el.style.display='none'}else if('j1IncAuditPrev'in el.dataset){el.style.display=el.dataset.j1IncAuditPrev||'';delete el.dataset.j1IncAuditPrev}})},[active,main]);
 return active&&host?createPortal(<Page onClose={()=>setActive(false)}/>,host):null;
}

function Page({onClose}:{onClose:()=>void}){
 const[period,setPeriod]=useState(nowPeriod()),[store,setStore]=useState('ALL'),[staff,setStaff]=useState('ALL'),[view,setView]=useState<'staff'|'store'>('staff');
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const[detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false);
 const load=async(force=false)=>{force?setRefreshing(true):setLoading(true);setError('');try{const r=await fetch(`/api/jakarta1-incentive?period=${period}${force?'&refresh=1':''}`,{cache:force?'no-store':'default'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal memuat');setData(j)}catch{setError('Data Est Incentive Jakarta 1 gagal dimuat. Silakan coba kembali.')}finally{setLoading(false);setRefreshing(false)}};
 useEffect(()=>{void load(false);setStore('ALL');setStaff('ALL');setDetail(null)},[period]);
 const staffOpts=useMemo(()=>[...(data?.rows??[]).filter(r=>store==='ALL'||r.store===store)].sort((a,b)=>a.name.localeCompare(b.name)),[data,store]);
 useEffect(()=>{if(staff!=='ALL'&&!staffOpts.some(r=>r.key===staff))setStaff('ALL')},[staff,staffOpts]);
 const rows=useMemo(()=>{let x=(data?.rows??[]).filter(r=>store==='ALL'||r.store===store);if(staff!=='ALL')x=x.filter(r=>r.key===staff);return[...x].sort((a,b)=>b.incentive.total-a.incentive.total||a.name.localeCompare(b.name))},[data,store,staff]);
 const total=rows.reduce((a,r)=>a+r.incentive.total,0),avg=rows.length?total/rows.length:0,highest=rows[0]?.incentive.total??0;
 const storeRows=useMemo(()=>{const m=new Map<string,{store:string;staff:Set<string>;device:number;accessories:number;qoala:number;total:number}>();for(const r of rows){const x=m.get(r.store)??{store:r.store,staff:new Set<string>(),device:0,accessories:0,qoala:0,total:0};x.staff.add(r.key);x.device+=r.incentive.iphone+r.incentive.macbook+r.incentive.ipad+r.incentive.watch;x.accessories+=r.incentive.accessories;x.qoala+=r.incentive.qoala;x.total+=r.incentive.total;m.set(r.store,x)}return[...m.values()].sort((a,b)=>b.total-a.total)},[rows]);
 const openDetail=async(r:SummaryRow)=>{setDetail(null);setDetailLoading(true);try{const res=await fetch(`/api/jakarta1-incentive?period=${period}&detailKey=${encodeURIComponent(r.key)}`,{cache:'no-store'}),j=await res.json();if(res.ok)setDetail(j.row)}finally{setDetailLoading(false)}};
 const[y,m]=period.split('-');
 return <div className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-40 border-b bg-white/95"><div className="flex items-center justify-between px-4 py-3 sm:px-7"><div className="text-sm"><span className="text-slate-400">Jakarta 1</span><span className="mx-2 text-slate-300">/</span><b>Est Incentive</b></div><div className="flex gap-2"><button onClick={()=>void load(true)} disabled={refreshing} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-bold disabled:opacity-50"><RefreshCw className={`size-4 ${refreshing?'animate-spin':''}`}/>{refreshing?'Memperbarui...':'Perbarui'}</button><button onClick={onClose} className="rounded-xl border bg-white p-2 lg:hidden"><X className="size-4"/></button></div></div></header><div className="space-y-5 p-4 sm:p-7">
 <div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Jakarta 1 • Incentive</p><h2 className="mt-2 text-3xl font-black">Est Incentive</h2><p className="mt-1 text-sm text-slate-500">Actual sales staff per periode • qty aktual • unit price • duplicate guard.</p></div>
 <div className="grid gap-3 md:grid-cols-4"><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Tahun</span><select value={y} onChange={e=>setPeriod(`${e.target.value}-${m}`)} className="h-11 w-full rounded-xl border bg-white px-3 font-bold"><option>2026</option><option>2025</option></select></label><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Bulan</span><select value={m} onChange={e=>setPeriod(`${y}-${e.target.value}`)} className="h-11 w-full rounded-xl border bg-white px-3 font-bold">{months.map((x,i)=><option key={x} value={String(i+1).padStart(2,'0')}>{x}</option>)}</select></label><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Store</span><select value={store} onChange={e=>{setStore(e.target.value);setStaff('ALL')}} className="h-11 w-full rounded-xl border bg-white px-3 font-bold"><option value="ALL">All Jakarta 1</option>{(data?.stores??[]).map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Staff</span><select value={staff} onChange={e=>setStaff(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 font-bold"><option value="ALL">Semua Staff</option>{staffOpts.map(s=><option key={s.key} value={s.key}>{s.name} • {s.store}</option>)}</select></label></div>
 <div className="grid grid-cols-2 gap-2 xl:grid-cols-4">{[['Total Est. Incentive',money.format(total)],['Total Staff',num.format(rows.length)],['Average Incentive / Staff',money.format(avg)],['Highest Incentive',money.format(highest)]].map(([l,v])=><div key={l} className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-[11px] font-black uppercase tracking-wide text-slate-400">{l}</p><p className="mt-2 text-lg font-black">{v}</p></div>)}</div>
 <div className="flex gap-2"><button onClick={()=>setView('staff')} className={`rounded-xl px-4 py-2 text-sm font-black ${view==='staff'?'bg-[#086aad] text-white':'border bg-white'}`}>Staff View</button><button onClick={()=>setView('store')} className={`rounded-xl px-4 py-2 text-sm font-black ${view==='store'?'bg-[#086aad] text-white':'border bg-white'}`}>Store View</button></div>
 {error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">{error}</div>:loading?<div className="rounded-2xl border bg-white p-10 text-center text-slate-500">Memuat Est Incentive…</div>:view==='staff'?<StaffTable rows={rows} onOpen={openDetail}/>:<StoreTable rows={storeRows}/>} 
 </div>{(detailLoading||detail)&&<DetailDrawer loading={detailLoading} detail={detail} period={period} onClose={()=>setDetail(null)}/>}</div>;
}

function StaffTable({rows,onOpen}:{rows:SummaryRow[];onOpen:(r:SummaryRow)=>void}){return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full"><thead><tr>{['Nama','Store','iPhone','MacBook','iPad','Apple Watch','Accessories','Qoala','Total'].map(x=><th className={th} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const needCheck=r.invalidAccessoryRows>0||r.invalidQoalaRows>0||r.sanityWarning;return <tr key={r.key} onClick={()=>onOpen(r)} className={`cursor-pointer border-t hover:bg-blue-50/40 ${i===0&&r.incentive.total>0?'bg-blue-50/30':''}`}><td className={`${td} font-bold`}>{r.name}{needCheck&&<span className="ml-2 rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-bold text-amber-700">Need Check</span>}</td><td className={td}>{r.store}</td><td className={td}>{money.format(r.incentive.iphone)}</td><td className={td}>{money.format(r.incentive.macbook)}</td><td className={td}>{money.format(r.incentive.ipad)}</td><td className={td}>{money.format(r.incentive.watch)}</td><td className={td}>{money.format(r.incentive.accessories)}</td><td className={td}>{money.format(r.incentive.qoala)}</td><td className={`${td} font-black`}>{money.format(r.incentive.total)}</td></tr>})}</tbody></table></div>}
function StoreTable({rows}:{rows:{store:string;staff:Set<string>;device:number;accessories:number;qoala:number;total:number}[]}){return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full"><thead><tr>{['Store','Total Staff','Device','Accessories','Qoala','Total Incentive'].map(x=><th className={th} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.store}><td className={`${td} font-bold`}>{r.store}</td><td className={td}>{r.staff.size}</td><td className={td}>{money.format(r.device)}</td><td className={td}>{money.format(r.accessories)}</td><td className={td}>{money.format(r.qoala)}</td><td className={`${td} font-black`}>{money.format(r.total)}</td></tr>)}</tbody></table></div>}

function DetailDrawer({loading,detail,period,onClose}:{loading:boolean;detail:Detail|null;period:string;onClose:()=>void}){
 const[open,setOpen]=useState<Record<Section,boolean>>({device:false,accessories:false,qoala:false});
 const[sectionLoading,setSectionLoading]=useState<Record<Section,boolean>>({device:false,accessories:false,qoala:false});
 const[deviceLines,setDeviceLines]=useState<DeviceLine[]|null>(null),[accessoryLines,setAccessoryLines]=useState<AccessoryLine[]|null>(null),[qoalaLines,setQoalaLines]=useState<QoalaLine[]|null>(null);
 useEffect(()=>{setOpen({device:false,accessories:false,qoala:false});setSectionLoading({device:false,accessories:false,qoala:false});setDeviceLines(null);setAccessoryLines(null);setQoalaLines(null)},[detail?.key]);
 const toggle=async(section:Section)=>{
  if(open[section]){setOpen(v=>({...v,[section]:false}));return}
  setOpen(v=>({...v,[section]:true}));
  const already=section==='device'?deviceLines:section==='accessories'?accessoryLines:qoalaLines;if(already!==null)return;
  if(!detail)return;setSectionLoading(v=>({...v,[section]:true}));
  try{const res=await fetch(`/api/jakarta1-incentive?period=${period}&detailKey=${encodeURIComponent(detail.key)}&section=${section}`,{cache:'no-store'}),j=await res.json();if(res.ok){if(section==='device')setDeviceLines(j.lines??[]);else if(section==='accessories')setAccessoryLines(j.lines??[]);else setQoalaLines(j.lines??[])}}
  finally{setSectionLoading(v=>({...v,[section]:false}))}
 };
 return <div className="fixed inset-0 z-[100] bg-slate-950/30 sm:p-4" onClick={()=>{if(!loading)onClose()}}><div onClick={e=>e.stopPropagation()} className="ml-auto h-full w-full max-w-4xl overflow-y-auto bg-white shadow-2xl sm:rounded-2xl">{loading?<div className="grid h-full place-items-center text-slate-500">Memuat detail…</div>:detail&&<><div className="sticky top-0 z-20 flex items-start justify-between gap-3 border-b bg-white/95 p-4 backdrop-blur sm:p-5"><div><p className="text-xs font-black uppercase tracking-wide text-blue-600">Detail Staff</p><h3 className="mt-1 text-xl font-black sm:text-2xl">{detail.name}</h3><p className="text-xs text-slate-500 sm:text-sm">{detail.store} • {detail.totalTransactions} transaksi • {detail.totalSoldQty} total sold qty</p></div><button onClick={onClose} aria-label="Close" className="shrink-0 rounded-xl border bg-white p-3"><X className="size-4"/></button></div><div className="p-4 pb-8 sm:p-5">{detail.sanityWarning&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-800">Possible calculation issue — Accessories Qty melebihi total sold item staff.</div>}{detail.duplicateRowsSkipped>0&&<div className="mt-3 rounded-xl border bg-slate-50 p-3 text-xs font-bold text-slate-600">Duplicate source rows dilewati: {detail.duplicateRowsSkipped}</div>}
 <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{[['iPhone',detail.qty.iphone,15000,detail.incentive.iphone],['MacBook',detail.qty.macbook,30000,detail.incentive.macbook],['iPad',detail.qty.ipad,10000,detail.incentive.ipad],['Apple Watch',detail.qty.watch,10000,detail.incentive.watch]].map(([l,q,r,v])=><div key={String(l)} className="rounded-xl border p-3"><b>{l}</b><p className="mt-1 text-sm text-slate-500">Qty: {q} • Rate: {money.format(Number(r))}</p><p className="mt-1 font-black">{money.format(Number(v))}</p></div>)}</div>
 <div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl border p-3"><b>Accessories</b><p className="mt-1 text-sm text-slate-500">Qty: {detail.qty.accessories}</p><p className="mt-1 font-black">{money.format(detail.incentive.accessories)}</p>{detail.invalidAccessoryRows>0&&<p className="mt-2 text-xs font-bold text-amber-700">Price Invalid / Need Check: {detail.invalidAccessoryRows} row • {detail.invalidAccessoryQty} qty.</p>}</div><div className="rounded-xl border p-3"><b>Qoala</b><p className="mt-1 text-sm text-slate-500">&lt; Rp1.315.000: {detail.qoalaTiers.low.qty} • ≥ Rp1.315.000: {detail.qoalaTiers.high.qty}</p><p className="mt-1 font-black">{money.format(detail.incentive.qoala)}</p></div></div>
 <div className="mt-4 rounded-xl bg-slate-950 p-4 text-white"><p className="text-xs uppercase text-slate-300">Total Est. Incentive</p><p className="mt-1 text-2xl font-black">{money.format(detail.incentive.total)}</p></div>
 <LazyAudit title="Audit Device Detail" open={open.device} loading={sectionLoading.device} onToggle={()=>void toggle('device')} headers={['Product','Article','Description','Qty','Rate','Incentive']} rows={deviceLines?.map(x=>[x.product,x.article,x.description,x.qty,money.format(x.rate),money.format(x.incentive)])??null}/>
 <LazyAudit title="Audit Accessories Detail" open={open.accessories} loading={sectionLoading.accessories} onToggle={()=>void toggle('accessories')} headers={['Article','Description','Qty','Unit Price','Tier','Incentive']} rows={accessoryLines?.map(x=>[x.article,x.description,x.qty,money.format(x.unitPrice),x.tier,money.format(x.incentive)])??null}/>
 {detail.qty.qoala>0&&<LazyAudit title="Audit Qoala Detail" open={open.qoala} loading={sectionLoading.qoala} onToggle={()=>void toggle('qoala')} headers={['Article','Description','Qty','Unit Price','Threshold','Rate','Incentive']} rows={qoalaLines?.map(x=>[x.article,x.description,x.qty,money.format(x.unitPrice),x.bucket,money.format(x.rate),money.format(x.incentive)])??null}/>} </div></>}</div></div>
}

function LazyAudit({title,open,loading,onToggle,headers,rows}:{title:string;open:boolean;loading:boolean;onToggle:()=>void;headers:string[];rows:(string|number)[][]|null}){return <div className="mt-4 rounded-xl border bg-white"><button onClick={onToggle} className="flex min-h-12 w-full items-center justify-between gap-3 px-4 py-3 text-left text-sm font-black"><span>{open?'▼':'▶'} {open?'Sembunyikan':'Lihat'} {title}</span><span className="text-xs font-medium text-slate-400">{open?'Hide':'Show'}</span></button>{open&&<div className="border-t p-3">{loading?<div className="p-4 text-sm text-slate-500">Memuat audit…</div>:rows&&<AuditTable headers={headers} rows={rows}/>}</div>}</div>}
function AuditTable({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-max"><thead><tr>{headers.map(x=><th className={th} key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr className="border-t" key={i}>{r.map((v,j)=><td key={j} className={j===2?"min-w-[260px] px-3 py-3 text-sm":td}>{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="p-4 text-sm text-slate-400">Tidak ada data eligible pada periode ini.</td></tr>}</tbody></table></div>}
