"use client";

import {useEffect} from "react";

type AuditRow={id:string;name:string;store:string;airpods:number;incentive:{iphone:number;macbook:number;ipad:number;watch:number;accessories:number;qoala:number;total:number}};

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const number=new Intl.NumberFormat("id-ID");
const cache=new Map<string,AuditRow[]>();
const pending=new Map<string,Promise<AuditRow[]>>();

function txt(el:any){return String(el?.textContent||"").trim()}
function byHeading(label:string){const all=Array.from(document.querySelectorAll("h2,h3")) as HTMLElement[];const h=all.find(el=>txt(el).toLowerCase()===label.toLowerCase());return (h?.closest("div.space-y-5,section")||h?.parentElement) as HTMLElement|null}
function currentPeriod(root:HTMLElement){const selects=Array.from(root.querySelectorAll("select")) as HTMLSelectElement[];const year=selects.find(s=>/^(2025|2026)$/.test(s.value));const month=selects.find(s=>/^(0[1-9]|1[0-2])$/.test(s.value));return `${year?.value||"2026"}-${month?.value||"09"}`}
async function audit(period:string):Promise<AuditRow[]>{const c=cache.get(period);if(c)return c;const p0=pending.get(period);if(p0)return p0;const p=fetch(`/api/jakarta1-staff-audit?period=${encodeURIComponent(period)}`,{cache:"no-store"}).then(r=>r.json()).then((j:any)=>{const rows=(j?.rows||[]) as AuditRow[];cache.set(period,rows);pending.delete(period);return rows}).catch(()=>{pending.delete(period);return [] as AuditRow[]});pending.set(period,p);return p}
function rowMap(rows:AuditRow[]){const m=new Map<string,AuditRow>();for(const r of rows)m.set(`${r.store}|${r.name.trim().toUpperCase()}`,r);return m}

function enhanceGrowth(){const headings=Array.from(document.querySelectorAll("h3")) as HTMLElement[];const heading=headings.find(h=>txt(h).startsWith("2025 vs 2026"));const table=(heading?.closest("section")?.querySelector("table")||heading?.parentElement?.parentElement?.querySelector("table")) as HTMLTableElement|null;if(!table)return;const trs=Array.from(table.querySelectorAll("tbody tr")) as HTMLTableRowElement[];for(const tr of trs){const cells=Array.from(tr.querySelectorAll("td")) as HTMLTableCellElement[];if(cells.length<4)continue;const cell=cells[3];if(!cell||cell.dataset.j1Growth==="1")continue;const raw=txt(cell);if(raw==="—")continue;const value=Number(raw.replace("%","").replace(",",".").replace(/[^0-9.-]/g,""));if(!Number.isFinite(value))continue;cell.dataset.j1Growth="1";cell.classList.add("font-black");if(value>0){cell.classList.add("text-emerald-600");cell.textContent=`↑ ${raw}`}else if(value<0){cell.classList.add("text-rose-600");cell.textContent=`↓ ${raw}`}else{cell.classList.add("text-slate-500");cell.textContent=`→ ${raw}`}}
}

function splitProductFocusFilters(){const headings=Array.from(document.querySelectorAll("h3")) as HTMLElement[];const heading=headings.find(h=>txt(h)==="Product Fokus Achievement");const section=heading?.closest("section") as HTMLElement|null;if(!section||section.dataset.j1FilterSplit==="1")return;const divs=Array.from(section.querySelectorAll("div")) as HTMLElement[];const grid=divs.find(d=>d.querySelectorAll(":scope > label").length===4);if(!grid)return;const labels=Array.from(grid.querySelectorAll(":scope > label")) as HTMLElement[];const year=labels.find(l=>txt(l).startsWith("Tahun"));const from=labels.find(l=>txt(l).startsWith("Dari"));const to=labels.find(l=>txt(l).startsWith("Sampai"));const week=labels.find(l=>txt(l).startsWith("Week"));if(!year||!from||!to||!week)return;
 const weekTitle=document.createElement("div");weekTitle.className="rounded-xl border bg-blue-50 px-4 py-3 text-sm font-black text-blue-700";weekTitle.textContent="FILTER WEEK";weekTitle.style.gridColumn="1 / -1";weekTitle.style.order="0";
 const customTitle=document.createElement("div");customTitle.className="rounded-xl border bg-slate-50 px-4 py-3 text-sm font-black text-slate-700";customTitle.textContent="CUSTOM RANGE";customTitle.style.gridColumn="1 / -1";customTitle.style.order="3";
 year.style.order="1";week.style.order="2";from.style.order="4";to.style.order="5";grid.appendChild(weekTitle);grid.appendChild(customTitle);section.dataset.j1FilterSplit="1";const desc=heading.nextElementSibling as HTMLElement|null;if(desc)desc.textContent="Pilih Week untuk periode mingguan, atau gunakan Custom Range untuk tanggal bebas. Keduanya dibuat terpisah agar tidak rancu.";
}

async function enhanceStaff(){const root=byHeading("Staff Performance");if(!root)return;const table=root.querySelector("table") as HTMLTableElement|null;if(!table)return;const rows=await audit(currentPeriod(root));const map=rowMap(rows);let headers=Array.from(table.querySelectorAll("thead th")) as HTMLTableCellElement[];if(!headers.some(h=>txt(h)==="AirPods")){const watchIndex=headers.findIndex(h=>txt(h)==="Apple Watch");const watch=watchIndex>=0?headers[watchIndex]:null;if(watch){const th=document.createElement("th");th.className=watch.className;th.textContent="AirPods";watch.insertAdjacentElement("afterend",th)}}
 const trs=Array.from(table.querySelectorAll("tbody tr")) as HTMLTableRowElement[];for(const tr of trs){const cells=Array.from(tr.querySelectorAll("td")) as HTMLTableCellElement[];if(cells.length<8)continue;const name=cells[0],store=cells[1],watch=cells[7];if(!name||!store||!watch)continue;const r=map.get(`${txt(store)}|${txt(name).toUpperCase()}`);let air=Array.from(tr.querySelectorAll("td")).find((c:any)=>c.dataset?.j1Airpods==="1") as HTMLTableCellElement|undefined;if(!air){air=document.createElement("td");air.className=watch.className;air.dataset.j1Airpods="1";watch.insertAdjacentElement("afterend",air)}air.textContent=number.format(r?.airpods||0)}
}

async function enhanceIncentive(){const root=byHeading("Est Incentive");if(!root)return;const divs=Array.from(root.querySelectorAll("div")) as HTMLElement[];for(const d of divs){const t=txt(d);if(t.includes("Accessories Rule")&&t.includes("Qoala Rule")){d.remove();break}}const table=root.querySelector("table") as HTMLTableElement|null;if(!table)return;const rows=await audit(currentPeriod(root));const map=rowMap(rows);const trs=Array.from(table.querySelectorAll("tbody tr")) as HTMLTableRowElement[];for(const tr of trs){const cells=Array.from(tr.querySelectorAll("td")) as HTMLTableCellElement[];if(cells.length<9)continue;const name=cells[0],store=cells[1];if(!name||!store)continue;const r=map.get(`${txt(store)}|${txt(name).toUpperCase()}`);if(!r)continue;const vals=[r.incentive.iphone,r.incentive.macbook,r.incentive.ipad,r.incentive.watch,r.incentive.accessories,r.incentive.qoala,r.incentive.total];for(let i=0;i<vals.length;i++){const cell=cells[i+2];if(cell){cell.textContent=money.format(vals[i]||0);cell.dataset.j1Audit="1"}}}}

export default function Jakarta1RevisionEnhancer(){useEffect(()=>{let raf=0;const run=()=>{raf=0;enhanceGrowth();splitProductFocusFilters();void enhanceStaff();void enhanceIncentive()};const schedule=()=>{if(!raf)raf=requestAnimationFrame(run)};run();const mo=new MutationObserver(schedule);mo.observe(document.body,{childList:true,subtree:true});document.addEventListener("change",schedule,true);return()=>{mo.disconnect();document.removeEventListener("change",schedule,true);if(raf)cancelAnimationFrame(raf)}},[]);return null}
