"use client";

import {useEffect,useMemo,useState} from "react";

type FilterMode="week"|"month"|"range";
type Tot={qty:number;value:number};
type Product={name:string;qty:number;value:number};
type StaffRow={id?:string;name:string;products:Record<string,Tot>;total:Tot;deviceTotal:Tot};
type Payload={periodLabel:string;week:string;month:string;from:string;to:string;availableWeeks:string[];availableMonths:string[];lob:{products:Product[];staff:StaffRow[];total:Tot}};
type TargetMap=Record<string,number>;

const LOBS=["iPhone","MacBook","iPad","Apple Watch","AirPods"] as const;
const API_KEYS:Record<(typeof LOBS)[number],string>={"iPhone":"iPhone","MacBook":"MacBook","iPad":"iPad","Apple Watch":"Watch","AirPods":"AirPods"};
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const monthName=(v:string)=>{if(!/^\d{4}-\d{2}$/.test(v))return v;const[y,m]=v.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))};
const panel="m238-soft-card rounded-2xl border";
const sub="m238-subcard rounded-2xl border";

function lobOf(name:string){const x=name.toUpperCase();if(x.includes("IPHONE"))return"iPhone";if(x.includes("MACBOOK")||x.startsWith("MAC "))return"MacBook";if(x.includes("IPAD"))return"iPad";if(x.includes("WATCH")||x.startsWith("AW "))return"Apple Watch";if(x.includes("AIRPODS"))return"AirPods";return""}
function status(ach:number,target:number){const a=target?ach/target*100:0;return a>=100?"Achieve":a>=80?"Need Push":"Critical"}
function statusClass(s:string){return s==="Achieve"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300":s==="Need Push"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300":"bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300"}

export default function LobTargetFocusPage(){
 const now=today(),initialMonth=now.slice(0,7);
 const[filterMode,setFilterMode]=useState<FilterMode>("week"),[week,setWeek]=useState(""),[month,setMonth]=useState(initialMonth),[from,setFrom]=useState(`${initialMonth}-01`),[to,setTo]=useState(now);
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[targetOpen,setTargetOpen]=useState(false),[targets,setTargets]=useState<TargetMap>({}),[draft,setDraft]=useState<TargetMap>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const q=new URLSearchParams({mode:filterMode});if(filterMode==="week"&&week)q.set("week",week);if(filterMode==="month")q.set("month",month);if(filterMode==="range"){q.set("from",from);q.set("to",to)}setLoading(true);fetch(`/api/target-focus?${q.toString()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{setData(j);if(!week&&j.week)setWeek(j.week);if(j.month&&!month)setMonth(j.month)}).finally(()=>setLoading(false))},[filterMode,week,month,from,to]);
 const targetScope=filterMode==="week"?"weekly":filterMode==="month"?"monthly":"range";
 const targetPeriod=filterMode==="week"?(data?.week||week):filterMode==="month"?month:`${from}|${to}`;
 useEffect(()=>{if(!targetPeriod)return;let alive=true;fetch(`/api/manual-target?scope=${targetScope}&period=${encodeURIComponent(targetPeriod)}&group=lob-focus`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!alive||j.error)return;const next:TargetMap={};for(const lob of LOBS)next[lob]=Number(j.targets?.[API_KEYS[lob]]?.target||0);setTargets(next);setDraft(next)}).catch(()=>{});return()=>{alive=false}},[targetScope,targetPeriod]);
 const achievements=useMemo(()=>{const out:TargetMap=Object.fromEntries(LOBS.map(x=>[x,0]));for(const p of data?.lob.products||[]){const l=lobOf(p.name);if(l)out[l]=(out[l]||0)+Number(p.qty||0)}return out},[data]);
 const products=useMemo(()=>data?.lob.products.filter(p=>p.qty>0||lobOf(p.name))??[],[data]);
 const teamFocusQty=useMemo(()=>data?.lob.staff.reduce((a,r)=>a+Number(r.total.qty||0),0)||0,[data]);
 const rankedStaff=useMemo(()=>[...(data?.lob.staff||[])].sort((a,b)=>b.total.qty-a.total.qty||a.name.localeCompare(b.name)),[data]);
 const totalTarget=LOBS.reduce((a,l)=>a+(targets[l]||0),0),totalAch=LOBS.reduce((a,l)=>a+(achievements[l]||0),0),overall=totalTarget?totalAch/totalTarget*100:0,gap=Math.max(0,totalTarget-totalAch);
 const saveTarget=async()=>{setSaving(true);setMessage("");try{const bodyTargets:TargetMap={};for(const lob of LOBS)bodyTargets[API_KEYS[lob]]=Math.max(0,Number(draft[lob]||0));const r=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:targetScope,period:targetPeriod,group:"lob-focus",targets:bodyTargets})}),j=await r.json();if(!r.ok){setMessage(j.error||"Gagal menyimpan target");return}setTargets({...draft});setTargetOpen(false)}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setSaving(false)}};
 return <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Target Fokus</p><h2 className="mt-1 text-3xl font-black">LOB Target Fokus</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Monitoring target berbasis Qty / Unit.</p></div>
 <section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{(["week","month","range"] as FilterMode[]).map(f=><button key={f} onClick={()=>setFilterMode(f)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filterMode===f?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"}`}>{f==="week"?"Week":f==="month"?"Bulan":"Range Tanggal"}</button>)}</div><button onClick={()=>{setDraft({...targets});setMessage("");setTargetOpen(true)}} className="rounded-xl border px-4 py-2 text-sm font-black">Set Target LOB</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{filterMode==="week"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Apple Week</span><select value={week} onChange={e=>setWeek(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableWeeks??[]).map(w=><option key={w} value={w}>{w}</option>)}</select></label>}{filterMode==="month"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Filter Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableMonths??[]).map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label>}{filterMode==="range"&&<><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Dari Tanggal</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Sampai Tanggal</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label></>}</div><p className="mt-3 text-xs text-slate-500">Periode aktif: <b>{data?.periodLabel||"-"}</b></p></section>
 {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat data LOB Target Fokus…</div>:!data?<div className={`${panel} p-8 text-center text-slate-500`}>Data belum tersedia.</div>:<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{LOBS.map(l=>{const t=targets[l]||0,a=achievements[l]||0,pc=t?a/t*100:0;return <div key={l} className={`${sub} p-4`}><p className="font-black">{l}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-slate-400">Target</p><p className="mt-1 text-lg font-black">{num.format(t)}</p></div><div><p className="text-slate-400">Ach</p><p className="mt-1 text-lg font-black">{num.format(a)}</p></div><div><p className="text-slate-400">Ach %</p><p className="mt-1 text-lg font-black">{pct(pc)}</p></div></div></div>})}</section><section className={`${panel} p-4`}><div className="flex flex-wrap gap-x-7 gap-y-2 text-sm"><span><b>Total Target:</b> {num.format(totalTarget)} Unit</span><span><b>Achievement:</b> {num.format(totalAch)} Unit</span><span><b>Overall Achievement:</b> {pct(overall)}</span><span><b>Gap:</b> {num.format(gap)} Unit</span></div></section>
 <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Product Fokus Device</h3><p className="mt-1 text-sm text-slate-500">Qty actual pada periode terpilih. Tidak menampilkan sales value.</p></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Product</th><th className="px-4 py-3 text-right">Target</th><th className="px-4 py-3 text-right">Ach</th><th className="px-4 py-3 text-right">Ach %</th><th className="px-4 py-3 text-right">Gap</th><th className="px-4 py-3 text-right">Status</th></tr></thead><tbody>{products.map(r=>{const l=lobOf(r.name),target=l?targets[l]||0:0,ach=Number(r.qty||0),pc=target?ach/target*100:0,g=ach-target,st=status(ach,target);return <tr key={r.name} className="border-t"><td className="px-4 py-3 font-bold">{r.name}</td><td className="px-4 py-3 text-right">{num.format(target)}</td><td className="px-4 py-3 text-right font-black">{num.format(ach)}</td><td className="px-4 py-3 text-right">{pct(pc)}</td><td className="px-4 py-3 text-right">{g>0?`+${num.format(g)}`:num.format(g)}</td><td className="px-4 py-3 text-right"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass(st)}`}>{st}</span></td></tr>})}</tbody></table></div></section>
 <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Penjualan Staff M238</h3><p className="mt-1 text-sm text-slate-500">Ranking dan contribution berdasarkan total Qty product fokus.</p></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead><tr><th className="px-3 py-3 text-center">#</th><th className="sticky left-0 bg-white px-4 py-3 text-left dark:bg-slate-950">Staff</th>{products.map(p=><th key={p.name} className="px-3 py-3 text-right">{p.name}</th>)}<th className="px-3 py-3 text-right">TOTAL</th><th className="px-3 py-3 text-right">Contribution %</th></tr></thead><tbody>{rankedStaff.map((r,i)=><tr key={r.id||r.name} className="border-t"><td className="px-3 py-3 text-center font-bold">{i+1}</td><td className="sticky left-0 bg-white px-4 py-3 font-bold dark:bg-slate-950">{r.name}</td>{products.map(p=><td key={p.name} className="px-3 py-3 text-right">{num.format(r.products[p.name]?.qty||0)}</td>)}<td className="px-3 py-3 text-right font-black">{num.format(r.total.qty||0)}</td><td className="px-3 py-3 text-right">{pct(teamFocusQty?r.total.qty/teamFocusQty*100:0)}</td></tr>)}</tbody></table></div></section></>}
 {targetOpen&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/35 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setTargetOpen(false)}}><div className="m238-soft-card w-full max-w-lg rounded-2xl border bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Set Target LOB</p><h3 className="mt-1 text-xl font-black">{data?.periodLabel||targetPeriod}</h3></div><button onClick={()=>setTargetOpen(false)} className="rounded-lg border px-3 py-1.5 text-sm font-bold">Tutup</button></div><div className="mt-4 space-y-3">{LOBS.map(l=><label key={l} className="flex items-center justify-between gap-4"><span className="font-bold">{l}</span><input type="number" min="0" step="1" value={draft[l]??0} onChange={e=>setDraft(v=>({...v,[l]:Math.max(0,Math.floor(Number(e.target.value)||0))}))} className="h-10 w-36 rounded-xl border px-3 text-right font-black"/></label>)}</div><div className="mt-4 border-t pt-4 text-sm"><b>Total Target:</b> {num.format(LOBS.reduce((a,l)=>a+(draft[l]||0),0))} Unit</div>{message&&<p className="mt-3 text-sm font-bold text-rose-600">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setTargetOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button disabled={saving} onClick={saveTarget} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{saving?"Menyimpan…":"Simpan Target"}</button></div></div></div>}
 </div>
}
