"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Tab="general"|"appearance"|"operations"|"system";
type ThemeMode="light"|"dark"|"system";
type FontKey="system"|"inter"|"roboto";
type Density="compact"|"normal"|"comfortable";
type RefreshKey="off"|"auto"|"300000"|"600000"|"900000";
type DefaultPage="Overview"|"Daily Sales"|"Daily Summary"|"Staff Performance";
type DefaultPeriod="month"|"appleweek"|"today";
type DashboardTheme="classic"|"natural"|"worklife"|"happiness"|"premium";
type HealthRow={label:string;status:"Connected"|"Warning"|"Error";detail:string};
type LoginRow={nik:string;name:string;count:number;lastLogin:string};

const fonts:{key:FontKey;label:string;family:string}[]=[
 {key:"system",label:"System / Default",family:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'},
 {key:"inter",label:"Inter",family:'Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif'},
 {key:"roboto",label:"Roboto",family:'Roboto,Arial,sans-serif'},
];
const themePreview:Record<DashboardTheme,{label:string;bg:string;card:string;primary:string;status:string}>={
 classic:{label:"Classic",bg:"#f8fafc",card:"#ffffff",primary:"#2563eb",status:"#16a34a"},
 natural:{label:"Natural",bg:"#f4f7f4",card:"#ffffff",primary:"#059669",status:"#16a34a"},
 worklife:{label:"Worklife",bg:"#f8fafc",card:"#ffffff",primary:"#334155",status:"#2563eb"},
 happiness:{label:"Happiness",bg:"#fffaf5",card:"#ffffff",primary:"#f97316",status:"#16a34a"},
 premium:{label:"M238 Premium",bg:"#f4f6f8",card:"#ffffff",primary:"#0f3b66",status:"#15803d"},
};
const input="h-11 w-full rounded-xl border bg-white px-3 text-sm font-semibold text-slate-700 outline-none focus:ring-2 focus:ring-blue-200 dark:bg-slate-900 dark:text-slate-100";
const card="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950";

function applyFont(key:FontKey){const item=fonts.find(x=>x.key===key)||fonts[0];document.documentElement.style.fontFamily=item.family;document.body.style.fontFamily=item.family;localStorage.setItem("m238-font-family",key)}
function applyThemeMode(mode:ThemeMode){localStorage.setItem("m238-theme-mode",mode);const dark=mode==="dark"||(mode==="system"&&window.matchMedia("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark",dark);localStorage.setItem("m238-theme",dark?"dark":"light")}
function ensureStyle(){let style=document.getElementById("m238-settings-runtime-style") as HTMLStyleElement|null;if(!style){style=document.createElement("style");style.id="m238-settings-runtime-style";style.textContent=`html[data-m238-density='compact'] table th,html[data-m238-density='compact'] table td{padding-top:.5rem!important;padding-bottom:.5rem!important}html[data-m238-density='comfortable'] table th,html[data-m238-density='comfortable'] table td{padding-top:1rem!important;padding-bottom:1rem!important}html[data-m238-dashboard-theme='premium']{--m238-premium:#0f3b66}html[data-m238-dashboard-theme='premium'] main{background:#f4f6f8}html[data-m238-dashboard-theme='premium'] button.bg-blue-600,html[data-m238-dashboard-theme='premium'] .bg-blue-600{background-color:#0f3b66!important}html[data-m238-dashboard-theme='premium'] .text-blue-600{color:#0f3b66!important}html[data-m238-dashboard-theme='premium'] .border-blue-500{border-color:#0f3b66!important}`;document.head.appendChild(style)}}
function applyDensity(v:Density){document.documentElement.dataset.m238Density=v;localStorage.setItem("m238-table-density",v)}
function applyDashboardTheme(v:DashboardTheme){document.documentElement.dataset.m238DashboardTheme=v;localStorage.setItem("m238-style",v)}
function statusBadge(status:HealthRow["status"]){const c=status==="Connected"?"bg-emerald-50 text-emerald-700":status==="Warning"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-black ${c}`}>{status}</span>}
function Section({title,sub,children}:{title:string;sub?:string;children:React.ReactNode}){return <section className={card}><div><h3 className="font-extrabold">{title}</h3>{sub?<p className="mt-1 text-sm text-slate-500">{sub}</p>:null}</div><div className="mt-4">{children}</div></section>}
function SettingSelect({label,value,onChange,children}:{label:string;value:string;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[.12em] text-slate-400">{label}</span><select className={input} value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}

export default function M238SettingsEnhancer(){
 const[host,setHost]=useState<HTMLElement|null>(null),[tab,setTab]=useState<Tab>("general"),[refresh,setRefresh]=useState<RefreshKey>("auto"),[defaultPage,setDefaultPage]=useState<DefaultPage>("Overview"),[defaultPeriod,setDefaultPeriod]=useState<DefaultPeriod>("month"),[density,setDensity]=useState<Density>("normal"),[fontSize,setFontSize]=useState("normal"),[themeMode,setThemeMode]=useState<ThemeMode>("light"),[font,setFont]=useState<FontKey>("system"),[dashboardTheme,setDashboardTheme]=useState<DashboardTheme>("worklife"),[threshold,setThreshold]=useState(2),[fastBasis,setFastBasis]=useState<7|30>(30),[health,setHealth]=useState<HealthRow[]>([]),[loginRows,setLoginRows]=useState<LoginRow[]>([]),[diag,setDiag]=useState<string[]>([]),[loadingDiag,setLoadingDiag]=useState(false),[lastSync,setLastSync]=useState("—");
 useEffect(()=>{ensureStyle();const r=(localStorage.getItem("m238-refresh")||"auto") as RefreshKey;setRefresh((["off","auto","300000","600000","900000"] as string[]).includes(r)?r:"auto");setDefaultPage((localStorage.getItem("m238-default-page")||"Overview") as DefaultPage);setDefaultPeriod((localStorage.getItem("m238-default-period")||"month") as DefaultPeriod);const d=(localStorage.getItem("m238-table-density")||"normal") as Density;setDensity(d);applyDensity(d);setFontSize(localStorage.getItem("m238-font")||"normal");const tm=(localStorage.getItem("m238-theme-mode")||localStorage.getItem("m238-theme")||"light") as ThemeMode;setThemeMode(tm);applyThemeMode(tm);const ff=(localStorage.getItem("m238-font-family")||"system") as FontKey;setFont(ff);applyFont(ff);const ds=(localStorage.getItem("m238-style")||"worklife") as DashboardTheme;setDashboardTheme((Object.keys(themePreview) as DashboardTheme[]).includes(ds)?ds:"worklife");applyDashboardTheme((Object.keys(themePreview) as DashboardTheme[]).includes(ds)?ds:"worklife");setThreshold(Math.max(0,Number(localStorage.getItem("m238-low-stock-threshold")||2)||2));setFastBasis((Number(localStorage.getItem("m238-fast-moving-days")||30)===7?7:30));const mq=window.matchMedia("(prefers-color-scheme: dark)"),fn=()=>{if((localStorage.getItem("m238-theme-mode")||"")==="system")applyThemeMode("system")};mq.addEventListener?.("change",fn);return()=>mq.removeEventListener?.("change",fn)},[]);
 useEffect(()=>{const sync=()=>{const title=Array.from(document.querySelectorAll("h1")).find(x=>(x.textContent||"").trim()==="Settings") as HTMLElement|undefined;if(!title){setHost(null);return}const page=title.closest("div.space-y-5") as HTMLElement|null;if(!page)return;let node=page.querySelector("[data-m238-settings-redesign]") as HTMLElement|null;if(!node){node=document.createElement("div");node.dataset.m238SettingsRedesign="1";page.appendChild(node)}Array.from(page.children).forEach(el=>{if(el===node||el.contains(title))return;(el as HTMLElement).style.display="none"});setHost(v=>v===node?v:node)};sync();const t=setInterval(sync,500);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(tab!=="system")return;void refreshSystem()},[tab]);
 const refreshSystem=async()=>{const now=new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"}),rows:HealthRow[]=[];try{const [data,daily,soh,weekly,login]=await Promise.allSettled([fetch(`/api/data?period=${new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date())}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/daily?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/soh?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/target-focus?mode=week&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/login-activity?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json())]);const dj=data.status==="fulfilled"?data.value:null,dd=daily.status==="fulfilled"?daily.value:null,ss=soh.status==="fulfilled"?soh.value:null,ww=weekly.status==="fulfilled"?weekly.value:null,ll=login.status==="fulfilled"?login.value:null;rows.push({label:"Raw Sales Data",status:dj?.mode==="live"?"Connected":"Warning",detail:dj?.latestDate?`Last sync ${dj.latestDate}`:"Data belum terbaca"});rows.push({label:"Config Data",status:dj?.target?"Connected":"Warning",detail:dj?.target?"Target/config terbaca":"Config belum terbaca"});rows.push({label:"Schedule Data",status:dd?.scheduleSource?"Connected":"Warning",detail:dd?.scheduleSource||"Schedule belum terbaca"});rows.push({label:"SOH Data",status:Array.isArray(ss?.rows)?"Connected":"Warning",detail:ss?.updated?`Update ${ss.updated}`:"Update belum tersedia"});rows.push({label:"Weekly Mapping",status:ww?.week||ww?.availableWeeks?.length?"Connected":"Warning",detail:ww?.week||"Apple Week belum terbaca"});rows.push({label:"Staff Data",status:Array.isArray(dj?.monthlyStaff)&&dj.monthlyStaff.length?"Connected":"Warning",detail:Array.isArray(dj?.monthlyStaff)?`${dj.monthlyStaff.length} staff terbaca`:"Staff belum terbaca"});setHealth(rows);setLoginRows(Array.isArray(ll?.rows)?ll.rows:[]);setLastSync(now)}catch{setHealth([{label:"System Health",status:"Error",detail:"Pemeriksaan data gagal dijalankan"}]);setLoginRows([]);setLastSync(now)}};
 const diagnose=async()=>{setLoadingDiag(true);await refreshSystem();setTimeout(()=>{const pass=health.filter(x=>x.status==="Connected").length,warn=health.filter(x=>x.status==="Warning").length,err=health.filter(x=>x.status==="Error").length;setDiag([`${pass} checks passed`,warn?`${warn} warning${warn>1?"s":""}`:"Tidak ada warning",err?`${err} error`:`Tidak ada error utama`]);setLoadingDiag(false)},0)};
 const updateHiddenRefresh=(v:RefreshKey)=>{setRefresh(v);localStorage.setItem("m238-refresh",v);const title=Array.from(document.querySelectorAll("h1")).find(x=>x.textContent?.trim()==="Settings"),page=title?.closest("div.space-y-5");const sel=page?.querySelector("section select") as HTMLSelectElement|null;if(sel&&v!=="off"&&[...sel.options].some(o=>o.value===v)){sel.value=v;sel.dispatchEvent(new Event("change",{bubbles:true}))}};
 const updateFontSize=(v:string)=>{setFontSize(v);localStorage.setItem("m238-font",v);const title=Array.from(document.querySelectorAll("h1")).find(x=>x.textContent?.trim()==="Settings"),sels=title?.closest("div.space-y-5")?.querySelectorAll("select");const sel=sels?.[1] as HTMLSelectElement|undefined;if(sel){sel.value=v;sel.dispatchEvent(new Event("change",{bubbles:true}))}};
 const updateDashboardTheme=(v:DashboardTheme)=>{setDashboardTheme(v);applyDashboardTheme(v);if(v!=="premium"){const title=Array.from(document.querySelectorAll("h1")).find(x=>x.textContent?.trim()==="Settings"),buttons=Array.from(title?.closest("div.space-y-5")?.querySelectorAll("button")||[]),btn=buttons.find(b=>b.textContent?.trim()===themePreview[v].label) as HTMLButtonElement|undefined;btn?.click()}};
 const saveThreshold=(v:number)=>{const x=Math.max(0,Math.floor(Number.isFinite(v)?v:0));setThreshold(x);localStorage.setItem("m238-low-stock-threshold",String(x))};
 const resetAppearance=()=>{if(!window.confirm("Reset tampilan dashboard ke default? Data operasional tidak akan berubah."))return;["m238-font-family","m238-font","m238-table-density","m238-theme-mode","m238-theme","m238-style"].forEach(k=>localStorage.removeItem(k));setFont("system");applyFont("system");setFontSize("normal");updateFontSize("normal");setDensity("normal");applyDensity("normal");setThemeMode("light");applyThemeMode("light");setDashboardTheme("worklife");applyDashboardTheme("worklife")};
 const tabs:Tab[]=["general","appearance","operations","system"];
 const onlineNow=useMemo(()=>loginRows.filter(x=>{const t=Date.parse(x.lastLogin);return Number.isFinite(t)&&Date.now()-t<15*60*1000}).length,[loginRows]);
 if(!host)return null;
 return createPortal(<div className="space-y-5"><div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm dark:bg-slate-950">{tabs.map(k=><button key={k} onClick={()=>setTab(k)} className={`shrink-0 rounded-xl px-4 py-2.5 text-sm font-black capitalize ${tab===k?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{k}</button>)}</div>
 {tab==="general"&&<div className="grid gap-5 xl:grid-cols-2"><Section title="Auto Refresh" sub="Gunakan logic refresh existing dashboard."><SettingSelect label="Interval" value={refresh} onChange={v=>updateHiddenRefresh(v as RefreshKey)}><option value="off">Off</option><option value="auto">Auto</option><option value="300000">5 menit</option><option value="600000">10 menit</option><option value="900000">15 menit</option></SettingSelect></Section><Section title="Default Page"><SettingSelect label="Halaman Awal" value={defaultPage} onChange={v=>{setDefaultPage(v as DefaultPage);localStorage.setItem("m238-default-page",v)}}>{["Overview","Daily Sales","Daily Summary","Staff Performance"].map(x=><option key={x}>{x}</option>)}</SettingSelect></Section><Section title="Default Period"><SettingSelect label="Periode Awal" value={defaultPeriod} onChange={v=>{setDefaultPeriod(v as DefaultPeriod);localStorage.setItem("m238-default-period",v)}}><option value="month">Bulan Berjalan</option><option value="appleweek">Apple Week Berjalan</option><option value="today">Hari Ini</option></SettingSelect></Section><Section title="Table Density"><div className="grid grid-cols-3 gap-2">{(["compact","normal","comfortable"] as Density[]).map(x=><button key={x} onClick={()=>{setDensity(x);applyDensity(x)}} className={`rounded-xl border px-3 py-2 text-sm font-bold capitalize ${density===x?"border-blue-500 bg-blue-50 text-blue-700":""}`}>{x}</button>)}</div></Section><Section title="Font Size"><SettingSelect label="Ukuran" value={fontSize} onChange={updateFontSize}><option value="small">Small</option><option value="normal">Normal</option><option value="large">Large</option></SettingSelect></Section></div>}
 {tab==="appearance"&&<div className="space-y-5"><div className="grid gap-5 xl:grid-cols-2"><Section title="Theme Mode"><div className="grid grid-cols-3 gap-2">{(["light","dark","system"] as ThemeMode[]).map(x=><button key={x} onClick={()=>{setThemeMode(x);applyThemeMode(x)}} className={`rounded-xl border px-3 py-2 text-sm font-bold capitalize ${themeMode===x?"border-blue-500 bg-blue-50 text-blue-700":""}`}>{x}</button>)}</div></Section><Section title="Font Family"><SettingSelect label="Font" value={font} onChange={v=>{setFont(v as FontKey);applyFont(v as FontKey)}}>{fonts.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</SettingSelect></Section></div><Section title="Dashboard Theme" sub="Preview menunjukkan background, card, primary accent, dan status color."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{(Object.keys(themePreview) as DashboardTheme[]).map(k=>{const x=themePreview[k];return <button key={k} onClick={()=>updateDashboardTheme(k)} className={`rounded-2xl border p-3 text-left ${dashboardTheme===k?"ring-2 ring-blue-300":""}`}><div className="rounded-xl p-2" style={{background:x.bg}}><div className="h-8 rounded-lg border" style={{background:x.card}}/><div className="mt-2 flex gap-2"><span className="h-2 flex-1 rounded-full" style={{background:x.primary}}/><span className="h-2 w-8 rounded-full" style={{background:x.status}}/></div></div><b className="mt-2 block text-sm">{x.label}</b></button>})}</div></Section><button onClick={resetAppearance} className="rounded-xl border px-4 py-2.5 text-sm font-bold text-slate-600">Reset Tampilan ke Default</button></div>}
 {tab==="operations"&&<div className="grid gap-5 xl:grid-cols-2"><Section title="Daily Sales Configuration"><div className="flex items-center justify-between gap-3"><div><b>Target Staff Source</b><p className="text-sm text-slate-500">Config L28</p></div>{statusBadge("Connected")}</div></Section><Section title="Schedule Integration"><div className="flex items-center justify-between"><b>Schedule Source</b>{statusBadge("Connected")}</div><div className="mt-3 grid gap-2 text-sm text-slate-600 sm:grid-cols-3"><span>D047 = 09.00–17.00</span><span>D083 = 12.00–20.00</span><span>D103 = 14.00–22.00</span></div></Section><Section title="SOH Settings"><label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-slate-400">Low Stock Threshold</span><input type="number" min={0} className={input} value={threshold} onChange={e=>saveThreshold(Number(e.target.value))}/><p className="mt-2 text-xs text-slate-500">Dipakai sebagai batas indikator Stok Terbatas tanpa mengubah actual SOH.</p></label></Section><Section title="Fast Moving Basis"><div className="grid grid-cols-2 gap-2">{([7,30] as const).map(x=><button key={x} onClick={()=>{setFastBasis(x);localStorage.setItem("m238-fast-moving-days",String(x))}} className={`rounded-xl border px-3 py-2 text-sm font-bold ${fastBasis===x?"border-blue-500 bg-blue-50 text-blue-700":""}`}>{x} Hari</button>)}</div></Section><Section title="Weekly Reason Integration"><div className="space-y-3">{["Weekly Sales Data","Staff Daily Reason","SOH","Product Focus"].map(x=><div key={x} className="flex items-center justify-between gap-3"><span className="text-sm font-semibold">{x}</span>{statusBadge("Connected")}</div>)}</div></Section></div>}
 {tab==="system"&&<div className="space-y-5"><Section title="SYSTEM HEALTH" sub={`Last Sync ${lastSync}`}><div className="space-y-3">{health.length?health.map(x=><div key={x.label} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div><b className="text-sm">{x.label}</b><p className="mt-1 text-xs text-slate-500">{x.detail}</p></div>{statusBadge(x.status)}</div>):<p className="text-sm text-slate-500">Memeriksa koneksi data…</p>}</div></Section><Section title="Dashboard Diagnostics" sub="Periksa koneksi data dan masalah dashboard."><button onClick={()=>void diagnose()} disabled={loadingDiag} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">{loadingDiag?"Memeriksa…":"Diagnose Dashboard"}</button>{diag.length?<div className="mt-4 space-y-2">{diag.map((x,i)=><div key={i} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900">{x}</div>)}</div>:null}</Section><Section title="Team Login Activity"><div className="mb-4 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Active Today</p><b>{loginRows.length}</b></div><div><p className="text-xs text-slate-400">Online Now</p><b>{onlineNow}</b></div><div><p className="text-xs text-slate-400">Last Login</p><b className="text-sm">{loginRows[0]?.lastLogin||"—"}</b></div></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3 text-left">NIK</th><th className="p-3 text-left">Nama</th><th className="p-3 text-left">Status Hari Ini</th><th className="p-3 text-left">Login Terakhir</th></tr></thead><tbody>{loginRows.length?loginRows.map(r=><tr key={r.nik} className="border-b"><td className="p-3">{r.nik}</td><td className="p-3 font-bold">{r.name}</td><td className="p-3">{Date.now()-Date.parse(r.lastLogin)<15*60*1000?"Online":"Active Today"}</td><td className="p-3">{r.lastLogin||"—"}</td></tr>):<tr><td colSpan={4} className="p-6 text-center text-slate-400">Belum ada aktivitas login hari ini.</td></tr>}</tbody></table></div></Section></div>}
 </div>,host)
}
