"use client";
import {useRef,useState} from "react";
import {ChevronDown,X} from "lucide-react";

type Action="spw-upload"|"exchange"|"cutoff"|"spw-clear"|"soh-upload"|"soh-clear"|null;
type Notice={type:"success"|"error";text:string}|null;
const input="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900";
const primary="rounded-xl bg-blue-600 px-4 py-3 font-black text-white disabled:opacity-50";
const danger="rounded-xl bg-rose-600 px-4 py-3 font-black text-white disabled:opacity-50";

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/45 p-0 sm:items-center sm:p-4" role="dialog" aria-modal="true">
  <div className="max-h-[88vh] w-full overflow-y-auto rounded-t-3xl border bg-white shadow-2xl dark:bg-slate-950 sm:max-w-lg sm:rounded-3xl">
   <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white/95 p-4 backdrop-blur dark:bg-slate-950/95"><h3 className="text-lg font-black">{title}</h3><button onClick={onClose} className="rounded-xl border p-2" aria-label="Tutup"><X className="size-4"/></button></div>
   <div className="space-y-4 p-4">{children}</div>
  </div>
 </div>
}
function NoticeBox({notice}:{notice:Notice}){if(!notice)return null;return <div className={`rounded-xl border p-3 text-sm font-bold ${notice.type==="success"?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}>{notice.text}</div>}

export function DailySalesDataActions({onChanged}:{onChanged:()=>void|Promise<void>}){
 const fileRef=useRef<HTMLInputElement>(null),[menu,setMenu]=useState(false),[action,setAction]=useState<Action>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[progress,setProgress]=useState("");
 const[invoice,setInvoice]=useState(""),[exchange,setExchange]=useState(""),[preview,setPreview]=useState<any>(null),[cutMode,setCutMode]=useState<"date"|"month">("date"),[cutValue,setCutValue]=useState(()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date())),[pin,setPin]=useState("");
 const open=(a:Action)=>{setMenu(false);setAction(a);setNotice(null);setProgress("")};
 const close=()=>{if(!busy)setAction(null)};
 const uploadSpw=async()=>{const file=fileRef.current?.files?.[0];if(!file)return setNotice({type:"error",text:"Pilih file SPW terlebih dahulu."});setBusy(true);setProgress("Uploading SPW...");setNotice(null);const t1=window.setTimeout(()=>setProgress("Processing Sales..."),700),t2=window.setTimeout(()=>setProgress("Updating Daily Sales..."),1800);try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload-spw",{method:"POST",body:fd,cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload SPW gagal");if(!j.fast?.ok){setNotice({type:"error",text:`SPW berhasil diupload, tetapi Fast Daily Sales gagal diproses. ${j.fast?.error||"Data existing tetap aman."}`});return}setProgress("Ready");setNotice({type:"success",text:`SPW berhasil diupload dan Daily Sales sudah diperbarui. ${j.processedRows??j.rows} row diproses • ${j.duplicateSkipped??0} duplicate skipped • ${((Number(j.processingMs)||0)/1000).toFixed(1)} dtk`});if(fileRef.current)fileRef.current.value="";await onChanged()}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Upload SPW gagal"})}finally{clearTimeout(t1);clearTimeout(t2);setBusy(false)}};
 const findInvoice=async()=>{if(!invoice.trim())return;setBusy(true);setNotice(null);try{const r=await fetch(`/api/data-upload-ops?invoice=${encodeURIComponent(invoice.trim())}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Invoice tidak ditemukan");if(j.existingNoExchange)throw new Error(`No Exchange invoice ini sudah terisi: ${j.existingNoExchange}`);setPreview(j.preview||null)}catch(e){setPreview(null);setNotice({type:"error",text:e instanceof Error?e.message:"Invoice tidak ditemukan"})}finally{setBusy(false)}};
 const saveExchange=async()=>{if(!preview)return setNotice({type:"error",text:"Cari invoice dan periksa preview terlebih dahulu."});if(!exchange.trim())return setNotice({type:"error",text:"Masukkan No Exchange."});setBusy(true);try{const r=await fetch("/api/data-upload-ops",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"exchange",invoice:invoice.trim(),noExchange:exchange.trim()}),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal menyimpan No Exchange");setNotice({type:"success",text:`No Exchange ${exchange.trim()} berhasil disimpan.`});setExchange("")}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Gagal menyimpan No Exchange"})}finally{setBusy(false)}};
 const cutoff=async()=>{if(!cutValue)return;if(!confirm(`Jalankan Cut Off ${cutMode==="date"?"tanggal":"bulan"} ${cutValue}? Hasil tetap append ke Data Copas dan history tidak dihapus.`))return;setBusy(true);try{const r=await fetch("/api/data-upload-ops",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"cutoff",mode:cutMode,value:cutValue}),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Cut Off gagal");setNotice({type:"success",text:`Cut Off berhasil. ${j.rows} baris ditambahkan ke Data Copas.`})}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Cut Off gagal"})}finally{setBusy(false)}};
 const clearSpw=async()=>{if(!pin)return setNotice({type:"error",text:"Masukkan Passcode Admin."});if(!confirm("Yakin ingin clear SPW aktif? Data upload aktif dan cache Daily Sales akan dikosongkan. Data Cut Off/history tetap aman."))return;setBusy(true);try{const r=await fetch("/api/data-tools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear-spw",passcode:pin}),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Clear SPW gagal");setNotice({type:"success",text:j.message||"SPW aktif dan Fast Daily Sales berhasil dikosongkan. Silakan upload file terbaru."});await onChanged()}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Clear SPW gagal"})}finally{setBusy(false)}};
 return <div className="relative">
  <button onClick={()=>setMenu(v=>!v)} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2.5 text-sm font-black dark:bg-slate-950">Kelola Data <ChevronDown className="size-4"/></button>
  {menu&&<div className="absolute right-0 top-12 z-50 w-56 overflow-hidden rounded-2xl border bg-white p-2 shadow-xl dark:bg-slate-950">{[["spw-upload","Upload SPW"],["exchange","No Exchange Invoice"],["cutoff","Cut Off Data"],["spw-clear","Clear SPW"]].map(([k,l])=><button key={k} onClick={()=>open(k as Action)} className="block w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-900">{l}</button>)}</div>}
  {action==="spw-upload"&&<Modal title="Upload SPW" onClose={close}><input ref={fileRef} type="file" accept=".xlsx,.xls" className="w-full rounded-xl border p-2"/><NoticeBox notice={notice}/>{progress&&<div className="rounded-xl bg-slate-50 p-3 text-sm font-bold dark:bg-slate-900">{progress}</div>}<button disabled={busy} onClick={uploadSpw} className={`${primary} w-full`}>{busy?progress||"Memproses...":"Upload SPW"}</button></Modal>}
  {action==="exchange"&&<Modal title="No Exchange Invoice" onClose={close}><input className={input} value={invoice} onChange={e=>{setInvoice(e.target.value);setPreview(null)}} placeholder="No Invoice"/><button disabled={busy||!invoice.trim()} onClick={findInvoice} className={`${primary} w-full`}>{busy?"Mencari...":"Cari Invoice"}</button>{preview&&<div className="rounded-xl border bg-slate-50 p-3 text-sm dark:bg-slate-900"><b>{preview.invoice}</b><div className="mt-1 text-slate-500">{preview.date||"—"} • {preview.staff||preview.staffId||"—"}</div><div className="mt-1 text-xs text-slate-500">{preview.article||"—"} • {preview.description||"—"} • Qty {preview.qty}</div></div>}<input className={input} value={exchange} onChange={e=>setExchange(e.target.value)} placeholder="No Exchange"/><NoticeBox notice={notice}/><button disabled={busy||!preview||!exchange.trim()} onClick={saveExchange} className={`${primary} w-full`}>Simpan No Exchange</button></Modal>}
  {action==="cutoff"&&<Modal title="Cut Off Data" onClose={close}><select className={input} value={cutMode} onChange={e=>{const m=e.target.value as "date"|"month";setCutMode(m);setCutValue(m==="date"?new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()):new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date()))}}><option value="date">Tanggal</option><option value="month">Bulan</option></select><input className={input} type={cutMode==="date"?"date":"month"} value={cutValue} onChange={e=>setCutValue(e.target.value)}/><NoticeBox notice={notice}/><button disabled={busy||!cutValue} onClick={cutoff} className={`${primary} w-full`}>{busy?"Memproses...":"Jalankan Cut Off"}</button></Modal>}
  {action==="spw-clear"&&<Modal title="Clear SPW" onClose={close}><p className="text-sm text-slate-500">Clear SPW aktif, SALES DASHBOARD DATA current, dan DAILY SALES CACHE current. Data Cut Off/history, No Exchange, Config, Schedule, dan SOH tetap aman.</p><input type="password" className={input} value={pin} onChange={e=>setPin(e.target.value)} placeholder="Passcode Admin"/><NoticeBox notice={notice}/><button disabled={busy||!pin} onClick={clearSpw} className={`${danger} w-full`}>{busy?"Memproses...":"Ya, Clear SPW"}</button></Modal>}
 </div>
}

export function SohDataActions({onChanged}:{onChanged:()=>void|Promise<void>}){
 const fileRef=useRef<HTMLInputElement>(null),[menu,setMenu]=useState(false),[action,setAction]=useState<Action>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState<Notice>(null),[pin,setPin]=useState("");
 const upload=async()=>{const file=fileRef.current?.files?.[0];if(!file)return setNotice({type:"error",text:"Pilih file SOH terlebih dahulu."});setBusy(true);try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload-soh",{method:"POST",body:fd,cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload SOH gagal");setNotice({type:"success",text:`Upload SOH berhasil. ${j.rows} baris tersimpan di MASTER DATA M238.`});if(fileRef.current)fileRef.current.value="";await onChanged()}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Upload SOH gagal"})}finally{setBusy(false)}};
 const clear=async()=>{if(!pin)return setNotice({type:"error",text:"Masukkan Passcode Admin."});if(!confirm("Yakin ingin Clear SOH aktif? Hanya data SOH aktif yang akan dikosongkan."))return;setBusy(true);try{const r=await fetch("/api/data-tools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear-soh",passcode:pin}),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Clear SOH gagal");setNotice({type:"success",text:j.message||"SOH aktif berhasil dikosongkan."});await onChanged()}catch(e){setNotice({type:"error",text:e instanceof Error?e.message:"Clear SOH gagal"})}finally{setBusy(false)}};
 return <div className="relative"><button onClick={()=>setMenu(v=>!v)} className="flex items-center gap-2 rounded-xl border bg-white px-3 py-2.5 text-sm font-black dark:bg-slate-950">Kelola SOH <ChevronDown className="size-4"/></button>{menu&&<div className="absolute right-0 top-12 z-50 w-48 overflow-hidden rounded-2xl border bg-white p-2 shadow-xl dark:bg-slate-950"><button onClick={()=>{setMenu(false);setAction("soh-upload");setNotice(null)}} className="block w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-900">Upload SOH</button><button onClick={()=>{setMenu(false);setAction("soh-clear");setNotice(null)}} className="block w-full rounded-xl px-3 py-2.5 text-left text-sm font-bold hover:bg-slate-100 dark:hover:bg-slate-900">Clear SOH</button></div>}{action==="soh-upload"&&<Modal title="Upload SOH" onClose={()=>!busy&&setAction(null)}><input ref={fileRef} type="file" accept=".xlsx,.xls" className="w-full rounded-xl border p-2"/><NoticeBox notice={notice}/><button disabled={busy} onClick={upload} className={`${primary} w-full`}>{busy?"Mengunggah...":"Upload SOH"}</button></Modal>}{action==="soh-clear"&&<Modal title="Clear SOH" onClose={()=>!busy&&setAction(null)}><p className="text-sm text-slate-500">Clear hanya data SOH aktif. SPW, Daily Sales, Cut Off, No Exchange, Config, dan Schedule tidak disentuh.</p><input type="password" className={input} value={pin} onChange={e=>setPin(e.target.value)} placeholder="Passcode Admin"/><NoticeBox notice={notice}/><button disabled={busy||!pin} onClick={clear} className={`${danger} w-full`}>{busy?"Memproses...":"Ya, Clear SOH"}</button></Modal>}</div>
}
