"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
type Data={target:{amount:number;device:number;accessories:number;vas:number};summary:{amount:number;device:number;accessories:number;vas:number;estimate:number};daily:Array<{date:string;amount:number;device:number;accessories:number;vas:number}>};
function estimate(actual:number,lastDay:number,dim:number){return lastDay?actual/lastDay*dim:0}
function readOverviewPeriod(){const labels=Array.from(document.querySelectorAll<HTMLLabelElement>("label"));for(const label of labels){const text=(label.textContent||"").toLowerCase(),select=label.querySelector("select") as HTMLSelectElement|null;if(text.includes("filter bulan")&&select&&/^20\d{2}-\d{2}$/.test(select.value)&&select.offsetParent!==null)return select.value}return today().slice(0,7)}
function Overview({period}:{period:string}){
 const[data,setData]=useState<Data|null>(null);
 useEffect(()=>{let alive=true;fetch(`/api/data?period=${period}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(alive)setData(d)}).catch(()=>{});return()=>{alive=false}},[period]);
 if(!data)return <div className="m238-soft-card p-5 text-sm text-slate-500 dark:text-slate-400">Memuat overview {period}…</div>;
 const days=data.daily||[],last=Math.max(1,...days.map(x=>Number(x.date.slice(8,10))||1)),[y,m]=period.split("-").map(Number),dim=new Date(y,m,0).getDate();
 const ratio=(a:number,t:number)=>t?a/t*100:0,point=(a:number,t:number,max:number)=>Math.min(t?a/t*max:0,max);
 const cards=[
  {label:"AMOUNT",actual:data.summary.amount,target:data.target.amount,estimate:data.summary.estimate||estimate(data.summary.amount,last,dim),point:""},
  {label:"DEVICE",actual:data.summary.device,target:data.target.device,estimate:estimate(data.summary.device,last,dim),point:` • Point ${point(data.summary.device,data.target.device,60).toFixed(1)}/60`},
  {label:"ACC",actual:data.summary.accessories,target:data.target.accessories,estimate:estimate(data.summary.accessories,last,dim),point:` • Point ${point(data.summary.accessories,data.target.accessories,30).toFixed(1)}/30`},
  {label:"VAS",actual:data.summary.vas,target:data.target.vas,estimate:estimate(data.summary.vas,last,dim),point:` • Point ${point(data.summary.vas,data.target.vas,10).toFixed(1)}/10`},
 ];
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white px-5 py-4 shadow-sm dark:bg-slate-950"><div className="flex items-center gap-4"><div className="text-3xl font-black tracking-[-.08em] text-blue-600">digimap</div><div className="h-9 w-px bg-slate-200 dark:bg-slate-800"/><div><div className="text-xs font-black uppercase tracking-[.16em] text-slate-400">M238</div><div className="text-lg font-black text-slate-900 dark:text-slate-100">Pondok Indah Mall 2</div></div></div><div className="text-xs font-bold text-slate-400">Periode {period}</div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(c=><article key={c.label} className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-950"><p className="text-[12px] font-black tracking-[.18em] text-slate-500 dark:text-slate-400">{c.label}</p><p className="mt-4 text-2xl font-black tracking-[-.04em] text-slate-900 dark:text-slate-100">{money.format(c.actual)}</p><p className="mt-2 text-sm font-medium text-slate-500 dark:text-slate-400">Target {money.format(c.target)} · {pct(ratio(c.actual,c.target))}{c.point}</p><p className="mt-4 text-sm font-black text-slate-600 dark:text-slate-300">Estimasi {money.format(c.estimate)}</p></article>)}</div></div>
}
export default function M238RevisionSep8(){const[period,setPeriod]=useState(today().slice(0,7)),[host,setHost]=useState<HTMLElement|null>(null);useEffect(()=>{let raf=0;const sync=()=>{raf=0;setPeriod(readOverviewPeriod());const h=Array.from(document.querySelectorAll("h2,h3")).find(x=>(x.textContent||"").includes("M238 Sales Overview")) as HTMLElement|undefined;if(!h)return;const sec=(h.closest("section")||h.parentElement?.parentElement) as HTMLElement|null;if(!sec)return;for(const child of Array.from(sec.children)){const el=child as HTMLElement;if(el.dataset.m238OverviewV2)continue;if(el.classList.contains("grid"))el.style.display="none"}let x=sec.querySelector("[data-m238-overview-v2]") as HTMLElement|null;if(!x){x=document.createElement("div");x.dataset.m238OverviewV2="1";x.className="mt-4";sec.appendChild(x)}setHost(v=>v===x?v:x)};const schedule=()=>{if(!raf)raf=requestAnimationFrame(sync)};sync();const mo=new MutationObserver(schedule);mo.observe(document.body,{childList:true,subtree:true});document.addEventListener("change",schedule,true);return()=>{if(raf)cancelAnimationFrame(raf);mo.disconnect();document.removeEventListener("change",schedule,true)}},[]);return <>{host&&createPortal(<Overview period={period}/>,host)}</>}
