"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {RefreshCw,Upload,X} from "lucide-react";

const moneyShort=new Intl.NumberFormat("id-ID",{notation:"compact",compactDisplay:"short",style:"currency",currency:"IDR",maximumFractionDigits:1});
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateLabel=(v:string)=>new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00`));
function label(button:HTMLButtonElement){return(button.dataset.menuLabel||button.querySelector("span:last-child")?.textContent||button.textContent||"").trim()}

type Staff={scheduleOrder:number;staffId:string;staffName:string;status:string;amount:number;vas:number;acc:number;upt:number;atv:number;transaction:number;qty:number};
type Slot={slot:string;status:string;totalSales:number|null;transaction:number|null;updateTime:string|null};
type Payload={date:string;updatedAt:string|null;lastUpdate:string|null;status:string;updateSlots:Slot[];staffSales:Staff[];summary:{totalSales:number;totalVas:number;totalAcc:number;avgUpt:number;avgAtv:number;totalTransactions:number};error?:string};
type SortKey="schedule"|"amount"|"vas"|"acc"|"upt"|"atv";

function Modal({onClose,children}:{onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl dark:bg-slate-950 sm:max-w-lg sm:rounded-3xl"><div className="sticky top-0 flex items-center justify-between border-b bg-white/95 p-4 dark:bg-slate-950/95"><h3 className="text-lg font-black">Upload Data Sales</h3><button onClick={onClose} className="rounded-xl border p-2"><X className="size-4"/></button></div>{children}</div></div>}

function UpdateSalesView(){
 const[date,setDate]=useState(today()),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sort,setSort]=useState<SortKey>("schedule"),[modal,setModal]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[notice,setNotice]=useState(""),fileRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/update-sales-2jam?date=${date}&t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Data Update Sales belum berhasil dimuat.");setData(j)}catch(e){setError(e instanceof Error?e.message:"Data Update Sales belum berhasil dimuat.")}finally{setLoading(false)}},[date]);
 useEffect(()=>{void load()},[load]);
 const rows=useMemo(()=>{const out=[...(data?.staffSales||[])];if(sort==="schedule")return out.sort((a,b)=>a.scheduleOrder-b.scheduleOrder);return out.sort((a,b)=>b[sort]-a[sort])},[data,sort]);
 const upload=async()=>{const file=fileRef.current?.files?.[0];if(!file)return setNotice("Pilih file XLS/XLSX terlebih dahulu.");setBusy(true);setNotice("");setProgress("Uploading Sales...");const t1=window.setTimeout(()=>setProgress("Processing Sales..."),700),t2=window.setTimeout(()=>setProgress("Updating Performance..."),1800);try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload-spw",{method:"POST",body:fd,cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload gagal");if(!j.fast?.ok)throw new Error("Upload berhasil, tetapi performance belum berhasil diperbarui.");setProgress("Ready");if(j.dataDate)setDate(j.dataDate);setNotice(`Data sales berhasil diperbarui. ${j.processedRows??j.rows} rows • ${j.staffDetected??0} staff • ${money.format(j.masterSales||0)} • ${((Number(j.processingMs)||0)/1000).toFixed(1)} dtk`);if(fileRef.current)fileRef.current.value="";await new Promise(r=>setTimeout(r,250));await load()}catch(e){setNotice(e instanceof Error?e.message:"Upload berhasil, tetapi performance belum berhasil diperbarui.")}finally{clearTimeout(t1);clearTimeout(t2);setBusy(false)}};
 const statusTone=data?.status==="Data Terbaru"?"bg-emerald-50 text-emerald-700 border-emerald-200":data?.status==="Data Terlambat"?"bg-amber-50 text-amber-700 border-amber-200":"bg-slate-50 text-slate-600";
 return <div className="space-y-5">
  <div className="flex flex-col gap-4 rounded-3xl border bg-white p-5 shadow-sm dark:bg-slate-950 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">M238 – Digimap PIM 2</p><h1 className="mt-1 text-3xl font-black">Update Sales 2 Jam</h1><div className="mt-3 flex flex-wrap gap-2 text-sm"><span className="rounded-xl border px-3 py-2">Tanggal Data: <b>{dateLabel(date)}</b></span><span className="rounded-xl border px-3 py-2">Update Terakhir: <b>{data?.lastUpdate?`${data.lastUpdate} WIB`:"—"}</b></span><span className={`rounded-xl border px-3 py-2 font-black ${statusTone}`}>{data?.status||"Belum Ada Data"}</span></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setModal(true)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-black text-white"><Upload className="size-4"/>Upload Data Sales</button><button onClick={()=>void load()} disabled={loading} className="flex items-center gap-2 rounded-xl border px-4 py-3 font-black disabled:opacity-50"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Perbarui</button></div></div>
  <div className="flex items-center justify-between gap-3"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 rounded-xl border bg-white px-3 font-bold dark:bg-slate-950"/></div>
  {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-700"><b>Data Update Sales belum berhasil dimuat.</b><button onClick={()=>void load()} className="ml-3 rounded-lg border px-3 py-1.5 font-bold">Coba Lagi</button></div>:null}
  <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b p-4"><h2 className="font-black">Update Sales Per 2 Jam</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr><th className="p-3">Jam</th><th className="p-3">Status</th><th className="p-3">Total Sales</th><th className="p-3">Transaction</th><th className="p-3">Update Time</th></tr></thead><tbody>{(data?.updateSlots||[]).map(s=><tr key={s.slot} className="border-t"><td className="p-3 font-black">{s.slot}</td><td className="p-3"><span className={`rounded-lg px-2 py-1 text-xs font-black ${s.status==="Updated"?"bg-emerald-50 text-emerald-700":s.status==="Menunggu Update"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{s.status}</span></td><td className="p-3 font-bold">{s.totalSales==null?"—":moneyShort.format(s.totalSales)}</td><td className="p-3">{s.transaction==null?"—":s.transaction}</td><td className="p-3">{s.updateTime?`${s.updateTime} WIB`:"—"}</td></tr>)}</tbody></table></div></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Total Sales",data?.summary.totalSales||0,"money"],["Total VAS",data?.summary.totalVas||0,"money"],["Total ACC",data?.summary.totalAcc||0,"money"],["Avg UPT",data?.summary.avgUpt||0,"num"],["Avg ATV",data?.summary.avgAtv||0,"money"]].map(([l,v,t])=><div key={String(l)} className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><p className="text-xs font-bold text-slate-500">{l}</p><p className="mt-2 text-xl font-black">{t==="money"?moneyShort.format(Number(v)):Number(v).toFixed(2)}</p></div>)}</section>
  <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">Penjualan Staff</h2><p className="text-sm text-slate-500">Mengikuti schedule/in-charge dan calculation Daily Sales existing.</p></div><select value={sort} onChange={e=>setSort(e.target.value as SortKey)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-950"><option value="schedule">Schedule Order</option><option value="amount">Amount Tertinggi</option><option value="vas">VAS Tertinggi</option><option value="acc">ACC Tertinggi</option><option value="upt">UPT Tertinggi</option><option value="atv">ATV Tertinggi</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr><th className="p-3">Staff</th><th className="p-3">Amount</th><th className="p-3">VAS</th><th className="p-3">ACC</th><th className="p-3">UPT</th><th className="p-3">ATV</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.staffId} className="border-t"><td className="p-3"><b>{r.staffName}</b><div className="text-xs text-slate-400">{r.staffId}</div></td><td className="p-3 font-black">{moneyShort.format(r.amount)}</td><td className="p-3">{moneyShort.format(r.vas)}</td><td className="p-3">{moneyShort.format(r.acc)}</td><td className="p-3">{r.upt.toFixed(2)}</td><td className="p-3">{moneyShort.format(r.atv)}</td><td className="p-3 text-xs font-bold">{r.status||"—"}</td></tr>)}</tbody></table></div></section>
  {modal&&<Modal onClose={()=>!busy&&setModal(false)}><div className="space-y-4 p-4"><label className="block"><span className="mb-1 block text-xs font-black uppercase text-slate-400">Tanggal Data</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><label className="block"><span className="mb-1 block text-xs font-black uppercase text-slate-400">File Sales</span><input ref={fileRef} type="file" accept=".xls,.xlsx" className="w-full rounded-xl border p-2"/></label>{progress&&<div className="rounded-xl bg-slate-50 p-3 text-sm font-black dark:bg-slate-900">{progress}</div>}{notice&&<div className="rounded-xl border p-3 text-sm font-bold">{notice}</div>}<div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>setModal(false)} className="rounded-xl border px-4 py-3 font-black disabled:opacity-50">Batal</button><button disabled={busy} onClick={upload} className="rounded-xl bg-blue-600 px-4 py-3 font-black text-white disabled:opacity-50">{busy?progress||"Memproses...":"Upload & Proses"}</button></div></div></Modal>}
 </div>
}

export default function M238UpdateSales2Jam(){
 const[active,setActive]=useState(false),[host,setHost]=useState<HTMLElement|null>(null);
 useEffect(()=>{const inject=()=>{const nav=document.querySelector("aside nav");if(!nav||nav.querySelector("[data-m238-sales2h-menu]"))return;const daily=Array.from(nav.querySelectorAll<HTMLButtonElement>("button")).find(b=>label(b)==="Daily Sales");if(!daily)return;const b=document.createElement("button");b.type="button";b.dataset.m238Sales2hMenu="1";b.dataset.menuLabel="Update Sales 2 Jam";b.className=daily.className;b.innerHTML='<span aria-hidden="true">↻</span><span>Update Sales 2 Jam</span>';daily.insertAdjacentElement("afterend",b)};inject();const nav=document.querySelector("aside nav");if(!nav)return;const mo=new MutationObserver(()=>requestAnimationFrame(inject));mo.observe(nav,{childList:true,subtree:true});return()=>mo.disconnect()},[]);
 useEffect(()=>{const click=(event:MouseEvent)=>{const b=(event.target as Element|null)?.closest("button") as HTMLButtonElement|null;if(!b||!b.closest("aside nav"))return;if(label(b)==="Update Sales 2 Jam"){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();for(const x of Array.from(document.querySelectorAll<HTMLButtonElement>("aside nav button")))if(x!==b)x.removeAttribute("aria-current");b.setAttribute("aria-current","page");const crumb=document.querySelector("main.min-w-0 header b");if(crumb)crumb.textContent="Update Sales 2 Jam";setActive(true);return}if(active){document.querySelector<HTMLButtonElement>("[data-m238-sales2h-menu]")?.removeAttribute("aria-current");setActive(false)}};document.addEventListener("click",click,true);return()=>document.removeEventListener("click",click,true)},[active]);
 useEffect(()=>{const root=document.querySelector("main.min-w-0 > div.px-4.pt-6") as HTMLElement|null;if(!root)return;let h=root.querySelector("[data-sales2h-view-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.sales2hViewHost="1";h.className="min-w-0 w-full";root.appendChild(h)}setHost(h)},[]);
 useEffect(()=>{document.body.classList.toggle("m238-sales2h-active",active);return()=>document.body.classList.remove("m238-sales2h-active")},[active]);
 return <>{host&&createPortal(<div style={{display:active?"block":"none"}} className="w-full min-w-0"><UpdateSalesView/></div>,host)}<style jsx global>{`body.m238-sales2h-active main.min-w-0>div.px-4.pt-6>*:not([data-sales2h-view-host]){display:none!important}body.m238-sales2h-active [data-sales2h-view-host]{display:block!important}`}</style></>
}
