"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {RefreshCw,Trash2,Upload,X} from "lucide-react";

const moneyShort=new Intl.NumberFormat("id-ID",{notation:"compact",compactDisplay:"short",style:"currency",currency:"IDR",maximumFractionDigits:1});
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateLabel=(v:string)=>new Intl.DateTimeFormat("id-ID",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00`));
function label(button:HTMLButtonElement){return(button.dataset.menuLabel||button.querySelector("span:last-child")?.textContent||button.textContent||"").trim()}

type Staff={scheduleOrder:number;staffId:string;staffName:string;amount:number;vas:number;acc:number;upt:number;atv:number;transaction:number;qty:number};
type Slot={slot:string;status:string;totalSales:number|null;transaction:number|null;updateTime:string|null};
type Payload={date:string;updatedAt:string|null;lastUpdate:string|null;status:string;updateSlots:Slot[];staffSales:Staff[];summary:{totalSales:number;totalVas:number;totalAcc:number;totalTransactions:number};clearedAt?:string|null;error?:string};
type Dialog="upload"|"clear"|null;

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/45 sm:items-center sm:p-4" role="dialog" aria-modal="true"><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl dark:bg-slate-950 sm:max-w-lg sm:rounded-3xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white/95 p-4 dark:bg-slate-950/95"><h3 className="text-lg font-black">{title}</h3><button onClick={onClose} className="rounded-xl border p-2" aria-label="Tutup"><X className="size-4"/></button></div>{children}</div></div>}

function UpdateSalesView(){
 const[date,setDate]=useState(today()),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[dialog,setDialog]=useState<Dialog>(null),[busy,setBusy]=useState(false),[progress,setProgress]=useState(""),[notice,setNotice]=useState(""),[pin,setPin]=useState(""),fileRef=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/update-sales-2jam?date=${date}&t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Data sales belum berhasil dimuat.");setData(j)}catch(e){setError(e instanceof Error?e.message:"Data sales belum berhasil dimuat.")}finally{setLoading(false)}},[date]);
 useEffect(()=>{void load()},[load]);
 const open=(d:Dialog)=>{setDialog(d);setNotice("");setProgress("")};
 const close=()=>{if(!busy)setDialog(null)};
 const upload=async()=>{const file=fileRef.current?.files?.[0];if(!file)return setNotice("Pilih file XLS/XLSX terlebih dahulu.");setBusy(true);setNotice("");const steps=["Uploading...","Validating...","Processing...","Generating Summary...","Saving...","Updating Display..."];let idx=0;setProgress(steps[0]);const timer=window.setInterval(()=>{idx=Math.min(idx+1,steps.length-1);setProgress(steps[idx])},650);try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload-spw",{method:"POST",body:fd,cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload gagal");if(!j.fast?.ok)throw new Error(j.fast?.error||"Upload berhasil, tetapi Fast Daily Sales gagal diproses.");if(j.dataDate)setDate(j.dataDate);if(fileRef.current)fileRef.current.value="";setProgress("Ready");setNotice(`${j.processedRows??j.rows} row diproses • ${j.duplicateSkipped??0} duplicate skipped • ${((Number(j.processingMs)||0)/1000).toFixed(1)} dtk`);await new Promise(r=>setTimeout(r,150));await load()}catch(e){setProgress("");setNotice(e instanceof Error?e.message:"Upload gagal diproses.")}finally{window.clearInterval(timer);setBusy(false)}};
 const clear=async()=>{if(!pin)return setNotice("Masukkan Passcode Admin terlebih dahulu.");setBusy(true);setNotice("");try{const r=await fetch("/api/data-tools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear-spw",passcode:pin,date}),cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Clear Data gagal");setNotice(j.message||"Data upload sementara berhasil dikosongkan.");setPin("");await load()}catch(e){setNotice(e instanceof Error?e.message:"Clear Data gagal")}finally{setBusy(false)}};
 const statusTone=data?.status==="Data Terbaru"?"border-emerald-200 bg-emerald-50 text-emerald-700":data?.status==="Data Terlambat"?"border-amber-200 bg-amber-50 text-amber-700":"border-slate-200 bg-slate-50 text-slate-600";
 return <div className="space-y-4">
  <section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">M238 – Daily Sales</p><h1 className="mt-1 text-2xl font-black">Update Penjualan 2 Jam</h1><div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><label className="flex items-center gap-2 rounded-xl border px-3 py-2">Tanggal Aktif <input type="date" value={date} onChange={e=>setDate(e.target.value)} className="bg-transparent font-black outline-none"/></label><span className="rounded-xl border px-3 py-2">{dateLabel(date)}</span><span className="rounded-xl border px-3 py-2">Last Update: <b>{data?.lastUpdate?`${data.lastUpdate} WIB`:"—"}</b></span><span className={`rounded-xl border px-3 py-2 font-black ${statusTone}`}>{data?.status||"Belum Ada Data"}</span></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>open("upload")} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 font-black text-white"><Upload className="size-4"/>Upload Data Sales</button><button onClick={()=>open("clear")} className="flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2.5 font-black text-rose-600"><Trash2 className="size-4"/>Clear Data</button><button onClick={()=>void load()} disabled={loading} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 font-black disabled:opacity-50"><RefreshCw className={`size-4 ${loading?"animate-spin":""}`}/>Refresh</button></div></div></section>
  {error?<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700"><b>{error}</b><button onClick={()=>void load()} className="ml-3 rounded-lg border px-3 py-1.5 font-bold">Coba Lagi</button></div>:null}
  <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-4 py-3"><h2 className="font-black">Status Update Per 2 Jam</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr><th className="p-3">Jam</th><th className="p-3">Status</th><th className="p-3">Total Sales</th><th className="p-3">Total Transaksi</th><th className="p-3">Upload Terakhir</th></tr></thead><tbody>{(data?.updateSlots||[]).map(s=><tr key={s.slot} className="border-t"><td className="p-3 font-black">{s.slot}</td><td className="p-3"><span className={`rounded-lg px-2 py-1 text-xs font-black ${s.status==="Updated"?"bg-emerald-50 text-emerald-700":s.status==="Menunggu Update"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{s.status}</span></td><td className="p-3 font-bold">{s.totalSales==null?"—":moneyShort.format(s.totalSales)}</td><td className="p-3">{s.transaction==null?"—":s.transaction}</td><td className="p-3">{s.updateTime?`${s.updateTime} WIB`:"—"}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-4 py-3"><h2 className="font-black">Penjualan Staff</h2><p className="text-sm text-slate-500">Semua staff aktif tetap tampil. Staff tanpa transaksi bernilai 0.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50 text-left dark:bg-slate-900"><tr><th className="p-3">Nama Staff</th><th className="p-3">Sales / Amount</th><th className="p-3">VAS</th><th className="p-3">ACC</th><th className="p-3">UPT</th><th className="p-3">ATV</th></tr></thead><tbody>{(data?.staffSales||[]).map(r=><tr key={r.staffId||r.staffName} className="border-t"><td className="p-3 font-black">{r.staffName}</td><td className="p-3 font-black">{moneyShort.format(r.amount)}</td><td className="p-3">{moneyShort.format(r.vas)}</td><td className="p-3">{moneyShort.format(r.acc)}</td><td className="p-3">{r.upt.toFixed(2)}</td><td className="p-3">{moneyShort.format(r.atv)}</td></tr>)}</tbody></table></div></section>
  {dialog==="upload"&&<Modal title="Upload Data Sales" onClose={close}><div className="space-y-4 p-4"><p className="text-sm text-slate-500">File dianggap snapshot kumulatif untuk data aktif. Sistem memakai replace/upsert, bukan append raw setiap 2 jam.</p><input ref={fileRef} type="file" accept=".xls,.xlsx" className="w-full rounded-xl border p-2"/>{progress&&<div className="rounded-xl bg-slate-50 p-3 text-sm font-black dark:bg-slate-900">{progress}</div>}{notice&&<div className="rounded-xl border p-3 text-sm font-bold">{notice}</div>}<div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={close} className="rounded-xl border px-4 py-3 font-black disabled:opacity-50">Batal</button><button disabled={busy} onClick={upload} className="rounded-xl bg-blue-600 px-4 py-3 font-black text-white disabled:opacity-50">{busy?progress||"Memproses...":"Upload & Proses"}</button></div></div></Modal>}
  {dialog==="clear"&&<Modal title="Clear Data" onClose={close}><div className="space-y-4 p-4"><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800">Yakin ingin menghapus data upload sementara? Hanya SPW aktif, normalized staging, dan cache Daily Sales aktif yang dikosongkan. Historical summary, hasil Cut Off, No Exchange, Config, Schedule, SOH, dan data permanen tetap aman.</div><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Passcode Admin" className="h-11 w-full rounded-xl border px-3"/>{notice&&<div className="rounded-xl border p-3 text-sm font-bold">{notice}</div>}<div className="grid grid-cols-2 gap-2"><button disabled={busy} onClick={close} className="rounded-xl border px-4 py-3 font-black disabled:opacity-50">Batal</button><button disabled={busy||!pin} onClick={clear} className="rounded-xl bg-rose-600 px-4 py-3 font-black text-white disabled:opacity-50">{busy?"Mengosongkan...":"Ya, Clear"}</button></div></div></Modal>}
 </div>
}

export default function M238UpdateSales2Jam(){
 const[active,setActive]=useState(false),[host,setHost]=useState<HTMLElement|null>(null);
 useEffect(()=>{const inject=()=>{const nav=document.querySelector("aside nav");if(!nav||nav.querySelector("[data-m238-sales2h-menu]"))return;const daily=Array.from(nav.querySelectorAll<HTMLButtonElement>("button")).find(b=>label(b)==="Daily Sales");if(!daily)return;const b=document.createElement("button");b.type="button";b.dataset.m238Sales2hMenu="1";b.dataset.menuLabel="Update Sales 2 Jam";b.className=daily.className;b.innerHTML='<span aria-hidden="true">↻</span><span>Update Sales 2 Jam</span>';daily.insertAdjacentElement("afterend",b)};inject();const nav=document.querySelector("aside nav");if(!nav)return;const mo=new MutationObserver(()=>requestAnimationFrame(inject));mo.observe(nav,{childList:true,subtree:true});return()=>mo.disconnect()},[]);
 useEffect(()=>{const click=(event:MouseEvent)=>{const b=(event.target as Element|null)?.closest("button") as HTMLButtonElement|null;if(!b||!b.closest("aside nav"))return;if(label(b)==="Update Sales 2 Jam"){event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();for(const x of Array.from(document.querySelectorAll<HTMLButtonElement>("aside nav button")))if(x!==b)x.removeAttribute("aria-current");b.setAttribute("aria-current","page");const crumb=document.querySelector("main.min-w-0 header b");if(crumb)crumb.textContent="Update Sales 2 Jam";setActive(true);return}if(active){document.querySelector<HTMLButtonElement>("[data-m238-sales2h-menu]")?.removeAttribute("aria-current");setActive(false)}};document.addEventListener("click",click,true);return()=>document.removeEventListener("click",click,true)},[active]);
 useEffect(()=>{const root=document.querySelector("main.min-w-0 > div.px-4.pt-6") as HTMLElement|null;if(!root)return;let h=root.querySelector("[data-sales2h-view-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.sales2hViewHost="1";h.className="min-w-0 w-full";root.appendChild(h)}setHost(h)},[]);
 useEffect(()=>{document.body.classList.toggle("m238-sales2h-active",active);return()=>document.body.classList.remove("m238-sales2h-active")},[active]);
 return <>{host&&createPortal(<div style={{display:active?"block":"none"}} className="w-full min-w-0"><UpdateSalesView/></div>,host)}<style jsx global>{`body.m238-sales2h-active main.min-w-0>div.px-4.pt-6>*:not([data-sales2h-view-host]){display:none!important}body.m238-sales2h-active [data-sales2h-view-host]{display:block!important}`}</style></>
}
