"use client";
import {useEffect,useState} from "react";
import {createPortal} from "react-dom";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}),pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
type Data={target:{amount:number;device:number;accessories:number;vas:number};summary:{amount:number;device:number;accessories:number;vas:number;estimate:number;upt:number;invoices:number};daily:Array<{date:string;amount:number;device:number;accessories:number;vas:number}>};
function estimate(actual:number,lastDay:number,dim:number){return lastDay?actual/lastDay*dim:0}
function Overview({period}:{period:string}){const[data,setData]=useState<Data|null>(null),[traffic,setTraffic]=useState(0);useEffect(()=>{const[y,m]=period.split("-").map(Number),end=`${period}-${String(new Date(y,m,0).getDate()).padStart(2,"0")}`;Promise.all([fetch(`/api/data?period=${period}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/traffic?from=${period}-01&to=${end}`,{cache:"no-store"}).then(r=>r.json())]).then(([d,t])=>{setData(d);setTraffic(Number(t?.total||0))}).catch(()=>{})},[period]);if(!data)return <div className="m238-soft-card p-5 text-sm text-slate-500">Memuat overview…</div>;const days=data.daily||[],last=Math.max(1,...days.map(x=>Number(x.date.slice(8,10))||1)),[y,m]=period.split("-").map(Number),dim=new Date(y,m,0).getDate(),cvr=traffic?data.summary.invoices/traffic*100:0;const ratio=(a:number,t:number)=>t?a/t*100:0,point=(a:number,t:number,max:number)=>Math.min(t?a/t*max:0,max);const cards=[
 ["Target vs Achievement",`${money.format(data.summary.amount)} / ${money.format(data.target.amount)}`,`${pct(ratio(data.summary.amount,data.target.amount))}`],
 ["Device vs Achievement",`${money.format(data.summary.device)} / ${money.format(data.target.device)}`,`${pct(ratio(data.summary.device,data.target.device))} • Point ${point(data.summary.device,data.target.device,60).toFixed(1)}/60`],
 ["VAS vs Achievement",`${money.format(data.summary.vas)} / ${money.format(data.target.vas)}`,`${pct(ratio(data.summary.vas,data.target.vas))} • Point ${point(data.summary.vas,data.target.vas,10).toFixed(1)}/10`],
 ["ACC vs Achievement",`${money.format(data.summary.accessories)} / ${money.format(data.target.accessories)}`,`${pct(ratio(data.summary.accessories,data.target.accessories))} • Point ${point(data.summary.accessories,data.target.accessories,30).toFixed(1)}/30`],
 ["Estimasi End Month",money.format(data.summary.estimate||estimate(data.summary.amount,last,dim)),`Proyeksi ${period}`],
 ["Estimasi Device",money.format(estimate(data.summary.device,last,dim)),`Berdasarkan ${last} hari data`],
 ["Estimasi VAS",money.format(estimate(data.summary.vas,last,dim)),`Berdasarkan ${last} hari data`],
 ["Estimasi ACC",money.format(estimate(data.summary.accessories,last,dim)),`Berdasarkan ${last} hari data`],
 ["UPT / CVR",`${Number(data.summary.upt||0).toFixed(1)} / ${pct(cvr)}`,`UPT / CVR • Traffic ${new Intl.NumberFormat("id-ID").format(traffic)}`],
 ];return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([a,b,c])=><article key={a} className="m238-soft-card p-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-slate-500 dark:text-slate-400">{a}</p><p className="mt-2 text-lg font-black text-slate-900 dark:text-slate-100">{b}</p><p className="mt-1 text-xs font-semibold text-slate-500 dark:text-slate-400">{c}</p></article>)}</div>}
function activePeriod(){for(const s of Array.from(document.querySelectorAll<HTMLSelectElement>("select"))){if(/^20\d{2}-\d{2}$/.test(s.value))return s.value}return today().slice(0,7)}
function textFix(root:ParentNode){for(const el of Array.from(root.querySelectorAll<HTMLElement>("th,h1,h2,h3,h4,p,span,b,label"))){if(el.children.length)continue;const t=el.textContent||"";let next=t.replace(/\bWatch SE\b/g,"Apple Watch SE").replace(/\bWatch \(Device\)/g,"Apple Watch (Device)");if(t.trim()==="Watch")next=t.replace("Watch","Apple Watch");if(next!==t)el.textContent=next}}
export default function M238RevisionSep8(){const[period,setPeriod]=useState(activePeriod()),[host,setHost]=useState<HTMLElement|null>(null);useEffect(()=>{let lock=false;const apply=()=>{if(lock)return;lock=true;requestAnimationFrame(()=>{lock=false;textFix(document);for(const input of Array.from(document.querySelectorAll<HTMLInputElement>('input[type="date"]'))){input.removeAttribute("min");input.removeAttribute("max");if(!input.value){input.value=today();input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}))}}
 const p=activePeriod();if(p!==period)setPeriod(p);const h=Array.from(document.querySelectorAll("h2,h3")).find(x=>(x.textContent||"").includes("M238 Sales Overview")) as HTMLElement|undefined;if(h){const sec=(h.closest("section")||h.parentElement?.parentElement) as HTMLElement|null;if(sec){const old=sec.querySelector("[data-m238-overview-business]") as HTMLElement|null;if(old)old.style.display="none";let x=sec.querySelector("[data-m238-overview-v2]") as HTMLElement|null;if(!x){x=document.createElement("div");x.dataset.m238OverviewV2="1";x.className="mt-4";sec.appendChild(x)}setHost(x)}}
 const detail=Array.from(document.querySelectorAll("h3")).find(x=>(x.textContent||"").trim()==="Detail Penjualan") as HTMLElement|undefined;const rev=Array.from(document.querySelectorAll("h2,h3")).find(x=>(x.textContent||"").trim()==="Revenue Analytics") as HTMLElement|undefined;if(detail&&rev){const d=(detail.closest("section")||detail.parentElement) as HTMLElement|null,r=(rev.closest("section")||rev.parentElement?.parentElement) as HTMLElement|null;if(d&&r&&!r.contains(d)){d.classList.remove("mt-5");d.style.marginTop="12px";r.appendChild(d)}}
 })};apply();const mo=new MutationObserver(apply);mo.observe(document.body,{childList:true,subtree:true});const change=()=>apply();document.addEventListener("change",change,true);const click=(e:MouseEvent)=>{const b=(e.target as Element|null)?.closest("button");if(!b)return;const t=(b.textContent||"").trim();const map:Record<string,string>={Classic:"classic",Natural:"natural",Worklife:"worklife",Happiness:"happiness"};if(map[t]){document.body.dataset.m238Theme=map[t];localStorage.setItem("m238-visual-theme",map[t])}};document.addEventListener("click",click,true);document.body.dataset.m238Theme=localStorage.getItem("m238-visual-theme")||"classic";return()=>{mo.disconnect();document.removeEventListener("change",change,true);document.removeEventListener("click",click,true)}},[period]);return <>{host&&createPortal(<Overview period={period}/>,host)}<style jsx global>{`
 body[data-m238-theme="natural"]{--m238-accent:#4f8f78;--m238-tint:rgba(79,143,120,.10)}body[data-m238-theme="worklife"]{--m238-accent:#55708f;--m238-tint:rgba(85,112,143,.11)}body[data-m238-theme="happiness"]{--m238-accent:#9b6b79;--m238-tint:rgba(155,107,121,.10)}body[data-m238-theme="classic"]{--m238-accent:#4d7ea8;--m238-tint:rgba(77,126,168,.10)}
 body.m238-apple-ui .m238-sidebar button[aria-current="page"]{background:var(--m238-tint)!important;color:var(--m238-accent)!important}body.m238-apple-ui .m238-main a,body.m238-apple-ui .m238-main [class*="text-blue-600"]{color:var(--m238-accent)!important}
 .dark body.m238-apple-ui .m238-main{color:#e9eaec!important}.dark body.m238-apple-ui .m238-main .text-slate-400{color:#aeb3b9!important}.dark body.m238-apple-ui .m238-main .text-slate-500{color:#b7bcc2!important}.dark body.m238-apple-ui .m238-main .text-slate-600,.dark body.m238-apple-ui .m238-main .text-slate-700{color:#d1d5d9!important}.dark body.m238-apple-ui .m238-main input,.dark body.m238-apple-ui .m238-main select,.dark body.m238-apple-ui .m238-main textarea{color:#f3f4f6!important;background:#25282c!important;border-color:#464b52!important}.dark body.m238-apple-ui .m238-main table{background:#1e2125!important}.dark body.m238-apple-ui .m238-main thead{background:#262a2f!important}.dark body.m238-apple-ui .m238-main th{color:#c7cbd0!important}
 `}</style></>}
