"use client";
import {useEffect,useMemo,useState} from "react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}),num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const months=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
type QtyValue={name:string;qty:number;value:number};
type Tot={amount:number;device:number;accessories:number;vas:number;qty:number;invoices:number;upt:number;staff:Array<{name:string;value:number}>;lob:QtyValue[];vasProviders:QtyValue[]};
type Metric={total:number;device:number;accessories:number;vas:number};
type Payload={period:string;asOf:string;summary:Tot;estimate:{amount:number;device:number;accessories:number;vas:number};compare:{cutoffDay:number;current:Metric;mtm:Metric&{period:string};lfl:Metric&{period:string}}};
type Core={target:{amount:number;device:number;accessories:number;vas:number}};
function Card({title,actual,target,estimate,point}:{title:string;actual:number;target:number;estimate:number;point?:string}){const a=target?actual/target*100:0;return <div className="m238-soft-card p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-500 dark:text-slate-400">{title}</p><p className="mt-2 text-xl font-black">{money.format(actual)}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Target {money.format(target)} • {pct(a)}{point?` • ${point}`:""}</p><p className="mt-2 text-xs font-semibold text-slate-600 dark:text-slate-300">Estimasi {money.format(estimate)}</p></div>}
function growth(a:number,b:number){return b?(a-b)/b*100:0}
export default function MadingPage(){const now=today(),[year,setYear]=useState(now.slice(0,4)),[month,setMonth]=useState(now.slice(5,7)),[data,setData]=useState<Payload|null>(null),[core,setCore]=useState<Core|null>(null),[loading,setLoading]=useState(true);const period=`${year}-${month}`;
 useEffect(()=>{setLoading(true);Promise.all([fetch(`/api/mading?period=${period}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/data?period=${period}`,{cache:"no-store"}).then(r=>r.json())]).then(([m,c])=>{setData(m);setCore(c)}).finally(()=>setLoading(false))},[period]);
 const t=core?.target||{amount:0,device:0,accessories:0,vas:0},point=useMemo(()=>({device:Math.min(t.device?((data?.summary.device||0)/t.device*60):0,60),acc:Math.min(t.accessories?((data?.summary.accessories||0)/t.accessories*30):0,30),vas:Math.min(t.vas?((data?.summary.vas||0)/t.vas*10):0,10)}),[data,t]);
 if(loading||!data)return <div className="m238-soft-card p-8 text-center text-slate-500">Memuat Mading…</div>;
 const metrics:[keyof Metric,string][]=[["total","Total"],["device","Device"],["accessories","ACC"],["vas","VAS"]];
 return <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Mading</p><h2 className="mt-1 text-3xl font-black">Mading Performance</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Ringkasan yang mengikuti struktur sheet Mading.</p></div>
 <section className="m238-soft-card p-4"><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-xs font-bold text-slate-500">Tahun</span><select value={year} onChange={e=>setYear(e.target.value)} className="h-11 w-full rounded-xl border px-3"><option>2025</option><option>2026</option></select></label><label><span className="mb-1 block text-xs font-bold text-slate-500">Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)} className="h-11 w-full rounded-xl border px-3">{months.map((x,i)=><option key={x} value={String(i+1).padStart(2,"0")}>{x}</option>)}</select></label></div><p className="mt-3 text-xs text-slate-500">Data sampai {data.asOf}</p></section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="Amount" actual={data.summary.amount} target={t.amount} estimate={data.estimate.amount}/><Card title="Device" actual={data.summary.device} target={t.device} estimate={data.estimate.device} point={`Point ${point.device.toFixed(1)}/60`}/><Card title="ACC" actual={data.summary.accessories} target={t.accessories} estimate={data.estimate.accessories} point={`Point ${point.acc.toFixed(1)}/30`}/><Card title="VAS" actual={data.summary.vas} target={t.vas} estimate={data.estimate.vas} point={`Point ${point.vas.toFixed(1)}/10`}/></section>
 <section className="grid gap-5 xl:grid-cols-2"><div className="m238-soft-card overflow-hidden"><div className="border-b px-5 py-4"><h3 className="font-black">Pencapaian Staff • Value</h3></div><div className="max-h-[480px] overflow-auto"><table className="w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Staff</th><th className="px-4 py-3 text-right">Value</th></tr></thead><tbody>{data.summary.staff.map(r=><tr key={r.name} className="border-t"><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3 text-right font-bold">{money.format(r.value)}</td></tr>)}</tbody></table></div></div><div className="m238-soft-card overflow-hidden"><div className="border-b px-5 py-4"><h3 className="font-black">Pencapaian LOB</h3></div><table className="w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">LOB</th><th className="px-4 py-3 text-right">Qty</th><th className="px-4 py-3 text-right">Value</th></tr></thead><tbody>{data.summary.lob.map(r=><tr key={r.name} className="border-t"><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3 text-right font-bold">{num.format(r.qty)}</td><td className="px-4 py-3 text-right">{money.format(r.value)}</td></tr>)}</tbody></table></div></section>
 <section className="grid gap-5 xl:grid-cols-2"><div className="m238-soft-card overflow-hidden"><div className="border-b px-5 py-4"><h3 className="font-black">VAS</h3></div><table className="w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Provider</th><th className="px-4 py-3 text-right">Qty</th><th className="px-4 py-3 text-right">Value</th></tr></thead><tbody>{data.summary.vasProviders.map(r=><tr key={r.name} className="border-t"><td className="px-4 py-3 font-semibold">{r.name}</td><td className="px-4 py-3 text-right font-bold">{num.format(r.qty)}</td><td className="px-4 py-3 text-right">{money.format(r.value)}</td></tr>)}</tbody></table></div><div className="m238-soft-card overflow-hidden"><div className="border-b px-5 py-4"><h3 className="font-black">LFL & MTM • H-1</h3><p className="mt-1 text-xs text-slate-500">Pembanding sampai tanggal {data.compare.cutoffDay}.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th className="px-3 py-3 text-left">Metric</th><th className="px-3 py-3 text-right">Current H-1</th><th className="px-3 py-3 text-right">MTM</th><th className="px-3 py-3 text-right">Growth</th><th className="px-3 py-3 text-right">LFL</th><th className="px-3 py-3 text-right">Growth</th></tr></thead><tbody>{metrics.map(([key,label])=>{const c=data.compare.current[key]||0,mt=data.compare.mtm[key]||0,lf=data.compare.lfl[key]||0;return <tr key={key} className="border-t"><td className="px-3 py-3 font-bold">{label}</td><td className="px-3 py-3 text-right">{money.format(c)}</td><td className="px-3 py-3 text-right">{money.format(mt)}</td><td className={`px-3 py-3 text-right font-bold ${growth(c,mt)>=0?"text-emerald-600":"text-rose-600"}`}>{pct(growth(c,mt))}</td><td className="px-3 py-3 text-right">{money.format(lf)}</td><td className={`px-3 py-3 text-right font-bold ${growth(c,lf)>=0?"text-emerald-600":"text-rose-600"}`}>{pct(growth(c,lf))}</td></tr>})}</tbody></table></div></div></section>
 </div>}
