"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

const focuses=["iPhone 15","MacBook Neo","iPad 11","Watch SE","AirPods"] as const;
type Scope="monthly"|"weekly";
type Staff={id:string;name:string;position:string;share:number};
type TargetMap=Record<string,number>;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
function currentWeek(){const d=new Date(`${today()}T00:00:00+07:00`),th=new Date(d);th.setDate(d.getDate()+4-(d.getDay()||7));const y=th.getFullYear(),jan1=new Date(y,0,1),w=Math.ceil((((th.getTime()-jan1.getTime())/86400000)+1)/7);return `${y}-W${String(w).padStart(2,"0")}`}
function defaultPeriod(scope:Scope){return scope==="monthly"?today().slice(0,7):currentWeek()}
export default function ManualTargetFocus(){
 const[hosts,setHosts]=useState<HTMLElement[]>([]),[scope,setScope]=useState<Scope>("monthly"),[period,setPeriod]=useState(defaultPeriod("monthly")),[targets,setTargets]=useState<TargetMap>({}),[staff,setStaff]=useState<Staff[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async(sc=scope,pe=period)=>{try{const r=await fetch(`/api/manual-target?scope=${sc}&period=${encodeURIComponent(pe)}`,{cache:"no-store"}),j=await r.json();if(!r.ok)return;const next:TargetMap={};for(const f of focuses)next[f]=Number(j.targets?.[f]?.target||0);setTargets(next);setStaff(j.staff||[])}catch{}};
 useEffect(()=>{void load()},[scope,period]);
 useEffect(()=>{let raf=0;const sync=()=>{raf=0;const found:Array<HTMLElement>=[];for(const h of Array.from(document.querySelectorAll("h2,h3"))){const t=(h.textContent||"").toLowerCase();if(!t.includes("product focus")&&!t.includes("target focus"))continue;const sec=h.closest("section") as HTMLElement|null;if(!sec)continue;let host=sec.querySelector(":scope > [data-m238-manual-target]") as HTMLElement|null;if(!host){host=document.createElement("div");host.dataset.m238ManualTarget="1";host.className="mt-4";sec.appendChild(host)}found.push(host)}setHosts(prev=>prev.length===found.length&&prev.every((x,i)=>x===found[i])?prev:found)};const schedule=()=>{if(!raf)raf=requestAnimationFrame(sync)};sync();const mo=new MutationObserver(schedule);mo.observe(document.body,{childList:true,subtree:true});return()=>{if(raf)cancelAnimationFrame(raf);mo.disconnect()}},[]);
 const save=async()=>{setBusy(true);setMessage("");try{const r=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope,period,targets}),cache:"no-store"}),j=await r.json();if(!r.ok)setMessage(j.error||"Gagal menyimpan target");else{setStaff(j.staff||staff);setMessage("Target tersimpan di MASTER DATA M238 dan otomatis dibagi sesuai %T staff.")}}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setBusy(false)}};
 const rows=useMemo(()=>staff.map(s=>({ ...s,values:Object.fromEntries(focuses.map(f=>[f,Math.round((targets[f]||0)*s.share)]))})),[staff,targets]);
 const panel=<section className="m238-soft-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-black">Target Focus Manual</h3><p className="mt-1 text-xs text-slate-500">Isi target bulanan atau weekly. Target staff dihitung dari %T pada Config M238; SPV tidak masuk pembagian.</p></div><div className="flex flex-wrap gap-2"><select value={scope} onChange={e=>{const v=e.target.value as Scope;setScope(v);setPeriod(defaultPeriod(v))}} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"><option value="monthly">Bulanan</option><option value="weekly">Weekly</option></select>{scope==="monthly"?<input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"/>:<input type="week" value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"/>}<button disabled={busy} onClick={save} className="h-10 rounded-xl bg-blue-600 px-4 text-sm font-black text-white disabled:opacity-50">{busy?"Menyimpan...":"Simpan Target"}</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{focuses.map(f=><label key={f} className="rounded-xl border p-3"><span className="block text-xs font-black text-slate-500">{f}</span><input inputMode="numeric" value={targets[f]||""} onChange={e=>setTargets(v=>({...v,[f]:Math.max(0,Number(e.target.value.replace(/[^0-9]/g,""))||0)}))} placeholder="0" className="mt-2 h-10 w-full rounded-lg border px-3 text-right font-black dark:bg-slate-900"/><span className="mt-1 block text-[10px] text-slate-400">unit / periode</span></label>)}</div>{message&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600 dark:bg-slate-900 dark:text-slate-300">{message}</div>}{rows.length>0&&<details className="mt-4"><summary className="cursor-pointer text-sm font-black">Lihat pembagian target per staff</summary><div className="mt-3 overflow-x-auto"><table className="min-w-full text-xs"><thead><tr><th className="px-2 py-2 text-left">Staff</th><th className="px-2 py-2 text-right">%T</th>{focuses.map(f=><th key={f} className="px-2 py-2 text-right">{f}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-2 py-2 font-bold">{r.name}</td><td className="px-2 py-2 text-right">{Math.round(r.share*100)}%</td>{focuses.map(f=><td key={f} className="px-2 py-2 text-right font-semibold">{Number(r.values[f]||0).toLocaleString("id-ID")}</td>)}</tr>)}</tbody></table></div></details>}</section>;
 return <>{hosts.map((h,i)=>createPortal(<div key={i}>{panel}</div>,h))}</>;
}
