"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Scope="monthly"|"weekly";
type Group="lob-focus"|"product-focus"|"vas-focus";
type Staff={id:string;name:string;position:string;share:number};
type TargetMap=Record<string,number>;
const groupItems:Record<Group,string[]>={
 "lob-focus":["iPhone","MacBook","iPad","Watch","AirPods"],
 "product-focus":["Hastag","Dino","Iga","IBacks","Handal","Omega","Torras"],
 "vas-focus":["Qoala","Telkomsel","XL","Indosat"],
};
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
function currentWeek(){const d=new Date(`${today()}T00:00:00+07:00`),th=new Date(d);th.setDate(d.getDate()+4-(d.getDay()||7));const y=th.getFullYear(),jan1=new Date(y,0,1),w=Math.ceil((((th.getTime()-jan1.getTime())/86400000)+1)/7);return `${y}-W${String(w).padStart(2,"0")}`}
function defaultPeriod(scope:Scope){return scope==="monthly"?today().slice(0,7):currentWeek()}
function groupFromTitle(title:string):Group|null{const t=title.toLowerCase();if(t.includes("lob target fokus"))return"lob-focus";if(t.includes("product fokus 3pp"))return"product-focus";if(t.includes("vas fokus"))return"vas-focus";return null}
function groupLabel(group:Group){return group==="lob-focus"?"LOB":group==="product-focus"?"3PP":"VAS"}
export default function ManualTargetFocus(){
 const[host,setHost]=useState<HTMLElement|null>(null),[group,setGroup]=useState<Group|null>(null),[scope,setScope]=useState<Scope>("weekly"),[period,setPeriod]=useState(defaultPeriod("weekly")),[targets,setTargets]=useState<TargetMap>({}),[staff,setStaff]=useState<Staff[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const items=group?groupItems[group]:[];
 useEffect(()=>{const sync=()=>{const root=document.querySelector("[data-inline-native]") as HTMLElement|null;if(!root){setHost(null);setGroup(null);return}const title=(root.querySelector("h1")?.textContent||"").trim(),g=groupFromTitle(title);if(!g){setHost(null);setGroup(null);return}setGroup(g);let h=root.querySelector("[data-m238-manual-target-native]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.m238ManualTargetNative="1";const native=root.querySelector(".m238-native-view")||root;native.insertBefore(h,native.firstChild)}setHost(h)};sync();const mo=new MutationObserver(()=>requestAnimationFrame(sync));mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()},[]);
 useEffect(()=>{if(!group)return;setTargets({});setMessage("");const pe=defaultPeriod(scope);setPeriod(pe)},[group,scope]);
 useEffect(()=>{if(!group||!period)return;let active=true;(async()=>{try{const r=await fetch(`/api/manual-target?scope=${scope}&period=${encodeURIComponent(period)}&group=${group}`,{cache:"no-store"}),j=await r.json();if(!r.ok||!active)return;const next:TargetMap={};for(const f of groupItems[group])next[f]=Number(j.targets?.[f]?.target||0);setTargets(next);setStaff(j.staff||[])}catch{}})();return()=>{active=false}},[group,scope,period]);
 const save=async()=>{if(!group)return;setBusy(true);setMessage("");try{const r=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope,period,group,targets}),cache:"no-store"}),j=await r.json();if(!r.ok)setMessage(j.error||"Gagal menyimpan target");else{setStaff(j.staff||staff);setMessage(`Target ${groupLabel(group)} tersimpan dan otomatis dibagi sesuai %T staff.`)}}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setBusy(false)}};
 const rows=useMemo(()=>staff.map(s=>({...s,values:Object.fromEntries(items.map(f=>[f,Math.round((targets[f]||0)*s.share)]))})),[staff,targets,items]);
 if(!host||!group)return null;
 const panel=<section className="m238-soft-card rounded-2xl border p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-black">Target Manual {groupLabel(group)}</h3><p className="mt-1 text-xs text-slate-500">Isi target pada tab Week atau Bulan. Setelah disimpan, target langsung dibagi ke staff sesuai %T; SPV tidak ikut pembagian.</p></div><div className="flex flex-wrap gap-2"><select value={scope} onChange={e=>setScope(e.target.value as Scope)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"><option value="weekly">Week</option><option value="monthly">Bulan</option></select>{scope==="monthly"?<input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"/>:<input type="week" value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"/>}<button disabled={busy} onClick={save} className="h-10 rounded-xl bg-blue-600 px-4 text-sm font-black text-white disabled:opacity-50">{busy?"Menyimpan...":"Simpan Target"}</button></div></div><div className={`mt-4 grid gap-3 sm:grid-cols-2 ${items.length>5?"xl:grid-cols-4":"xl:grid-cols-5"}`}>{items.map(f=><label key={f} className="rounded-xl border p-3"><span className="block text-xs font-black text-slate-500">{f}</span><input inputMode="numeric" value={targets[f]||""} onChange={e=>setTargets(v=>({...v,[f]:Math.max(0,Number(e.target.value.replace(/[^0-9]/g,""))||0)}))} placeholder="0" className="mt-2 h-10 w-full rounded-lg border px-3 text-right font-black dark:bg-slate-900"/><span className="mt-1 block text-[10px] text-slate-400">target / periode</span></label>)}</div>{message&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-600 dark:bg-slate-900 dark:text-slate-300">{message}</div>}{rows.length>0&&<details className="mt-4"><summary className="cursor-pointer text-sm font-black">Lihat pembagian target per staff</summary><div className="mt-3 overflow-x-auto"><table className="min-w-full text-xs"><thead><tr><th className="px-2 py-2 text-left">Staff</th><th className="px-2 py-2 text-right">%T</th>{items.map(f=><th key={f} className="px-2 py-2 text-right">{f}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-2 py-2 font-bold">{r.name}</td><td className="px-2 py-2 text-right">{Math.round(r.share*100)}%</td>{items.map(f=><td key={f} className="px-2 py-2 text-right font-semibold">{Number(r.values[f]||0).toLocaleString("id-ID")}</td>)}</tr>)}</tbody></table></div></details>}</section>;
 return createPortal(panel,host);
}
