"use client";
import {useEffect,useMemo,useState} from "react";
import OverviewExportActions from "@/components/overview-export-actions";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"▲ ":"▼ "}${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Math.abs(Number.isFinite(v)?v:0))}%`;
const monthName=(i:number)=>new Intl.DateTimeFormat("id-ID",{month:"long"}).format(new Date(`2026-${String(i).padStart(2,"0")}-01T00:00:00`));
const monthShort=(i:number)=>new Intl.DateTimeFormat("id-ID",{month:"short"}).format(new Date(`2026-${String(i).padStart(2,"0")}-01T00:00:00`));
const compactMoney=(v:number)=>{const a=Math.abs(v);if(a>=1e9)return `Rp${(v/1e9).toLocaleString("id-ID",{maximumFractionDigits:1})}M`;if(a>=1e6)return `Rp${(v/1e6).toLocaleString("id-ID",{maximumFractionDigits:1})}jt`;return money.format(v)};

type LobCompare={lob:string;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null};
type Compare={month:number;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null;device2025:number;device2026:number|null;deviceQty2025:number;deviceQty2026:number|null;deviceDiff:number|null;deviceGrowth:number|null;deviceQtyDiff:number|null;deviceQtyGrowth:number|null;lobs:LobCompare[];started:boolean};
type YtdLob={lob:string;amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number|null;qtyDiff:number;qtyGrowth:number|null};
type Payload={period:string;compare:Compare[];ytd:{amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number;qtyDiff:number;qtyGrowth:number;device2025:number;device2026:number;deviceQty2025:number;deviceQty2026:number;deviceDiff:number;deviceGrowth:number;deviceQtyDiff:number;deviceQtyGrowth:number;lobs:YtdLob[];throughMonth:number};error?:string};

const card="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950";
const lobTabs=["All Sales","iPhone","iPad","Mac","Apple Watch","AirPods"] as const;
type LobTab=(typeof lobTabs)[number];
function growthClass(v:number|null|undefined){return (v??0)>=0?"text-emerald-600":"text-rose-500"}

export default function OverviewPage({period}:{period:string;setPeriod:(v:string)=>void}){
 const[mode,setMode]=useState<"ytd"|"compare">("ytd"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");fetch(`/api/overview?period=${encodeURIComponent(period)}&t=${Date.now()}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||"Overview gagal dibaca");if(alive)setData(j)}).catch(e=>alive&&setError(e instanceof Error?e.message:"Overview gagal dibaca")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[period]);
 return <div className="space-y-4 sm:space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
   <div className="flex gap-2 overflow-x-auto pb-1 sm:pb-0"><div className="shrink-0 rounded-xl border bg-white px-3 py-2 text-xs font-bold shadow-sm dark:bg-slate-950 sm:text-sm">📅 Jan – {data?monthShort(data.ytd.throughMonth):"..."}</div><div className="shrink-0 rounded-xl border bg-white px-3 py-2 text-xs font-bold shadow-sm dark:bg-slate-950 sm:text-sm">2026</div></div>
   {data&&!loading&&<div className="shrink-0"><OverviewExportActions data={data}/></div>}
  </div>
  <div className="grid w-full grid-cols-2 rounded-xl border bg-white p-1 shadow-sm dark:bg-slate-950 sm:inline-grid sm:w-auto"><button onClick={()=>setMode("ytd")} className={`rounded-lg px-3 py-2.5 text-xs font-black sm:px-6 sm:text-sm ${mode==="ytd"?"bg-blue-600 text-white":"text-slate-500"}`}>YTD Overview</button><button onClick={()=>setMode("compare")} className={`rounded-lg px-3 py-2.5 text-xs font-black sm:px-6 sm:text-sm ${mode==="compare"?"bg-blue-600 text-white":"text-slate-500"}`}>Compare 2025 vs 2026</button></div>
  {loading&&<div className={`${card} p-5`}>Memuat Overview…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
  {data&&!loading&&(mode==="ytd"?<YtdView data={data}/>:<CompareView data={data}/>)}
 </div>
}

function YearCard({year,data}:{year:2025|2026;data:Payload}){
 const is2026=year===2026,qty=is2026?data.ytd.qty2026:data.ytd.qty2025,value=is2026?data.ytd.amount2026:data.ytd.amount2025;
 return <div className={`min-w-0 overflow-hidden rounded-xl border sm:rounded-2xl ${is2026?"border-emerald-100":"border-blue-100"}`}>
  <div className={`px-2.5 py-2 text-base font-black sm:px-4 sm:py-3 sm:text-xl ${is2026?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{year}</div>
  <div className="p-2.5 sm:p-4">
   <div className="grid gap-2 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="text-[10px] font-bold uppercase text-slate-400 sm:text-xs">All Sales</p><div className="mt-1 grid grid-cols-2 gap-2 sm:gap-5"><div><span className="text-[10px] text-slate-400 sm:text-xs">Qty</span><p className="text-base font-black sm:text-2xl">{num.format(qty)}</p></div><div className="min-w-0"><span className="text-[10px] text-slate-400 sm:text-xs">Value</span><p className="truncate text-sm font-black sm:hidden">{compactMoney(value)}</p><p className="hidden text-xl font-black sm:block">{money.format(value)}</p></div></div></div>{is2026&&<div className="grid grid-cols-2 gap-2 text-[10px] sm:text-right sm:text-xs"><div><b className={growthClass(data.ytd.qtyGrowth)}>{pct(data.ytd.qtyGrowth)}</b><p className="text-slate-400">Qty</p></div><div><b className={growthClass(data.ytd.growth)}>{pct(data.ytd.growth)}</b><p className="text-slate-400">Value</p></div></div>}</div>
   <div className="mt-3 overflow-hidden rounded-lg border sm:mt-5 sm:rounded-xl"><div className="grid grid-cols-[1.15fr_.55fr_.9fr] bg-slate-50 px-2 py-1.5 text-[9px] font-bold text-slate-500 dark:bg-slate-900 sm:px-3 sm:py-2 sm:text-xs"><span>LOB</span><span className="text-right">Qty</span><span className="text-right">Value</span></div>{data.ytd.lobs.map(x=><div key={x.lob} className="grid grid-cols-[1.15fr_.55fr_.9fr] items-center border-t px-2 py-2 text-[10px] sm:px-3 sm:py-3 sm:text-sm"><b className="truncate pr-1">{x.lob}</b><span className="text-right">{num.format(is2026?x.qty2026:x.qty2025)}</span><span className="truncate text-right font-semibold sm:hidden">{compactMoney(is2026?x.amount2026:x.amount2025)}</span><span className="hidden text-right font-semibold sm:block">{money.format(is2026?x.amount2026:x.amount2025)}</span></div>)}</div>
  </div>
 </div>
}

function YtdView({data}:{data:Payload}){const[detail,setDetail]=useState<LobTab>("All Sales");return <div className="space-y-4 sm:space-y-5">
 <section className={`${card} p-3 sm:p-4`}><h2 className="text-lg font-black sm:text-xl">YTD 2025 vs 2026</h2><p className="mt-1 text-xs text-slate-500 sm:text-sm">Januari – {monthName(data.ytd.throughMonth)}. Bulan 2026 yang belum berjalan tidak dihitung sebagai -100%.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:mt-4 sm:gap-4"><YearCard year={2025} data={data}/><YearCard year={2026} data={data}/></div></section>
 <section className={`${card} p-3 sm:p-4`}><h2 className="text-lg font-black sm:text-xl">Detail Per Bulan</h2><div className="mt-3 overflow-x-auto"><div className="inline-flex min-w-max rounded-xl border bg-white p-1 dark:bg-slate-950">{lobTabs.map(x=><button key={x} onClick={()=>setDetail(x)} className={`rounded-lg px-3 py-2 text-[11px] font-black sm:px-4 sm:text-xs ${detail===x?"bg-blue-600 text-white":"text-slate-500"}`}>{x}</button>)}</div></div><div className="mt-3 sm:mt-4"><DetailTable data={data} detail={detail}/></div></section>
 </div>}

function DetailTable({data,detail}:{data:Payload;detail:LobTab}){
 const rows=useMemo(()=>data.compare.map(r=>{if(detail==="All Sales")return{month:r.month,started:r.started,q25:r.qty2025,v25:r.amount2025,q26:r.qty2026,v26:r.amount2026,qg:r.qtyGrowth,vg:r.growth};const lob=r.lobs.find(x=>x.lob===detail);return{month:r.month,started:r.started,q25:lob?.qty2025||0,v25:lob?.amount2025||0,q26:r.started?(lob?.qty2026||0):null,v26:r.started?(lob?.amount2026||0):null,qg:lob?.qtyGrowth??null,vg:lob?.growth??null}}),[data,detail]);
 const ytd=data.ytd.lobs.find(x=>x.lob===detail);
 return <div className="-mx-1 overflow-x-auto px-1"><table className="min-w-[760px] w-full text-xs sm:min-w-[900px] sm:text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500 dark:bg-slate-900"><th rowSpan={2} className="p-2 text-left sm:p-3">Bulan</th><th colSpan={2}>2025</th><th colSpan={2}>2026</th><th colSpan={2}>Growth</th></tr><tr className="border-b bg-slate-50 text-slate-500 dark:bg-slate-900"><th>Qty</th><th>Value</th><th>Qty</th><th>Value</th><th>Qty</th><th>Value</th></tr></thead><tbody>{rows.map(r=><tr key={r.month} className="border-b"><td className="p-2 font-semibold sm:p-3">{monthShort(r.month)}</td><td className="text-center">{num.format(r.q25)}</td><td className="text-right">{money.format(r.v25)}</td><td className="text-center">{r.started?num.format(r.q26||0):"—"}</td><td className="text-right">{r.started?money.format(r.v26||0):"—"}</td><td className={`text-center font-bold ${growthClass(r.qg)}`}>{r.started?pct(r.qg):"—"}</td><td className={`text-center font-bold ${growthClass(r.vg)}`}>{r.started?pct(r.vg):"—"}</td></tr>)}</tbody><tfoot><tr className="bg-slate-50 font-black dark:bg-slate-900"><td className="p-2 sm:p-3">YTD</td><td className="text-center">{num.format(detail==="All Sales"?data.ytd.qty2025:ytd?.qty2025||0)}</td><td className="text-right">{money.format(detail==="All Sales"?data.ytd.amount2025:ytd?.amount2025||0)}</td><td className="text-center">{num.format(detail==="All Sales"?data.ytd.qty2026:ytd?.qty2026||0)}</td><td className="text-right">{money.format(detail==="All Sales"?data.ytd.amount2026:ytd?.amount2026||0)}</td><td className={growthClass(detail==="All Sales"?data.ytd.qtyGrowth:ytd?.qtyGrowth)}>{pct(detail==="All Sales"?data.ytd.qtyGrowth:ytd?.qtyGrowth)}</td><td className={growthClass(detail==="All Sales"?data.ytd.growth:ytd?.growth)}>{pct(detail==="All Sales"?data.ytd.growth:ytd?.growth)}</td></tr></tfoot></table></div>}

function CompareView({data}:{data:Payload}){const[compareMode,setCompareMode]=useState<"all"|"device">("all");return <section className={`${card} p-3 sm:p-4`}><div><h2 className="text-lg font-black sm:text-xl">Compare 2025 vs 2026</h2><p className="mt-1 text-xs text-slate-500 sm:text-sm">Perbandingan bulanan Qty, Value, Selisih, dan Growth.</p></div><div className="mt-3 grid w-full grid-cols-2 rounded-xl border bg-slate-50 p-1 dark:bg-slate-900 sm:inline-grid sm:w-auto"><button onClick={()=>setCompareMode("all")} className={`rounded-lg px-3 py-2.5 text-xs font-black sm:px-5 sm:text-sm ${compareMode==="all"?"bg-blue-600 text-white":"text-slate-500"}`}>All Sales</button><button onClick={()=>setCompareMode("device")} className={`rounded-lg px-3 py-2.5 text-xs font-black sm:px-5 sm:text-sm ${compareMode==="device"?"bg-blue-600 text-white":"text-slate-500"}`}>Device Only</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-[820px] w-full text-xs sm:min-w-[980px] sm:text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500 dark:bg-slate-900"><th className="p-2 text-left sm:p-3">Bulan</th><th>2025 Qty</th><th>2025 Value</th><th>2026 Qty</th><th>2026 Value</th><th>Selisih Value</th><th>Growth</th></tr></thead><tbody>{data.compare.map(r=>{const q25=compareMode==="all"?r.qty2025:r.deviceQty2025,q26=compareMode==="all"?r.qty2026:r.deviceQty2026,a25=compareMode==="all"?r.amount2025:r.device2025,a26=compareMode==="all"?r.amount2026:r.device2026,diff=compareMode==="all"?r.diff:r.deviceDiff,growth=compareMode==="all"?r.growth:r.deviceGrowth;return <tr key={r.month} className="border-b"><td className="p-2 font-bold sm:p-3">{monthShort(r.month)}</td><td className="text-center">{num.format(q25)}</td><td className="text-right">{money.format(a25)}</td><td className="text-center">{r.started?num.format(q26||0):"—"}</td><td className="text-right">{r.started?money.format(a26||0):"—"}</td><td className="text-right">{r.started?money.format(diff||0):"—"}</td><td className={`text-center font-bold ${growthClass(growth)}`}>{r.started?pct(growth):"—"}</td></tr>})}</tbody></table></div></section>}
