"use client";
import {useEffect,useState} from "react";
import OverviewExportActions from "@/components/overview-export-actions";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number|null|undefined)=>v==null?"—":`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const monthShort=(i:number)=>new Intl.DateTimeFormat("id-ID",{month:"short"}).format(new Date(`2026-${String(i).padStart(2,"0")}-01T00:00:00`));

type LobCompare={lob:string;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null};
type Compare={month:number;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null;device2025:number;device2026:number|null;deviceQty2025:number;deviceQty2026:number|null;deviceDiff:number|null;deviceGrowth:number|null;deviceQtyDiff:number|null;deviceQtyGrowth:number|null;lobs:LobCompare[];started:boolean};
type YtdLob={lob:string;amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number|null;qtyDiff:number;qtyGrowth:number|null};
type Payload={period:string;compare:Compare[];ytd:{amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number;qtyDiff:number;qtyGrowth:number;device2025:number;device2026:number;deviceQty2025:number;deviceQty2026:number;deviceDiff:number;deviceGrowth:number;deviceQtyDiff:number;deviceQtyGrowth:number;lobs:YtdLob[];throughMonth:number};error?:string};
const card="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950";

function ValuePair({qty,value}:{qty:number;value:number}){return <div><div className="text-lg font-black">{num.format(qty)} <span className="text-xs font-bold text-slate-400">Qty</span></div><div className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-200">{money.format(value)}</div></div>}

export default function OverviewPage({period}:{period:string;setPeriod:(v:string)=>void}){
 const[mode,setMode]=useState<"ytd"|"compare">("ytd"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");fetch(`/api/overview?period=${encodeURIComponent(period)}&t=${Date.now()}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||"Overview gagal dibaca");if(alive)setData(j)}).catch(e=>alive&&setError(e instanceof Error?e.message:"Overview gagal dibaca")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[period]);
 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">M238 Performance Hub</p><h1 className="mt-2 text-3xl font-black">Overview</h1><p className="mt-1 text-sm text-slate-500">YTD 2025 vs 2026 dan detail per bulan.</p></div>
  <div className="grid grid-cols-2 rounded-xl border bg-white p-1 shadow-sm dark:bg-slate-950"><button onClick={()=>setMode("ytd")} className={`rounded-lg px-3 py-2.5 text-sm font-black ${mode==="ytd"?"bg-blue-600 text-white":"text-slate-500"}`}>YTD Overview</button><button onClick={()=>setMode("compare")} className={`rounded-lg px-3 py-2.5 text-sm font-black ${mode==="compare"?"bg-blue-600 text-white":"text-slate-500"}`}>Compare 2025 vs 2026</button></div>
  {loading&&<div className={card}>Memuat Overview…</div>}
  {error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
  {data&&!loading&&(mode==="ytd"?<YtdView data={data}/>:<CompareView data={data}/>)}
 </div>
}

function YtdView({data}:{data:Payload}){return <div className="space-y-5">
 <div className="flex justify-end"><OverviewExportActions data={data}/></div>
 <section className={card}><div><h2 className="font-black">YTD 2025 vs 2026</h2><p className="mt-1 text-sm text-slate-500">Januari–{monthShort(data.ytd.throughMonth)}. Qty dan value ditampilkan berdampingan.</p></div>
  <div className="mt-4 grid grid-cols-2 gap-3">
   <div className="rounded-2xl border p-4"><div className="text-center text-lg font-black">2025</div><div className="mt-4 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div className="text-xs font-bold uppercase text-slate-400">All Sales</div><div className="mt-2"><ValuePair qty={data.ytd.qty2025} value={data.ytd.amount2025}/></div></div><div className="mt-3 divide-y">{data.ytd.lobs.map(x=><div key={x.lob} className="flex items-center justify-between gap-2 py-3"><b className="text-sm">{x.lob}</b><div className="text-right"><div className="font-black">{num.format(x.qty2025)} Qty</div><div className="text-xs font-semibold text-slate-500">{money.format(x.amount2025)}</div></div></div>)}</div></div>
   <div className="rounded-2xl border p-4"><div className="text-center text-lg font-black">2026</div><div className="mt-4 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><div className="text-xs font-bold uppercase text-slate-400">All Sales</div><div className="mt-2"><ValuePair qty={data.ytd.qty2026} value={data.ytd.amount2026}/></div></div><div className="mt-3 divide-y">{data.ytd.lobs.map(x=><div key={x.lob} className="flex items-center justify-between gap-2 py-3"><b className="text-sm">{x.lob}</b><div className="text-right"><div className="font-black">{num.format(x.qty2026)} Qty</div><div className="text-xs font-semibold text-slate-500">{money.format(x.amount2026)}</div></div></div>)}</div></div>
  </div>
 </section>
 <section className={card}><div><h2 className="font-black">Detail Per Bulan</h2><p className="mt-1 text-sm text-slate-500">Baris kedua Overview: breakdown Qty dan Value setiap bulan.</p></div><div className="mt-4 space-y-3">{data.compare.map(r=><MonthDetail key={r.month} row={r}/>)}</div></section>
 </div>}

function MonthDetail({row:r}:{row:Compare}){return <div className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between bg-slate-50 px-3 py-2.5 dark:bg-slate-900"><b>{monthShort(r.month)}</b><span className="text-xs font-bold text-slate-400">2025 vs 2026</span></div><div className="grid grid-cols-2 divide-x"><div className="p-3"><div className="text-xs font-bold text-slate-400">2025</div><div className="mt-1 font-black">{num.format(r.qty2025)} Qty</div><div className="text-xs font-semibold text-slate-500">{money.format(r.amount2025)}</div></div><div className="p-3"><div className="text-xs font-bold text-slate-400">2026</div><div className="mt-1 font-black">{r.started?`${num.format(r.qty2026||0)} Qty`:"—"}</div><div className="text-xs font-semibold text-slate-500">{r.started?money.format(r.amount2026||0):"Belum berjalan"}</div></div></div><div className="border-t overflow-x-auto"><table className="min-w-[560px] w-full text-xs"><thead><tr className="border-b text-slate-400"><th className="p-2 text-left">LOB</th><th className="text-right">2025 Qty</th><th className="text-right">2025 Value</th><th className="text-right">2026 Qty</th><th className="text-right">2026 Value</th></tr></thead><tbody>{r.lobs.filter(x=>x.lob!=="Other Device"||x.qty2025>0||(x.qty2026||0)>0).map(x=><tr key={x.lob} className="border-b last:border-0"><td className="p-2 font-bold">{x.lob}</td><td className="text-right">{num.format(x.qty2025)}</td><td className="text-right">{money.format(x.amount2025)}</td><td className="text-right">{r.started?num.format(x.qty2026||0):"—"}</td><td className="text-right">{r.started?money.format(x.amount2026||0):"—"}</td></tr>)}</tbody></table></div></div>}

function CompareView({data}:{data:Payload}){const[compareMode,setCompareMode]=useState<"all"|"device">("all");return <div className="space-y-5"><section className={card}><div><h2 className="font-black">Compare 2025 vs 2026</h2><p className="mt-1 text-sm text-slate-500">Perbandingan bulanan dengan Qty, Value, Selisih, dan Growth.</p></div><div className="mt-4 grid grid-cols-2 rounded-xl border bg-slate-50 p-1 dark:bg-slate-900"><button onClick={()=>setCompareMode("all")} className={`rounded-lg px-3 py-2.5 text-sm font-black ${compareMode==="all"?"bg-blue-600 text-white":"text-slate-500"}`}>All Sales</button><button onClick={()=>setCompareMode("device")} className={`rounded-lg px-3 py-2.5 text-sm font-black ${compareMode==="device"?"bg-blue-600 text-white":"text-slate-500"}`}>Device Only</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Bulan</th><th className="text-right">2025 Qty</th><th className="text-right">2025 Value</th><th className="text-right">2026 Qty</th><th className="text-right">2026 Value</th><th className="text-right">Selisih Value</th><th className="text-right">Growth</th></tr></thead><tbody>{data.compare.map(r=>{const q25=compareMode==="all"?r.qty2025:r.deviceQty2025,q26=compareMode==="all"?r.qty2026:r.deviceQty2026,a25=compareMode==="all"?r.amount2025:r.device2025,a26=compareMode==="all"?r.amount2026:r.device2026,diff=compareMode==="all"?r.diff:r.deviceDiff,growth=compareMode==="all"?r.growth:r.deviceGrowth;return <tr key={r.month} className="border-b"><td className="p-2 font-bold">{monthShort(r.month)}</td><td className="text-right">{num.format(q25)}</td><td className="text-right">{money.format(a25)}</td><td className="text-right">{r.started?num.format(q26||0):"—"}</td><td className="text-right">{r.started?money.format(a26||0):"—"}</td><td className="text-right">{r.started?money.format(diff||0):"—"}</td><td className="text-right">{r.started?pct(growth):"—"}</td></tr>})}</tbody></table></div></section>{compareMode==="device"&&<section className={card}><h2 className="font-black">Compare Device per LOB</h2><p className="mt-1 text-sm text-slate-500">iPhone, iPad, Mac, Apple Watch, dan AirPods per bulan.</p><div className="mt-4 space-y-3">{data.compare.map(r=><MonthDetail key={r.month} row={r}/>)}</div></section>}</div>}
