"use client";
import {useEffect,useMemo,useState} from "react";
import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import OverviewExportActions from "@/components/overview-export-actions";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"▲ ":"▼ "}${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Math.abs(Number.isFinite(v)?v:0))}%`;
const currentPeriod=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date()).slice(0,7);
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`);
const monthName=(v:string|number)=>new Intl.DateTimeFormat("id-ID",{month:"long"}).format(new Date(`2026-${String(v).padStart(2,"0").replace(/^2026-/,"")}-01T00:00:00`));
const monthLabel=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`));
const monthShort=(i:number)=>new Intl.DateTimeFormat("id-ID",{month:"short"}).format(new Date(`2026-${String(i).padStart(2,"0")}-01T00:00:00`));
const compactMoney=(v:number)=>{const a=Math.abs(v);if(a>=1e9)return `Rp${(v/1e9).toLocaleString("id-ID",{maximumFractionDigits:1})}M`;if(a>=1e6)return `Rp${(v/1e6).toLocaleString("id-ID",{maximumFractionDigits:1})}jt`;return money.format(v)};

type Staff={id:string;name:string;amount:number;device:number;accessories:number;vas:number;qty:number;invoices:number;upt:number;atv:number;target:number;achievement:number|null;gap:number;status:string};
type LobCompare={lob:string;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null};
type Compare={month:number;amount2025:number;amount2026:number|null;qty2025:number;qty2026:number|null;diff:number|null;growth:number|null;qtyDiff:number|null;qtyGrowth:number|null;device2025:number;device2026:number|null;deviceQty2025:number;deviceQty2026:number|null;deviceDiff:number|null;deviceGrowth:number|null;deviceQtyDiff:number|null;deviceQtyGrowth:number|null;lobs:LobCompare[];started:boolean};
type YtdLob={lob:string;amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number|null;qtyDiff:number;qtyGrowth:number|null};
type Payload={period:string;label:string;target:{amount:number;device:number;accessories:number;vas:number};summary:{amount:number;device:number;accessories:number;vas:number;invoices:number;qty:number;upt:number;atv:number;achievement:number;gap:number;pace:number;status:string;estimate:{amount:number;device:number;accessories:number;vas:number};point:{total:number;device:number;accessories:number;vas:number}};staff:Staff[];daily:{date:string;amount:number}[];team:{total:number;productive:number;needPush:number;totalTransactions:number;avgUpt:number;avgAtv:number};lfl:Compare|null;compare:Compare[];ytd:{amount2025:number;amount2026:number;qty2025:number;qty2026:number;diff:number;growth:number;qtyDiff:number;qtyGrowth:number;device2025:number;device2026:number;deviceQty2025:number;deviceQty2026:number;deviceDiff:number;deviceGrowth:number;deviceQtyDiff:number;deviceQtyGrowth:number;lobs:YtdLob[];throughMonth:number};error?:string};

const card="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/[0.08] dark:bg-[#1c1c1e] dark:shadow-none";
const lobTabs=["All Sales","iPhone","iPad","Mac","Apple Watch","AirPods"] as const;
type LobTab=(typeof lobTabs)[number];
function growthClass(v:number|null|undefined){return (v??0)>=0?"text-emerald-600":"text-rose-500"}
function Badge({children}:{children:string}){const tone=children==="Productive"||children==="Achieve"||children==="On Track"?"bg-emerald-50 text-emerald-700":children==="Need Push"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${tone}`}>{children}</span>}
function MiniKpi({label,actual,target,estimate,point,maxPoint}:{label:string;actual:number;target:number;estimate:number;point:number;maxPoint:number}){const a=target?actual/target*100:0,variance=target-actual,varianceTone=variance>0?"text-rose-600 dark:text-rose-400":variance<0?"text-emerald-600 dark:text-emerald-400":"text-slate-500 dark:text-slate-400",varianceValue=money.format(variance);return <div className={`${card} p-4`}><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-black">{money.format(actual)}</p><div className="mt-3 border-t pt-3"><div className="flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate text-slate-500 dark:text-[#8e8e93]">Target {money.format(target)}</span><b className="shrink-0">{pct(a)}</b></div><div className="mt-2 flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate font-semibold text-blue-600 dark:text-[#7eb0ff]">Est. {money.format(estimate)}</span><b className="shrink-0 text-slate-700 dark:text-slate-200">{new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(point)}/{maxPoint} pts</b></div><div className="mt-2 flex items-center justify-between gap-3 text-xs"><span className="text-slate-500 dark:text-[#8e8e93]">Variance</span><b className={`shrink-0 ${varianceTone}`}>{varianceValue}</b></div></div></div>}

export default function OverviewMain({period,setPeriod}:{period:string;setPeriod:(v:string)=>void}){
 const[mode,setMode]=useState<"monthly"|"ytd"|"compare">("monthly"),[monthMode,setMonthMode]=useState<"current"|"pick">(period===currentPeriod()?"current":"pick"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");fetch(`/api/overview?period=${encodeURIComponent(period)}&t=${Date.now()}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||"Overview gagal dibaca");if(alive)setData(j)}).catch(e=>alive&&setError(e instanceof Error?e.message:"Overview gagal dibaca")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[period]);
 const top=useMemo(()=>[...(data?.staff||[])].sort((a,b)=>b.amount-a.amount).slice(0,3),[data]);
 const needPush=useMemo(()=>[...(data?.staff||[])].filter(x=>x.status!=="Productive").sort((a,b)=>(a.achievement??999)-(b.achievement??999)||a.amount-b.amount).slice(0,3),[data]);
 const setCurrent=()=>{setMonthMode("current");setPeriod(currentPeriod())};
 return <div className="m238-overview-canvas min-h-[100dvh] space-y-4 bg-slate-50 text-slate-950 sm:space-y-5 dark:bg-black dark:text-white">
  <div className="grid w-full grid-cols-3 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm dark:border-white/[0.08] dark:bg-[#1c1c1e] dark:shadow-none">
   <button onClick={()=>setMode("monthly")} className={`rounded-lg px-2 py-2.5 text-[11px] font-black sm:px-5 sm:text-sm ${mode==="monthly"?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>Overview Bulanan</button>
   <button onClick={()=>setMode("ytd")} className={`rounded-lg px-2 py-2.5 text-[11px] font-black sm:px-5 sm:text-sm ${mode==="ytd"?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>YTD Overview</button>
   <button onClick={()=>setMode("compare")} className={`rounded-lg px-2 py-2.5 text-[11px] font-black sm:px-5 sm:text-sm ${mode==="compare"?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>Compare 2025 vs 2026</button>
  </div>
  {mode==="monthly"&&<>
   <section className={`${card} p-4`}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Periode</p><div className="mt-2 flex flex-wrap gap-2"><button onClick={setCurrent} className={`rounded-xl border px-3 py-2 text-sm font-bold ${monthMode==="current"?"border-[#0a84ff] bg-blue-50 text-blue-700 dark:bg-[#1d2a44] dark:text-[#7eb0ff]":"bg-white dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-white"}`}>● Bulan Berjalan</button><button onClick={()=>setMonthMode("pick")} className={`rounded-xl border px-3 py-2 text-sm font-bold ${monthMode==="pick"?"border-[#0a84ff] bg-blue-50 text-blue-700 dark:bg-[#1d2a44] dark:text-[#7eb0ff]":"bg-white dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-white"}`}>○ Pilih Bulan</button>{monthMode==="pick"&&<select value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-white">{months.map(x=><option key={x} value={x}>{monthLabel(x)}</option>)}</select>}</div></div><b className="text-sm text-slate-500">{data?.label||monthLabel(period)}</b></div></section>
   {loading&&<div className={`${card} p-4`}>Memuat Overview…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
   {data&&!loading&&<>
    <section><div className="mb-3"><h2 className="font-black text-slate-950 dark:text-white">Store Performance</h2><p className="text-sm text-slate-500 dark:text-[#8e8e93]">Actual vs target bulan terpilih.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniKpi label="Total Sales" actual={data.summary.amount} target={data.target.amount} estimate={data.summary.estimate.amount} point={data.summary.point.total} maxPoint={100}/><MiniKpi label="Device" actual={data.summary.device} target={data.target.device} estimate={data.summary.estimate.device} point={data.summary.point.device} maxPoint={60}/><MiniKpi label="Accessories" actual={data.summary.accessories} target={data.target.accessories} estimate={data.summary.estimate.accessories} point={data.summary.point.accessories} maxPoint={30}/><MiniKpi label="VAS" actual={data.summary.vas} target={data.target.vas} estimate={data.summary.estimate.vas} point={data.summary.point.vas} maxPoint={10}/></div></section>
    <section className={`${card} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Month Progress</h2><p className="mt-1 text-sm text-slate-500">Progress target dan produktivitas transaksi.</p></div><Badge>{data.summary.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat l="Target" v={money.format(data.target.amount)}/><Stat l="Achievement" v={`${money.format(data.summary.amount)} • ${pct(data.summary.achievement)}`}/><Stat l="Gap" v={money.format(data.summary.gap)}/><Stat l="Month Pace" v={pct(data.summary.pace)}/><Stat l="UPT" v={data.summary.upt.toFixed(1)}/><Stat l="ATV" v={money.format(data.summary.atv)}/><Stat l="Transaction" v={num.format(data.summary.invoices)}/></div></section>
    <section className={`${card} p-4`}><h2 className="font-black">Team Performance</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-6">{[["Total Staff",data.team.total],["Productive",data.team.productive],["Need Push",data.team.needPush],["Total Transaction",data.team.totalTransactions],["Avg UPT",data.team.avgUpt.toFixed(1)],["Avg ATV",money.format(data.team.avgAtv)]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-slate-200 p-3 dark:border-white/[0.08] dark:bg-[#2c2c2e]"><span className="text-xs text-slate-400 dark:text-[#8e8e93]">{l}</span><b className="mt-1 block text-lg">{v}</b></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className={`${card} p-4`}><h2 className="font-black">Top Performance</h2><div className="mt-3 divide-y">{top.length?top.map((r,i)=><div key={r.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 py-3"><div className="grid size-8 place-items-center rounded-lg bg-blue-50 font-black text-blue-600">{i+1}</div><div><b>{r.name}</b><p className="text-xs text-slate-400 dark:text-[#8e8e93]">UPT {r.upt.toFixed(1)} • ATV {money.format(r.atv)}</p></div><div className="text-right"><b>{money.format(r.amount)}</b><p className="text-xs text-slate-400 dark:text-[#8e8e93]">{pct(r.achievement)}</p></div></div>):<p className="py-5 text-sm text-slate-400">Belum ada data staff.</p>}</div></div><div className={`${card} p-4`}><h2 className="font-black">Need Push</h2><div className="mt-3 divide-y">{needPush.length?needPush.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto] gap-3 py-3"><div><b>{r.name}</b><p className="text-xs text-slate-400 dark:text-[#8e8e93]">Achievement {pct(r.achievement)}</p></div><div className="text-right"><b>{money.format(r.amount)}</b><p className="text-xs text-slate-400 dark:text-[#8e8e93]">Gap {r.target?money.format(r.gap):"—"}</p></div></div>):<p className="py-5 text-sm text-slate-400">Tidak ada staff Need Push.</p>}</div></div></section>
    <section className={`${card} p-4`}><h2 className="font-black">Staff Productivity</h2><p className="mt-1 text-sm text-slate-500">Staff mengikuti histori transaksi M238 pada bulan terpilih, bukan roster aktif saat ini.</p><div className="mt-4 overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Staff</th><th>Sales</th><th>Trx</th><th>Device</th><th>Accessories</th><th>VAS</th><th>UPT</th><th>ATV</th><th>Status</th></tr></thead><tbody>{data.staff.length?data.staff.map(r=><tr key={r.id} className="border-b dark:border-white/[0.08]"><td className="p-2 font-bold">{r.name}</td><td>{money.format(r.amount)}</td><td>{r.invoices}</td><td>{money.format(r.device)}</td><td>{money.format(r.accessories)}</td><td>{money.format(r.vas)}</td><td>{r.upt.toFixed(1)}</td><td>{money.format(r.atv)}</td><td><Badge>{r.status}</Badge></td></tr>):<tr><td colSpan={9} className="p-8 text-center text-slate-400">Belum ada transaksi staff M238 pada bulan ini.</td></tr>}</tbody></table></div></section>
    <section className={`${card} p-4`}><h2 className="font-black">Sales Trend</h2><p className="mt-1 text-sm text-slate-500">Tanggal vs Total Sales bulan terpilih.</p><div className="mt-4 h-64">{data.daily.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={data.daily}><XAxis dataKey="date" tickFormatter={v=>String(v).slice(8,10)} tick={{fontSize:11}}/><YAxis tickFormatter={v=>`${Math.round(Number(v)/1000000)}jt`} width={48} tick={{fontSize:11}}/><Tooltip formatter={v=>money.format(Number(v||0))} labelFormatter={v=>String(v)}/><Line type="monotone" dataKey="amount" stroke="currentColor" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">Belum ada data sales trend.</div>}</div></section>
    <section className={`${card} p-4`}><h2 className="font-black">LFL Summary</h2><p className="mt-1 text-sm text-slate-500">Bulan terpilih dibanding bulan yang sama tahun sebelumnya.</p>{data.lfl&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat l={`${monthShort(data.lfl.month)} 2025`} v={money.format(data.lfl.amount2025)}/><Stat l={`${monthShort(data.lfl.month)} 2026`} v={data.lfl.started?money.format(data.lfl.amount2026||0):"—"}/><Stat l="Growth" v={data.lfl.started?pct(data.lfl.growth):"Belum berjalan"}/><Stat l="Selisih" v={data.lfl.started?money.format(data.lfl.diff||0):"—"}/></div>}</section>
   </>}
  </>}
  {mode==="ytd"&&<>{loading&&<div className={`${card} p-4`}>Memuat YTD…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}{data&&!loading&&<YtdView data={data}/>}</>}
  {mode==="compare"&&<>{loading&&<div className={`${card} p-4`}>Memuat Compare…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}{data&&!loading&&<CompareView data={data}/>}</>}
 </div>
}

function Stat({l,v}:{l:string;v:string}){return <div><span className="text-xs text-slate-400 dark:text-[#8e8e93]">{l}</span><b className="mt-1 block">{v}</b></div>}
function YearCard({year,data}:{year:2025|2026;data:Payload}){const is2026=year===2026,qty=is2026?data.ytd.qty2026:data.ytd.qty2025,value=is2026?data.ytd.amount2026:data.ytd.amount2025;return <div className={`min-w-0 overflow-hidden rounded-xl border sm:rounded-2xl ${is2026?"border-emerald-100":"border-blue-100"}`}><div className={`px-2.5 py-2 text-base font-black sm:px-4 sm:py-3 sm:text-xl ${is2026?"bg-emerald-50 text-emerald-700":"bg-blue-50 text-blue-700"}`}>{year}</div><div className="p-2.5 sm:p-4"><div><p className="text-[10px] font-bold uppercase text-slate-400 sm:text-xs">All Sales</p><div className="mt-1 grid grid-cols-2 gap-2"><div><span className="text-[10px] text-slate-400">Qty</span><p className="text-base font-black sm:text-2xl">{num.format(qty)}</p></div><div><span className="text-[10px] text-slate-400">Value</span><p className="text-sm font-black sm:hidden">{compactMoney(value)}</p><p className="hidden text-xl font-black sm:block">{money.format(value)}</p></div></div>{is2026&&<div className="mt-2 grid grid-cols-2 gap-2 text-[10px] sm:text-xs"><b className={growthClass(data.ytd.qtyGrowth)}>{pct(data.ytd.qtyGrowth)} Qty</b><b className={growthClass(data.ytd.growth)}>{pct(data.ytd.growth)} Value</b></div>}</div><div className="mt-3 overflow-hidden rounded-lg border"><div className="grid grid-cols-[1.15fr_.55fr_.9fr] bg-slate-50 px-2 py-1.5 text-[9px] font-bold text-slate-500 dark:bg-[#2c2c2e] dark:text-[#8e8e93]"><span>LOB</span><span className="text-right">Qty</span><span className="text-right">Value</span></div>{data.ytd.lobs.map(x=><div key={x.lob} className="grid grid-cols-[1.15fr_.55fr_.9fr] items-center border-t px-2 py-2 text-[10px] sm:text-sm"><b className="truncate pr-1">{x.lob}</b><span className="text-right">{num.format(is2026?x.qty2026:x.qty2025)}</span><span className="text-right sm:hidden">{compactMoney(is2026?x.amount2026:x.amount2025)}</span><span className="hidden text-right sm:block">{money.format(is2026?x.amount2026:x.amount2025)}</span></div>)}</div></div></div>}
function YtdView({data}:{data:Payload}){const[detail,setDetail]=useState<LobTab>("All Sales");return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex gap-2"><span className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold shadow-sm dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-white dark:shadow-none">📅 Jan – {monthShort(data.ytd.throughMonth)}</span><span className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold shadow-sm dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-white dark:shadow-none">2026</span></div><OverviewExportActions data={data}/></div><section className={`${card} p-3 sm:p-4`}><h2 className="text-lg font-black sm:text-xl">YTD 2025 vs 2026</h2><p className="mt-1 text-xs text-slate-500">Januari – {monthShort(data.ytd.throughMonth)}. Bulan 2026 yang belum berjalan tidak dihitung sebagai -100%.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:gap-4"><YearCard year={2025} data={data}/><YearCard year={2026} data={data}/></div></section><section className={`${card} p-3 sm:p-4`}><h2 className="text-lg font-black">Detail Per Bulan</h2><div className="mt-3 overflow-x-auto"><div className="inline-flex min-w-max rounded-xl border border-slate-200 bg-white p-1 dark:border-white/[0.08] dark:bg-[#2c2c2e]">{lobTabs.map(x=><button key={x} onClick={()=>setDetail(x)} className={`rounded-lg px-3 py-2 text-[11px] font-black ${detail===x?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>{x}</button>)}</div></div><div className="mt-3"><DetailTable data={data} detail={detail}/></div></section></div>}
function DetailTable({data,detail}:{data:Payload;detail:LobTab}){const rows=useMemo(()=>data.compare.map(r=>{if(detail==="All Sales")return{month:r.month,started:r.started,q25:r.qty2025,v25:r.amount2025,q26:r.qty2026,v26:r.amount2026,qg:r.qtyGrowth,vg:r.growth};const lob=r.lobs.find(x=>x.lob===detail);return{month:r.month,started:r.started,q25:lob?.qty2025||0,v25:lob?.amount2025||0,q26:r.started?(lob?.qty2026||0):null,v26:r.started?(lob?.amount2026||0):null,qg:lob?.qtyGrowth??null,vg:lob?.growth??null}}),[data,detail]);const ytd=data.ytd.lobs.find(x=>x.lob===detail);return <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-xs sm:text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500 dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-[#8e8e93]"><th rowSpan={2} className="p-2 text-left">Bulan</th><th colSpan={2}>2025</th><th colSpan={2}>2026</th><th colSpan={2}>Growth</th></tr><tr className="border-b bg-slate-50 text-slate-500 dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-[#8e8e93]"><th>Qty</th><th>Value</th><th>Qty</th><th>Value</th><th>Qty</th><th>Value</th></tr></thead><tbody>{rows.map(r=><tr key={r.month} className="border-b dark:border-white/[0.08]"><td className="p-2 font-semibold">{monthShort(r.month)}</td><td className="text-center">{num.format(r.q25)}</td><td className="text-right">{money.format(r.v25)}</td><td className="text-center">{r.started?num.format(r.q26||0):"—"}</td><td className="text-right">{r.started?money.format(r.v26||0):"—"}</td><td className={`text-center font-bold ${growthClass(r.qg)}`}>{r.started?pct(r.qg):"—"}</td><td className={`text-center font-bold ${growthClass(r.vg)}`}>{r.started?pct(r.vg):"—"}</td></tr>)}</tbody><tfoot><tr className="bg-slate-50 font-black dark:bg-[#2c2c2e] dark:text-white"><td className="p-2">YTD</td><td className="text-center">{num.format(detail==="All Sales"?data.ytd.qty2025:ytd?.qty2025||0)}</td><td className="text-right">{money.format(detail==="All Sales"?data.ytd.amount2025:ytd?.amount2025||0)}</td><td className="text-center">{num.format(detail==="All Sales"?data.ytd.qty2026:ytd?.qty2026||0)}</td><td className="text-right">{money.format(detail==="All Sales"?data.ytd.amount2026:ytd?.amount2026||0)}</td><td className={growthClass(detail==="All Sales"?data.ytd.qtyGrowth:ytd?.qtyGrowth)}>{pct(detail==="All Sales"?data.ytd.qtyGrowth:ytd?.qtyGrowth)}</td><td className={growthClass(detail==="All Sales"?data.ytd.growth:ytd?.growth)}>{pct(detail==="All Sales"?data.ytd.growth:ytd?.growth)}</td></tr></tfoot></table></div>}
function CompareView({data}:{data:Payload}){const[compareMode,setCompareMode]=useState<"all"|"device">("all");return <section className={`${card} p-3 sm:p-4`}><h2 className="text-lg font-black">Compare 2025 vs 2026</h2><p className="mt-1 text-xs text-slate-500">Perbandingan bulanan Qty, Value, Selisih, dan Growth.</p><div className="mt-3 grid w-full grid-cols-2 rounded-xl border bg-slate-50 p-1 sm:inline-grid sm:w-auto"><button onClick={()=>setCompareMode("all")} className={`rounded-lg px-3 py-2.5 text-xs font-black ${compareMode==="all"?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>All Sales</button><button onClick={()=>setCompareMode("device")} className={`rounded-lg px-3 py-2.5 text-xs font-black ${compareMode==="device"?"bg-[#3a3a3c] text-white":"text-slate-500 dark:text-[#8e8e93]"}`}>Device Only</button></div><div className="mt-4 overflow-x-auto"><table className="min-w-[820px] w-full text-xs sm:text-sm"><thead><tr className="border-b bg-slate-50 text-slate-500 dark:border-white/[0.08] dark:bg-[#2c2c2e] dark:text-[#8e8e93]"><th className="p-2 text-left">Bulan</th><th>2025 Qty</th><th>2025 Value</th><th>2026 Qty</th><th>2026 Value</th><th>Selisih Value</th><th>Growth</th></tr></thead><tbody>{data.compare.map(r=>{const q25=compareMode==="all"?r.qty2025:r.deviceQty2025,q26=compareMode==="all"?r.qty2026:r.deviceQty2026,a25=compareMode==="all"?r.amount2025:r.device2025,a26=compareMode==="all"?r.amount2026:r.device2026,diff=compareMode==="all"?r.diff:r.deviceDiff,growth=compareMode==="all"?r.growth:r.deviceGrowth;return <tr key={r.month} className="border-b dark:border-white/[0.08]"><td className="p-2 font-bold">{monthShort(r.month)}</td><td className="text-center">{num.format(q25)}</td><td className="text-right">{money.format(a25)}</td><td className="text-center">{r.started?num.format(q26||0):"—"}</td><td className="text-right">{r.started?money.format(a26||0):"—"}</td><td className="text-right">{r.started?money.format(diff||0):"—"}</td><td className={`text-center font-bold ${growthClass(growth)}`}>{r.started?pct(growth):"—"}</td></tr>})}</tbody></table></div></section>}
