"use client";
import {useEffect,useMemo,useState} from "react";
import {Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number|null|undefined)=>v==null?"—":`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const currentPeriod=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date()).slice(0,7);
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`);
const monthName=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`));
const monthShort=(i:number)=>new Intl.DateTimeFormat("id-ID",{month:"short"}).format(new Date(`2026-${String(i).padStart(2,"0")}-01T00:00:00`));
type Staff={id:string;name:string;amount:number;device:number;accessories:number;vas:number;qty:number;invoices:number;upt:number;atv:number;target:number;achievement:number|null;gap:number;status:string};
type LobCompare={lob:string;amount2025:number;amount2026:number|null;diff:number|null;growth:number|null};
type Compare={month:number;amount2025:number;amount2026:number|null;diff:number|null;growth:number|null;device2025:number;device2026:number|null;deviceDiff:number|null;deviceGrowth:number|null;lobs:LobCompare[];started:boolean};
type Payload={period:string;label:string;target:{amount:number;device:number;accessories:number;vas:number};summary:{amount:number;device:number;accessories:number;vas:number;invoices:number;qty:number;upt:number;atv:number;achievement:number;gap:number;pace:number;status:string};staff:Staff[];daily:{date:string;amount:number}[];team:{total:number;productive:number;needPush:number;totalTransactions:number;avgUpt:number;avgAtv:number};lfl:Compare|null;compare:Compare[];ytd:{amount2025:number;amount2026:number;diff:number;growth:number;device2025:number;device2026:number;deviceDiff:number;deviceGrowth:number;throughMonth:number};error?:string};
const card="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950";
function Badge({children}:{children:string}){const tone=children==="Productive"||children==="Achieve"||children==="On Track"?"bg-emerald-50 text-emerald-700":children==="Need Push"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${tone}`}>{children}</span>}
function MiniKpi({label,actual,target}:{label:string;actual:number;target:number}){const a=target?actual/target*100:0;return <div className={card}><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-black">{money.format(actual)}</p><div className="mt-3 flex items-center justify-between gap-2 border-t pt-3 text-xs"><span className="text-slate-500">Target {money.format(target)}</span><b>{pct(a)}</b></div></div>}
export default function OverviewPage({period,setPeriod}:{period:string;setPeriod:(v:string)=>void}){
 const[mode,setMode]=useState<"monthly"|"compare">("monthly"),[monthMode,setMonthMode]=useState<"current"|"pick">(period===currentPeriod()?"current":"pick"),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setError("");fetch(`/api/overview?period=${encodeURIComponent(period)}&t=${Date.now()}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||"Overview gagal dibaca");if(alive)setData(j)}).catch(e=>alive&&setError(e instanceof Error?e.message:"Overview gagal dibaca")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[period]);
 const top=useMemo(()=>[...(data?.staff||[])].sort((a,b)=>b.amount-a.amount).slice(0,3),[data]),needPush=useMemo(()=>[...(data?.staff||[])].filter(x=>x.status!=="Productive").sort((a,b)=>(a.achievement??999)-(b.achievement??999)||a.amount-b.amount).slice(0,3),[data]);
 const setCurrent=()=>{setMonthMode("current");setPeriod(currentPeriod())},pick=()=>setMonthMode("pick");
 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">M238 Performance Hub</p><h1 className="mt-2 text-3xl font-black">Overview</h1><p className="mt-1 text-sm text-slate-500">Ringkasan performa store dan team M238.</p></div>
  <div className="inline-flex rounded-xl border bg-white p-1 shadow-sm dark:bg-slate-950"><button onClick={()=>setMode("monthly")} className={`rounded-lg px-4 py-2 text-sm font-black ${mode==="monthly"?"bg-blue-600 text-white":"text-slate-500"}`}>Overview Bulanan</button><button onClick={()=>setMode("compare")} className={`rounded-lg px-4 py-2 text-sm font-black ${mode==="compare"?"bg-blue-600 text-white":"text-slate-500"}`}>Compare 2025 vs 2026</button></div>
  {mode==="monthly"?<>
   <section className={card}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Periode</p><div className="mt-2 flex flex-wrap gap-2"><button onClick={setCurrent} className={`rounded-xl border px-3 py-2 text-sm font-bold ${monthMode==="current"?"border-blue-600 bg-blue-50 text-blue-700":"bg-white dark:bg-slate-900"}`}>● Bulan Berjalan</button><button onClick={pick} className={`rounded-xl border px-3 py-2 text-sm font-bold ${monthMode==="pick"?"border-blue-600 bg-blue-50 text-blue-700":"bg-white dark:bg-slate-900"}`}>○ Pilih Bulan</button>{monthMode==="pick"&&<select value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900">{months.map(x=><option key={x} value={x}>{monthName(x)}</option>)}</select>}</div></div><b className="text-sm text-slate-500">{data?.label||monthName(period)}</b></div></section>
   {loading&&<div className={card}>Memuat Overview…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
   {data&&!loading&&<>
    <section><div className="mb-3"><h2 className="font-black">Store Performance</h2><p className="text-sm text-slate-500">Actual vs target bulan terpilih.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniKpi label="Total Sales" actual={data.summary.amount} target={data.target.amount}/><MiniKpi label="Device" actual={data.summary.device} target={data.target.device}/><MiniKpi label="Accessories" actual={data.summary.accessories} target={data.target.accessories}/><MiniKpi label="VAS" actual={data.summary.vas} target={data.target.vas}/></div></section>
    <section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Month Progress</h2><p className="mt-1 text-sm text-slate-500">Progress target dan produktivitas transaksi.</p></div><Badge>{data.summary.status}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-xs text-slate-400">Target</span><b className="mt-1 block">{money.format(data.target.amount)}</b></div><div><span className="text-xs text-slate-400">Achievement</span><b className="mt-1 block">{money.format(data.summary.amount)} • {pct(data.summary.achievement)}</b></div><div><span className="text-xs text-slate-400">Gap</span><b className="mt-1 block">{money.format(data.summary.gap)}</b></div><div><span className="text-xs text-slate-400">Month Pace</span><b className="mt-1 block">{pct(data.summary.pace)}</b></div><div><span className="text-xs text-slate-400">UPT</span><b className="mt-1 block">{data.summary.upt.toFixed(1)}</b></div><div><span className="text-xs text-slate-400">ATV</span><b className="mt-1 block">{money.format(data.summary.atv)}</b></div><div><span className="text-xs text-slate-400">Transaction</span><b className="mt-1 block">{num.format(data.summary.invoices)}</b></div></div></section>
    <section className={card}><h2 className="font-black">Team Performance</h2><div className="mt-4 grid gap-3 grid-cols-2 lg:grid-cols-6">{[["Total Staff",data.team.total],["Productive",data.team.productive],["Need Push",data.team.needPush],["Total Transaction",data.team.totalTransactions],["Avg UPT",data.team.avgUpt.toFixed(1)],["Avg ATV",money.format(data.team.avgAtv)]].map(([l,v])=><div key={String(l)} className="rounded-xl border p-3"><span className="text-xs text-slate-400">{l}</span><b className="mt-1 block text-lg">{v}</b></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className={card}><h2 className="font-black">Top Performance</h2><div className="mt-3 divide-y">{top.length?top.map((r,i)=><div key={r.id} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 py-3"><div className="grid size-8 place-items-center rounded-lg bg-blue-50 font-black text-blue-600">{i+1}</div><div><b>{r.name}</b><p className="text-xs text-slate-400">UPT {r.upt.toFixed(1)} • ATV {money.format(r.atv)}</p></div><div className="text-right"><b>{money.format(r.amount)}</b><p className="text-xs text-slate-400">{pct(r.achievement)}</p></div></div>):<p className="py-5 text-sm text-slate-400">Belum ada data staff.</p>}</div></div><div className={card}><h2 className="font-black">Need Push</h2><div className="mt-3 divide-y">{needPush.length?needPush.map(r=><div key={r.id} className="grid grid-cols-[1fr_auto] gap-3 py-3"><div><b>{r.name}</b><p className="text-xs text-slate-400">Achievement {pct(r.achievement)}</p></div><div className="text-right"><b>{money.format(r.amount)}</b><p className="text-xs text-slate-400">Gap {r.target?money.format(r.gap):"—"}</p></div></div>):<p className="py-5 text-sm text-slate-400">Tidak ada staff yang masuk Need Push pada periode ini.</p>}</div></div></section>
    <section className={card}><h2 className="font-black">Staff Productivity</h2><p className="mt-1 text-sm text-slate-500">Staff mengikuti histori transaksi M238 pada bulan terpilih, bukan roster aktif saat ini.</p><div className="mt-4 overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Staff</th><th>Sales</th><th>Trx</th><th>Device</th><th>Accessories</th><th>VAS</th><th>UPT</th><th>ATV</th><th>Status</th></tr></thead><tbody>{data.staff.length?data.staff.map(r=><tr key={r.id} className="border-b"><td className="p-2 font-bold">{r.name}</td><td>{money.format(r.amount)}</td><td>{r.invoices}</td><td>{money.format(r.device)}</td><td>{money.format(r.accessories)}</td><td>{money.format(r.vas)}</td><td>{r.upt.toFixed(1)}</td><td>{money.format(r.atv)}</td><td><Badge>{r.status}</Badge></td></tr>):<tr><td colSpan={9} className="p-8 text-center text-slate-400">Belum ada transaksi staff M238 pada bulan ini.</td></tr>}</tbody></table></div></section>
    <section className={card}><h2 className="font-black">Sales Trend</h2><p className="mt-1 text-sm text-slate-500">Tanggal vs Total Sales bulan terpilih.</p><div className="mt-4 h-64">{data.daily.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={data.daily}><XAxis dataKey="date" tickFormatter={(v)=>String(v).slice(8,10)} tick={{fontSize:11}}/><YAxis tickFormatter={(v)=>`${Math.round(Number(v)/1000000)}jt`} width={48} tick={{fontSize:11}}/><Tooltip formatter={(v)=>money.format(Number(v||0))} labelFormatter={v=>String(v)}/><Line type="monotone" dataKey="amount" stroke="currentColor" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer>:<div className="grid h-full place-items-center text-sm text-slate-400">Belum ada data sales trend.</div>}</div></section>
    <section className={card}><h2 className="font-black">LFL Summary</h2><p className="mt-1 text-sm text-slate-500">Bulan terpilih dibanding bulan yang sama tahun sebelumnya.</p>{data.lfl?<div className="mt-4 grid gap-3 sm:grid-cols-4"><div><span className="text-xs text-slate-400">{monthShort(data.lfl.month)} 2025</span><b className="mt-1 block">{money.format(data.lfl.amount2025)}</b></div><div><span className="text-xs text-slate-400">{monthShort(data.lfl.month)} 2026</span><b className="mt-1 block">{data.lfl.started?money.format(data.lfl.amount2026||0):"—"}</b></div><div><span className="text-xs text-slate-400">Growth</span><b className="mt-1 block">{data.lfl.started?pct(data.lfl.growth):"Belum berjalan"}</b></div><div><span className="text-xs text-slate-400">Selisih</span><b className="mt-1 block">{data.lfl.started?money.format(data.lfl.diff||0):"—"}</b></div></div>:null}</section>
   </>}
  </>:<CompareView data={data} loading={loading} error={error}/>} 
 </div>
}
function CompareTable({rows,type}:{rows:Compare[];type:"all"|"device"}){return <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-sm"><thead><tr className="border-b"><th className="p-2 text-left">Bulan</th><th className="text-right">2025</th><th className="text-right">2026</th><th className="text-right">Selisih</th><th className="text-right">Growth</th></tr></thead><tbody>{rows.map(r=>{const a25=type==="all"?r.amount2025:r.device2025,a26=type==="all"?r.amount2026:r.device2026,diff=type==="all"?r.diff:r.deviceDiff,growth=type==="all"?r.growth:r.deviceGrowth;return <tr key={r.month} className="border-b"><td className="p-2 font-bold">{monthShort(r.month)}</td><td className="text-right">{money.format(a25)}</td><td className="text-right">{r.started?money.format(a26||0):"—"}</td><td className="text-right">{r.started?money.format(diff||0):"—"}</td><td className="text-right">{r.started?pct(growth):"Belum berjalan"}</td></tr>})}</tbody></table></div>}
function CompareView({data,loading,error}:{data:Payload|null;loading:boolean;error:string}){
 const[compareMode,setCompareMode]=useState<"all"|"device">("all");
 return <div className="space-y-5">{loading&&<div className={card}>Memuat compare tahunan…</div>}{error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}{data&&!loading&&<>
  <section className={card}><div><h2 className="font-black">Compare 2025 vs 2026</h2><p className="mt-1 text-sm text-slate-500">Full comparison Januari–Desember. Bulan 2026 yang belum berjalan tidak dihitung sebagai -100%.</p></div><div className="mt-4 grid grid-cols-2 rounded-xl border bg-slate-50 p-1 dark:bg-slate-900"><button onClick={()=>setCompareMode("all")} className={`rounded-lg px-3 py-2.5 text-sm font-black transition ${compareMode==="all"?"bg-blue-600 text-white shadow-sm":"text-slate-500"}`}>All Sales</button><button onClick={()=>setCompareMode("device")} className={`rounded-lg px-3 py-2.5 text-sm font-black transition ${compareMode==="device"?"bg-blue-600 text-white shadow-sm":"text-slate-500"}`}>Device Only</button></div><div className="mt-4"><CompareTable rows={data.compare} type={compareMode}/><div className="mt-3 grid gap-2 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900 sm:grid-cols-5"><b>YTD Jan–{monthShort(data.ytd.throughMonth)}</b><span className="sm:text-right">2025: {money.format(compareMode==="all"?data.ytd.amount2025:data.ytd.device2025)}</span><span className="sm:text-right">2026: {money.format(compareMode==="all"?data.ytd.amount2026:data.ytd.device2026)}</span><span className="sm:text-right">Selisih: {money.format(compareMode==="all"?data.ytd.diff:data.ytd.deviceDiff)}</span><span className="sm:text-right">Growth: {pct(compareMode==="all"?data.ytd.growth:data.ytd.deviceGrowth)}</span></div></div></section>
  {compareMode==="device"&&<section className={card}><div><h2 className="font-black">Compare Device per LOB</h2><p className="mt-1 text-sm text-slate-500">Per bulan: iPhone, iPad, Mac, Apple Watch, dan AirPods dibandingkan 2025 vs 2026.</p></div><div className="mt-4 space-y-4">{data.compare.map(r=><div key={r.month} className="overflow-hidden rounded-xl border"><div className="flex items-center justify-between bg-slate-50 px-3 py-2.5 dark:bg-slate-900"><b>{monthShort(r.month)}</b><span className="text-xs font-bold text-slate-400">Device {money.format(r.device2025)} → {r.started?money.format(r.device2026||0):"—"}</span></div><div className="overflow-x-auto"><table className="min-w-[650px] w-full text-sm"><thead><tr className="border-b text-slate-400"><th className="p-2 text-left">LOB</th><th className="text-right">2025</th><th className="text-right">2026</th><th className="text-right">Selisih</th><th className="text-right">Growth</th></tr></thead><tbody>{r.lobs.filter(x=>x.lob!=="Other Device"||x.amount2025>0||(x.amount2026||0)>0).map(x=><tr key={x.lob} className="border-b last:border-b-0"><td className="p-2 font-bold">{x.lob}</td><td className="text-right">{money.format(x.amount2025)}</td><td className="text-right">{r.started?money.format(x.amount2026||0):"—"}</td><td className="text-right">{r.started?money.format(x.diff||0):"—"}</td><td className="text-right">{r.started?pct(x.growth):"Belum berjalan"}</td></tr>)}</tbody></table></div></div>)}</div></section>}
 </>}</div>
}
