"use client";

import {useEffect,useMemo,useState} from "react";

type FilterMode="week"|"month"|"range";
type Tot={qty:number;value:number};
type Detail={name:string;article:string;qty:number;value:number};
type Brand={code:string;name:string;qty:number;value:number;details:Detail[]};
type Supplier={supplier:string;qty:number;value:number;brands:Brand[];staff:Array<{name:string;qty:number;value:number}>};
type Payload={periodLabel:string;week:string;month:string;from:string;to:string;availableWeeks:string[];availableMonths:string[];thirdParty:{suppliers:Supplier[];total:Tot}};
type TargetMap=Record<string,number>;

const SUPPLIERS=["Hastag","Dino","IGA","IBacks","Handal","Omega","Torras"] as const;
const num=new Intl.NumberFormat("id-ID");
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const norm=(v:unknown)=>String(v??"").trim().toLocaleLowerCase("id-ID");
const monthName=(v:string)=>{if(!/^\d{4}-\d{2}$/.test(v))return v;const[y,m]=v.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))};
const panel="m238-soft-card rounded-2xl border";
const sub="m238-subcard rounded-2xl border";
const status=(ach:number,target:number)=>{const p=target?ach/target*100:0;return p>=100?"Achieve":p>=80?"Need Push":"Critical"};
const statusClass=(s:string)=>s==="Achieve"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300":s==="Need Push"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300":"bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300";

export default function ProductFocus3PPFinalPage(){
 const now=today(),initialMonth=now.slice(0,7);
 const[filterMode,setFilterMode]=useState<FilterMode>("week");
 const[week,setWeek]=useState(""),[month,setMonth]=useState(initialMonth),[from,setFrom]=useState(`${initialMonth}-01`),[to,setTo]=useState(now);
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[activeSupplier,setActiveSupplier]=useState<string>("Hastag");
 const[targetOpen,setTargetOpen]=useState(false),[targets,setTargets]=useState<TargetMap>({}),[draft,setDraft]=useState<TargetMap>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState("");

 useEffect(()=>{let alive=true;const q=new URLSearchParams({mode:filterMode});if(filterMode==="week"&&week)q.set("week",week);if(filterMode==="month")q.set("month",month);if(filterMode==="range"){q.set("from",from);q.set("to",to)}setLoading(true);fetch(`/api/product-focus-3pp?${q.toString()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!alive)return;setData(j);if(filterMode==="week"&&!week&&j.week)setWeek(j.week);if(filterMode==="month"&&j.month)setMonth(j.month)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[filterMode,week,month,from,to]);

 const targetScope=filterMode==="week"?"weekly":filterMode==="month"?"monthly":"range";
 const activePeriod=filterMode==="week"?(data?.week||week):filterMode==="month"?month:`${from}|${to}`;
 useEffect(()=>{if(!activePeriod)return;let alive=true;fetch(`/api/manual-target?scope=${targetScope}&period=${encodeURIComponent(activePeriod)}&group=product-focus`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!alive||j.error)return;const next:TargetMap={};for(const s of SUPPLIERS){const raw=j.targets?.[s]?.target??(s==="IGA"?j.targets?.Iga?.target:undefined);next[s]=Number(raw||0)}setTargets(next);setDraft(next)}).catch(()=>{});return()=>{alive=false}},[targetScope,activePeriod]);

 const supplierMap=useMemo(()=>new Map((data?.thirdParty.suppliers||[]).map(s=>[norm(s.supplier),s])),[data]);
 const supplierRows=useMemo(()=>SUPPLIERS.map(name=>{const src=supplierMap.get(norm(name));return src?{...src,supplier:name}:{supplier:name,qty:0,value:0,brands:[],staff:[]}}),[supplierMap]);
 const active=useMemo(()=>supplierRows.find(s=>norm(s.supplier)===norm(activeSupplier))||supplierRows[0],[supplierRows,activeSupplier]);
 const staffRows=useMemo(()=>[...(active?.staff||[])].sort((a,b)=>b.qty-a.qty||a.name.localeCompare(b.name)),[active]);
 const totalTarget=SUPPLIERS.reduce((a,s)=>a+(targets[s]||0),0),totalAch=supplierRows.reduce((a,s)=>a+Number(s.qty||0),0),totalValue=supplierRows.reduce((a,s)=>a+Number(s.value||0),0);
 const overall=totalTarget?totalAch/totalTarget*100:0,totalGap=Math.max(0,totalTarget-totalAch);
 const activeTarget=targets[active?.supplier||""]||0,activeAch=Number(active?.qty||0),activePc=activeTarget?activeAch/activeTarget*100:0,activeGap=activeAch-activeTarget,activeStatus=status(activeAch,activeTarget);
 const noActiveData=!active||(!active.qty&&!active.value&&!active.staff.length&&!active.brands.length);

 const saveTarget=async()=>{setSaving(true);setMessage("");try{const body:TargetMap={};for(const s of SUPPLIERS)body[s]=Math.max(0,Math.floor(Number(draft[s]||0)));const r=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:targetScope,period:activePeriod,group:"product-focus",targets:body})}),j=await r.json();if(!r.ok){setMessage(j.error||"Gagal menyimpan target");return}setTargets({...body});setTargetOpen(false)}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setSaving(false)}};

 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Target Fokus</p><h2 className="mt-1 text-3xl font-black">Product Fokus 3PP</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Target supplier berbasis Qty, Value tetap actual sales contribution.</p></div>
  <section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{(["week","month","range"] as FilterMode[]).map(f=><button key={f} onClick={()=>setFilterMode(f)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filterMode===f?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"}`}>{f==="week"?"Week":f==="month"?"Bulan":"Range Tanggal"}</button>)}</div><button onClick={()=>{setDraft({...targets});setMessage("");setTargetOpen(true)}} className="rounded-xl border px-4 py-2 text-sm font-black">Set Target 3PP</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{filterMode==="week"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Apple Week</span><select value={week} onChange={e=>setWeek(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableWeeks||[]).map(w=><option key={w} value={w}>{w}</option>)}</select></label>}{filterMode==="month"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Filter Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableMonths||[]).map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label>}{filterMode==="range"&&<><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Dari Tanggal</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Sampai Tanggal</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label></>}</div><p className="mt-3 text-xs text-slate-500">Periode aktif: <b>{data?.periodLabel||activePeriod||"-"}</b></p></section>

  {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat Product Fokus 3PP…</div>:!data?<div className={`${panel} p-8 text-center text-slate-500`}>Data belum tersedia.</div>:<>
   <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{supplierRows.map(s=>{const t=targets[s.supplier]||0,a=Number(s.qty||0),pc=t?a/t*100:0,g=a-t,st=status(a,t);return <div key={s.supplier} className={`${sub} p-4`}><div className="flex items-center justify-between gap-2"><p className="font-black">{s.supplier}</p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass(st)}`}>{st}</span></div><div className="mt-3 grid grid-cols-4 gap-2 text-xs"><div><p className="text-slate-400">Target</p><p className="mt-1 font-black">{num.format(t)}</p></div><div><p className="text-slate-400">Ach</p><p className="mt-1 font-black">{num.format(a)}</p></div><div><p className="text-slate-400">Ach %</p><p className="mt-1 font-black">{pct(pc)}</p></div><div><p className="text-slate-400">Gap</p><p className="mt-1 font-black">{g>0?`+${num.format(g)}`:num.format(g)}</p></div></div><p className="mt-3 text-xs text-slate-500">{money.format(s.value)}</p></div>})}</section>
   <section className={`${panel} p-4`}><div className="flex flex-wrap gap-x-7 gap-y-2 text-sm"><span><b>Target:</b> {num.format(totalTarget)} Unit</span><span><b>Achievement:</b> {num.format(totalAch)} Unit</span><span><b>Overall:</b> {pct(overall)}</span><span><b>Gap:</b> {num.format(totalGap)} Unit</span><span><b>Total Value:</b> {money.format(totalValue)}</span></div></section>
   <section className={`${panel} p-3`}><div className="overflow-x-auto"><div className="flex min-w-max gap-2">{supplierRows.map(s=><button key={s.supplier} onClick={()=>setActiveSupplier(s.supplier)} className={`rounded-xl border px-4 py-2 text-sm font-black ${norm(activeSupplier)===norm(s.supplier)?"border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/25 dark:text-blue-300":"bg-white text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{s.supplier}</button>)}</div></div></section>
   <section key={`summary-${active?.supplier}`} className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-slate-400">Supplier Summary</p><h3 className="mt-1 text-xl font-black">{active?.supplier}</h3></div><div className="flex flex-wrap gap-x-6 gap-y-2 text-sm"><span><b>Target:</b> {num.format(activeTarget)}</span><span><b>Ach:</b> {num.format(activeAch)}</span><span><b>Ach %:</b> {pct(activePc)}</span><span><b>Gap:</b> {activeGap>0?`+${num.format(activeGap)}`:num.format(activeGap)}</span><span><b>Value:</b> {money.format(active?.value||0)}</span><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass(activeStatus)}`}>{activeStatus}</span></div></div></section>

   {noActiveData?<section key={`empty-${active?.supplier}`} className={`${panel} p-8 text-center text-slate-500`}>Belum ada penjualan {active?.supplier} pada periode ini</section>:<>
    <section key={`staff-${active?.supplier}`} className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Penjualan Staff • {active?.supplier}</h3></div><div className="overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead><tr><th className="px-3 py-3 text-center">#</th><th className="px-4 py-3 text-left">Staff</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3 text-right">Contribution %</th></tr></thead><tbody>{staffRows.map((r,i)=><tr key={`${active?.supplier}-${r.name}`} className="border-t"><td className="px-3 py-3 text-center font-bold">{i+1}</td><td className="px-4 py-3 font-bold">{r.name}</td><td className="px-3 py-3 text-right font-black">{num.format(r.qty)}</td><td className="px-3 py-3 text-right">{money.format(r.value)}</td><td className="px-3 py-3 text-right">{pct(activeAch?r.qty/activeAch*100:0)}</td></tr>)}</tbody></table></div></section>
    <section key={`detail-${active?.supplier}`} className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Detail Product • {active?.supplier}</h3><p className="mt-1 text-sm text-slate-500">Hanya product supplier aktif, dikelompokkan berdasarkan prefix / brand existing.</p></div><div className="divide-y">{active?.brands.map(b=>{const top=b.details.reduce((m,d)=>Math.max(m,Number(d.qty||0)),0);return <div key={`${active.supplier}-${b.code}-${b.name}`} className="p-4"><div><p className="font-black">{b.code} • {b.name}</p><p className="mt-1 text-xs text-slate-500">{num.format(b.qty)} qty • {money.format(b.value)}</p></div><div className="mt-3 overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead><tr><th className="py-2 text-left">Article</th><th className="py-2 text-left">Product</th><th className="py-2 text-right">Qty</th><th className="py-2 text-right">Value</th><th className="py-2 text-right">Contribution</th></tr></thead><tbody>{b.details.map((d,i)=><tr key={`${active.supplier}-${b.code}-${d.article}-${d.name}-${i}`} className="border-t"><td className="py-2 pr-3 font-mono text-xs">{d.article||"-"}</td><td className="py-2 pr-3 font-bold">{d.name}{top>0&&d.qty===top&&<span className="ml-2 rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">Top Selling</span>}</td><td className="px-3 py-2 text-right font-black">{num.format(d.qty)}</td><td className="px-3 py-2 text-right">{money.format(d.value)}</td><td className="px-3 py-2 text-right">{pct(activeAch?d.qty/activeAch*100:0)}</td></tr>)}</tbody></table></div></div>})}</div></section>
   </>}
  </>}

  {targetOpen&&<div className="fixed inset-0 z-[90] grid place-items-center bg-black/35 p-4" onMouseDown={e=>{if(e.currentTarget===e.target)setTargetOpen(false)}}><div className={`${panel} w-full max-w-xl bg-white p-5 shadow-2xl dark:bg-slate-950`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">Set Target 3PP</p><h3 className="mt-1 text-xl font-black">{data?.periodLabel||activePeriod||"Periode aktif"}</h3></div><button onClick={()=>setTargetOpen(false)} className="rounded-lg border px-3 py-1.5 text-sm font-black">✕</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{SUPPLIERS.map(s=><label key={s} className="rounded-xl border p-3"><span className="text-xs font-black text-slate-500">{s}</span><input inputMode="numeric" value={draft[s]||""} onChange={e=>setDraft(v=>({...v,[s]:Math.max(0,Number(e.target.value.replace(/[^0-9]/g,""))||0)}))} placeholder="0" className="mt-2 h-10 w-full rounded-lg border px-3 text-right font-black dark:bg-slate-900"/></label>)}</div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900"><b>Total Target:</b> {num.format(SUPPLIERS.reduce((a,s)=>a+Number(draft[s]||0),0))} Unit</div>{message&&<p className="mt-3 text-sm font-bold text-rose-600">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setTargetOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-black">Batal</button><button disabled={saving} onClick={saveTarget} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{saving?"Menyimpan...":"Simpan Target"}</button></div></div></div>}
 </div>;
}
