"use client";

import {useEffect,useMemo,useState} from "react";

type FilterMode="week"|"month"|"range";
type Tot={qty:number;value:number};
type BrandDetail={name:string;article?:string;qty:number;value:number};
type Supplier={supplier:string;qty:number;value:number;brands:Array<{code:string;name:string;qty:number;value:number;details:BrandDetail[]}>;staff:Array<{name:string;qty:number;value:number}>};
type Payload={periodLabel:string;week:string;month:string;from:string;to:string;availableWeeks:string[];availableMonths:string[];thirdParty:{suppliers:Supplier[];total:Tot}};
type TargetMap=Record<string,number>;

const SUPPLIERS=["Hastag","Dino","IGA","IBacks","Handal","Omega","Torras"] as const;
const num=new Intl.NumberFormat("id-ID");
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const monthName=(v:string)=>{if(!/^\d{4}-\d{2}$/.test(v))return v;const[y,m]=v.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))};
const panel="m238-soft-card rounded-2xl border";
const sub="m238-subcard rounded-2xl border";
const status=(ach:number,target:number)=>{const p=target?ach/target*100:0;return p>=100?"Achieve":p>=80?"Need Push":"Critical"};
const statusClass=(s:string)=>s==="Achieve"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300":s==="Need Push"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300":"bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300";

export default function ProductFocus3PPPage(){
 const now=today(),initialMonth=now.slice(0,7);
 const[filterMode,setFilterMode]=useState<FilterMode>("week"),[week,setWeek]=useState(""),[month,setMonth]=useState(initialMonth),[from,setFrom]=useState(`${initialMonth}-01`),[to,setTo]=useState(now);
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[activeSupplier,setActiveSupplier]=useState<string>("Hastag");
 const[targetOpen,setTargetOpen]=useState(false),[targets,setTargets]=useState<TargetMap>({}),[draft,setDraft]=useState<TargetMap>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const q=new URLSearchParams({mode:filterMode});if(filterMode==="week"&&week)q.set("week",week);if(filterMode==="month")q.set("month",month);if(filterMode==="range"){q.set("from",from);q.set("to",to)}setLoading(true);fetch(`/api/target-focus?${q.toString()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{setData(j);if(!week&&j.week)setWeek(j.week);if(j.month&&!month)setMonth(j.month)}).finally(()=>setLoading(false))},[filterMode,week,month,from,to]);
 const targetScope=filterMode==="week"?"weekly":filterMode==="month"?"monthly":"range";
 const targetPeriod=filterMode==="week"?(data?.week||week):filterMode==="month"?month:`${from}|${to}`;
 useEffect(()=>{if(!targetPeriod)return;let alive=true;fetch(`/api/manual-target?scope=${targetScope}&period=${encodeURIComponent(targetPeriod)}&group=product-focus`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!alive||j.error)return;const next:TargetMap={};for(const s of SUPPLIERS)next[s]=Number(j.targets?.[s]?.target||0);setTargets(next);setDraft(next)}).catch(()=>{});return()=>{alive=false}},[targetScope,targetPeriod]);
 const supplierMap=useMemo(()=>new Map((data?.thirdParty.suppliers||[]).map(s=>[s.supplier.toUpperCase(),s])),[data]);
 const supplierRows=useMemo(()=>SUPPLIERS.map(name=>supplierMap.get(name.toUpperCase())||{supplier:name,qty:0,value:0,brands:[],staff:[]}),[supplierMap]);
 const active=supplierRows.find(s=>s.supplier===activeSupplier)||supplierRows[0];
 const totalTarget=SUPPLIERS.reduce((a,s)=>a+(targets[s]||0),0),totalAch=supplierRows.reduce((a,s)=>a+Number(s.qty||0),0),totalValue=supplierRows.reduce((a,s)=>a+Number(s.value||0),0),overall=totalTarget?totalAch/totalTarget*100:0,gap=Math.max(0,totalTarget-totalAch);
 const staffRows=useMemo(()=>[...(active?.staff||[])].sort((a,b)=>b.qty-a.qty||a.name.localeCompare(b.name)),[active]);
 const detailRows=useMemo(()=>{const rows=(active?.brands||[]).flatMap(b=>b.details.map(d=>({...d,brand:b.name,code:b.code})));return rows.sort((a,b)=>b.qty-a.qty||a.name.localeCompare(b.name))},[active]);
 const topQty=detailRows.reduce((m,r)=>Math.max(m,Number(r.qty||0)),0);
 const saveTarget=async()=>{setSaving(true);setMessage("");try{const body:TargetMap={};for(const s of SUPPLIERS)body[s]=Math.max(0,Math.floor(Number(draft[s]||0)));const r=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:targetScope,period:targetPeriod,group:"product-focus",targets:body})}),j=await r.json();if(!r.ok){setMessage(j.error||"Gagal menyimpan target");return}setTargets({...body});setTargetOpen(false)}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setSaving(false)}};
 return <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Target Fokus</p><h2 className="mt-1 text-3xl font-black">Product Fokus 3PP</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Target supplier berbasis Qty, Value tetap actual sales contribution.</p></div>
 <section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{(["week","month","range"] as FilterMode[]).map(f=><button key={f} onClick={()=>setFilterMode(f)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filterMode===f?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"}`}>{f==="week"?"Week":f==="month"?"Bulan":"Range Tanggal"}</button>)}</div><button onClick={()=>{setDraft({...targets});setMessage("");setTargetOpen(true)}} className="rounded-xl border px-4 py-2 text-sm font-black">Set Target 3PP</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{filterMode==="week"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Apple Week</span><select value={week} onChange={e=>setWeek(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableWeeks||[]).map(w=><option key={w} value={w}>{w}</option>)}</select></label>}{filterMode==="month"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Filter Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableMonths||[]).map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label>}{filterMode==="range"&&<><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Dari Tanggal</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Sampai Tanggal</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label></>}</div><p className="mt-3 text-xs text-slate-500">Periode aktif: <b>{data?.periodLabel||"-"}</b></p></section>
 {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat Product Fokus 3PP…</div>:!data?<div className={`${panel} p-8 text-center text-slate-500`}>Data belum tersedia.</div>:<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{supplierRows.map(s=>{const t=targets[s.supplier]||0,a=Number(s.qty||0),pc=t?a/t*100:0,g=a-t;return <button key={s.supplier} onClick={()=>setActiveSupplier(s.supplier)} className={`${sub} p-4 text-left ${activeSupplier===s.supplier?"border-blue-500":""}`}><div className="flex items-center justify-between gap-2"><p className="font-black">{s.supplier}</p><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass(status(a,t))}`}>{status(a,t)}</span></div><div className="mt-3 grid grid-cols-4 gap-2 text-xs"><div><p className="text-slate-400">Target</p><p className="mt-1 font-black">{num.format(t)}</p></div><div><p className="text-slate-400">Ach</p><p className="mt-1 font-black">{num.format(a)}</p></div><div><p className="text-slate-400">Ach %</p><p className="mt-1 font-black">{pct(pc)}</p></div><div><p className="text-slate-400">Gap</p><p className="mt-1 font-black">{g>0?`+${num.format(g)}`:num.format(g)}</p></div></div><p className="mt-3 text-xs text-slate-500">{money.format(s.value)}</p></button>})}</section><section className={`${panel} p-4`}><div className="flex flex-wrap gap-x-7 gap-y-2 text-sm"><span><b>Target:</b> {num.format(totalTarget)} Unit</span><span><b>Achievement:</b> {num.format(totalAch)} Unit</span><span><b>Overall:</b> {pct(overall)}</span><span><b>Gap:</b> {num.format(gap)} Unit</span><span><b>Total Value:</b> {money.format(totalValue)}</span></div></section>
 <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Supplier Performance</h3></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Supplier</th><th className="px-3 py-3 text-right">Target</th><th className="px-3 py-3 text-right">Ach Qty</th><th className="px-3 py-3 text-right">Ach %</th><th className="px-3 py-3 text-right">Gap</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3 text-right">Status</th></tr></thead><tbody>{supplierRows.map(s=>{const t=targets[s.supplier]||0,a=Number(s.qty||0),pc=t?a/t*100:0,g=a-t,st=status(a,t);return <tr key={s.supplier} className="border-t"><td className="px-4 py-3 font-bold">{s.supplier}</td><td className="px-3 py-3 text-right">{num.format(t)}</td><td className="px-3 py-3 text-right font-black">{num.format(a)}</td><td className="px-3 py-3 text-right">{pct(pc)}</td><td className="px-3 py-3 text-right">{g>0?`+${num.format(g)}`:num.format(g)}</td><td className="px-3 py-3 text-right">{money.format(s.value)}</td><td className="px-3 py-3 text-right"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${statusClass(st)}`}>{st}</span></td></tr>})}</tbody></table></div></section>
 <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Penjualan Staff • {active?.supplier}</h3></div><div className="overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead><tr><th className="px-3 py-3 text-center">#</th><th className="px-4 py-3 text-left">Staff</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3 text-right">Contribution %</th></tr></thead><tbody>{staffRows.length?staffRows.map((r,i)=><tr key={r.name} className="border-t"><td className="px-3 py-3 text-center font-bold">{i+1}</td><td className="px-4 py-3 font-bold">{r.name}</td><td className="px-3 py-3 text-right font-black">{num.format(r.qty)}</td><td className="px-3 py-3 text-right">{money.format(r.value)}</td><td className="px-3 py-3 text-right">{pct(active?.qty?r.qty/active.qty*100:0)}</td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-400">Belum ada penjualan.</td></tr>}</tbody></table></div></section>
 <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Detail Product • {active?.supplier}</h3><p className="mt-1 text-sm text-slate-500">Mapping supplier + prefix article + brand name mengikuti logic existing.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Article</th><th className="px-4 py-3 text-left">Product</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3 text-right">Contribution Qty %</th></tr></thead><tbody>{detailRows.length?detailRows.map((d,i)=><tr key={`${d.article||""}-${d.name}-${i}`} className="border-t"><td className="px-4 py-3 font-mono text-xs">{d.article||"-"}</td><td className="px-4 py-3 font-bold">{d.name}{topQty>0&&d.qty===topQty&&<span className="ml-2 rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">Top Selling</span>}</td><td className="px-3 py-3 text-right font-black">{num.format(d.qty)}</td><td className="px-3 py-3 text-right">{money.format(d.value)}</td><td className="px-3 py-3 text-right">{pct(active?.qty?d.qty/active.qty*100:0)}</td></tr>):<tr><td colSpan={5} className="p-8 text-center text-slate-400">Belum ada detail product.</td></tr>}</tbody></table></div></section></>}
 {targetOpen&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/35 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setTargetOpen(false)}}><div className="m238-soft-card w-full max-w-lg rounded-2xl border bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Set Target 3PP</p><h3 className="mt-1 text-xl font-black">{data?.periodLabel||targetPeriod}</h3></div><button onClick={()=>setTargetOpen(false)} className="rounded-lg border px-3 py-1.5 text-sm font-bold">Tutup</button></div><div className="mt-4 space-y-3">{SUPPLIERS.map(s=><label key={s} className="flex items-center justify-between gap-4"><span className="font-bold">{s}</span><input type="number" min="0" step="1" value={draft[s]??0} onChange={e=>setDraft(v=>({...v,[s]:Math.max(0,Math.floor(Number(e.target.value)||0))}))} className="h-10 w-36 rounded-xl border px-3 text-right font-black"/></label>)}</div><div className="mt-4 border-t pt-4 text-sm"><b>Total Target:</b> {num.format(SUPPLIERS.reduce((a,s)=>a+(draft[s]||0),0))} Unit</div>{message&&<p className="mt-3 text-sm font-bold text-rose-600">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setTargetOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button disabled={saving} onClick={saveTarget} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{saving?"Menyimpan…":"Simpan Target"}</button></div></div></div>}
 </div>
}
