"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useDeferredValue,useEffect,useMemo,useRef,useState} from "react";
import {Check,ChevronDown,Clipboard,Search,SlidersHorizontal,Tag,X} from "lucide-react";
import type {AccessoryComparison,AccessoryParseResult,AccessoryPriceProduct} from "@/lib/promo-board-accessory";

type Product=AccessoryPriceProduct&{brandCode?:string};
type Audit={totalSku:number;totalBrand:number;totalSupplier:number;brandChanged:number;supplierChanged:number;unmappedSupplier:number;duplicateSku:number;masterConflicts:string[];mappingProblems:string[]};
type Stored=Omit<AccessoryParseResult,"products">&{products:Product[];id?:string;uploadedAt?:string;audit?:Audit};
type History={id?:string;uploadedAt?:string;fileName:string;priceListDate:string|null;totalRows:number;totalSku:number;totalBrand:number;totalCategory:number;warnings:string[]};
type ApiResponse={active?:Stored|null;history?:History[];comparison?:AccessoryComparison;audit?:Audit|null;error?:string};
type PreviewResponse={preview?:AccessoryParseResult;comparison?:AccessoryComparison;identicalToActive?:boolean;error?:string;message?:string};
type PickerKind="supplier"|"brand"|"category";
type SortKind="name-asc"|"name-desc"|"price-asc"|"price-desc"|"brand";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const norm=(v:unknown)=>String(v??"").trim().toLowerCase();
const dateLabel=(v:string|null|undefined)=>{if(!v)return"-";const d=new Date(`${v}T00:00:00+07:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(d)};
const priceMeta=(p:Product)=>{const candidates=[p.referenceSrp,p.currentSrpCash].filter(v=>Number.isFinite(v)&&v>0);const normal=candidates.length?Math.max(...candidates):p.activePrice;const promo=p.repricingCash>0&&normal>0&&p.repricingCash<normal?p.repricingCash:0;const active=promo||p.activePrice||normal;const saving=promo?normal-promo:0;const discount=promo&&normal?Math.round((saving/normal)*100):0;return{normal,promo,active,saving,discount,hasPromo:Boolean(promo&&saving>0)}};
const changeLabel=(type:string)=>({NEW_SKU:"PRODUK BARU",REMOVED_SKU:"PRODUK DIHAPUS",PRICE_DOWN:"HARGA TURUN",PRICE_UP:"HARGA NAIK",REMARKS_CHANGED:"REMARKS BERUBAH",BR_ZOUT_CHANGED:"BR / ZOUT BERUBAH"}[type]||type);

function CopyButton({value}:{value:string}){const[ok,setOk]=useState(false);return <button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#0b63f6] px-4 text-xs font-black text-white" onClick={async()=>{try{await navigator.clipboard.writeText(value);setOk(true);setTimeout(()=>setOk(false),1200)}catch{setOk(false)}}}>{ok?<Check className="size-4"/>:<Clipboard className="size-4"/>}{ok?"Tersalin":"Copy SAP"}</button>}
function Detail({item,onClose}:{item:Product;onClose:()=>void}){const pm=priceMeta(item);useEffect(()=>{const before=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=before}},[]);return <div className="fixed inset-0 z-[10060] flex items-end justify-center bg-slate-950/45 backdrop-blur-[2px]" onClick={onClose}><div className="max-h-[88dvh] w-full overflow-y-auto rounded-t-[30px] bg-white px-5 pb-[calc(28px+env(safe-area-inset-bottom))] pt-3 shadow-2xl sm:max-w-lg sm:rounded-[30px]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-4 h-1.5 w-11 rounded-full bg-[#dfe6ef]"/><div className="flex justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-[11px] font-black uppercase tracking-[.12em] text-[#0b63f6]">{item.brand}</p>{pm.hasPromo?<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">-{pm.discount}% PROMO</span>:null}</div><h3 className="mt-1 text-lg font-black leading-snug text-[#172238]">{item.sapDescription}</h3>{pm.hasPromo?<div className="mt-4"><p className="text-xs font-bold text-[#8a98aa] line-through">{money.format(pm.normal)}</p><p className="text-[28px] font-black tracking-[-.03em] text-[#0b63f6]">{money.format(pm.promo)}</p><p className="mt-1 text-xs font-black text-emerald-600">Hemat {money.format(pm.saving)} ({pm.discount}%)</p></div>:<p className="mt-4 text-[28px] font-black tracking-[-.03em] text-[#172238]">{pm.active?money.format(pm.active):"-"}</p>}</div><button onClick={onClose} className="grid size-10 shrink-0 place-items-center rounded-full bg-[#f1f5f9]"><X className="size-5"/></button></div><div className="mt-5 border-t border-[#e7edf4] pt-4"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#63748b]">SAP Article</p><div className="mt-1 flex items-center justify-between gap-3"><p className="break-all text-sm font-black text-[#172238]">{item.sapArticle}</p><CopyButton value={item.sapArticle}/></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f6f8fb] p-3"><p className="text-[10px] font-black uppercase text-[#63748b]">Category</p><p className="mt-1 text-sm font-bold">{item.category||"-"}</p></div><div className="rounded-2xl bg-[#f6f8fb] p-3"><p className="text-[10px] font-black uppercase text-[#63748b]">Supplier</p><p className="mt-1 text-sm font-bold">{item.supplier||"Supplier belum ter-mapping"}</p></div></div>{pm.hasPromo&&item.remarks?<div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-3"><p className="text-[10px] font-black uppercase text-emerald-700">Promo / Remarks</p><p className="mt-1 text-xs font-semibold leading-5 text-emerald-900">{item.remarks}</p>{item.brZout?<p className="mt-2 text-[11px] font-bold text-emerald-700">BR / ZOUT: {item.brZout}</p>:null}</div>:null}</div></div></div>}

export default function PromoBoardAccessories({mode="catalog"}:{mode?:"catalog"|"changes"|"history"}){
 const fileRef=useRef<HTMLInputElement>(null);const[active,setActive]=useState<Stored|null>(null),[history,setHistory]=useState<History[]>([]),[comparison,setComparison]=useState<AccessoryComparison|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const[preview,setPreview]=useState<AccessoryParseResult|null>(null),[selectedFile,setSelectedFile]=useState<File|null>(null),[identical,setIdentical]=useState(false),[busy,setBusy]=useState(false);const[query,setQuery]=useState(""),[supplier,setSupplier]=useState(""),[brand,setBrand]=useState(""),[category,setCategory]=useState(""),[quickCategory,setQuickCategory]=useState(""),[sort,setSort]=useState<SortKind>("name-asc"),[filterOpen,setFilterOpen]=useState(false),[sortOpen,setSortOpen]=useState(false),[picker,setPicker]=useState<PickerKind|null>(null),[pickerQuery,setPickerQuery]=useState(""),[visible,setVisible]=useState(60),[detail,setDetail]=useState<Product|null>(null);const deferredQuery=useDeferredValue(query.trim());
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/promo-board-accessories",{cache:"no-store"}),j=await r.json() as ApiResponse;if(!r.ok)throw new Error(j.error||"Pricelist gagal dimuat.");setActive(j.active||null);setHistory(j.history||[]);setComparison(j.comparison||null)}catch(e){setError(e instanceof Error?e.message:"Pricelist gagal dimuat.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const upload=async(file:File)=>{setBusy(true);setError("");setSelectedFile(file);try{const form=new FormData();form.append("file",file);form.append("mode","preview");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok||!j.preview)throw new Error(j.error||"Pricelist ACC gagal dianalisa");setPreview(j.preview);setIdentical(Boolean(j.identicalToActive))}catch(e){setPreview(null);setSelectedFile(null);setError(e instanceof Error?e.message:"Pricelist ACC gagal dianalisa")}finally{setBusy(false)}};
 const activate=async()=>{if(!selectedFile||!preview||preview.blockingErrors||identical)return;setBusy(true);try{const form=new FormData();form.append("file",selectedFile);form.append("mode","activate");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok)throw new Error(j.error||"Aktivasi gagal");setPreview(null);setSelectedFile(null);await load()}catch(e){setError(e instanceof Error?e.message:"Aktivasi gagal")}finally{setBusy(false)}};
 const products=useMemo(()=>active?.products||[],[active]);const quickCategories=useMemo(()=>[...new Set(products.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b)).slice(0,18),[products]);const suppliers=useMemo(()=>[...new Set(products.map(p=>p.supplier).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products]);const brands=useMemo(()=>[...new Set(products.filter(p=>!supplier||p.supplier===supplier).map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products,supplier]);const categories=useMemo(()=>[...new Set(products.filter(p=>(!supplier||p.supplier===supplier)&&(!brand||p.brand===brand)).map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products,supplier,brand]);
 const filtered=useMemo(()=>{const q=norm(deferredQuery);const out=products.filter(p=>(!supplier||p.supplier===supplier)&&(!brand||p.brand===brand)&&(!category||p.category===category)&&(!quickCategory||p.category===quickCategory)&&(!q||[p.sapArticle,p.sapDescription,p.brand,p.brandCode,p.category].some(v=>norm(v).includes(q))));return [...out].sort((a,b)=>{if(q){const ae=norm(a.sapArticle)===q,be=norm(b.sapArticle)===q;if(ae!==be)return ae?-1:1}if(sort==="name-desc")return b.sapDescription.localeCompare(a.sapDescription);if(sort==="price-asc")return a.activePrice-b.activePrice;if(sort==="price-desc")return b.activePrice-a.activePrice;if(sort==="brand")return a.brand.localeCompare(b.brand);return a.sapDescription.localeCompare(b.sapDescription)})},[products,supplier,brand,category,quickCategory,deferredQuery,sort]);useEffect(()=>setVisible(60),[deferredQuery,supplier,brand,category,quickCategory,sort]);
 const filterCount=[supplier,brand,category,quickCategory].filter(Boolean).length;const reset=()=>{setSupplier("");setBrand("");setCategory("");setQuickCategory("")};const pickerItems=picker==="supplier"?suppliers:picker==="brand"?brands:categories;const pickerValue=picker==="supplier"?supplier:picker==="brand"?brand:category;const pickerLabel=picker==="supplier"?"Supplier":picker==="brand"?"Brand":"Category";const shownPickerItems=pickerItems.filter(x=>norm(x).includes(norm(pickerQuery)));const choose=(value:string)=>{if(picker==="supplier"){setSupplier(value);setBrand("");setCategory("")}else if(picker==="brand"){setBrand(value);setCategory("")}else setCategory(value);setPicker(null);setPickerQuery("")};
 if(mode==="changes")return <section className="mt-4 space-y-2">{loading?<p className="p-6 text-center text-sm text-[#63748b]">Memuat perubahan Accessories...</p>:comparison?.changes.length?comparison.changes.slice(0,200).map((c,i)=>{const diff=Math.abs(c.afterPrice-c.beforePrice),pct=c.beforePrice>0?Math.round(diff/c.beforePrice*100):0;return <div key={`${c.type}-${c.sapArticle}-${i}`} className="rounded-2xl border border-[#dfe6ef] bg-white p-4 text-sm"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-black tracking-[.12em] text-[#0b63f6]">{changeLabel(c.type)}</span><b className="mt-1 block">{c.description}</b><p className="mt-1 text-xs text-[#63748b]">SAP {c.sapArticle}</p></div>{(c.type==="PRICE_DOWN"||c.type==="PRICE_UP")?<span className={`rounded-full px-2 py-1 text-[10px] font-black ${c.type==="PRICE_DOWN"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{c.type==="PRICE_DOWN"?"↓":"↑"} {money.format(diff)}{pct?` • ${pct}%`:""}</span>:null}</div>{(c.type==="PRICE_DOWN"||c.type==="PRICE_UP")?<p className="mt-3 font-black">{money.format(c.beforePrice)} → {money.format(c.afterPrice)}</p>:c.beforeText!==undefined||c.afterText!==undefined?<p className="mt-3 text-xs text-[#63748b]">{c.beforeText||"—"} → {c.afterText||"—"}</p>:null}</div>}) :<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-[#63748b]">Belum ada perubahan Accessories.</div>}</section>;
 if(mode==="history")return <section className="mt-4 space-y-2">{history.length?history.map(h=><div key={h.id||h.fileName} className="rounded-2xl border border-[#dfe6ef] bg-white p-4"><div className="flex justify-between gap-3"><div><b>{dateLabel(h.priceListDate)}</b><p className="text-xs text-[#63748b]">{h.fileName}</p></div><b>{h.totalSku} SKU</b></div></div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-[#63748b]">Belum ada riwayat Accessories.</div>}</section>;
 return <section className="-mx-4 mt-0 bg-[#eef3f9] pb-[calc(120px+env(safe-area-inset-bottom))] text-[#172238]">
  <input id="promo-acc-file-input" ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/>
  
  {error?<div className="mx-4 mb-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700">Pricelist gagal dimuat. <button onClick={()=>void load()} className="underline">Coba Lagi</button></div>:null}
  {preview?<div className="mx-4 mb-3 rounded-2xl border border-blue-200 bg-white p-4"><p className="text-xs font-black text-[#0b63f6]">PREVIEW UPDATE ACC</p><p className="mt-1 text-sm font-bold">{preview.fileName} · {preview.totalSku} SKU</p><div className="mt-3 flex gap-2"><button className="min-h-11 flex-1 rounded-xl border" onClick={()=>{setPreview(null);setSelectedFile(null)}}>Batal</button><button disabled={busy||identical||Boolean(preview.blockingErrors)} className="min-h-11 flex-1 rounded-xl bg-[#0b63f6] font-black text-white disabled:opacity-40" onClick={()=>void activate()}>Aktifkan</button></div></div>:null}
  <div className="sticky top-0 z-20 border-b border-[#dfe6ef] bg-white px-4 py-3">{active?.priceListDate?<div className="mb-2 flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0b63f6]">Accessories</p><p className="text-[10px] font-bold text-[#63748b]">Pricelist • Update {dateLabel(active.priceListDate)}</p></div>:null}<div className="relative"><Search className="absolute left-3 top-1/2 size-[17px] -translate-y-1/2 text-[#63748b]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari produk, brand, SAP..." className="h-12 w-full rounded-xl border border-[#dfe6ef] bg-[#f6f8fb] pl-10 pr-10 text-sm font-semibold outline-none focus:border-[#0b63f6]"/>{query?<button onClick={()=>setQuery("")} className="absolute right-2 top-1/2 grid size-9 -translate-y-1/2 place-items-center"><X className="size-4"/></button>:null}</div><div className="mt-2 flex gap-2 overflow-x-auto"><button onClick={()=>setFilterOpen(true)} className="shrink-0 rounded-full bg-[#0b63f6] px-3 py-2 text-xs font-black text-white">Filter{filterCount?` ${filterCount}`:""}</button><button onClick={()=>setFilterOpen(true)} className="shrink-0 rounded-full border border-[#dfe6ef] bg-white px-3 py-2 text-xs font-black">Supplier: {supplier||"Semua"}</button><button onClick={()=>setSortOpen(true)} className="shrink-0 rounded-full border border-[#dfe6ef] bg-white px-3 py-2 text-xs font-black">Urutkan</button></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setQuickCategory("")} className={`shrink-0 rounded-full px-3 py-2 text-xs font-black ${!quickCategory?"bg-[#172238] text-white":"bg-[#f1f5f9] text-[#63748b]"}`}>All</button>{quickCategories.map(c=><button key={c} onClick={()=>{setQuickCategory(c);setCategory("")}} className={`shrink-0 rounded-full px-3 py-2 text-xs font-black ${quickCategory===c?"bg-[#172238] text-white":"bg-[#f1f5f9] text-[#63748b]"}`}>{c}</button>)}</div></div>
  <div className="bg-white px-4 pb-5 pt-3"><div className="mb-2 flex justify-between"><p className="text-xs font-black text-[#63748b]">{active?`${filtered.length.toLocaleString("id-ID")} produk`:"Belum ada pricelist aktif"}</p>{active?.priceListDate?<p className="text-[10px] font-bold text-[#63748b]">Update {dateLabel(active.priceListDate)}</p>:null}</div>
  {loading?<div className="space-y-2.5">{[1,2,3,4].map(i=><div key={i} className="h-28 animate-pulse rounded-[20px] border border-[#e2e9f1] bg-[#f6f8fb]"/>)}</div>:!active?<div className="rounded-2xl border border-dashed p-8 text-center">Belum ada pricelist aktif.</div>:filtered.length?<div className="space-y-2.5">{filtered.slice(0,visible).map((p,i)=>{const pm=priceMeta(p);return <button key={`${p.sapArticle}-${i}`} onClick={()=>setDetail(p)} className="block w-full rounded-[20px] border border-[#e2e9f1] bg-white px-4 py-3.5 text-left shadow-[0_5px_18px_rgba(15,35,65,.05)]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#0b63f6]">{p.brand||"-"}</p>{pm.hasPromo?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700"><Tag className="size-3"/>-{pm.discount}%</span>:null}</div><h3 className="mt-1.5 text-[14px] font-black leading-snug text-[#172238]">{p.sapDescription}</h3></div><div className="shrink-0 text-right">{pm.hasPromo?<><p className="text-[10px] font-bold text-[#8a98aa] line-through">{money.format(pm.normal)}</p><p className="mt-0.5 whitespace-nowrap text-[16px] font-black text-[#0b63f6]">{money.format(pm.promo)}</p></>:<p className="whitespace-nowrap text-[16px] font-black">{pm.active?money.format(pm.active):"-"}</p>}</div></div>{pm.hasPromo?<p className="mt-2 text-[11px] font-black text-emerald-600">Hemat {money.format(pm.saving)}</p>:null}<div className="mt-2.5 flex items-center justify-between gap-2 border-t border-[#eef2f6] pt-2.5"><p className="min-w-0 truncate text-[11px] font-bold text-[#63748b]">SAP {p.sapArticle}</p>{p.category?<span className="shrink-0 rounded-full bg-[#f1f5f9] px-2.5 py-1 text-[10px] font-black text-[#63748b]">{p.category}</span>:null}</div></button>})}</div>:<div className="rounded-2xl border border-dashed p-8 text-center"><p className="font-black">Produk tidak ditemukan.</p><button onClick={()=>{setQuery("");reset()}} className="mt-3 rounded-xl bg-[#0b63f6] px-4 py-2 text-xs font-black text-white">Reset Filter</button></div>}
  {visible<filtered.length?<button onClick={()=>setVisible(v=>v+60)} className="mt-3 min-h-11 w-full rounded-xl border border-[#dfe6ef] bg-white text-sm font-black">Tampilkan 60 lagi</button>:null}</div>
  {filterOpen?<div className="fixed inset-0 z-[10050] flex items-end bg-slate-950/40" onClick={()=>setFilterOpen(false)}><div className="w-full rounded-t-[28px] bg-white p-5 pb-[calc(24px+env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-4 h-1.5 w-11 rounded-full bg-[#dfe6ef]"/><div className="flex justify-between"><div><h3 className="text-lg font-black">Filter Pricelist</h3><p className="text-xs text-[#63748b]">Supplier → Brand → Category</p></div><button onClick={()=>setFilterOpen(false)}><X/></button></div><div className="mt-5 space-y-3">{[["Supplier",supplier,"Semua Supplier","supplier"],["Brand",brand,"Semua Brand","brand"],["Category",category,"Semua Category","category"]].map(([label,value,empty,kind])=><div key={kind}><p className="mb-1 text-xs font-black text-[#63748b]">{label}</p><button onClick={()=>{setPickerQuery("");setPicker(kind as PickerKind)}} className="flex min-h-12 w-full items-center justify-between rounded-xl border border-[#dfe6ef] bg-[#f6f8fb] px-4 text-sm font-bold"><span>{value||empty}</span><ChevronDown className="size-4"/></button></div>)}</div><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={reset} className="min-h-12 rounded-xl border border-[#dfe6ef] font-black">Reset</button><button onClick={()=>setFilterOpen(false)} className="min-h-12 rounded-xl bg-[#0b63f6] font-black text-white">Tampilkan {filtered.length.toLocaleString("id-ID")}</button></div></div></div>:null}
  {picker?<div className="fixed inset-0 z-[10070] flex items-end bg-slate-950/40" onClick={()=>setPicker(null)}><div className="flex h-[min(86dvh,760px)] w-full flex-col rounded-t-[28px] bg-white p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h3 className="font-black">Pilih {pickerLabel}</h3><button onClick={()=>setPicker(null)}><X/></button></div><input autoFocus value={pickerQuery} onChange={e=>setPickerQuery(e.target.value)} placeholder={`Cari ${pickerLabel.toLowerCase()}...`} className="mt-3 h-12 rounded-xl border border-[#dfe6ef] bg-[#f6f8fb] px-4"/><div className="mt-2 overflow-y-auto"><button onClick={()=>choose("")} className="flex min-h-12 w-full justify-between border-b py-3 font-bold">Semua {pickerLabel}{!pickerValue?<Check className="size-4 text-[#0b63f6]"/>:null}</button>{shownPickerItems.map(x=><button key={x} onClick={()=>choose(x)} className="flex min-h-12 w-full justify-between border-b py-3 font-bold">{x}{pickerValue===x?<Check className="size-4 text-[#0b63f6]"/>:null}</button>)}</div></div></div>:null}
  {sortOpen?<div className="fixed inset-0 z-[10050] flex items-end bg-slate-950/40" onClick={()=>setSortOpen(false)}><div className="w-full rounded-t-[28px] bg-white p-5 pb-[calc(24px+env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><h3 className="mb-3 text-lg font-black">Urutkan</h3>{[["name-asc","Nama A–Z"],["name-desc","Nama Z–A"],["price-asc","Harga Terendah"],["price-desc","Harga Tertinggi"],["brand","Brand"]].map(([v,l])=><button key={v} onClick={()=>{setSort(v as SortKind);setSortOpen(false)}} className="flex min-h-12 w-full items-center justify-between border-b text-sm font-bold">{l}{sort===v?<Check className="size-4 text-[#0b63f6]"/>:null}</button>)}</div></div>:null}
  {detail?<Detail item={detail} onClose={()=>setDetail(null)}/>:null}
 </section>
}
