"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {Check,ChevronRight,Clipboard,Search,Upload,X} from "lucide-react";
import type {AccessoryComparison,AccessoryParseResult,AccessoryPriceProduct} from "@/lib/promo-board-accessory";

type Stored=AccessoryParseResult&{id?:string;uploadedAt?:string};
type History={id?:string;uploadedAt?:string;fileName:string;priceListDate:string|null;totalRows:number;totalSku:number;totalBrand:number;totalCategory:number;warnings:string[]};
type ApiResponse={active?:Stored|null;history?:History[];comparison?:AccessoryComparison;error?:string};
type PreviewResponse={preview?:AccessoryParseResult;comparison?:AccessoryComparison;identicalToActive?:boolean;error?:string;message?:string};
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const norm=(v:string)=>v.trim().toLowerCase();
const dateLabel=(v:string|null|undefined)=>{if(!v)return"-";const d=new Date(`${v}T00:00:00+07:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(d)};
function originalPrice(p:AccessoryPriceProduct){return p.referenceSrp>p.activePrice?p.referenceSrp:p.currentSrpCash>p.activePrice?p.currentSrpCash:0}
function CopyButton({value,label}:{value:string;label:string}){const[ok,setOk]=useState(false);if(!value)return null;return <button className="inline-flex min-h-9 items-center gap-1 rounded-xl bg-slate-100 px-3 text-[11px] font-black text-slate-600 dark:bg-slate-900 dark:text-slate-300" onClick={async()=>{await navigator.clipboard.writeText(value);setOk(true);setTimeout(()=>setOk(false),1200)}}>{ok?<Check className="size-3.5"/>:<Clipboard className="size-3.5"/>}{ok?"Tersalin":label}</button>}
function Detail({item,onClose}:{item:AccessoryPriceProduct;onClose:()=>void}){const old=originalPrice(item);return <div className="fixed inset-0 z-[10020] flex items-end justify-center bg-slate-950/40 backdrop-blur-sm" onClick={onClose}><div className="max-h-[88dvh] w-full overflow-y-auto rounded-t-[30px] bg-white p-5 shadow-2xl dark:bg-slate-950 sm:max-w-2xl sm:rounded-[30px]" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-3 h-1.5 w-12 rounded-full bg-slate-200"/><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">{item.supplier} · {item.brand}</p><h3 className="mt-1 text-xl font-black">{item.sapDescription}</h3><p className="mt-1 text-xs font-bold text-slate-400">{item.category}</p></div><button onClick={onClose} className="grid size-10 place-items-center rounded-full bg-slate-100 dark:bg-slate-900"><X className="size-4"/></button></div><div className="mt-4 rounded-2xl bg-slate-50 p-4 dark:bg-slate-900"><p className="text-[10px] font-black uppercase text-slate-400">Harga Aktif</p><p className="mt-1 text-2xl font-black text-blue-600">{item.activePrice?money.format(item.activePrice):"-"}</p>{old?<p className="mt-1 text-xs text-slate-400 line-through">{money.format(old)}</p>:null}</div><div className="mt-4 space-y-3 rounded-2xl border p-4 text-sm dark:border-slate-800"><div><b>SAP Article</b><p className="break-all text-slate-500">{item.sapArticle}</p><div className="mt-2"><CopyButton value={item.sapArticle} label="Copy SAP"/></div></div>{item.articleMapemall?<div><b>Article Mapemall</b><p className="break-all text-slate-500">{item.articleMapemall}</p><div className="mt-2"><CopyButton value={item.articleMapemall} label="Copy Mapemall"/></div></div>:null}<p><b>Reference SRP:</b> {item.referenceSrp?money.format(item.referenceSrp):"-"}</p><p><b>Current SRP Cash:</b> {item.currentSrpCash?money.format(item.currentSrpCash):"-"}</p><p><b>Repricing Cash:</b> {item.repricingCash?money.format(item.repricingCash):"-"}</p><p><b>BR/Zoutn:</b> {item.brZout||"-"}</p><p><b>Remarks:</b> {item.remarks||"-"}</p></div></div></div>}

export default function PromoBoardAccessories({mode="catalog"}:{mode?:"catalog"|"changes"|"history"}){
 const fileRef=useRef<HTMLInputElement>(null);const[active,setActive]=useState<Stored|null>(null),[history,setHistory]=useState<History[]>([]),[comparison,setComparison]=useState<AccessoryComparison|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[preview,setPreview]=useState<AccessoryParseResult|null>(null),[previewComparison,setPreviewComparison]=useState<AccessoryComparison|null>(null),[selectedFile,setSelectedFile]=useState<File|null>(null),[identical,setIdentical]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const[supplier,setSupplier]=useState("Semua"),[brand,setBrand]=useState("Semua"),[category,setCategory]=useState("Semua"),[query,setQuery]=useState(""),[sort,setSort]=useState("default"),[visible,setVisible]=useState(100),[detail,setDetail]=useState<AccessoryPriceProduct|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/promo-board-accessories",{cache:"no-store"}),j=await r.json() as ApiResponse;if(!r.ok)throw new Error(j.error||"Pricelist ACC gagal dibaca");setActive(j.active||null);setHistory(j.history||[]);setComparison(j.comparison||null)}catch(e){setError(e instanceof Error?e.message:"Pricelist ACC gagal dibaca")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const upload=async(file:File)=>{setBusy(true);setError("");setNotice("");setSelectedFile(file);try{const form=new FormData();form.append("file",file);form.append("mode","preview");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok||!j.preview)throw new Error(j.error||"Pricelist ACC gagal dianalisa");setPreview(j.preview);setPreviewComparison(j.comparison||null);setIdentical(Boolean(j.identicalToActive))}catch(e){setPreview(null);setSelectedFile(null);setError(e instanceof Error?e.message:"Pricelist ACC gagal dianalisa")}finally{setBusy(false)}};
 const activate=async()=>{if(!selectedFile||!preview||preview.blockingErrors||identical)return;setBusy(true);setError("");try{const form=new FormData();form.append("file",selectedFile);form.append("mode","activate");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok)throw new Error(j.error||"Aktivasi Pricelist ACC gagal");setNotice(j.message||"Pricelist ACC berhasil diaktifkan.");setPreview(null);setSelectedFile(null);setIdentical(false);if(fileRef.current)fileRef.current.value="";await load()}catch(e){setError(e instanceof Error?e.message:"Aktivasi Pricelist ACC gagal")}finally{setBusy(false)}};
 const products=active?.products||[];
 const supplierCounts=useMemo(()=>{const m=new Map<string,number>();for(const p of products)m.set(p.supplier,(m.get(p.supplier)||0)+1);return m},[products]);
 const suppliers=useMemo(()=>["Semua",...Array.from(supplierCounts.keys()).sort((a,b)=>a.localeCompare(b))],[supplierCounts]);
 const brands=useMemo(()=>["Semua",...Array.from(new Set(products.filter(p=>supplier==="Semua"||p.supplier===supplier).map(p=>p.brand))).sort((a,b)=>a.localeCompare(b))],[products,supplier]);
 const categories=useMemo(()=>["Semua",...Array.from(new Set(products.filter(p=>(supplier==="Semua"||p.supplier===supplier)&&(brand==="Semua"||p.brand===brand)).map(p=>p.category))).sort((a,b)=>a.localeCompare(b))],[products,supplier,brand]);
 const filtered=useMemo(()=>{const q=norm(query);const arr=products.filter(p=>(supplier==="Semua"||p.supplier===supplier)&&(brand==="Semua"||p.brand===brand)&&(category==="Semua"||p.category===category)&&(!q||[p.supplier,p.brand,p.sapArticle,p.articleMapemall,p.sapDescription,p.category,p.remarks].some(v=>norm(v).includes(q))));return arr.sort((a,b)=>{const exactA=q&&norm(a.sapArticle)===q?-1:0,exactB=q&&norm(b.sapArticle)===q?-1:0;if(exactA!==exactB)return exactA-exactB;if(sort==="low")return a.activePrice-b.activePrice;if(sort==="high")return b.activePrice-a.activePrice;if(sort==="brand")return a.brand.localeCompare(b.brand)||a.sapDescription.localeCompare(b.sapDescription);return a.supplier.localeCompare(b.supplier)||a.brand.localeCompare(b.brand)||a.category.localeCompare(b.category)||a.sapDescription.localeCompare(b.sapDescription)||a.sapArticle.localeCompare(b.sapArticle)})},[products,supplier,brand,category,query,sort]);
 useEffect(()=>{setBrand("Semua");setCategory("Semua");setVisible(100)},[supplier]);useEffect(()=>{setCategory("Semua");setVisible(100)},[brand]);useEffect(()=>setVisible(100),[category,query,sort]);
 if(mode==="changes")return <section className="mt-4 space-y-2">{loading?<p className="p-5 text-center text-sm text-slate-400">Memuat perubahan Accessories...</p>:comparison?.changes.length?comparison.changes.slice(0,200).map((c,i)=><div key={`${c.type}-${c.sapArticle}-${i}`} className="rounded-2xl border bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between gap-2"><div><b>{c.description}</b><p className="mt-1 text-xs text-slate-400">{c.sapArticle}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black dark:bg-slate-900">{c.type}</span></div>{c.beforePrice!==c.afterPrice?<p className="mt-2 text-xs font-bold">{c.beforePrice?money.format(c.beforePrice):"-"} → {c.afterPrice?money.format(c.afterPrice):"-"}</p>:null}</div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada perubahan Accessories.</div>}</section>;
 if(mode==="history")return <section className="mt-4 space-y-2">{history.length?history.map(h=><div key={h.id||h.fileName} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between gap-3"><div><b>{dateLabel(h.priceListDate)}</b><p className="mt-1 text-xs text-slate-500">{h.fileName}</p></div><div className="text-right"><p className="font-black">{h.totalSku} SKU</p><p className="text-xs text-slate-400">{h.totalBrand} brand · {h.totalCategory} category</p></div></div></div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada riwayat Accessories.</div>}</section>;
 return <section className="mt-4"><input id="promo-acc-file-input" ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/>
  {error?<div className="mb-3 rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>:null}{notice?<div className="mb-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{notice}</div>:null}
  {preview?<div className="mb-4 rounded-3xl border border-blue-200 bg-white p-4 shadow-sm dark:bg-slate-950"><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Preview Pricelist ACC</p><h3 className="mt-1 font-black">{preview.fileName}</h3><p className="mt-1 text-xs text-slate-500">{preview.totalSku} SKU · {preview.totalBrand} brand · {preview.totalCategory} category · {preview.blockingErrors} blocking</p>{identical?<p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-700">Pricelist ACC ini sama dengan data aktif. Tidak ada perubahan yang perlu disimpan.</p>:null}{preview.warnings.length?<p className="mt-2 text-xs font-bold text-amber-600">{preview.warnings.length} warning terdeteksi.</p>:null}{previewComparison?<div className="mt-3 grid grid-cols-2 gap-2 text-xs">{[["SKU Baru",previewComparison.counts.NEW_SKU],["SKU Hilang",previewComparison.counts.REMOVED_SKU],["Harga Turun",previewComparison.counts.PRICE_DOWN],["Harga Naik",previewComparison.counts.PRICE_UP]].map(([l,v])=><div key={String(l)} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><span className="text-slate-400">{l}</span><b className="mt-1 block text-lg">{v}</b></div>)}</div>:null}<div className="mt-3 flex gap-2"><button onClick={()=>{setPreview(null);setSelectedFile(null);if(fileRef.current)fileRef.current.value=""}} className="min-h-11 flex-1 rounded-xl border text-sm font-black">Batal</button><button disabled={busy||identical||Boolean(preview.blockingErrors)} onClick={()=>void activate()} className="min-h-11 flex-1 rounded-xl bg-emerald-600 text-sm font-black text-white disabled:opacity-40">Aktifkan</button></div></div>:null}
  <div className="rounded-3xl border bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari supplier, brand, SAP, Mapemall..." className="h-12 w-full rounded-2xl border bg-transparent pl-10 pr-3 text-sm font-semibold outline-none"/></div><select value={sort} onChange={e=>setSort(e.target.value)} className="h-12 max-w-[118px] rounded-2xl border bg-white px-2 text-xs font-black dark:bg-slate-950"><option value="default">Default</option><option value="brand">Brand A-Z</option><option value="low">Harga ↑</option><option value="high">Harga ↓</option></select></div>
  <p className="mb-2 mt-3 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Supplier</p><div className="flex gap-2 overflow-x-auto pb-1">{suppliers.map(s=><button key={s} onClick={()=>setSupplier(s)} className={`min-h-10 shrink-0 rounded-xl px-3 text-xs font-black ${supplier===s?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{s}{s!=="Semua"?` ${supplierCounts.get(s)||0}`:""}</button>)}</div>
  <p className="mb-2 mt-3 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Brand</p><div className="flex gap-2 overflow-x-auto pb-1">{brands.map(s=><button key={s} onClick={()=>setBrand(s)} className={`min-h-9 shrink-0 rounded-xl px-3 text-xs font-black ${brand===s?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{s}</button>)}</div>
  <p className="mb-2 mt-3 text-[10px] font-black uppercase tracking-[.14em] text-slate-400">Category</p><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(s=><button key={s} onClick={()=>setCategory(s)} className={`min-h-9 shrink-0 rounded-xl px-3 text-xs font-black ${category===s?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{s}</button>)}</div></div>
  <div className="mt-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Pricelist Accessories</p><p className="mt-1 text-sm text-slate-500">{filtered.length} dari {products.length} SKU</p></div><button onClick={()=>fileRef.current?.click()} className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-blue-50 px-3 text-xs font-black text-blue-600"><Upload className="size-4"/> Update ACC</button></div>
  {loading?<div className="mt-3 rounded-3xl border p-8 text-center text-sm text-slate-400">Memuat Pricelist ACC...</div>:filtered.length?<div className="mt-3 overflow-hidden rounded-3xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">{filtered.slice(0,visible).map((p,i)=>{const old=originalPrice(p),drop=old>p.activePrice?old-p.activePrice:0;return <button key={p.sapArticle} onClick={()=>setDetail(p)} className={`block w-full px-4 py-4 text-left ${i?"border-t dark:border-slate-800":""}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.12em] text-blue-600">{p.supplier} · {p.brand}</p><h3 className="mt-1 text-sm font-black">{p.sapDescription}</h3><p className="mt-1 text-[11px] font-bold text-slate-500">SAP: {p.sapArticle}</p>{p.articleMapemall?<p className="text-[10px] text-slate-400">Mapemall: {p.articleMapemall}</p>:null}<p className="mt-1 text-[10px] font-bold text-slate-400">{p.category}</p></div><div className="shrink-0 text-right"><p className="text-sm font-black text-blue-600">{p.activePrice?money.format(p.activePrice):"-"}</p>{old?<p className="mt-0.5 text-[10px] text-slate-400 line-through">{money.format(old)}</p>:null}{drop?<p className="mt-1 text-[9px] font-black text-emerald-600">Turun {money.format(drop)}</p>:null}<ChevronRight className="ml-auto mt-2 size-4 text-slate-300"/></div></div></button>})}</div>:<div className="mt-3 rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Tidak ada Accessories untuk filter ini.</div>}
  {visible<filtered.length?<button onClick={()=>setVisible(v=>v+100)} className="mt-3 min-h-11 w-full rounded-2xl border bg-white text-sm font-black dark:bg-slate-950">Muat 100 lagi</button>:null}{detail?<Detail item={detail} onClose={()=>setDetail(null)}/>:null}
 </section>
}
