"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useDeferredValue,useEffect,useMemo,useRef,useState} from "react";
import {ArrowUpDown,Check,ChevronDown,ChevronRight,Clipboard,Search,SlidersHorizontal,X} from "lucide-react";
import type {AccessoryComparison,AccessoryParseResult,AccessoryPriceProduct} from "@/lib/promo-board-accessory";

type Product=AccessoryPriceProduct&{brandCode?:string};
type Audit={totalSku:number;totalBrand:number;totalSupplier:number;brandChanged:number;supplierChanged:number;unmappedSupplier:number;duplicateSku:number;masterConflicts:string[];mappingProblems:string[]};
type Stored=Omit<AccessoryParseResult,"products">&{products:Product[];id?:string;uploadedAt?:string;audit?:Audit};
type History={id?:string;uploadedAt?:string;fileName:string;priceListDate:string|null;totalRows:number;totalSku:number;totalBrand:number;totalCategory:number;warnings:string[]};
type ApiResponse={active?:Stored|null;history?:History[];comparison?:AccessoryComparison;audit?:Audit|null;error?:string};
type PreviewResponse={preview?:AccessoryParseResult;comparison?:AccessoryComparison;identicalToActive?:boolean;error?:string;message?:string};
type PickerKind="supplier"|"brand"|"category";
type SortKind="name-asc"|"name-desc"|"price-asc"|"price-desc"|"brand";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const norm=(v:unknown)=>String(v??"").trim().toLowerCase();
const dateLabel=(v:string|null|undefined)=>{if(!v)return"-";const d=new Date(`${v}T00:00:00+07:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(d)};

function CopyButton({value}:{value:string}){
 const[ok,setOk]=useState(false);
 return <button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-100 px-4 text-xs font-black dark:bg-slate-900" onClick={async()=>{try{await navigator.clipboard.writeText(value);setOk(true);setTimeout(()=>setOk(false),1200)}catch{setOk(false)}}}>{ok?<Check className="size-4"/>:<Clipboard className="size-4"/>}{ok?"Tersalin":"Copy SAP"}</button>;
}

function Detail({item,onClose}:{item:Product;onClose:()=>void}){
 useEffect(()=>{const before=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=before}},[]);
 return <div className="fixed inset-0 z-[10060] flex items-end bg-slate-950/45 backdrop-blur-[2px]" role="dialog" aria-modal="true" aria-label={`Detail ${item.sapDescription}`} onClick={onClose}>
  <div className="max-h-[86dvh] w-full overflow-y-auto overscroll-contain rounded-t-[28px] bg-white px-5 pb-[calc(28px+env(safe-area-inset-bottom))] pt-3 shadow-2xl dark:bg-slate-950" onClick={e=>e.stopPropagation()}>
   <div className="mx-auto mb-4 h-1.5 w-11 rounded-full bg-slate-200 dark:bg-slate-700"/>
   <div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-[.12em] text-blue-600">{item.brand}</p><h3 className="mt-1 text-lg font-black leading-snug text-slate-950 dark:text-white">{item.sapDescription}</h3><p className="mt-3 text-[26px] font-black tracking-[-.03em] text-blue-600">{item.activePrice?money.format(item.activePrice):"-"}</p></div><button className="grid size-11 shrink-0 place-items-center rounded-full bg-slate-100 dark:bg-slate-900" onClick={onClose} aria-label="Tutup"><X className="size-5"/></button></div>
   <div className="mt-5 border-t border-slate-200 pt-4 dark:border-slate-800"><p className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">SAP Article</p><div className="mt-1 flex items-center justify-between gap-3"><p className="min-w-0 break-all text-sm font-black">{item.sapArticle}</p><CopyButton value={item.sapArticle}/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Category</p><p className="mt-1 text-sm font-bold">{item.category||"-"}</p></div>
  </div>
 </div>;
}

export default function PromoBoardAccessories({mode="catalog"}:{mode?:"catalog"|"changes"|"history"}){
 const fileRef=useRef<HTMLInputElement>(null);
 const[active,setActive]=useState<Stored|null>(null),[history,setHistory]=useState<History[]>([]),[comparison,setComparison]=useState<AccessoryComparison|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[preview,setPreview]=useState<AccessoryParseResult|null>(null),[selectedFile,setSelectedFile]=useState<File|null>(null),[identical,setIdentical]=useState(false),[busy,setBusy]=useState(false);
 const[query,setQuery]=useState(""),[supplier,setSupplier]=useState(""),[brand,setBrand]=useState(""),[category,setCategory]=useState(""),[sort,setSort]=useState<SortKind>("name-asc"),[filterOpen,setFilterOpen]=useState(false),[sortOpen,setSortOpen]=useState(false),[picker,setPicker]=useState<PickerKind|null>(null),[pickerQuery,setPickerQuery]=useState(""),[visible,setVisible]=useState(60),[detail,setDetail]=useState<Product|null>(null);
 const deferredQuery=useDeferredValue(query.trim());

 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/promo-board-accessories",{cache:"no-store"}),j=await r.json() as ApiResponse;if(!r.ok)throw new Error(j.error||"Pricelist gagal dimuat.");setActive(j.active||null);setHistory(j.history||[]);setComparison(j.comparison||null)}catch(e){setError(e instanceof Error?e.message:"Pricelist gagal dimuat.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const upload=async(file:File)=>{setBusy(true);setError("");setSelectedFile(file);try{const form=new FormData();form.append("file",file);form.append("mode","preview");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok||!j.preview)throw new Error(j.error||"Pricelist ACC gagal dianalisa");setPreview(j.preview);setIdentical(Boolean(j.identicalToActive))}catch(e){setPreview(null);setSelectedFile(null);setError(e instanceof Error?e.message:"Pricelist ACC gagal dianalisa")}finally{setBusy(false)}};
 const activate=async()=>{if(!selectedFile||!preview||preview.blockingErrors||identical)return;setBusy(true);try{const form=new FormData();form.append("file",selectedFile);form.append("mode","activate");const r=await fetch("/api/promo-board-accessories",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok)throw new Error(j.error||"Aktivasi gagal");setPreview(null);setSelectedFile(null);await load()}catch(e){setError(e instanceof Error?e.message:"Aktivasi gagal")}finally{setBusy(false)}};

 const products=useMemo(()=>active?.products||[],[active]);
 const suppliers=useMemo(()=>[...new Set(products.map(p=>p.supplier).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products]);
 const brands=useMemo(()=>[...new Set(products.filter(p=>!supplier||p.supplier===supplier).map(p=>p.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products,supplier]);
 const categories=useMemo(()=>[...new Set(products.filter(p=>(!supplier||p.supplier===supplier)&&(!brand||p.brand===brand)).map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b)),[products,supplier,brand]);
 const filtered=useMemo(()=>{const q=norm(deferredQuery);const out=products.filter(p=>(!supplier||p.supplier===supplier)&&(!brand||p.brand===brand)&&(!category||p.category===category)&&(!q||[p.sapArticle,p.sapDescription,p.brand,p.brandCode,p.category].some(v=>norm(v).includes(q))));return [...out].sort((a,b)=>{if(q){const ae=norm(a.sapArticle)===q,be=norm(b.sapArticle)===q;if(ae!==be)return ae?-1:1}if(sort==="name-desc")return b.sapDescription.localeCompare(a.sapDescription)||a.sapArticle.localeCompare(b.sapArticle);if(sort==="price-asc")return a.activePrice-b.activePrice||a.sapDescription.localeCompare(b.sapDescription);if(sort==="price-desc")return b.activePrice-a.activePrice||a.sapDescription.localeCompare(b.sapDescription);if(sort==="brand")return a.brand.localeCompare(b.brand)||a.sapDescription.localeCompare(b.sapDescription);return a.sapDescription.localeCompare(b.sapDescription)||a.sapArticle.localeCompare(b.sapArticle)})},[products,supplier,brand,category,deferredQuery,sort]);
 useEffect(()=>setVisible(60),[deferredQuery,supplier,brand,category,sort]);
 const filterCount=[supplier,brand,category].filter(Boolean).length;
 const reset=()=>{setSupplier("");setBrand("");setCategory("")};
 const pickerItems=picker==="supplier"?suppliers:picker==="brand"?brands:categories;
 const pickerValue=picker==="supplier"?supplier:picker==="brand"?brand:category;
 const pickerLabel=picker==="supplier"?"Supplier":picker==="brand"?"Brand":"Category";
 const shownPickerItems=pickerItems.filter(x=>norm(x).includes(norm(pickerQuery)));
 const choose=(value:string)=>{if(picker==="supplier"){setSupplier(value);setBrand("");setCategory("")}else if(picker==="brand"){setBrand(value);setCategory("")}else setCategory(value);setPicker(null);setPickerQuery("")};
 const openPicker=(kind:PickerKind)=>{setPickerQuery("");setPicker(kind)};

 if(mode==="changes")return <section className="mt-4 space-y-2">{loading?<p className="p-6 text-center text-sm text-slate-400">Memuat perubahan Accessories...</p>:comparison?.changes.length?comparison.changes.slice(0,200).map((c,i)=><div key={`${c.type}-${c.sapArticle}-${i}`} className="rounded-2xl border bg-white p-4 text-sm dark:border-slate-800 dark:bg-slate-950"><b>{c.description}</b><p className="mt-1 text-xs text-slate-400">{c.sapArticle}</p></div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada perubahan Accessories.</div>}</section>;
 if(mode==="history")return <section className="mt-4 space-y-2">{history.length?history.map(h=><div key={h.id||h.fileName} className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex justify-between gap-3"><div className="min-w-0"><b>{dateLabel(h.priceListDate)}</b><p className="truncate text-xs text-slate-500">{h.fileName}</p></div><b className="shrink-0">{h.totalSku} SKU</b></div></div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada riwayat Accessories.</div>}</section>;

 return <section className="mt-3 pb-[calc(120px+env(safe-area-inset-bottom))]">
  <input id="promo-acc-file-input" ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/>
  {error?<div className="mb-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-bold text-rose-700"><p>Pricelist gagal dimuat.</p><button onClick={()=>void load()} className="mt-3 min-h-10 rounded-xl border border-rose-300 bg-white px-4 text-xs font-black">Coba Lagi</button></div>:null}
  {preview?<div className="mb-3 rounded-3xl border border-blue-200 bg-white p-4 dark:bg-slate-950"><p className="text-xs font-black uppercase text-blue-600">Preview Update ACC</p><p className="mt-1 text-sm font-bold">{preview.fileName} · {preview.totalSku} SKU</p><div className="mt-3 flex gap-2"><button className="min-h-11 flex-1 rounded-xl border font-black" onClick={()=>{setPreview(null);setSelectedFile(null)}}>Batal</button><button disabled={busy||identical||Boolean(preview.blockingErrors)} className="min-h-11 flex-1 rounded-xl bg-blue-600 font-black text-white disabled:opacity-40" onClick={()=>void activate()}>Aktifkan</button></div></div>:null}

  <div className="sticky top-0 z-20 -mx-1 bg-slate-50/95 px-1 pb-2 pt-1 backdrop-blur-xl dark:bg-slate-900/95">
   <div className="relative"><Search className="absolute left-4 top-1/2 size-[18px] -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari produk, brand, SAP..." autoComplete="off" enterKeyHint="search" className="h-12 w-full rounded-2xl border border-slate-200 bg-white pl-11 pr-10 text-[15px] font-semibold outline-none focus:border-blue-500 dark:border-slate-800 dark:bg-slate-950"/>{query?<button onClick={()=>setQuery("")} aria-label="Hapus pencarian" className="absolute right-2 top-1/2 grid size-9 -translate-y-1/2 place-items-center"><X className="size-4"/></button>:null}</div>
   <div className="mt-2 flex gap-2"><button onClick={()=>setFilterOpen(true)} className="flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-black dark:border-slate-800 dark:bg-slate-950"><SlidersHorizontal className="size-4"/>Filter{filterCount?` · ${filterCount}`:""}</button><button onClick={()=>setSortOpen(true)} className="flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-xs font-black dark:border-slate-800 dark:bg-slate-950"><ArrowUpDown className="size-4"/>Urutkan</button></div>
   {filterCount?<div className="mt-2 flex gap-1.5 overflow-x-auto pb-1">{[[supplier,"supplier"],[brand,"brand"],[category,"category"]].filter(([v])=>v).map(([v,t])=><button key={t} onClick={()=>t==="supplier"?(setSupplier(""),setBrand(""),setCategory("")):t==="brand"?(setBrand(""),setCategory("")):setCategory("")} className="flex min-h-8 shrink-0 items-center gap-1 rounded-full bg-blue-50 px-2.5 text-[11px] font-black text-blue-700 dark:bg-blue-950/40 dark:text-blue-300">{v}<X className="size-3"/></button>)}<button onClick={reset} className="min-h-8 shrink-0 px-2 text-[11px] font-black text-slate-500">Reset</button></div>:null}
  </div>

  <div className="mb-2 mt-3 flex items-end justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.14em] text-blue-600">Accessories</p><p className="mt-0.5 text-xs font-semibold text-slate-400">{active?`${filtered.length.toLocaleString("id-ID")} produk`:"Belum ada pricelist aktif"}</p></div>{active?.priceListDate?<p className="text-[10px] font-bold text-slate-400">Update {dateLabel(active.priceListDate)}</p>:null}</div>

  {loading?<div className="rounded-2xl border border-slate-200 bg-white p-8 text-center text-sm font-semibold text-slate-400 dark:border-slate-800 dark:bg-slate-950">Memuat Pricelist...</div>:!active?<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-sm font-bold text-slate-500">Belum ada pricelist aktif.</div>:filtered.length?<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950">{filtered.slice(0,visible).map((p,i)=><button key={`${p.sapArticle}-${i}`} onClick={()=>setDetail(p)} className={`block w-full px-4 py-3.5 text-left active:bg-slate-50 dark:active:bg-slate-900 ${i?"border-t border-slate-100 dark:border-slate-800":""}`}><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><p className="text-[11px] font-black uppercase tracking-[.1em] text-slate-500 dark:text-slate-400">{p.brand||"-"}</p><h3 className="mt-1 text-[13px] font-black leading-[1.35] text-slate-950 dark:text-white">{p.sapDescription}</h3><div className="mt-2 flex flex-wrap items-center gap-x-2 gap-y-1 text-[10px] font-bold"><span className="text-slate-500">SAP&nbsp; {p.sapArticle}</span>{p.category?<><span className="text-slate-300">•</span><span className="text-slate-400">{p.category}</span></>:null}</div></div><div className="flex items-start gap-1 pt-0.5"><p className="whitespace-nowrap text-[14px] font-black tracking-[-.02em] text-blue-600">{p.activePrice?money.format(p.activePrice):"-"}</p><ChevronRight className="mt-0.5 size-4 text-slate-300"/></div></div></button>)}</div>:<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center"><p className="text-sm font-black">Produk tidak ditemukan.</p><p className="mt-1 text-xs text-slate-400">Coba ganti keyword atau reset filter.</p><button onClick={()=>{setQuery("");reset()}} className="mt-4 min-h-10 rounded-xl bg-blue-600 px-4 text-xs font-black text-white">Reset Filter</button></div>}
  {visible<filtered.length?<button onClick={()=>setVisible(v=>v+60)} className="mt-3 min-h-11 w-full rounded-xl border border-slate-200 bg-white text-sm font-black dark:border-slate-800 dark:bg-slate-950">Tampilkan 60 lagi</button>:null}

  {filterOpen?<div className="fixed inset-0 z-[10050] flex items-end bg-slate-950/40" onClick={()=>setFilterOpen(false)}><div className="w-full rounded-t-[28px] bg-white p-5 pb-[calc(24px+env(safe-area-inset-bottom))] shadow-2xl dark:bg-slate-950" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-4 h-1.5 w-11 rounded-full bg-slate-200"/><div className="flex items-center justify-between"><div><h3 className="text-base font-black">Filter Accessories</h3><p className="mt-0.5 text-xs text-slate-400">Supplier → Brand → Category</p></div><button onClick={()=>setFilterOpen(false)} className="grid size-10 place-items-center"><X className="size-5"/></button></div><div className="mt-5 space-y-3">{[["Supplier",supplier,"Semua Supplier","supplier"],["Brand",brand,"Semua Brand","brand"],["Category",category,"Semua Category","category"]].map(([label,value,empty,kind])=><div key={kind}><p className="mb-1.5 text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><button onClick={()=>openPicker(kind as PickerKind)} className="flex min-h-12 w-full items-center justify-between rounded-2xl border bg-slate-50 px-4 text-left text-sm font-bold dark:border-slate-800 dark:bg-slate-900"><span className={value?"text-slate-900 dark:text-white":"text-slate-500"}>{value||empty}</span><ChevronDown className="size-4 text-slate-400"/></button></div>)}</div><div className="mt-5 grid grid-cols-[.8fr_1.2fr] gap-2"><button onClick={reset} className="min-h-12 rounded-2xl border text-sm font-black">Reset</button><button onClick={()=>setFilterOpen(false)} className="min-h-12 rounded-2xl bg-blue-600 px-2 text-sm font-black text-white">Tampilkan {filtered.length.toLocaleString("id-ID")}</button></div></div></div>:null}

  {picker?<div className="fixed inset-0 z-[10070] flex items-end bg-slate-950/40" onClick={()=>{setPicker(null);setPickerQuery("")}}><div className="flex h-[min(86dvh,760px)] w-full min-h-0 flex-col overflow-hidden rounded-t-[28px] bg-white shadow-2xl dark:bg-slate-950" onClick={e=>e.stopPropagation()}><div className="shrink-0 px-5 pt-3"><div className="mx-auto mb-3 h-1.5 w-11 rounded-full bg-slate-200"/><div className="flex items-center justify-between"><h3 className="text-base font-black">Pilih {pickerLabel}</h3><button onClick={()=>{setPicker(null);setPickerQuery("")}} className="grid size-10 place-items-center"><X className="size-5"/></button></div><div className="relative mt-2"><Search className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input autoFocus value={pickerQuery} onChange={e=>setPickerQuery(e.target.value)} placeholder={`Cari ${pickerLabel.toLowerCase()}...`} className="h-12 w-full rounded-2xl border bg-slate-50 pl-11 pr-4 text-sm font-semibold outline-none focus:border-blue-500 dark:border-slate-800 dark:bg-slate-900"/></div></div><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 pb-[calc(32px+env(safe-area-inset-bottom))] pt-2 [-webkit-overflow-scrolling:touch] touch-pan-y"><button onClick={()=>choose("")} className="flex min-h-12 w-full items-center justify-between border-b px-1 text-left text-sm font-bold dark:border-slate-800"><span>Semua {pickerLabel}</span>{!pickerValue?<Check className="size-4 text-blue-600"/>:null}</button>{shownPickerItems.map(x=><button key={x} onClick={()=>choose(x)} className="flex min-h-12 w-full items-center justify-between border-b px-1 text-left text-sm font-bold last:border-0 dark:border-slate-800"><span>{x}</span>{pickerValue===x?<Check className="size-4 text-blue-600"/>:null}</button>)}{!shownPickerItems.length?<p className="py-8 text-center text-sm text-slate-400">{pickerLabel} tidak ditemukan</p>:null}</div></div></div>:null}

  {sortOpen?<div className="fixed inset-0 z-[10050] flex items-end bg-slate-950/40" onClick={()=>setSortOpen(false)}><div className="w-full rounded-t-[28px] bg-white p-5 pb-[calc(24px+env(safe-area-inset-bottom))] dark:bg-slate-950" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-4 h-1.5 w-11 rounded-full bg-slate-200"/><h3 className="mb-3 text-base font-black">Urutkan</h3>{[["name-asc","Nama A–Z"],["name-desc","Nama Z–A"],["price-asc","Harga Terendah"],["price-desc","Harga Tertinggi"],["brand","Brand"]].map(([v,l])=><button key={v} onClick={()=>{setSort(v as SortKind);setSortOpen(false)}} className="flex min-h-12 w-full items-center justify-between border-b text-left text-sm font-bold last:border-0 dark:border-slate-800">{l}{sort===v?<Check className="size-4 text-blue-600"/>:null}</button>)}</div></div>:null}
  {detail?<Detail item={detail} onClose={()=>setDetail(null)}/>:null}
 </section>;
}
