"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {ArrowLeft,CheckCircle2,ChevronRight,Search,SlidersHorizontal,Upload,X,XCircle} from "lucide-react";
import type {PromoParseResult,PromoProduct,PromoStatus} from "@/lib/promo-board-parser";
import {comparePromoPriceLists,type PromoComparison} from "@/lib/promo-board-insights";
import {buildPromoCatalog,type PromoCatalogItem,type SohRow,type StockStatus} from "@/lib/promo-board-catalog";

type Snapshot=PromoParseResult&{id?:string;uploadedAt?:string};
type PromoResponse={ok?:boolean;active?:Snapshot|null;history?:Snapshot[];error?:string};
type PreviewResponse={ok?:boolean;preview?:PromoParseResult;comparison?:PromoComparison;error?:string};
type SohResponse={rows?:SohRow[];updated?:string;error?:string};
type ViewMode="promo"|"changes"|"history";
type PromoScope="ALL"|"ACTIVE"|"ENDING";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const dateFmt=new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"});
const LOB_ORDER=["iPhone","iPad","Mac","Watch","AirPods"];
const CAPACITY_ORDER=["64GB","128GB","256GB","512GB","1TB","2TB","4TB"];

function fmtDate(value:string|null|undefined){if(!value)return"-";const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:dateFmt.format(d)}
function promoMeta(item:PromoCatalogItem){
 const p=item.group;
 const hasPromo=p.promotionPrice>0&&p.normalPrice>0&&p.promotionPrice<p.normalPrice;
 if(!hasPromo)return{label:"Tidak Ada Promo",cls:"border-slate-200 bg-slate-100 text-slate-600",price:p.normalPrice||p.promotionPrice};
 if(p.promoStatus==="FURTHER_NOTICE")return{label:"Further Notice",cls:"border-blue-200 bg-blue-50 text-blue-700",price:p.promotionPrice};
 if(p.promoStatus==="ENDING_SOON")return{label:p.daysRemaining===0?"Berakhir hari ini":p.daysRemaining===1?"Berakhir besok":`Berakhir ${p.daysRemaining} hari lagi`,cls:"border-amber-200 bg-amber-50 text-amber-700",price:p.promotionPrice};
 if(p.promoStatus==="EXPIRED")return{label:"Expired",cls:"border-rose-200 bg-rose-50 text-rose-700",price:p.promotionPrice};
 if(p.promoStatus==="ACTIVE")return{label:"Promo Aktif",cls:"border-emerald-200 bg-emerald-50 text-emerald-700",price:p.promotionPrice};
 return{label:"Perlu Diperiksa",cls:"border-slate-200 bg-slate-50 text-slate-600",price:p.promotionPrice};
}
function stockMeta(status:StockStatus){
 if(status==="READY")return{label:"Ready",cls:"text-emerald-600"};
 if(status==="LOW_STOCK")return{label:"Low Stock",cls:"text-amber-600"};
 if(status==="OUT_OF_STOCK")return{label:"Out of Stock",cls:"text-rose-600"};
 return{label:"SOH Tidak Ditemukan",cls:"text-slate-400"};
}
function colorName(value:string){
 const u=value.toUpperCase();
 const map:[RegExp,string][]=[[/\bSPG\b|SPACE GR(?:E|A)Y/,"Space Grey"],[/\bSLV\b|SILVER/,"Silver"],[/\bSTL\b|STARLIGHT/,"Starlight"],[/\bMDN\b|MIDNIGHT/,"Midnight"],[/\bBLK\b|BLACK/,"Black"],[/\bWHT\b|WHITE/,"White"],[/\bBLU\b|BLUE/,"Blue"],[/PINK/,"Pink"],[/PUR|PURPLE/,"Purple"],[/NAT|NATURAL/,"Natural"],[/GLD|GOLD/,"Gold"],[/GRN|GREEN/,"Green"],[/RED/,"Red"]];
 return map.find(([r])=>r.test(u))?.[1]||"Variant";
}
function isActive(item:PromoCatalogItem){return item.group.promoStatus!=="EXPIRED"}
function capacitySort(a:string,b:string){const ai=CAPACITY_ORDER.indexOf(a),bi=CAPACITY_ORDER.indexOf(b);return(ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b)}
function searchText(item:PromoCatalogItem){return `${item.lob} ${item.model} ${item.capacity} ${item.connectivity} ${item.friendlyName} ${item.group.variants.map(v=>`${v.sapArticle} ${v.sapDescription}`).join(" ")}`.toLowerCase()}
function changeLabel(type:string){return({PROMO_PRICE_DOWN:"Harga Turun",PROMO_PRICE_UP:"Harga Naik",NEW_PROMO:"Promo Baru",PROMO_ENDED:"Promo Berakhir",PROMO_PERIOD_CHANGED:"Periode Berubah",NEW_PRODUCT:"Produk Baru",REMOVED_PRODUCT:"Produk Hilang",UNCHANGED:"Tidak Berubah"} as Record<string,string>)[type]||type}

function DetailSheet({item,onClose}:{item:PromoCatalogItem;onClose:()=>void}){
 const p=item.group,first=p.variants[0],promo=promoMeta(item),stock=stockMeta(item.stockStatus);
 return <div className="fixed inset-0 z-[10000] flex items-end justify-center bg-slate-950/40 backdrop-blur-sm sm:items-center" onClick={onClose}>
  <div className="max-h-[90dvh] w-full overflow-y-auto rounded-t-[28px] bg-white p-5 shadow-2xl dark:bg-slate-950 sm:max-w-3xl sm:rounded-[28px]" onClick={e=>e.stopPropagation()}>
   <div className="mx-auto mb-3 h-1.5 w-12 rounded-full bg-slate-200 sm:hidden"/>
   <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-blue-600">{item.lob}</p><h2 className="mt-1 text-2xl font-black">{item.friendlyName}</h2></div><button onClick={onClose} className="grid size-11 place-items-center rounded-full bg-slate-100 dark:bg-slate-900" aria-label="Tutup"><X className="size-4"/></button></div>
   <div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${promo.cls}`}>{promo.label}</span><span className={`rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black dark:bg-slate-900 ${stock.cls}`}>{item.totalSoh==null?"SOH -":`SOH ${item.totalSoh}`} • {stock.label}</span></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-900"><p className="text-xs text-slate-400">Harga</p><p className="mt-1 text-2xl font-black text-blue-600">{promo.price?money.format(promo.price):"-"}</p>{p.normalPrice>0&&p.promotionPrice>0&&p.promotionPrice<p.normalPrice?<><p className="mt-1 text-xs text-slate-400 line-through">{money.format(p.normalPrice)}</p><p className="mt-2 text-xs font-black text-emerald-600">Hemat {money.format(p.savingAmount)} • {p.discountPercentage.toFixed(1)}%</p></>:null}</div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-900"><p className="text-xs text-slate-400">Periode</p><p className="mt-1 font-black">{p.promoPeriodType==="FURTHER_NOTICE"?"Further Notice":p.promoEndDate?`s.d. ${fmtDate(p.promoEndDate)}`:"Perlu diperiksa"}</p><p className="mt-2 text-xs text-slate-500">Mulai {fmtDate(p.promoStartDate)}</p></div></div>
   <div className="mt-5"><p className="text-sm font-black">Variant / SAP / SOH</p><div className="mt-2 overflow-hidden rounded-2xl border dark:border-slate-800">{item.stockVariants.map(v=>{const st=stockMeta(v.status);return <div key={v.product.sapArticle} className="grid grid-cols-[1fr_auto] gap-2 border-t p-3 text-sm first:border-t-0 dark:border-slate-800 sm:grid-cols-[1fr_1.3fr_.5fr_.8fr] sm:items-center"><b>{colorName(v.product.sapDescription)}</b><span className={`text-right text-xs font-black sm:order-4 ${st.cls}`}>{st.label}</span><span className="col-span-2 text-xs text-slate-500 sm:col-span-1 sm:order-2">{v.product.sapArticle}</span><span className="text-xs font-black sm:order-3">SOH {v.soh==null?"-":v.soh}</span></div>})}</div></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border p-4 text-sm dark:border-slate-800"><p><b>Remarks:</b> {p.remarks||"-"}</p></div><div className="rounded-2xl border p-4 text-sm dark:border-slate-800"><p><b>BR/ZOUT:</b> {first?.brZout||"-"}</p><p className="mt-2"><b>EOL:</b> {first?.eolStatus||"-"}</p><p className="mt-2"><b>Cicilan Bundling:</b> {first?.promotionInstallmentBundling?money.format(first.promotionInstallmentBundling):"-"}</p><p className="mt-2"><b>Cash Bundling:</b> {first?.promotionCashBundling?money.format(first.promotionCashBundling):"-"}</p></div></div>
  </div>
 </div>
}

function ModelCard({model,items,onDetail}:{model:string;items:PromoCatalogItem[];onDetail:(item:PromoCatalogItem)=>void}){
 const capacities=useMemo(()=>Array.from(new Set(items.map(i=>i.capacity).filter(Boolean))).sort(capacitySort),[items]);
 const[capacity,setCapacity]=useState(capacities[0]||"");
 useEffect(()=>{if(capacities.length&&!capacities.includes(capacity))setCapacity(capacities[0]);if(!capacities.length)setCapacity("")},[capacities,capacity]);
 const capacityItems=useMemo(()=>items.filter(i=>!capacity||i.capacity===capacity),[items,capacity]);
 const connectivities=useMemo(()=>Array.from(new Set(capacityItems.map(i=>i.connectivity).filter(Boolean))),[capacityItems]);
 const[connectivity,setConnectivity]=useState(connectivities[0]||"");
 useEffect(()=>{if(connectivities.length&&!connectivities.includes(connectivity))setConnectivity(connectivities[0]);if(!connectivities.length)setConnectivity("")},[connectivities,connectivity]);
 const choices=useMemo(()=>capacityItems.filter(i=>!connectivity||i.connectivity===connectivity),[capacityItems,connectivity]);
 const[selectedKey,setSelectedKey]=useState(choices[0]?.key||"");
 useEffect(()=>{if(choices.length&&!choices.some(i=>i.key===selectedKey))setSelectedKey(choices[0].key)},[choices,selectedKey]);
 const item=choices.find(i=>i.key===selectedKey)||choices[0]||items[0];
 if(!item)return null;
 const p=item.group,promo=promoMeta(item),stock=stockMeta(item.stockStatus),colors=Array.from(new Set(item.stockVariants.map(v=>`${colorName(v.product.sapDescription)}${v.soh==null?"":` ${v.soh}`}`)));
 return <article className="rounded-[26px] border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950 sm:p-5">
  <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-blue-600">{item.lob}</p><h2 className="mt-1 text-xl font-black tracking-[-.02em]">{model}</h2></div><span className={`shrink-0 rounded-full border px-2.5 py-1 text-[10px] font-black ${promo.cls}`}>{promo.label}</span></div>
  {capacities.length>1?<div className="mt-4 flex gap-2 overflow-x-auto pb-1">{capacities.map(c=><button key={c} onClick={()=>setCapacity(c)} className={`min-h-10 shrink-0 rounded-xl px-3 text-xs font-black ${capacity===c?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300"}`}>{c}</button>)}</div>:capacities.length===1?<p className="mt-3 text-xs font-black text-slate-500">{capacities[0]}</p>:null}
  {connectivities.length>1?<div className="mt-2 flex gap-2 overflow-x-auto pb-1">{connectivities.map(c=><button key={c} onClick={()=>setConnectivity(c)} className={`min-h-9 shrink-0 rounded-lg border px-3 text-[11px] font-black ${connectivity===c?"border-blue-600 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500 dark:border-slate-800"}`}>{c}</button>)}</div>:connectivities.length===1?<p className="mt-2 text-[11px] font-bold text-slate-400">{connectivities[0]}</p>:null}
  {choices.length>1?<div className="mt-2 flex gap-2 overflow-x-auto pb-1">{choices.map((choice,index)=><button key={choice.key} onClick={()=>setSelectedKey(choice.key)} className={`min-h-8 shrink-0 rounded-lg px-2.5 text-[10px] font-black ${item.key===choice.key?"bg-blue-600 text-white":"bg-slate-100 text-slate-500 dark:bg-slate-900"}`}>Pilihan {index+1}</button>)}</div>:null}
  <div className="mt-4 grid grid-cols-[1.25fr_.75fr] gap-3"><div className="rounded-2xl bg-slate-50 p-3.5 dark:bg-slate-900"><p className="text-[10px] font-black uppercase text-slate-400">{p.promotionPrice>0&&p.normalPrice>p.promotionPrice?"Promo Price":"Harga"}</p><p className="mt-1 break-words text-[22px] font-black tracking-[-.04em] text-blue-600">{promo.price?money.format(promo.price):"-"}</p>{p.promotionPrice>0&&p.normalPrice>p.promotionPrice?<><p className="mt-0.5 text-[11px] text-slate-400 line-through">{money.format(p.normalPrice)}</p><p className="mt-2 text-[11px] font-black text-emerald-600">Hemat {money.format(p.savingAmount)} • {p.discountPercentage.toFixed(1)}%</p></>:null}</div><div className="rounded-2xl bg-slate-50 p-3.5 dark:bg-slate-900"><p className="text-[10px] font-black uppercase text-slate-400">SOH M238</p><p className="mt-1 text-[22px] font-black tracking-[-.03em]">{item.totalSoh==null?"-":num.format(item.totalSoh)}</p><p className={`mt-1 text-[10px] font-black ${stock.cls}`}>{stock.label}</p></div></div>
  <div className="mt-3 flex flex-wrap gap-1.5">{colors.slice(0,8).map(c=><span key={c} className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black text-slate-600 dark:bg-slate-900 dark:text-slate-300">{c}</span>)}</div>
  <button onClick={()=>onDetail(item)} className="mt-4 flex min-h-11 w-full items-center justify-center gap-1 rounded-2xl bg-slate-950 text-sm font-black text-white dark:bg-white dark:text-slate-950">Lihat Detail <ChevronRight className="size-4"/></button>
 </article>
}

export default function PromoBoardV6(){
 const fileRef=useRef<HTMLInputElement>(null);
 const[active,setActive]=useState<Snapshot|null>(null),[history,setHistory]=useState<Snapshot[]>([]),[soh,setSoh]=useState<SohResponse>({rows:[]});
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sohWarning,setSohWarning]=useState("");
 const[preview,setPreview]=useState<PromoParseResult|null>(null),[previewComparison,setPreviewComparison]=useState<PromoComparison|null>(null),[selectedFile,setSelectedFile]=useState<File|null>(null);
 const[lob,setLob]=useState("iPhone"),[query,setQuery]=useState(""),[searchAll,setSearchAll]=useState(false),[scope,setScope]=useState<PromoScope>("ALL"),[stockFilter,setStockFilter]=useState<"ALL"|"READY">("ALL"),[endingWindow,setEndingWindow]=useState(7),[showFilters,setShowFilters]=useState(false),[view,setView]=useState<ViewMode>("promo"),[detail,setDetail]=useState<PromoCatalogItem|null>(null);

 const load=useCallback(async()=>{setLoading(true);setError("");setSohWarning("");try{const[p,s]=await Promise.all([fetch("/api/promo-board",{cache:"no-store"}),fetch("/api/promo-board-soh",{cache:"no-store"})]);const pj=await p.json() as PromoResponse,sj=await s.json() as SohResponse;if(!p.ok)throw new Error(pj.error||"Promo Board gagal dibaca");setActive(pj.active||null);setHistory(pj.history||[]);if(s.ok)setSoh(sj);else{setSoh({rows:[]});setSohWarning(sj.error||"SOH belum dapat dibaca")}}catch(e){setError(e instanceof Error?e.message:"Gagal membaca Promo Board")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);

 const catalog=useMemo(()=>buildPromoCatalog(active?.products||[],soh.rows||[]),[active,soh.rows]);
 const lobs=useMemo(()=>LOB_ORDER.filter(x=>catalog.some(i=>i.lob===x)),[catalog]);
 useEffect(()=>{if(lobs.length&&!lobs.includes(lob))setLob(lobs[0])},[lobs,lob]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();let rows=searchAll&&q?catalog:catalog.filter(i=>i.lob===lob);if(q)rows=rows.filter(i=>searchText(i).includes(q));if(scope==="ACTIVE")rows=rows.filter(isActive);if(scope==="ENDING")rows=rows.filter(i=>i.group.promoStatus==="ENDING_SOON"&&i.group.daysRemaining!=null&&i.group.daysRemaining>=0&&i.group.daysRemaining<=endingWindow);if(stockFilter==="READY")rows=rows.filter(i=>i.stockStatus==="READY");return rows},[catalog,lob,query,searchAll,scope,endingWindow,stockFilter]);
 const modelGroups=useMemo(()=>{const map=new Map<string,PromoCatalogItem[]>();for(const item of filtered){const key=`${item.lob}|${item.model}`;const current=map.get(key)||[];current.push(item);map.set(key,current)}return Array.from(map.entries()).map(([key,items])=>({key,model:items[0].model,lob:items[0].lob,items})).sort((a,b)=>a.model.localeCompare(b.model,undefined,{numeric:true}))},[filtered]);
 const comparison=useMemo(()=>comparePromoPriceLists(history[0]||null,active),[history,active]);
 const stats=useMemo(()=>({models:modelGroups.length,sku:filtered.reduce((n,i)=>n+i.group.variants.length,0),ready:filtered.filter(i=>i.stockStatus==="READY").length}),[modelGroups,filtered]);

 const previewFile=async(file:File)=>{setBusy(true);setError("");setSelectedFile(file);try{const form=new FormData();form.append("file",file);form.append("mode","preview");const r=await fetch("/api/promo-board",{method:"POST",body:form}),j=await r.json() as PreviewResponse;if(!r.ok||!j.preview)throw new Error(j.error||"Pricelist gagal dianalisa");setPreview(j.preview);setPreviewComparison(j.comparison||null)}catch(e){setPreview(null);setSelectedFile(null);setError(e instanceof Error?e.message:"Pricelist gagal dianalisa")}finally{setBusy(false)}};
 const activate=async()=>{if(!selectedFile)return;setBusy(true);setError("");try{const form=new FormData();form.append("file",selectedFile);form.append("mode","activate");const r=await fetch("/api/promo-board",{method:"POST",body:form}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal mengaktifkan Pricelist");setPreview(null);setPreviewComparison(null);setSelectedFile(null);if(fileRef.current)fileRef.current.value="";await load()}catch(e){setError(e instanceof Error?e.message:"Gagal mengaktifkan Pricelist")}finally{setBusy(false)}};

 return <main className="min-h-[100dvh] bg-slate-50 pb-[calc(28px+env(safe-area-inset-bottom))] text-slate-950 dark:bg-slate-900 dark:text-white"><div className="mx-auto max-w-7xl px-4 py-4 sm:px-6 lg:px-8">
  <header className="flex items-start justify-between gap-3"><div><a href="/" className="inline-flex items-center gap-1 text-xs font-black text-slate-500"><ArrowLeft className="size-4"/> Dashboard M238</a><h1 className="mt-3 text-3xl font-black tracking-[-.04em]">Promo Board</h1><p className="mt-1 text-xs text-slate-500">Pricelist {fmtDate(active?.priceListDate)}{soh.updated?` • SOH ${soh.updated}`:""}</p></div><button onClick={()=>fileRef.current?.click()} className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-2xl bg-blue-600 px-3 text-xs font-black text-white"><Upload className="size-4"/><span className="hidden sm:inline">Update Pricelist</span><span className="sm:hidden">Update</span></button><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void previewFile(f)}}/></header>
  {error?<div className="mt-4 flex items-center gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm font-bold text-rose-700"><XCircle className="size-5"/>{error}</div>:null}{sohWarning?<div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-700">{sohWarning}</div>:null}
  {preview?<section className="mt-4 rounded-3xl border border-blue-200 bg-white p-4 shadow-sm dark:border-blue-900 dark:bg-slate-950"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Preview Pricelist</p><h2 className="mt-1 font-black">{preview.fileName}</h2><p className="text-xs text-slate-500">{preview.totalSku} SKU • {fmtDate(preview.priceListDate)} • {preview.warnings.length} warning</p></div><div className="flex gap-2"><button onClick={()=>{setPreview(null);setSelectedFile(null)}} className="min-h-11 rounded-xl border px-3 text-sm font-black">Batal</button><button onClick={()=>void activate()} className="min-h-11 rounded-xl bg-emerald-600 px-3 text-sm font-black text-white">Gunakan Sebagai Aktif</button></div></div>{previewComparison?<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Harga Turun",previewComparison.counts.PROMO_PRICE_DOWN],["Harga Naik",previewComparison.counts.PROMO_PRICE_UP],["Promo Baru",previewComparison.counts.NEW_PROMO+previewComparison.counts.NEW_PRODUCT],["Promo Berakhir",previewComparison.counts.PROMO_ENDED+previewComparison.counts.REMOVED_PRODUCT]].map(([label,value])=><div key={String(label)} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</div>:null}<div className="mt-3 flex items-center gap-2 text-xs font-bold text-emerald-700"><CheckCircle2 className="size-4"/> Preview dibaca sebelum aktivasi.</div></section>:null}

  <div className="mt-4 flex rounded-2xl bg-slate-200/70 p-1 dark:bg-slate-800">{(["promo","changes","history"] as ViewMode[]).map(v=><button key={v} onClick={()=>setView(v)} className={`min-h-10 flex-1 rounded-xl text-xs font-black ${view===v?"bg-white shadow-sm dark:bg-slate-950":"text-slate-500"}`}>{v==="promo"?"Pricelist":v==="changes"?"Perubahan":"Riwayat"}</button>)}</div>

  {view==="promo"?<>
   <div className="mt-4 flex gap-2 overflow-x-auto pb-1">{lobs.map(x=><button key={x} onClick={()=>{setLob(x);setQuery("");setSearchAll(false)}} className={`min-h-11 shrink-0 rounded-2xl px-4 text-sm font-black ${lob===x?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-white text-slate-600 shadow-sm dark:bg-slate-950 dark:text-slate-300"}`}>{x}</button>)}</div>
   <section className="mt-4 rounded-3xl border bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari model, capacity, warna, atau SAP..." className="h-12 w-full rounded-2xl border bg-transparent pl-10 pr-4 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-200"/></div><div className="mt-2 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>{setScope("ALL");setStockFilter("ALL")}} className={`min-h-9 shrink-0 rounded-xl px-3 text-[11px] font-black ${scope==="ALL"&&stockFilter==="ALL"?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"bg-slate-100 text-slate-600 dark:bg-slate-900"}`}>Semua</button><button onClick={()=>{setScope("ACTIVE");setStockFilter("ALL")}} className={`min-h-9 shrink-0 rounded-xl px-3 text-[11px] font-black ${scope==="ACTIVE"?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-900"}`}>Promo Aktif</button><button onClick={()=>{setStockFilter("READY");setScope("ALL")}} className={`min-h-9 shrink-0 rounded-xl px-3 text-[11px] font-black ${stockFilter==="READY"?"bg-emerald-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-900"}`}>Ready</button><button onClick={()=>{setScope("ENDING");setStockFilter("ALL")}} className={`min-h-9 shrink-0 rounded-xl px-3 text-[11px] font-black ${scope==="ENDING"?"bg-amber-500 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-900"}`}>Akan Berakhir</button><button onClick={()=>setShowFilters(v=>!v)} className="inline-flex min-h-9 shrink-0 items-center gap-1 rounded-xl bg-slate-100 px-3 text-[11px] font-black text-slate-600 dark:bg-slate-900"><SlidersHorizontal className="size-3.5"/> Filter</button></div>{showFilters?<div className="mt-2 flex flex-wrap items-center gap-3 border-t pt-3 text-xs"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={searchAll} onChange={e=>setSearchAll(e.target.checked)}/> Cari semua LOB</label>{scope==="ENDING"?<label className="font-bold">Batas <select value={endingWindow} onChange={e=>setEndingWindow(Number(e.target.value))} className="ml-1 rounded-lg border bg-transparent px-2 py-1"><option value={3}>3 hari</option><option value={7}>7 hari</option><option value={14}>14 hari</option></select></label>:null}</div>:null}</section>
   <div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span><b>{stats.models}</b> model • {stats.sku} SKU</span><span>{stats.ready} pilihan ready</span></div>
   <div className="mt-4 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{loading?<div className="col-span-full rounded-3xl border bg-white p-8 text-center text-sm text-slate-400 dark:bg-slate-950">Memuat digital pricelist...</div>:modelGroups.length?modelGroups.map(group=><ModelCard key={group.key} model={group.model} items={group.items} onDetail={setDetail}/>):<div className="col-span-full rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Tidak ada produk yang cocok.</div>}</div>
  </>:view==="changes"?<section className="mt-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Harga Turun",comparison.counts.PROMO_PRICE_DOWN],["Harga Naik",comparison.counts.PROMO_PRICE_UP],["Promo Baru",comparison.counts.NEW_PROMO+comparison.counts.NEW_PRODUCT],["Promo Berakhir",comparison.counts.PROMO_ENDED+comparison.counts.REMOVED_PRODUCT]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950"><p className="text-xs text-slate-400">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div><div className="mt-3 space-y-2">{comparison.changes.filter(x=>x.type!=="UNCHANGED").slice(0,100).map(x=><div key={`${x.type}-${x.sapArticle}`} className="rounded-2xl border bg-white p-4 text-sm shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between gap-3"><div><b>{x.description}</b><p className="mt-1 text-xs text-slate-400">{x.sapArticle}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black dark:bg-slate-900">{changeLabel(x.type)}</span></div></div>)}</div></section>:<section className="mt-4 space-y-3">{history.length?history.map(x=><div key={x.id||`${x.fileName}-${x.uploadedAt}`} className="flex items-center justify-between gap-3 rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div><b>{fmtDate(x.priceListDate)}</b><p className="mt-1 text-xs text-slate-500">{x.fileName}</p>{x.uploadedAt?<p className="mt-1 text-[10px] text-slate-400">Upload {new Date(x.uploadedAt).toLocaleString("id-ID")}</p>:null}</div><div className="text-right"><p className="font-black">{x.totalSku} SKU</p><p className="text-xs text-slate-400">{x.warnings.length} warning</p></div></div>):<div className="rounded-3xl border border-dashed p-8 text-center text-sm text-slate-400">Belum ada riwayat Pricelist.</div>}</section>}
 </div>{detail?<DetailSheet item={detail} onClose={()=>setDetail(null)}/>:null}</main>
}
