"use client"
import {useEffect,useMemo,useState} from "react"
import type {M238Payload,StaffMetric} from "@/lib/m238-types"

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0})
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`)
const monthName=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`))
const ach=(v:number,t:number)=>t?v/t*100:0

function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-black text-slate-950">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>}
function Row({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="grid gap-1 border-b px-4 py-3 last:border-b-0 sm:grid-cols-[220px_1fr] sm:items-center"><div className="text-sm font-bold text-slate-500">{label}</div><div><div className="font-black text-slate-950">{value}</div>{sub&&<div className="text-xs text-slate-400">{sub}</div>}</div></div>}

export default function StaffProductivity(){
 const[period,setPeriod]=useState("2026-09"),[staff,setStaff]=useState("ALL"),[data,setData]=useState<M238Payload|null>(null),[loading,setLoading]=useState(true)
 useEffect(()=>{setLoading(true);fetch(`/api/data?period=${period}`).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[period])
 const rows=data?.monthlyStaff??[],selected=useMemo(()=>rows.find(x=>x.id===staff)||null,[rows,staff])
 const total=useMemo(()=>rows.reduce((a,r)=>({target:a.target+r.targets.amount,amount:a.amount+r.amount,device:a.device+r.device,acc:a.acc+r.accessories,vas:a.vas+r.vas,qty:a.qty+r.qty,inv:a.inv+r.invoices,iphone:a.iphone+r.lob.iphone,mac:a.mac+r.lob.mac,ipad:a.ipad+r.lob.ipad,watch:a.watch+r.lob.watch,airpods:a.airpods+r.lob.airpods,qoala:a.qoala+r.vasDetail.qoala.value,telkomsel:a.telkomsel+r.vasDetail.telkomsel.value,xl:a.xl+r.vasDetail.xl.value,indosat:a.indosat+r.vasDetail.indosat.value}),{target:0,amount:0,device:0,acc:0,vas:0,qty:0,inv:0,iphone:0,mac:0,ipad:0,watch:0,airpods:0,qoala:0,telkomsel:0,xl:0,indosat:0}),[rows])
 if(loading&&!data)return <div className="grid min-h-screen place-items-center bg-slate-50 font-bold text-slate-500">Memuat produktivitas staff…</div>
 return <main className="min-h-screen bg-slate-50 p-4 text-slate-950 sm:p-7"><div className="mx-auto max-w-7xl space-y-5"><div><a href="/" className="text-sm font-bold text-blue-600">← Kembali ke Dashboard M238</a><h1 className="mt-3 text-3xl font-black">Produktivitas Staff M238</h1><p className="mt-1 text-sm text-slate-500">Rekap seluruh produktivitas staff. Pilih satu staff untuk melihat detail vertikal yang lebih jelas.</p></div>
 <section className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-2"><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Bulan</span><select value={period} onChange={e=>{setPeriod(e.target.value);setStaff("ALL")}} className="h-11 w-full rounded-xl border px-3 font-bold">{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Staff</span><select value={staff} onChange={e=>setStaff(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-bold"><option value="ALL">Semua Staff</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label></section>
 {staff==="ALL"?<AllStaff rows={rows} total={total}/>:selected?<StaffDetail r={selected}/>:<div className="rounded-2xl border bg-white p-6 text-slate-400">Staff tidak ditemukan.</div>}</div></main>
}

function AllStaff({rows,total}:{rows:StaffMetric[];total:any}){return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total Target" value={money.format(total.target)}/><Metric label="Achievement" value={money.format(total.amount)} sub={pct(ach(total.amount,total.target))}/><Metric label="UPT" value={(total.inv?total.qty/total.inv:0).toFixed(1)} sub={`${total.qty} unit / ${total.inv} transaksi`}/><Metric label="ATV" value={money.format(total.inv?total.amount/total.inv:0)}/></section><div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[1200px]"><thead><tr>{["Staff","Target","Achievement","%","Device","ACC","VAS","UPT","ATV","iPhone","MacBook","iPad","Watch","AirPods","Qoala","Telkomsel","XL","Indosat"].map(h=><th key={h} className="px-3 py-3 text-left text-xs font-black uppercase text-slate-400">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-3"><b>{r.name}</b><div className="text-xs text-slate-400">{r.position}</div></td><td className="px-3 py-3">{money.format(r.targets.amount)}</td><td className="px-3 py-3 font-bold">{money.format(r.amount)}</td><td className="px-3 py-3">{pct(ach(r.amount,r.targets.amount))}</td><td className="px-3 py-3">{money.format(r.device)}</td><td className="px-3 py-3">{money.format(r.accessories)}</td><td className="px-3 py-3">{money.format(r.vas)}</td><td className="px-3 py-3">{r.upt.toFixed(1)}</td><td className="px-3 py-3">{money.format(r.atv)}</td><td className="px-3 py-3">{r.lob.iphone}</td><td className="px-3 py-3">{r.lob.mac}</td><td className="px-3 py-3">{r.lob.ipad}</td><td className="px-3 py-3">{r.lob.watch}</td><td className="px-3 py-3">{r.lob.airpods}</td><td className="px-3 py-3">{money.format(r.vasDetail.qoala.value)}</td><td className="px-3 py-3">{money.format(r.vasDetail.telkomsel.value)}</td><td className="px-3 py-3">{money.format(r.vasDetail.xl.value)}</td><td className="px-3 py-3">{money.format(r.vasDetail.indosat.value)}</td></tr>)}</tbody></table></div></div>}

function StaffDetail({r}:{r:StaffMetric}){const achievement=ach(r.amount,r.targets.amount),deviceAch=ach(r.device,r.targets.device),accAch=ach(r.accessories,r.targets.accessories),vasAch=ach(r.vas,r.targets.vas);return <div className="space-y-5"><section className="rounded-3xl bg-gradient-to-br from-[#0872b9] to-[#075b97] p-5 text-white shadow-lg"><p className="text-sm text-blue-100">Detail Produktivitas Staff</p><h2 className="mt-1 text-2xl font-black">{r.name}</h2><p className="text-sm text-blue-100">{r.position||"Staff M238"}</p></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Target" value={money.format(r.targets.amount)}/><Metric label="Achievement" value={money.format(r.amount)} sub={pct(achievement)}/><Metric label="UPT" value={r.upt.toFixed(1)} sub={`${r.qty} unit / ${r.invoices} transaksi`}/><Metric label="ATV" value={money.format(r.atv)}/></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><Row label="Achievement" value={`${money.format(r.amount)} / ${money.format(r.targets.amount)}`} sub={pct(achievement)}/><Row label="Device" value={`${money.format(r.device)} / ${money.format(r.targets.device)}`} sub={pct(deviceAch)}/><Row label="Accessories" value={`${money.format(r.accessories)} / ${money.format(r.targets.accessories)}`} sub={pct(accAch)}/><Row label="VAS" value={`${money.format(r.vas)} / ${money.format(r.targets.vas)}`} sub={pct(vasAch)}/><Row label="iPhone" value={`${r.lob.iphone} unit`}/><Row label="MacBook" value={`${r.lob.mac} unit`}/><Row label="iPad" value={`${r.lob.ipad} unit`}/><Row label="Apple Watch" value={`${r.lob.watch} unit`}/><Row label="AirPods" value={`${r.lob.airpods} unit`}/><Row label="Qoala" value={`${r.vasDetail.qoala.qty} qty • ${money.format(r.vasDetail.qoala.value)}`}/><Row label="Telkomsel" value={`${r.vasDetail.telkomsel.qty} qty • ${money.format(r.vasDetail.telkomsel.value)}`}/><Row label="XL" value={`${r.vasDetail.xl.qty} qty • ${money.format(r.vasDetail.xl.value)}`}/><Row label="Indosat" value={`${r.vasDetail.indosat.qty} qty • ${money.format(r.vasDetail.indosat.value)}`}/><Row label="Est. Incentive" value={money.format(r.incentive.total)} sub={`Device ${money.format(r.incentive.mac+r.incentive.iphone+r.incentive.ipad+r.incentive.watch)} • ACC ${money.format(r.incentive.accessories)} • Qoala ${money.format(r.incentive.qoala)}`}/></section></div>}
