"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {ExportMenu} from "@/components/export-menu";
import {exportReportPdf,exportReportPng,exportReportXlsx,type ExportSheet} from "@/lib/dashboard-export";
import type {M238Payload,StaffMetric} from "@/lib/m238-types";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const shortMoney=(v:number)=>{const a=Math.abs(v);if(a>=1_000_000_000)return`Rp ${(v/1_000_000_000).toLocaleString("id-ID",{maximumFractionDigits:2})} M`;if(a>=1_000_000)return`Rp ${(v/1_000_000).toLocaleString("id-ID",{maximumFractionDigits:0})} Jt`;return money.format(v)};
const pct=(v:number)=>`${v.toLocaleString("id-ID",{maximumFractionDigits:1})}%`;
const ach=(r:StaffMetric)=>r.targets.amount?r.amount/r.targets.amount*100:0;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`);
const monthName=(v:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${v}-01T00:00:00`));
type SortKey="achievement"|"sales"|"upt"|"atv";
function status(a:number,top=false){if(top)return{label:"Top Performer",cls:"bg-emerald-50 text-emerald-700"};if(a>=100)return{label:"Achieved",cls:"bg-emerald-50 text-emerald-700"};if(a>=90)return{label:"On Track",cls:"bg-blue-50 text-blue-700"};if(a>=80)return{label:"Need Push",cls:"bg-amber-50 text-amber-700"};return{label:"Need Attention",cls:"bg-rose-50 text-rose-700"}}
function Summary({label,value,sub}:{label:string;value:string;sub?:string}){return <article className="min-w-[170px] rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><p className="text-[11px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 truncate text-lg font-black">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</article>}

export default function StaffPerformanceV2(){
 const reportRef=useRef<HTMLDivElement>(null),[period,setPeriod]=useState(today().slice(0,7)),[staffFilter,setStaffFilter]=useState("ALL"),[search,setSearch]=useState(""),[sort,setSort]=useState<SortKey>("achievement"),[data,setData]=useState<M238Payload|null>(null),[loading,setLoading]=useState(true),[selected,setSelected]=useState<StaffMetric|null>(null);
 const load=async()=>{setLoading(true);try{const r=await fetch(`/api/data?period=${period}&refresh=1&t=${Date.now()}`,{cache:"no-store"});setData(await r.json())}finally{setLoading(false)}};
 useEffect(()=>{void load()},[period]);
 const all=data?.monthlyStaff||[];
 const sorted=useMemo(()=>{const rows=all.filter(r=>(staffFilter==="ALL"||r.id===staffFilter)&&(!search||r.name.toLowerCase().includes(search.toLowerCase())));return [...rows].sort((a,b)=>sort==="sales"?b.amount-a.amount:sort==="upt"?b.upt-a.upt:sort==="atv"?b.atv-a.atv:ach(b)-ach(a))},[all,staffFilter,search,sort]);
 const rankedAll=useMemo(()=>[...all].sort((a,b)=>ach(b)-ach(a)),[all]),top=rankedAll[0],avgAch=all.length?all.reduce((s,r)=>s+ach(r),0)/all.length:0,avgUpt=all.length?all.reduce((s,r)=>s+r.upt,0)/all.length:0,avgAtv=all.length?all.reduce((s,r)=>s+r.atv,0)/all.length:0,need=all.filter(r=>ach(r)<80).length;
 const downloadXls=async()=>{const rows:ExportSheet[]=[{name:"Staff Ranking",rows:[["Rank","Staff","Sales","Target","Achievement","Accessories","VAS","UPT","ATV","Status"],...sorted.map((r,i)=>[i+1,r.name,r.amount,r.targets.amount,ach(r)/100,r.accessories,r.vas,r.upt,r.atv,status(ach(r),rankedAll[0]?.id===r.id).label])]}];await exportReportXlsx(rows,`M238-Staff-Performance-${period}`)};
 const downloadPdf=async()=>{if(!reportRef.current)throw new Error("Tampilan Staff Performance belum siap.");await exportReportPdf(reportRef.current,`M238-Staff-Performance-${period}`)};
 const downloadPicture=async()=>{if(!reportRef.current)throw new Error("Tampilan Staff Performance belum siap.");await exportReportPng(reportRef.current,`M238-Staff-Performance-${period}`)};
 const click=(r:StaffMetric)=>setSelected(r);
 return <div ref={reportRef} className="space-y-5">
  <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><h1 className="text-3xl font-black">Staff Performance</h1><p className="mt-1 text-sm text-slate-500">Monitor pencapaian dan produktivitas staff berdasarkan periode yang dipilih.</p></div><div className="flex flex-wrap items-end gap-2"><label><span className="mb-1 block text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Bulan</span><select value={period} onChange={e=>{setPeriod(e.target.value);setSelected(null)}} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-950">{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label><label><span className="mb-1 block text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Staff</span><select value={staffFilter} onChange={e=>setStaffFilter(e.target.value)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-950"><option value="ALL">Semua Staff</option>{all.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button onClick={()=>void load()} className="h-10 rounded-xl border bg-white px-4 text-sm font-black dark:bg-slate-950">{loading?"Memuat…":"Perbarui"}</button><ExportMenu onXls={downloadXls} onPdf={downloadPdf} onPicture={downloadPicture}/></div></header>

  <section className="-mx-1 flex gap-3 overflow-x-auto px-1 pb-1 xl:grid xl:grid-cols-5"><Summary label="Top Performer" value={top?.name||"—"} sub={top?pct(ach(top)):""}/><Summary label="Average Achievement" value={pct(avgAch)}/><Summary label="Average UPT" value={avgUpt.toLocaleString("id-ID",{maximumFractionDigits:1})}/><Summary label="Average ATV" value={shortMoney(avgAtv)}/><Summary label="Need Attention" value={`${need} Staff`}/></section>

  <section className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="flex flex-col gap-3 border-b p-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-black">Staff Ranking</h2><p className="mt-1 text-xs text-slate-500">Default diurutkan berdasarkan achievement tertinggi.</p></div><div className="flex flex-col gap-2 sm:flex-row"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff" className="h-10 rounded-xl border px-3 text-sm dark:bg-slate-900"/><select value={sort} onChange={e=>setSort(e.target.value as SortKey)} className="h-10 rounded-xl border bg-white px-3 text-sm font-bold dark:bg-slate-900"><option value="achievement">Sort: Achievement</option><option value="sales">Sort: Sales</option><option value="upt">Sort: UPT</option><option value="atv">Sort: ATV</option></select></div></div>
   <div className="hidden overflow-x-auto md:block"><table className="min-w-full text-sm"><thead><tr className="text-slate-400"><th className="px-3 py-3 text-center">Rank</th><th className="px-3 py-3 text-left">Staff</th><th className="px-3 py-3 text-right">Sales</th><th className="px-3 py-3 text-right">Target</th><th className="px-3 py-3 text-right">Achievement</th><th className="px-3 py-3 text-right">Accessories</th><th className="px-3 py-3 text-right">VAS</th><th className="px-3 py-3 text-right">UPT</th><th className="px-3 py-3 text-right">ATV</th><th className="px-4 py-3 text-right">Status</th></tr></thead><tbody>{sorted.map((r,i)=>{const a=ach(r),topRow=rankedAll[0]?.id===r.id,st=status(a,topRow);return <tr key={r.id} onClick={()=>click(r)} className="cursor-pointer border-t hover:bg-slate-50 dark:hover:bg-slate-900"><td className="px-3 py-3 text-center font-black">{i+1}</td><td className="px-3 py-3 font-black">{r.name}</td><td className="px-3 py-3 text-right">{shortMoney(r.amount)}</td><td className="px-3 py-3 text-right">{shortMoney(r.targets.amount)}</td><td className={`px-3 py-3 text-right font-black ${a>=100?"text-emerald-600":a>=90?"text-blue-600":a>=80?"text-amber-600":"text-rose-600"}`}>{pct(a)}</td><td className="px-3 py-3 text-right">{shortMoney(r.accessories)}</td><td className="px-3 py-3 text-right">{shortMoney(r.vas)}</td><td className="px-3 py-3 text-right">{r.upt.toLocaleString("id-ID",{maximumFractionDigits:1})}</td><td className="px-3 py-3 text-right">{shortMoney(r.atv)}</td><td className="px-4 py-3 text-right"><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${st.cls}`}>{st.label}</span></td></tr>})}</tbody></table></div>
   <div className="divide-y md:hidden">{sorted.map((r,i)=>{const a=ach(r),st=status(a,rankedAll[0]?.id===r.id);return <button key={r.id} onClick={()=>click(r)} className="block w-full p-4 text-left"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-slate-400">#{i+1}</p><b>{r.name}</b></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${st.cls}`}>{st.label}</span></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-slate-400">Sales</p><b>{shortMoney(r.amount)}</b></div><div><p className="text-xs text-slate-400">Achievement</p><b>{pct(a)}</b></div><div><p className="text-xs text-slate-400">UPT</p><b>{r.upt.toLocaleString("id-ID",{maximumFractionDigits:1})}</b></div><div><p className="text-xs text-slate-400">ATV</p><b>{shortMoney(r.atv)}</b></div></div></button>})}</div>
  </section>

  {selected&&<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Staff Detail</p><h2 className="mt-1 text-2xl font-black">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">Sales Achievement <b className="text-slate-800 dark:text-white">{shortMoney(selected.amount)} / {shortMoney(selected.targets.amount)} • {pct(ach(selected))}</b></p></div><button onClick={()=>setSelected(null)} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Tutup</button></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Accessories",shortMoney(selected.accessories)],["VAS",shortMoney(selected.vas)],["UPT",selected.upt.toLocaleString("id-ID",{maximumFractionDigits:1})],["ATV",shortMoney(selected.atv)]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-xs font-bold text-slate-400">{l}</p><p className="mt-1 font-black">{v}</p></div>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="overflow-hidden rounded-xl border"><div className="border-b px-4 py-3"><b>Achievement by LOB</b></div><table className="w-full text-sm"><thead><tr><th className="px-4 py-2 text-left">LOB</th><th className="px-4 py-2 text-right">Qty</th></tr></thead><tbody>{[["iPhone",selected.lob.iphone],["MacBook",selected.lob.mac],["iPad",selected.lob.ipad],["Apple Watch",selected.lob.watch],["AirPods",selected.lob.airpods]].map(([l,v])=><tr key={String(l)} className="border-t"><td className="px-4 py-2.5">{l}</td><td className="px-4 py-2.5 text-right font-bold">{v}</td></tr>)}</tbody></table></div><div className="overflow-hidden rounded-xl border"><div className="border-b px-4 py-3"><b>VAS Performance</b><p className="mt-1 text-[11px] text-slate-400">Data existing M238 dipertahankan; iCloud belum memiliki field khusus.</p></div><table className="w-full text-sm"><thead><tr><th className="px-4 py-2 text-left">VAS</th><th className="px-3 py-2 text-right">Qty</th><th className="px-4 py-2 text-right">Amount</th></tr></thead><tbody>{[["Qoala",selected.vasDetail.qoala],["Telkomsel",selected.vasDetail.telkomsel],["XL",selected.vasDetail.xl],["Indosat",selected.vasDetail.indosat]].map(([l,x])=>{const d=x as {qty:number;value:number};return <tr key={String(l)} className="border-t"><td className="px-4 py-2.5">{l as string}</td><td className="px-3 py-2.5 text-right font-bold">{d.qty}</td><td className="px-4 py-2.5 text-right">{money.format(d.value)}</td></tr>})}<tr className="border-t"><td className="px-4 py-2.5">iCloud</td><td className="px-3 py-2.5 text-right text-slate-400">—</td><td className="px-4 py-2.5 text-right text-slate-400">Belum mapped</td></tr></tbody></table></div></div></section>}
 </div>
}
