"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import type {M238Payload,StaffMetric} from "@/lib/m238-types";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const safe=(v:number)=>Number.isFinite(v)?v:0;
const ach=(v:number,t:number)=>t?safe(v/t*100):0;
function paceFor(period:string){const now=new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date()),dim=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate();if(period<now.slice(0,7))return 100;if(period>now.slice(0,7))return 0;return Number(now.slice(8,10))/dim*100}
function paceStatus(a:number,p:number){const d=a-p;if(d>5)return{label:"Ahead",cls:"bg-emerald-50 text-emerald-700"};if(d>=-5)return{label:"On Track",cls:"bg-blue-50 text-blue-700"};if(d>=-15)return{label:"Need Push",cls:"bg-amber-50 text-amber-700"};return{label:"Behind",cls:"bg-rose-50 text-rose-700"}}
function Badge({label,cls}:{label:string;cls:string}){return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${cls}`}><span className="size-1.5 rounded-full bg-current"/>{label}</span>}
function Box({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="rounded-xl border bg-slate-50/60 p-3 dark:bg-slate-900"><div className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 font-black">{value}</div>{sub?<div className="mt-1 text-xs text-slate-400">{sub}</div>:null}</div>}
function TotalVas({r}:{r:StaffMetric}){const vs=Object.values(r.vasDetail),qty=vs.reduce((a,x)=>a+x.qty,0),value=vs.reduce((a,x)=>a+x.value,0);return <><b>{num.format(qty)}</b><div className="text-xs text-slate-400">{money.format(value)}</div></>}

type DetailPayload={daily:Array<{date:string;sales:number;trx:number;device:number;accessories:number;accessoriesQty:number;vas:number;qty:number;upt:number;atv:number}>;accessoriesQty:number;lob:{iphone:number;mac:number;ipad:number;watch:number;airpods:number};vas:{qoala:{qty:number;value:number};telkomsel:{qty:number;value:number};xl:{qty:number;value:number};indosat:{qty:number;value:number}};error?:string};

export default function StaffPerformanceLiveEnhancer(){const[mount,setMount]=useState<HTMLElement|null>(null),[period,setPeriod]=useState(""),[staffId,setStaffId]=useState("ALL"),[data,setData]=useState<M238Payload|null>(null),[detail,setDetail]=useState<DetailPayload|null>(null);
 useEffect(()=>{let cleanup:undefined|(()=>void);const sync=()=>{const h=[...document.querySelectorAll("h1")].find(x=>x.textContent?.trim()==="Staff Performance") as HTMLElement|undefined;if(!h){setMount(null);return}const root=h.parentElement?.parentElement as HTMLElement|undefined;if(!root)return;const sections=[...root.children].filter(x=>x.tagName==="SECTION") as HTMLElement[];if(sections.length<2)return;let m=root.querySelector<HTMLElement>("[data-staff-live-enhancer]");if(!m){m=document.createElement("div");m.dataset.staffLiveEnhancer="1";m.className="space-y-5";root.appendChild(m)}sections.slice(1).forEach(s=>s.style.display="none");const selects=sections[0].querySelectorAll("select"),p=selects[0] as HTMLSelectElement|undefined,st=selects[1] as HTMLSelectElement|undefined;if(p)setPeriod(p.value);if(st)setStaffId(st.value);const on=()=>{if(p)setPeriod(p.value);if(st)setStaffId(st.value)};p?.addEventListener("change",on);st?.addEventListener("change",on);cleanup=()=>{p?.removeEventListener("change",on);st?.removeEventListener("change",on);sections.slice(1).forEach(s=>s.style.display="");m?.remove()};setMount(m)};sync();const ob=new MutationObserver(sync);ob.observe(document.body,{subtree:true,childList:true});const id=setInterval(sync,700);return()=>{ob.disconnect();clearInterval(id);cleanup?.()}},[]);
 useEffect(()=>{if(!mount||!period)return;let dead=false;fetch(`/api/data?period=${period}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!dead)setData(j)});return()=>{dead=true}},[mount,period]);
 useEffect(()=>{if(!mount||!period||staffId==="ALL"){setDetail(null);return}let dead=false;fetch(`/api/staff-performance-detail?period=${period}&staffId=${encodeURIComponent(staffId)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(!dead)setDetail(j)});return()=>{dead=true}},[mount,period,staffId]);
 if(!mount)return null;return createPortal(<Enhanced data={data} detail={detail} period={period} staffId={staffId}/>,mount)}

function Enhanced({data,detail,period,staffId}:{data:M238Payload|null;detail:DetailPayload|null;period:string;staffId:string}){const all=data?.monthlyStaff??[],row=all.find(x=>x.id===staffId),pace=paceFor(period);if(!data)return <section className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-950">Memuat Staff Performance…</section>;return staffId==="ALL"?<Overview rows={all} pace={pace}/>:row?<StaffDetail r={row} detail={detail} period={period} pace={pace}/>:<section className="rounded-2xl border bg-white p-6 shadow-sm dark:bg-slate-950">Data staff tidak ditemukan.</section>}

function Overview({rows,pace}:{rows:StaffMetric[];pace:number}){const t=rows.reduce((a,r)=>({target:a.target+r.targets.amount,amount:a.amount+r.amount,acc:a.acc+r.accessories,vas:a.vas+r.vas,qty:a.qty+r.qty,trx:a.trx+r.invoices}),{target:0,amount:0,acc:0,vas:0,qty:0,trx:0}),a=ach(t.amount,t.target),status=paceStatus(a,pace),gap=Math.max(0,t.target-t.amount),lob=rows.reduce((x,r)=>({iphone:x.iphone+r.lob.iphone,mac:x.mac+r.lob.mac,ipad:x.ipad+r.lob.ipad,watch:x.watch+r.lob.watch,airpods:x.airpods+r.lob.airpods}),{iphone:0,mac:0,ipad:0,watch:0,airpods:0});const vasKeys=["qoala","telkomsel","xl","indosat"] as const;return <>
<section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm"><b>Team Sales {money.format(t.amount)} / Target {money.format(t.target)}</b><span>Achievement {pct(a)}</span><span>Monthly Pace {pct(pace)}</span><Badge {...status}/><span>Gap {money.format(gap)}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.min(100,a)}%`}}/></div></section>
<section className="overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Staff Performance</h2><p className="mt-1 text-sm text-slate-500">Achievement value bulanan</p></div><table className="w-full min-w-[1180px] text-sm"><thead><tr className="border-b text-slate-500">{["Nama","Target","Achievement","%","Pace","Gap","Accessories","VAS","UPT","ATV","Trx"].map((x,i)=><th key={x} className={`p-3 ${i?"text-right":"text-left"}`}>{x}</th>)}</tr></thead><tbody>{rows.map(r=>{const ar=ach(r.amount,r.targets.amount),st=paceStatus(ar,pace);return <tr key={r.id} className="border-b last:border-0"><td className="p-3"><b>{r.name}</b><div className="text-xs text-slate-400">{r.position}</div></td><td className="p-3 text-right">{money.format(r.targets.amount)}</td><td className="p-3 text-right font-bold">{money.format(r.amount)}</td><td className="p-3 text-right">{pct(ar)}</td><td className="p-3 text-right"><Badge {...st}/></td><td className="p-3 text-right">{money.format(Math.max(0,r.targets.amount-r.amount))}</td><td className="p-3 text-right">{money.format(r.accessories)}</td><td className="p-3 text-right">{money.format(r.vas)}</td><td className="p-3 text-right">{safe(r.upt).toFixed(1)}</td><td className="p-3 text-right">{money.format(safe(r.atv))}</td><td className="p-3 text-right">{num.format(r.invoices)}</td></tr>})}</tbody></table></section>
<section className="overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Achievement by LOB</h2><p className="mt-1 text-sm text-slate-500">Qty per staff</p></div><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-slate-500">{["Nama","iPhone","MacBook","iPad","Apple Watch","AirPods","Total Device"].map((x,i)=><th key={x} className={`p-3 ${i?"text-right":"text-left"}`}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="p-3 font-bold">{r.name}</td><td className="p-3 text-right">{r.lob.iphone}</td><td className="p-3 text-right">{r.lob.mac}</td><td className="p-3 text-right">{r.lob.ipad}</td><td className="p-3 text-right">{r.lob.watch}</td><td className="p-3 text-right">{r.lob.airpods}</td><td className="p-3 text-right font-black">{r.lob.iphone+r.lob.mac+r.lob.ipad+r.lob.watch}</td></tr>})}<tr className="bg-slate-50 font-black dark:bg-slate-900"><td className="p-3">TOTAL</td><td className="p-3 text-right">{lob.iphone}</td><td className="p-3 text-right">{lob.mac}</td><td className="p-3 text-right">{lob.ipad}</td><td className="p-3 text-right">{lob.watch}</td><td className="p-3 text-right">{lob.airpods}</td><td className="p-3 text-right">{lob.iphone+lob.mac+lob.ipad+lob.watch}</td></tr></tbody></table></section>
<section className="overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Achievement VAS</h2><p className="mt-1 text-sm text-slate-500">Qty / Amount per staff</p></div><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3 text-left">Nama</th>{["Qoala","Telkomsel","XL","Indosat","Total VAS"].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="p-3 font-bold">{r.name}</td>{vasKeys.map(k=><td key={k} className="p-3 text-right"><b>{r.vasDetail[k].qty}</b><div className="text-xs text-slate-400">{money.format(r.vasDetail[k].value)}</div></td>)}<td className="p-3 text-right"><TotalVas r={r}/></td></tr>)}</tbody></table></section></>}

function StaffDetail({r,detail,period,pace}:{r:StaffMetric;detail:DetailPayload|null;period:string;pace:number}){const a=ach(r.amount,r.targets.amount),status=paceStatus(a,pace),gap=Math.max(0,r.targets.amount-r.amount),now=new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date()),current=period===now.slice(0,7),dim=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate(),remain=current?Math.max(0,dim-Number(now.slice(8,10))):0,need=current&&remain?gap/remain:0,accQty=detail?.accessoriesQty??0,ar=accQty?r.accessories/accQty:0,vas=detail?.vas??r.vasDetail,lob=detail?.lob??r.lob,daily=detail?.daily??[];const active=daily.filter(x=>x.trx>0),best=[...daily].sort((x,y)=>y.sales-x.sales)[0],bestAtv=[...daily].sort((x,y)=>y.atv-x.atv)[0],bestUpt=[...daily].sort((x,y)=>y.upt-x.upt)[0],zero=daily.filter(x=>x.trx===0).length,avg=active.length?active.reduce((x,y)=>x+y.sales,0)/active.length:0,totalVasQty=Object.values(vas).reduce((x,y)=>x+y.qty,0),totalVasValue=Object.values(vas).reduce((x,y)=>x+y.value,0),deviceTotal=lob.iphone+lob.mac+lob.ipad+lob.watch;return <>
<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="text-xl font-black">{r.name}</h2><p className="mt-1 text-sm text-slate-500">{r.position||"Staff"} · {new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${period}-01T00:00:00`))}</p></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-center gap-3"><h2 className="font-extrabold">Sales Achievement</h2><Badge {...status}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Box label="Target" value={money.format(r.targets.amount)}/><Box label="Achievement" value={money.format(r.amount)} sub={pct(a)}/><Box label="Monthly Pace" value={pct(pace)}/><Box label="Gap" value={money.format(gap)}/>{current?<Box label="Need / Day" value={money.format(need)}/>:<Box label="Final Result" value={pct(a)}/>}<Box label="Transaction" value={num.format(r.invoices)}/><Box label="UPT" value={safe(r.upt).toFixed(1)}/><Box label="ATV" value={money.format(safe(r.atv))}/></div></section>
<section className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="font-extrabold">Device Performance</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><Box label="iPhone" value={num.format(lob.iphone)}/><Box label="MacBook" value={num.format(lob.mac)}/><Box label="iPad" value={num.format(lob.ipad)}/><Box label="Apple Watch" value={num.format(lob.watch)}/><Box label="AirPods" value={num.format(lob.airpods)}/><Box label="Total Device" value={num.format(deviceTotal)}/></div></div><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="font-extrabold">Accessories Performance</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Box label="Accessories Sales" value={money.format(r.accessories)}/><Box label="Accessories Qty" value={num.format(accQty)}/><Box label="AR Accessories" value={money.format(ar)}/></div></div></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="font-extrabold">VAS Performance</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(["qoala","telkomsel","xl","indosat"] as const).map(k=><Box key={k} label={k==="qoala"?"Qoala":k==="telkomsel"?"Telkomsel":k.toUpperCase()} value={`${num.format(vas[k].qty)} / ${money.format(vas[k].value)}`}/>)}<Box label="Total VAS" value={`${num.format(totalVasQty)} / ${money.format(totalVasValue)}`}/></div></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="font-extrabold">Estimated Incentive</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Box label="iPhone" value={money.format(r.incentive.iphone)}/><Box label="MacBook" value={money.format(r.incentive.mac)}/><Box label="iPad" value={money.format(r.incentive.ipad)}/><Box label="Apple Watch" value={money.format(r.incentive.watch)}/><Box label="Accessories" value={money.format(r.incentive.accessories)}/><Box label="Qoala" value={money.format(r.incentive.qoala)}/><Box label="Total Estimated Incentive" value={money.format(r.incentive.total)}/></div></section>
<section className="overflow-x-auto rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-5 py-4"><h2 className="font-extrabold">Daily Performance</h2><p className="mt-1 text-sm text-slate-500">Performance harian pada bulan terpilih</p></div><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-slate-500">{["Date","Sales","Trx","Device","Accessories","VAS","UPT","ATV"].map((x,i)=><th key={x} className={`p-3 ${i?"text-right":"text-left"}`}>{x}</th>)}</tr></thead><tbody>{daily.map(x=><tr key={x.date} className="border-b last:border-0"><td className="p-3">{new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short"}).format(new Date(`${x.date}T00:00:00`))}</td><td className="p-3 text-right">{money.format(x.sales)}</td><td className="p-3 text-right">{x.trx}</td><td className="p-3 text-right">{x.device}</td><td className="p-3 text-right">{money.format(x.accessories)}</td><td className="p-3 text-right">{money.format(x.vas)}</td><td className="p-3 text-right">{safe(x.upt).toFixed(1)}</td><td className="p-3 text-right">{money.format(safe(x.atv))}</td></tr>)}</tbody></table></section>
<section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="font-extrabold">Monthly Insight</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Box label="Best Sales Day" value={best?money.format(best.sales):money.format(0)} sub={best?best.date:"—"}/><Box label="Highest ATV Day" value={bestAtv?money.format(bestAtv.atv):money.format(0)} sub={bestAtv?bestAtv.date:"—"}/><Box label="Highest UPT Day" value={bestUpt?safe(bestUpt.upt).toFixed(1):"0.0"} sub={bestUpt?bestUpt.date:"—"}/><Box label="Zero Sales Days" value={num.format(zero)}/><Box label="Avg Sales / Active Day" value={money.format(avg)}/></div></section></>}
