"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import {Copy,Mail,RefreshCw,TriangleAlert} from "lucide-react";
import {cachedJson} from "@/lib/m238-client-cache";

type Item={lob:string;article:string;description:string;soh:number;soldQty:number;lostCount:number;requestQty:number;priority:"Critical"|"High"|"Medium";reason:string};
type Payload={week:string;period:{from:string;to:string};sohUpdated:string;summary:{recommendations:number;outOfStock:number;weekSales:number;lostFeedback:number};recommendations:Item[];outOfStock:Item[];email:{subject:string;body:string};error?:string};
const num=new Intl.NumberFormat("id-ID");
function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={`m238m-card ${className}`}>{children}</section>}

export default function StockRequestMd(){
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[copied,setCopied]=useState(""),[selected,setSelected]=useState<Record<string,boolean>>({}),[qty,setQty]=useState<Record<string,number>>({});
 const load=async(force=false)=>{setLoading(true);setError("");try{const d=await cachedJson<Payload>("/api/stock-request",force?0:120000,force);if(d.error)throw new Error(d.error);setData(d);setSelected(Object.fromEntries((d.recommendations||[]).map(x=>[x.article,true])));setQty(Object.fromEntries((d.recommendations||[]).map(x=>[x.article,x.requestQty])))}catch(e){setError(e instanceof Error?e.message:"Gagal compile stock request")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const chosen=useMemo(()=>data?.recommendations.filter(x=>selected[x.article]).map(x=>({...x,requestQty:Math.max(0,Number(qty[x.article]??x.requestQty))}))||[],[data,selected,qty]);
 const emailBody=useMemo(()=>{if(!data)return"";const grouped=new Map<string,Item[]>();for(const x of chosen){if(!grouped.has(x.lob))grouped.set(x.lob,[]);grouped.get(x.lob)!.push(x)}const lost=chosen.reduce((a,x)=>a+x.lostCount,0),sold=chosen.reduce((a,x)=>a+x.soldQty,0),lines=["Dear MD Team,","",`Mohon support stock untuk M238 Digimap PIM 2 berdasarkan evaluasi ${data.week} (${data.period.from} s.d. ${data.period.to}).`,`SOH update: ${data.sohUpdated}.`,`Ringkasan: ${chosen.length} item prioritas • ${data.summary.outOfStock} item SOH 0 • ${sold} unit sold pada item prioritas • ${lost} indikasi lost/feedback terkait stock.`,`","Detail request:"];for(const[lob,rows]of grouped){lines.push("",lob);for(const r of rows)lines.push(`- ${r.description||r.article} (${r.article}) | Sold ${r.soldQty} | SOH ${r.soh} | Lost ${r.lostCount} | Request ${r.requestQty} unit | ${r.priority}`)}lines.push("","Mohon dibantu untuk support replenishment item di atas agar opportunity penjualan tidak lost karena ketersediaan stock.","","Terima kasih.","Regards,","M238 Digimap PIM 2");return lines.join("\n")},[data,chosen]);
 const copy=async(type:"subject"|"body")=>{if(!data)return;await navigator.clipboard.writeText(type==="subject"?data.email.subject:emailBody);setCopied(type);setTimeout(()=>setCopied(""),1400)};
 const openMail=()=>{if(!data)return;window.location.href=`mailto:?subject=${encodeURIComponent(data.email.subject)}&body=${encodeURIComponent(emailBody)}`};
 if(loading&&!data)return <div className="m238m-stack"><Card>Memuat SOH, penjualan week berjalan, dan lost stock…</Card></div>;
 if(error&&!data)return <div className="m238m-stack"><Card className="m238m-error">{error}</Card><button className="m238m-primary" onClick={()=>void load(true)}>Coba Lagi</button></div>;
 if(!data)return null;
 return <div className="m238m-stack">
  <Card className="m238m-copy-card"><div className="m238m-copy-head"><div><strong>Stock Request MD</strong><p>{data.week} • SOH {data.sohUpdated}</p></div><button onClick={()=>void load(true)} aria-label="Refresh"><RefreshCw size={17}/></button></div><p>Compile otomatis dari SOH terbaru, penjualan week berjalan, dan feedback/lost terkait stock. Checklist dulu sebelum copy email.</p></Card>
  <div className="m238m-grid"><Card className="m238m-metric"><span>Prioritas</span><strong>{num.format(data.summary.recommendations)}</strong><small>item rekomendasi</small></Card><Card className="m238m-metric"><span>SOH 0</span><strong>{num.format(data.summary.outOfStock)}</strong><small>item kosong</small></Card><Card className="m238m-metric"><span>Week Sales</span><strong>{num.format(data.summary.weekSales)}</strong><small>qty terjual</small></Card><Card className="m238m-metric"><span>Lost/Feedback</span><strong>{num.format(data.summary.lostFeedback)}</strong><small>indikasi stock</small></Card></div>
  <div className="m238m-section-head"><h2>Rekomendasi Request</h2><span>{chosen.length} dipilih</span></div>
  <div className="m238m-list">{data.recommendations.map(r=><Card key={r.article} className="m238m-stock-request-row"><label className="m238m-stock-request-check"><input type="checkbox" checked={!!selected[r.article]} onChange={e=>setSelected(v=>({...v,[r.article]:e.target.checked}))}/><span><strong>{r.description||r.article}</strong><small>{r.article} • {r.lob}</small></span></label><div className="m238m-stock-request-stats"><span>Sold <b>{r.soldQty}</b></span><span>SOH <b>{r.soh}</b></span><span>Lost <b>{r.lostCount}</b></span></div><div className="m238m-stock-request-foot"><span className={`prio ${r.priority.toLowerCase()}`}>{r.priority}</span><small>{r.reason}</small><label>Req <input inputMode="numeric" value={qty[r.article]??r.requestQty} onChange={e=>setQty(v=>({...v,[r.article]:Math.max(0,Number(e.target.value)||0)}))}/></label></div></Card>)}{!data.recommendations.length?<Card className="m238m-empty">Belum ada item yang masuk prioritas request berdasarkan week berjalan.</Card>:null}</div>
  {data.outOfStock.length?<><div className="m238m-section-head"><h2>SOH 0</h2><span>{data.summary.outOfStock} item</span></div><Card className="m238m-copy-card"><p><TriangleAlert size={14} style={{display:"inline",verticalAlign:"-2px"}}/> Tidak semua SOH 0 otomatis masuk email. Item tanpa sales/lost week berjalan tetap ditampilkan sebagai referensi agar produk lama/discontinue tidak langsung direquest.</p></Card><div className="m238m-stock-oos-list">{data.outOfStock.slice(0,15).map(x=><div key={x.article}><span>{x.description||x.article}</span><small>{x.article} • Sold {x.soldQty} • Lost {x.lostCount}</small></div>)}</div></>:null}
  <div className="m238m-section-head"><h2>Draft Email</h2><span>Review sebelum kirim</span></div>
  <Card className="m238m-email-preview"><strong>{data.email.subject}</strong><pre>{emailBody}</pre></Card>
  <div className="m238m-stock-email-actions"><button onClick={()=>void copy("subject")}><Copy size={16}/>{copied==="subject"?"Copied":"Copy Subject"}</button><button onClick={()=>void copy("body")}><Copy size={16}/>{copied==="body"?"Copied":"Copy Email"}</button><button className="primary" onClick={openMail}><Mail size={16}/>Buka Email</button></div>
  <style jsx global>{`
   .m238m-stock-request-row{display:flex;flex-direction:column;gap:10px}.m238m-stock-request-check{display:flex;align-items:flex-start;gap:10px}.m238m-stock-request-check input{margin-top:3px}.m238m-stock-request-check span{display:flex;flex-direction:column;gap:2px;min-width:0}.m238m-stock-request-check strong{font-size:13px}.m238m-stock-request-check small{font-size:9px;color:var(--m-secondary)}.m238m-stock-request-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.m238m-stock-request-stats span{background:var(--m-surface2);border-radius:10px;padding:8px;font-size:9px;color:var(--m-secondary);display:flex;justify-content:space-between}.m238m-stock-request-stats b{color:var(--m-text)}.m238m-stock-request-foot{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center}.m238m-stock-request-foot small{font-size:9px;color:var(--m-secondary)}.m238m-stock-request-foot .prio{font-size:8px;font-weight:900;border-radius:999px;padding:5px 7px}.m238m-stock-request-foot .critical{background:rgba(239,68,68,.12);color:#ef4444}.m238m-stock-request-foot .high{background:rgba(245,158,11,.12);color:#f59e0b}.m238m-stock-request-foot .medium{background:rgba(59,130,246,.12);color:#3b82f6}.m238m-stock-request-foot label{font-size:9px;color:var(--m-secondary);display:flex;align-items:center;gap:5px}.m238m-stock-request-foot input{width:48px;border:1px solid var(--m-line);border-radius:9px;background:var(--m-surface2);color:var(--m-text);padding:7px;text-align:center;font-weight:800}.m238m-stock-oos-list{display:flex;flex-direction:column;gap:6px}.m238m-stock-oos-list>div{background:var(--m-surface);border-radius:12px;padding:10px 12px;display:flex;flex-direction:column;gap:2px}.m238m-stock-oos-list span{font-size:11px;font-weight:800}.m238m-stock-oos-list small{font-size:9px;color:var(--m-secondary)}.m238m-email-preview pre{white-space:pre-wrap;word-break:break-word;font:inherit;font-size:10px;line-height:1.55;color:var(--m-secondary);margin:10px 0 0}.m238m-stock-email-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.m238m-stock-email-actions button{border:0;border-radius:12px;padding:12px;background:var(--m-surface);color:var(--m-text);font-weight:850;display:flex;gap:7px;align-items:center;justify-content:center}.m238m-stock-email-actions button.primary{grid-column:1/-1;background:var(--m-blue);color:white}
  `}</style>
 </div>
}
