"use client";

import {useEffect,useMemo,useRef,useState} from "react";

type Staff={id:string;name:string;position:string};
type PreviewRow={brand:string;article:string;description:string;serial:string;totalStock:number|null;sourceNo:string};
type AssignedRow=PreviewRow&{stocker:string};
type StockRow={rowNumber:number;no:string;stocker:string;brand:string;article:string;description:string;serial:string;totalStock:number;backroom:string;dropbox:string;floor:string;stockDate:string;period:string;uploadID:string;uploadedAt:string};
type Batch={uploadID:string;stockDate:string;period:string;uploadedAt:string;totalArticles:number;totalStock:number;totalStockers:number};
type Data={history:Batch[];selected:Batch|null;rows:StockRow[];staff:Staff[]};
type Preview={fileName:string;sheet:string;rows:PreviewRow[];samples:PreviewRow[];totalArticles:number;totalStock:number;staff:Staff[];distribution:{min:number;max:number};valid:boolean};

const num=new Intl.NumberFormat("id-ID");
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateLabel=(v:string)=>!/^\d{4}-\d{2}-\d{2}$/.test(v)?v||"-":new Intl.DateTimeFormat("id-ID",{timeZone:"UTC",day:"numeric",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00Z`));
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]!));
const panel="m238-soft-card rounded-2xl border";

export default function StokanPage(){
 const fileRef=useRef<HTMLInputElement>(null);
 const[data,setData]=useState<Data>({history:[],selected:null,rows:[],staff:[]});
 const[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[preview,setPreview]=useState<Preview|null>(null),[assigned,setAssigned]=useState<AssignedRow[]|null>(null),[period,setPeriod]=useState(""),[stockDate,setStockDate]=useState(today());
 const[query,setQuery]=useState(""),[stockerFilter,setStockerFilter]=useState("ALL"),[detailStocker,setDetailStocker]=useState("");

 const load=async(uploadID="")=>{setLoading(true);setError("");try{const q=uploadID?`?uploadID=${encodeURIComponent(uploadID)}`:"",r=await fetch(`/api/stokan${q}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal membaca stokan");setData(j);if(j.selected){setPeriod(j.selected.period||"");setStockDate(j.selected.stockDate||today())}}catch(e){setError(e instanceof Error?e.message:"Gagal membaca stokan")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);

 const stockers=useMemo(()=>{const m=new Map<string,number>();for(const r of data.rows)if(r.stocker)m.set(r.stocker,(m.get(r.stocker)||0)+1);return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[data.rows]);
 const totalStock=useMemo(()=>data.rows.reduce((a,r)=>a+Number(r.totalStock||0),0),[data.rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return data.rows.filter(r=>(stockerFilter==="ALL"||r.stocker===stockerFilter)&&(!q||r.article.toLowerCase().includes(q)||r.description.toLowerCase().includes(q)||r.brand.toLowerCase().includes(q)))},[data.rows,query,stockerFilter]);
 const assignedSummary=useMemo(()=>{const m=new Map<string,number>();for(const r of assigned||[])m.set(r.stocker,(m.get(r.stocker)||0)+1);return [...m.entries()]},[assigned]);
 const detailPreviewRows=useMemo(()=>detailStocker&&assigned?assigned.filter(r=>r.stocker===detailStocker):[],[assigned,detailStocker]);
 const validAssigned=!!assigned?.length&&assigned.every(r=>r.article&&r.stocker&&r.totalStock!==null&&Number.isFinite(Number(r.totalStock))&&Number(r.totalStock)>=0);

 const previewFile=async(file:File)=>{setWorking(true);setError("");setMessage("");setAssigned(null);try{const form=new FormData();form.append("file",file);const r=await fetch("/api/stokan",{method:"POST",body:form}),j=await r.json();if(!r.ok)throw new Error(j.error||"Format file stokan tidak sesuai.");setPreview(j)}catch(e){setError(e instanceof Error?e.message:"Upload gagal")}finally{setWorking(false)}};
 const autoAssign=()=>{if(!preview?.staff.length)return;let cursor=0;const total=preview.rows.length,count=preview.staff.length,base=Math.floor(total/count),extra=total%count;const out:AssignedRow[]=[];preview.staff.forEach((p,i)=>{const take=base+(i<extra?1:0);preview.rows.slice(cursor,cursor+take).forEach(r=>out.push({...r,stocker:p.name}));cursor+=take});setAssigned(out);setDetailStocker("")};
 const saveAssignment=async()=>{if(!assigned||!validAssigned)return;setWorking(true);setError("");setMessage("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commit",period,stockDate,rows:assigned})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal menyimpan pembagian");setMessage(j.message||"Stokan berhasil diproses dan siap diprint.");setPreview(null);setAssigned(null);if(fileRef.current)fileRef.current.value="";await load(j.uploadID)}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan pembagian")}finally{setWorking(false)}};
 const clearStokan=async()=>{if(!confirm("Yakin ingin menghapus data stokan aktif?"))return;setWorking(true);setError("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear",uploadID:data.selected?.uploadID||""})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal clear stokan");setPreview(null);setAssigned(null);setDetailStocker("");setMessage(j.message);await load()}catch(e){setError(e instanceof Error?e.message:"Gagal clear stokan")}finally{setWorking(false)}};

 const printRows=(rows:StockRow[],one?:string)=>{if(!rows.length)return;const groups=one?[[one,rows] as const]:[...new Map(rows.map(r=>[r.stocker,rows.filter(x=>x.stocker===r.stocker)])).entries()];const w=window.open("","_blank","noopener,noreferrer");if(!w){setError("Popup print diblokir browser.");return}const html=groups.map(([name,list])=>`<section class="sheet"><table><thead><tr><th colspan="9" class="meta"><b>DIGIMAP PIM 2 - M238</b><br><span>STOKAN AKSESORIS</span><br><small>Stocker: ${esc(name)} &nbsp; | &nbsp; Periode: ${esc(data.selected?.period||period)} &nbsp; | &nbsp; Tanggal: ${esc(dateLabel(data.selected?.stockDate||stockDate))}</small></th></tr><tr><th>No</th><th>Brand</th><th>Artikel</th><th>Description</th><th>S/N</th><th>Qty</th><th>Backroom</th><th>Dropbox</th><th>Floor</th></tr></thead><tbody>${list.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.brand)}</td><td>${esc(r.article)}</td><td>${esc(r.description)}</td><td>${esc(r.serial)}</td><td>${esc(r.totalStock)}</td><td></td><td></td><td></td></tr>`).join("")}</tbody></table></section>`).join("");w.document.write(`<!doctype html><html><head><style>@page{size:A4 landscape;margin:8mm}body{font-family:Arial;margin:0;color:#111}.sheet{page-break-after:always}.sheet:last-child{page-break-after:auto}table{width:100%;border-collapse:collapse;font-size:8px;table-layout:fixed}thead{display:table-header-group}th,td{border:1px solid #555;padding:3px}.meta{text-align:left;border:0;font-size:11px}.meta span{font-size:14px;font-weight:800}.meta small{font-weight:400}th:nth-child(1){width:4%}th:nth-child(2){width:9%}th:nth-child(3){width:15%}th:nth-child(4){width:27%}th:nth-child(5){width:12%}th:nth-child(6){width:6%}th:nth-child(n+7){width:9%}</style></head><body>${html}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};

 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Inventory</p><h2 className="mt-1 text-3xl font-black">Stokan Aksesoris</h2></div>
  <section className={`${panel} p-4`}><div className="grid gap-3 md:grid-cols-[1fr_180px_auto] md:items-end"><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Periode Stokan</span><input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="Contoh: Week 11 Q4" className="h-11 w-full rounded-xl border px-3"/></label><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Tanggal</span><input type="date" value={stockDate} onChange={e=>setStockDate(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><div className="flex flex-wrap gap-2"><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void previewFile(f)}}/><button onClick={()=>fileRef.current?.click()} disabled={working} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white">Upload File Stokan</button><button onClick={()=>printRows(data.rows)} disabled={!data.rows.length} className="rounded-xl border px-4 py-2.5 text-sm font-black disabled:opacity-40">Print Semua</button><button onClick={clearStokan} disabled={working||(!data.rows.length&&!preview&&!assigned)} className="rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-black text-rose-600 disabled:opacity-40">Clear Stokan</button></div></div></section>

  {preview&&!assigned&&<section className={`${panel} border-blue-200 p-5`}><h3 className="font-black">Preview Data</h3><p className="mt-2 text-sm text-slate-500">Accessories ditemukan: <b>{num.format(preview.totalArticles)} artikel</b> • Total Qty: <b>{num.format(preview.totalStock)} unit</b> • Sales Assistant: <b>{preview.staff.length} staff</b> • Pembagian: <b>{preview.distribution.min===preview.distribution.max?preview.distribution.min:`${preview.distribution.min}–${preview.distribution.max}`}</b> artikel/staff</p><div className="mt-4 overflow-x-auto"><table className="min-w-[700px] w-full text-sm"><thead><tr><th className="px-3 py-2 text-left">Brand</th><th className="px-3 py-2 text-left">Artikel</th><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-left">S/N</th><th className="px-3 py-2 text-right">Qty</th></tr></thead><tbody>{preview.samples.map((r,i)=><tr key={i} className="border-t"><td className="px-3 py-2">{r.brand}</td><td className="px-3 py-2 font-semibold">{r.article||"-"}</td><td className="px-3 py-2">{r.description||"-"}</td><td className="px-3 py-2">{r.serial||"-"}</td><td className="px-3 py-2 text-right">{r.totalStock??"Invalid"}</td></tr>)}</tbody></table></div><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setPreview(null)} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button onClick={autoAssign} disabled={!preview.valid||!period||!stockDate} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-40">Proses & Bagi Otomatis</button></div></section>}

  {assigned&&preview&&<section className={`${panel} border-blue-200 p-5`}><h3 className="font-black">Preview Pembagian Stocker</h3><p className="mt-2 text-sm text-slate-500"><b>{num.format(assigned.length)} artikel</b> • <b>{num.format(assigned.reduce((a,r)=>a+Number(r.totalStock||0),0))} unit</b> • <b>{preview.staff.length} Sales Assistant</b></p><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{assignedSummary.map(([name,count])=><div key={name} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-bold">{name}</p><p className="text-xs text-slate-500">{count} artikel</p></div><button onClick={()=>setDetailStocker(name)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Lihat Detail</button></div>)}</div>{detailStocker&&<div className="mt-4 overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-2 py-2">No</th><th className="px-2 py-2 text-left">Stocker</th><th className="px-2 py-2 text-left">Brand</th><th className="px-2 py-2 text-left">Artikel</th><th className="px-2 py-2 text-left">Description</th><th className="px-2 py-2 text-left">S/N</th><th className="px-2 py-2 text-right">Qty</th></tr></thead><tbody>{detailPreviewRows.map((r,i)=><tr key={`${r.sourceNo}-${i}`} className="border-t"><td className="px-2 py-2">{i+1}</td><td className="px-2 py-2"><select value={r.stocker} onChange={e=>setAssigned(rows=>rows?.map(x=>x===r?{...x,stocker:e.target.value}:x)||null)} className="h-9 rounded-lg border px-2">{preview.staff.map(s=><option key={s.id||s.name} value={s.name}>{s.name}</option>)}</select></td><td className="px-2 py-2">{r.brand}</td><td className="px-2 py-2 font-semibold">{r.article}</td><td className="px-2 py-2">{r.description||"-"}</td><td className="px-2 py-2">{r.serial||"-"}</td><td className="px-2 py-2 text-right">{r.totalStock}</td></tr>)}</tbody></table></div>}<div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setAssigned(null);setDetailStocker("")}} className="rounded-xl border px-4 py-2 text-sm font-bold">Kembali</button><button onClick={saveAssignment} disabled={!validAssigned||working} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-40">{working?"Menyimpan…":"Simpan Pembagian"}</button></div></section>}

  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}

  <section className={`${panel} p-4`}><label className="min-w-[240px]"><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Histori Stokan</span><select value={data.selected?.uploadID||""} onChange={e=>void load(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"><option value="">{loading?"Memuat…":"Pilih periode"}</option>{data.history.map(h=><option key={h.uploadID} value={h.uploadID}>{h.period} • {dateLabel(h.stockDate)} • {h.totalArticles} artikel</option>)}</select></label></section>

  {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat data stokan…</div>:data.rows.length===0?<div className={`${panel} p-8 text-center text-slate-500`}>Belum ada data stokan final.</div>:<><section className="grid gap-3 sm:grid-cols-3"><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Artikel</p><p className="mt-1 text-2xl font-black">{num.format(data.rows.length)}</p></div><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Qty</p><p className="mt-1 text-2xl font-black">{num.format(totalStock)} Unit</p></div><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Stocker</p><p className="mt-1 text-2xl font-black">{stockers.length} Sales Assistant</p></div></section><section className={`${panel} overflow-hidden`}><div className="grid gap-3 border-b p-4 md:grid-cols-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari Brand / Artikel / Description" className="h-10 rounded-xl border px-3"/><select value={stockerFilter} onChange={e=>setStockerFilter(e.target.value)} className="h-10 rounded-xl border px-3"><option value="ALL">Semua Stocker</option>{stockers.map(([name])=><option key={name}>{name}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-[1100px] w-full text-sm"><thead><tr><th className="px-3 py-3">No</th><th className="px-3 py-3 text-left">Stocker</th><th className="px-3 py-3 text-left">Brand</th><th className="px-3 py-3 text-left">Artikel</th><th className="px-3 py-3 text-left">Description</th><th className="px-3 py-3 text-left">S/N</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3">Backroom</th><th className="px-3 py-3">Dropbox</th><th className="px-3 py-3">Floor</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.rowNumber} className="border-t"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2 font-semibold">{r.stocker}</td><td className="px-3 py-2">{r.brand}</td><td className="px-3 py-2 font-semibold">{r.article}</td><td className="px-3 py-2">{r.description||"-"}</td><td className="px-3 py-2">{r.serial||"-"}</td><td className="px-3 py-2 text-right font-bold">{num.format(r.totalStock)}</td><td></td><td></td><td></td></tr>)}</tbody></table></div></section></>}
 </div>
}
