"use client";

import {useEffect,useMemo,useRef,useState} from "react";

type Staff={id:string;name:string;position:string};
type PreviewRow={brand:string;article:string;description:string;serial:string;totalStock:number|null;sourceNo:string};
type AssignedRow=PreviewRow&{stocker:string};
type StockRow={rowNumber:number;no:string;stocker:string;brand:string;article:string;description:string;serial:string;totalStock:number;backroom:string;dropbox:string;floor:string;stockDate:string;period:string;uploadID:string;uploadedAt:string};
type Batch={uploadID:string;stockDate:string;period:string;uploadedAt:string;totalArticles:number;totalStock:number;totalStockers:number};
type Data={history:Batch[];selected:Batch|null;rows:StockRow[];staff:Staff[];schemaValid:boolean;readBackValid:boolean};
type Preview={fileName:string;sheet:string;descriptionSource?:string;rows:PreviewRow[];samples:PreviewRow[];totalArticles:number;totalStock:number;staff:Staff[];distribution:{min:number;max:number};valid:boolean};
type Mode="ordered"|"random";

const num=new Intl.NumberFormat("id-ID");
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateLabel=(v:string)=>!/^\d{4}-\d{2}-\d{2}$/.test(v)?v||"-":new Intl.DateTimeFormat("id-ID",{timeZone:"UTC",day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(`${v}T00:00:00Z`));
const fileDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)?`${v.slice(8,10)}-${v.slice(5,7)}-${v.slice(0,4)}`:v.replace(/[^\d-]/g,"");
const PDF_ROWS_PER_PAGE=40;
const pdfEstimate=(count:number)=>Math.max(1,Math.ceil(count/PDF_ROWS_PER_PAGE));
const panel="m238-soft-card rounded-2xl border";
const button="rounded-xl px-4 py-2.5 text-sm font-black transition disabled:cursor-not-allowed disabled:opacity-40";

export default function StokanPage(){
 const fileRef=useRef<HTMLInputElement>(null);
 const[data,setData]=useState<Data>({history:[],selected:null,rows:[],staff:[],schemaValid:false,readBackValid:false});
 const[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[preview,setPreview]=useState<Preview|null>(null),[assigned,setAssigned]=useState<AssignedRow[]|null>(null),[period,setPeriod]=useState(""),[stockDate,setStockDate]=useState(today());
 const[mode,setMode]=useState<Mode>("ordered"),[detailStocker,setDetailStocker]=useState("");

 const load=async(uploadID="")=>{setLoading(true);setError("");try{const q=uploadID?`?uploadID=${encodeURIComponent(uploadID)}`:"",r=await fetch(`/api/stokan${q}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal membaca stokan");setData(j);if(j.selected){setPeriod(j.selected.period||"");setStockDate(j.selected.stockDate||today())}return j as Data}catch(e){setError(e instanceof Error?e.message:"Gagal membaca stokan");return null}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);

 const stockers=useMemo(()=>{const m=new Map<string,number>();for(const r of data.rows)if(r.stocker)m.set(r.stocker,(m.get(r.stocker)||0)+1);return [...m.entries()]},[data.rows]);
 const assignedSummary=useMemo(()=>{const m=new Map<string,number>();for(const r of assigned||[])m.set(r.stocker,(m.get(r.stocker)||0)+1);return [...m.entries()]},[assigned]);
 const validAssigned=!!assigned?.length&&assigned.every(r=>r.article&&r.stocker&&r.totalStock!==null&&Number.isFinite(Number(r.totalStock))&&Number(r.totalStock)>=0);
 const previewDetailRows=useMemo(()=>detailStocker&&assigned?assigned.filter(r=>r.stocker===detailStocker):[],[assigned,detailStocker]);
 const finalDetailRows=useMemo(()=>detailStocker&&!assigned?data.rows.filter(r=>r.stocker===detailStocker):[],[data.rows,assigned,detailStocker]);
 const finalReady=!!data.rows.length&&data.schemaValid&&data.readBackValid&&!preview&&!assigned;
 const showEmpty=!loading&&!preview&&!assigned&&data.rows.length===0;

 const previewFile=async(file:File)=>{setWorking(true);setError("");setMessage("");setPreview(null);setAssigned(null);setDetailStocker("");setMode("ordered");try{const form=new FormData();form.append("file",file);const r=await fetch("/api/stokan",{method:"POST",body:form}),j=await r.json();if(!r.ok)throw new Error(j.error||"Format file stokan tidak sesuai.");setPreview(j)}catch(e){setError(e instanceof Error?e.message:"Upload gagal")}finally{setWorking(false)}};
 const shuffled=(names:string[])=>{const out=[...names];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
 const assignBlocks=(names:string[])=>{if(!preview?.valid||!preview.staff.length)return;let cursor=0;const total=preview.rows.length,count=preview.staff.length,base=Math.floor(total/count),extra=total%count;const out:AssignedRow[]=[];names.forEach((name,i)=>{const take=base+(i<extra?1:0);preview.rows.slice(cursor,cursor+take).forEach(r=>out.push({...r,stocker:name}));cursor+=take});setAssigned(out);setDetailStocker("")};
 const autoAssign=()=>{if(!preview)return;const names=preview.staff.map(s=>s.name);assignBlocks(mode==="random"?shuffled(names):names)};
 const reshuffle=()=>{if(!preview||mode!=="random")return;assignBlocks(shuffled(preview.staff.map(s=>s.name)))};
 const changeBlockStocker=(oldName:string,newName:string)=>{if(!assigned||oldName===newName)return;setAssigned(assigned.map(r=>r.stocker===oldName?{...r,stocker:newName}:r));setDetailStocker(newName)};

 const saveAssignment=async()=>{if(!assigned||!validAssigned||!period||!stockDate)return;setWorking(true);setError("");setMessage("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commit",period,stockDate,rows:assigned})}),j=await r.json();if(!r.ok||!j.verified)throw new Error(j.error||"Gagal menyimpan Stokan — struktur data berubah saat penyimpanan.");const fresh=await load(j.uploadID);if(!fresh?.schemaValid||!fresh?.readBackValid||!fresh.rows.length)throw new Error("Gagal menyimpan Stokan — struktur data berubah saat penyimpanan.");setPreview(null);setAssigned(null);setDetailStocker("");if(fileRef.current)fileRef.current.value="";setMessage("Stokan berhasil disimpan dan siap dibuat PDF.")}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan pembagian")}finally{setWorking(false)}};
 const clearStokan=async()=>{if(!confirm("Yakin ingin menghapus data stokan aktif?"))return;setWorking(true);setError("");setMessage("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"clear",uploadID:data.selected?.uploadID||""})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal clear stokan");setPreview(null);setAssigned(null);setDetailStocker("");setMode("ordered");if(fileRef.current)fileRef.current.value="";setData(d=>({...d,selected:null,rows:[],schemaValid:true,readBackValid:true}));setMessage(j.message||"Stokan berhasil dikosongkan. Silakan upload file week berikutnya.")}catch(e){setError(e instanceof Error?e.message:"Gagal clear stokan")}finally{setWorking(false)}};

 const makePdf=async(rows:StockRow[],one?:string)=>{if(!rows.length||!finalReady)return;setPdfBusy(true);setError("");setMessage("");try{const {jsPDF}=await import("jspdf");const doc=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const margin=5,pageW=297,footerY=205.2,rowH=4.35;const cols=[{label:"No",w:7},{label:"Brand",w:21},{label:"Artikel",w:38},{label:"Description",w:84},{label:"S/N",w:35},{label:"Qty",w:9},{label:"Backroom",w:29},{label:"Dropbox",w:29},{label:"Floor",w:30}];const groups=one?[[one,rows] as const]:stockers.map(([name])=>[name,rows.filter(r=>r.stocker===name)] as const).filter(([,list])=>list.length);let firstPage=true;
  const clip=(value:unknown,width:number,maxLines:number)=>{const split=doc.splitTextToSize(String(value??""),width-1.6) as string[];if(split.length<=maxLines)return split;const out=split.slice(0,maxLines);let last=out[maxLines-1].replace(/\s+$/g,"");while(last&&doc.getTextWidth(`${last}…`)>width-1.6)last=last.slice(0,-1);out[maxLines-1]=`${last}…`;return out};
  const header=(name:string)=>{doc.setFont("helvetica","bold");doc.setFontSize(9.2);doc.text("DIGIMAP PIM 2 - M238 | STOKAN AKSESORIS",margin,7.6);doc.setFont("helvetica","normal");doc.setFontSize(7);doc.text(`Periode: ${data.selected?.period||period} | Tanggal: ${dateLabel(data.selected?.stockDate||stockDate)} | Stocker: ${name}`,margin,11.8);let x=margin;doc.setFont("helvetica","bold");doc.setFontSize(6.4);for(const c of cols){doc.rect(x,14,c.w,4.8);doc.text(c.label,x+.8,17.1);x+=c.w}return 18.8};
  for(const [name,list] of groups){for(let start=0;start<list.length;start+=PDF_ROWS_PER_PAGE){if(!firstPage)doc.addPage("a4","landscape");firstPage=false;let y=header(name);const pageRows=list.slice(start,start+PDF_ROWS_PER_PAGE);for(let local=0;local<pageRows.length;local++){const r=pageRows[local],globalNo=start+local+1;const values=[String(globalNo),r.brand,r.article,r.description,r.serial,String(r.totalStock),"","",""];let x=margin;doc.setFont("helvetica","normal");doc.setFontSize(5.9);for(let c=0;c<cols.length;c++){doc.rect(x,y,cols[c].w,rowH);const lines=clip(values[c],cols[c].w,c===3?2:1);doc.text(lines,x+.8,y+(lines.length>1?1.45:2.75),{lineHeightFactor:.8});x+=cols[c].w}y+=rowH}}}
  const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);doc.setFont("helvetica","normal");doc.setFontSize(6.2);doc.text("Checked by: __________     SPV: __________",margin,footerY);doc.text(`Page ${p} of ${pages}`,pageW-margin,footerY,{align:"right"})}const who=one?one.replace(/[^A-Za-z0-9]+/g,"_").replace(/^_|_$/g,""):"All_Stocker";doc.save(`Stokan_M238_${who}_${fileDate(data.selected?.stockDate||stockDate)}.pdf`);setMessage("PDF Stokan berhasil dibuat.")}catch{setError("Gagal membuat PDF Stokan. Silakan coba kembali.")}finally{setPdfBusy(false)}};

 return <div className="space-y-4">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Inventory</p><h2 className="mt-1 text-3xl font-black">STOKAN AKSESORIS</h2><p className="mt-1 text-sm text-slate-500">Stokan mingguan Accessories M238</p></div>

  <section className={`${panel} p-4`}><div className="grid gap-3 md:grid-cols-[1fr_180px_auto] md:items-end"><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Periode Stokan</span><input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="Contoh: Week 11 Q4" className="h-11 w-full rounded-xl border px-3"/></label><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Tanggal</span><input type="date" value={stockDate} onChange={e=>setStockDate(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><div className="flex flex-wrap gap-2"><input ref={fileRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void previewFile(f)}}/><button onClick={()=>fileRef.current?.click()} disabled={working||!!assigned} className={`${button} bg-blue-600 text-white`}>Upload File Stokan</button><button onClick={clearStokan} disabled={working||(!data.rows.length&&!preview&&!assigned)} className={`${button} border border-rose-200 text-rose-600`}>Clear Stokan</button></div></div></section>

  {preview&&!assigned&&<section className={`${panel} p-4`}><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><div className="rounded-xl border p-3"><p className="text-[11px] font-bold uppercase text-slate-500">Accessories</p><p className="mt-1 text-lg font-black">{num.format(preview.totalArticles)} Artikel</p></div><div className="rounded-xl border p-3"><p className="text-[11px] font-bold uppercase text-slate-500">Total Qty</p><p className="mt-1 text-lg font-black">{num.format(preview.totalStock)} Unit</p></div><div className="rounded-xl border p-3"><p className="text-[11px] font-bold uppercase text-slate-500">Sales Assistant</p><p className="mt-1 text-lg font-black">{preview.staff.length} Staff</p></div><div className="rounded-xl border p-3"><p className="text-[11px] font-bold uppercase text-slate-500">Pembagian</p><p className="mt-1 text-lg font-black">{preview.distribution.min===preview.distribution.max?preview.distribution.min:`${preview.distribution.min}–${preview.distribution.max}`} Artikel / Staff</p></div></div><div className="mt-4 border-t pt-4"><p className="text-xs font-black uppercase tracking-[.14em] text-slate-500">Mode Pembagian</p><div className="mt-2 flex flex-wrap gap-2"><button onClick={()=>setMode("ordered")} className={`${button} border ${mode==="ordered"?"border-blue-600 bg-blue-50 text-blue-700 dark:bg-blue-950/20":""}`}>Urut</button><button onClick={()=>setMode("random")} className={`${button} border ${mode==="random"?"border-blue-600 bg-blue-50 text-blue-700 dark:bg-blue-950/20":""}`}>Acak Nama Staff</button></div><p className="mt-2 text-xs text-slate-500">{mode==="ordered"?"Urut = nama staff mengikuti urutan default.":"Acak Nama Staff = hanya menukar nama staff antar block. Artikel, row, dan urutan brand tetap."}</p></div><div className="mt-4 flex justify-end"><button onClick={autoAssign} disabled={!preview.valid||!preview.staff.length||working} className={`${button} bg-blue-600 text-white`}>Proses & Bagi Otomatis</button></div></section>}

  {assigned&&preview&&<section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-blue-600">Preview Pembagian Stocker</p><p className="mt-1 text-sm text-slate-500">Cek block assignment sebelum disimpan.</p></div>{mode==="random"&&<button onClick={reshuffle} className={`${button} border`}>Acak Ulang Nama Staff</button>}</div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{assignedSummary.map(([name,count],i)=><div key={name} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{i+1}. {name}</p><p className="mt-1 text-xs text-slate-500">{count} Artikel</p></div><button onClick={()=>setDetailStocker(detailStocker===name?"":name)} className="text-xs font-black text-blue-600">Lihat Detail</button></div><label className="mt-3 block"><span className="text-[10px] font-bold uppercase text-slate-400">Stocker Block</span><select value={name} onChange={e=>changeBlockStocker(name,e.target.value)} className="mt-1 h-9 w-full rounded-lg border px-2 text-sm">{preview.staff.map(s=><option key={s.id||s.name} value={s.name}>{s.name}</option>)}</select></label></div>)}</div>{detailStocker&&<div className="mt-4 rounded-xl border"><div className="flex items-center justify-between border-b p-3"><div><p className="font-black">DETAIL — {detailStocker.toUpperCase()}</p><p className="text-xs text-slate-500">{previewDetailRows.length} Artikel</p></div><button onClick={()=>setDetailStocker("")} className="text-xs font-black text-slate-500">Tutup</button></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-3 py-2">No</th><th className="px-3 py-2 text-left">Brand</th><th className="px-3 py-2 text-left">Artikel</th><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-left">S/N</th><th className="px-3 py-2 text-right">Qty</th></tr></thead><tbody>{previewDetailRows.map((r,i)=><tr key={`${r.sourceNo}-${i}`} className="border-t"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2">{r.brand}</td><td className="px-3 py-2 font-semibold">{r.article}</td><td className="px-3 py-2">{r.description}</td><td className="px-3 py-2">{r.serial}</td><td className="px-3 py-2 text-right">{r.totalStock}</td></tr>)}</tbody></table></div></div>}<div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setAssigned(null);setDetailStocker("")}} className={`${button} border`}>Kembali</button><button onClick={saveAssignment} disabled={!validAssigned||working||!period||!stockDate} className={`${button} bg-blue-600 text-white`}>{working?"Menyimpan…":"Simpan Pembagian"}</button></div></section>}

  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}

  {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat data stokan…</div>:showEmpty?<div className={`${panel} p-8 text-center text-slate-500`}>Belum ada data stokan aktif. Silakan upload file .xls/.xlsx.</div>:finalReady&&<section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-600">Stokan Siap Print</p><p className="mt-1 text-sm text-slate-500">PDF A4 Landscape • hemat kertas • {PDF_ROWS_PER_PAGE} artikel/halaman</p></div><button onClick={()=>void makePdf(data.rows)} disabled={pdfBusy} className={`${button} bg-blue-600 text-white`}>{pdfBusy?"Membuat PDF…":"Print / PDF Semua"}</button></div><div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{stockers.map(([name,count])=><div key={name} className="rounded-xl border p-3"><p className="font-black">{name}</p><p className="mt-1 text-xs text-slate-500">{count} Artikel • estimasi {pdfEstimate(count)} halaman</p><div className="mt-3 flex gap-2"><button onClick={()=>setDetailStocker(detailStocker===name?"":name)} className={`${button} flex-1 border py-2 text-xs`}>Lihat Detail</button><button onClick={()=>void makePdf(data.rows.filter(r=>r.stocker===name),name)} disabled={pdfBusy} className={`${button} flex-1 border py-2 text-xs`}>PDF</button></div></div>)}</div>{detailStocker&&finalDetailRows.length>0&&<div className="mt-4 rounded-xl border"><div className="flex items-center justify-between border-b p-3"><div><p className="font-black">DETAIL — {detailStocker.toUpperCase()}</p><p className="text-xs text-slate-500">{finalDetailRows.length} Artikel</p></div><button onClick={()=>setDetailStocker("")} className="text-xs font-black text-slate-500">Tutup</button></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-3 py-2">No</th><th className="px-3 py-2 text-left">Brand</th><th className="px-3 py-2 text-left">Artikel</th><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-left">S/N</th><th className="px-3 py-2 text-right">Qty</th></tr></thead><tbody>{finalDetailRows.map((r,i)=><tr key={r.rowNumber||`${r.article}-${i}`} className="border-t"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2">{r.brand}</td><td className="px-3 py-2 font-semibold">{r.article}</td><td className="px-3 py-2">{r.description}</td><td className="px-3 py-2">{r.serial}</td><td className="px-3 py-2 text-right font-bold">{num.format(r.totalStock)}</td></tr>)}</tbody></table></div></div>}</section>}

  {!loading&&data.history.length>0&&<section className={`${panel} p-4`}><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Histori Stokan</span><select value={data.selected?.uploadID||""} onChange={e=>void load(e.target.value)} className="h-10 w-full rounded-xl border px-3 text-sm md:max-w-md"><option value="">Pilih periode</option>{data.history.map(h=><option key={h.uploadID} value={h.uploadID}>{h.period} • {dateLabel(h.stockDate)} • {h.totalArticles} artikel</option>)}</select></label></section>}
 </div>
}
