"use client";

import {useEffect,useMemo,useRef,useState} from "react";

type Staff={id:string;name:string;position:string};
type PreviewRow={article:string;description:string;totalStock:number;sourceNo:string};
type StockRow={rowNumber:number;no:string;stocker:string;article:string;description:string;totalStock:number;backroom:string;dropbox:string;floor:string;stockDate:string;period:string;uploadID:string;uploadedAt:string};
type Batch={uploadID:string;stockDate:string;period:string;uploadedAt:string;totalArticles:number;totalStock:number;totalStockers:number};
type Data={history:Batch[];selected:Batch|null;rows:StockRow[];staff:Staff[];error?:string};
type Preview={fileName:string;sheet:string;rows:PreviewRow[];totalArticles:number;totalStock:number;staff:Staff[];distribution:{min:number;max:number}};

const num=new Intl.NumberFormat("id-ID");
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const dateLabel=(v:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return v||"-";return new Intl.DateTimeFormat("id-ID",{timeZone:"UTC",day:"numeric",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00Z`))};
const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]!));
const panel="m238-soft-card rounded-2xl border";

export default function StokanPage(){
 const fileRef=useRef<HTMLInputElement>(null);
 const[data,setData]=useState<Data>({history:[],selected:null,rows:[],staff:[]});
 const[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[preview,setPreview]=useState<Preview|null>(null),[period,setPeriod]=useState(""),[stockDate,setStockDate]=useState(today());
 const[query,setQuery]=useState(""),[stockerFilter,setStockerFilter]=useState("ALL"),[detailStocker,setDetailStocker]=useState("");

 const load=async(uploadID="")=>{setLoading(true);setError("");try{const q=uploadID?`?uploadID=${encodeURIComponent(uploadID)}`:"",r=await fetch(`/api/stokan${q}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal membaca stokan");setData(j);if(j.selected){setPeriod(j.selected.period||"");setStockDate(j.selected.stockDate||today())}}catch(e){setError(e instanceof Error?e.message:"Gagal membaca stokan")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);

 const stockers=useMemo(()=>{const m=new Map<string,number>();for(const r of data.rows)if(r.stocker)m.set(r.stocker,(m.get(r.stocker)||0)+1);return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[data.rows]);
 const totalStock=useMemo(()=>data.rows.reduce((a,r)=>a+Number(r.totalStock||0),0),[data.rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return data.rows.filter(r=>(stockerFilter==="ALL"||r.stocker===stockerFilter)&&(!q||r.article.toLowerCase().includes(q)||r.description.toLowerCase().includes(q)))},[data.rows,query,stockerFilter]);
 const detailRows=useMemo(()=>detailStocker?data.rows.filter(r=>r.stocker===detailStocker):[],[data.rows,detailStocker]);

 const chooseFile=()=>fileRef.current?.click();
 const previewFile=async(file:File)=>{setWorking(true);setError("");setMessage("");try{const form=new FormData();form.append("action","preview");form.append("file",file);const r=await fetch("/api/stokan",{method:"POST",body:form}),j=await r.json();if(!r.ok)throw new Error(j.error||"Format file stokan tidak sesuai.");setPreview(j)}catch(e){setError(e instanceof Error?e.message:"Upload gagal")}finally{setWorking(false)}};
 const commit=async()=>{if(!preview)return;setWorking(true);setError("");setMessage("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"commit",period,stockDate,rows:preview.rows})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memproses stokan");setMessage(j.message||"Stokan berhasil diproses.");setPreview(null);if(fileRef.current)fileRef.current.value="";await load(j.uploadID)}catch(e){setError(e instanceof Error?e.message:"Gagal memproses stokan")}finally{setWorking(false)}};
 const override=async(row:StockRow,stocker:string)=>{if(stocker===row.stocker)return;setWorking(true);setError("");try{const r=await fetch("/api/stokan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"override",rowNumber:row.rowNumber,uploadID:row.uploadID,stocker})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal mengubah stocker");await load(row.uploadID)}catch(e){setError(e instanceof Error?e.message:"Gagal mengubah stocker")}finally{setWorking(false)}};

 const printRows=(rows:StockRow[],titleStocker?:string)=>{
  if(!rows.length)return;
  const selected=data.selected,groups=titleStocker?[[titleStocker,rows] as const]:[...new Map(rows.map(r=>[r.stocker,rows.filter(x=>x.stocker===r.stocker)])).entries()];
  const win=window.open("","_blank","noopener,noreferrer");if(!win){setError("Popup print diblokir browser. Izinkan popup lalu coba lagi.");return}
  const tables=groups.map(([name,list])=>`<section class="sheet"><table><thead><tr><th colspan="7" class="meta"><b>DIGIMAP PIM 2 - M238</b><br><span>STOKAN AKSESORIS</span><br><small>Periode: ${esc(selected?.period||period)} &nbsp; | &nbsp; Tanggal: ${esc(dateLabel(selected?.stockDate||stockDate))} &nbsp; | &nbsp; Stocker: ${esc(name)}</small></th></tr><tr><th>No</th><th>Artikel</th><th>Description</th><th>Total Stock</th><th>Backroom</th><th>Dropbox</th><th>Floor</th></tr></thead><tbody>${list.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.article)}</td><td>${esc(r.description)}</td><td class="center">${esc(r.totalStock)}</td><td></td><td></td><td></td></tr>`).join("")}</tbody></table></section>`).join("");
  win.document.write(`<!doctype html><html><head><title>Stokan M238</title><style>@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#111;margin:0}.sheet{break-after:page;page-break-after:always}.sheet:last-child{break-after:auto;page-break-after:auto}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9px}thead{display:table-header-group}th,td{border:1px solid #555;padding:4px 5px;vertical-align:middle}th{background:#f1f3f5;font-weight:700}.meta{background:white;text-align:left;border:0;padding:0 0 8px;font-size:12px}.meta span{font-size:15px;font-weight:800}.meta small{font-size:9px;font-weight:400}th:nth-child(1),td:nth-child(1){width:5%}th:nth-child(2),td:nth-child(2){width:14%}th:nth-child(3),td:nth-child(3){width:36%}th:nth-child(4),td:nth-child(4){width:10%}th:nth-child(n+5),td:nth-child(n+5){width:11.66%;height:24px}.center{text-align:center}</style></head><body>${tables}<script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}<\/script></body></html>`);win.document.close();
 };

 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Inventory</p><h2 className="mt-1 text-3xl font-black">Stokan Aksesoris</h2><p className="mt-1 text-sm text-slate-500">Stokan mingguan M238 • pembagian artikel otomatis ke Sales Assistant.</p></div>

  <section className={`${panel} p-4`}><div className="grid gap-3 md:grid-cols-[1fr_180px_auto] md:items-end"><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Periode Stokan</span><input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="Contoh: Week 11 Q4" className="h-11 w-full rounded-xl border px-3"/></label><label><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Tanggal</span><input type="date" value={stockDate} onChange={e=>setStockDate(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><div className="flex flex-wrap gap-2"><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void previewFile(f)}}/><button onClick={chooseFile} disabled={working} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">Upload File Stokan</button><button onClick={commit} disabled={!preview||working||!period||!stockDate} className="rounded-xl border px-4 py-2.5 text-sm font-black disabled:opacity-40">Bagi Otomatis</button><button onClick={()=>printRows(data.rows)} disabled={!data.rows.length} className="rounded-xl border px-4 py-2.5 text-sm font-black disabled:opacity-40">Print Semua</button></div></div></section>

  {preview&&<section className={`${panel} border-blue-200 p-5`}><h3 className="font-black">Preview File Stokan</h3><p className="mt-2 text-sm text-slate-500">File berhasil dibaca • <b>{num.format(preview.totalArticles)} artikel</b> ditemukan • <b>{preview.staff.length} Sales Assistant</b> ditemukan • pembagian <b>{preview.distribution.min===preview.distribution.max?preview.distribution.min:`${preview.distribution.min}–${preview.distribution.max}`}</b> artikel per staff.</p><p className="mt-1 text-xs text-slate-400">Total stock: {num.format(preview.totalStock)} Unit • Sheet: {preview.sheet}</p><div className="mt-4 flex justify-end gap-2"><button onClick={()=>{setPreview(null);if(fileRef.current)fileRef.current.value=""}} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button onClick={commit} disabled={working||!period||!stockDate} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{working?"Memproses…":"Proses & Bagi Otomatis"}</button></div></section>}

  {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{message}</div>}

  <section className={`${panel} p-4`}><div className="flex flex-wrap items-end justify-between gap-3"><label className="min-w-[240px]"><span className="mb-1 block text-xs font-bold uppercase text-slate-500">Histori Stokan</span><select value={data.selected?.uploadID||""} onChange={e=>void load(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"><option value="">{loading?"Memuat…":"Pilih periode"}</option>{data.history.map(h=><option key={h.uploadID} value={h.uploadID}>{h.period} • {dateLabel(h.stockDate)} • {h.totalArticles} artikel</option>)}</select></label>{data.selected&&<p className="text-xs text-slate-500">Batch: <b>{data.selected.uploadID}</b></p>}</div></section>

  {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat data stokan…</div>:data.rows.length===0?<div className={`${panel} p-8 text-center text-slate-500`}>Belum ada data stokan pada periode ini.</div>:<>
   <section className="grid gap-3 sm:grid-cols-3"><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Artikel</p><p className="mt-1 text-2xl font-black">{num.format(data.rows.length)}</p></div><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Stock</p><p className="mt-1 text-2xl font-black">{num.format(totalStock)} Unit</p></div><div className={`${panel} p-4`}><p className="text-xs text-slate-500">Total Stocker</p><p className="mt-1 text-2xl font-black">{stockers.length} Sales Assistant</p></div></section>

   <section className={`${panel} p-4`}><h3 className="font-black">Summary per Stocker</h3><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{stockers.map(([name,count])=><div key={name} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="truncate font-bold">{name}</p><p className="text-xs text-slate-500">{count} Artikel</p></div><div className="flex gap-1"><button onClick={()=>setDetailStocker(name)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Lihat</button><button onClick={()=>printRows(data.rows.filter(r=>r.stocker===name),name)} className="rounded-lg border px-2.5 py-1.5 text-xs font-bold">Print</button></div></div>)}</div></section>

   {detailStocker&&<section className={`${panel} overflow-hidden`}><div className="flex items-center justify-between border-b px-4 py-3"><div><h3 className="font-black">Detail Stocker • {detailStocker}</h3><p className="text-xs text-slate-500">{detailRows.length} artikel</p></div><button onClick={()=>setDetailStocker("")} className="rounded-lg border px-3 py-1.5 text-xs font-bold">Tutup</button></div><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead><tr><th className="px-3 py-2 text-left">No</th><th className="px-3 py-2 text-left">Artikel</th><th className="px-3 py-2 text-left">Description</th><th className="px-3 py-2 text-right">Total Stock</th><th className="px-3 py-2">Backroom</th><th className="px-3 py-2">Dropbox</th><th className="px-3 py-2">Floor</th></tr></thead><tbody>{detailRows.map((r,i)=><tr key={r.rowNumber} className="border-t"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2 font-semibold">{r.article}</td><td className="px-3 py-2">{r.description}</td><td className="px-3 py-2 text-right font-bold">{num.format(r.totalStock)}</td><td></td><td></td><td></td></tr>)}</tbody></table></div></section>}

   <section className={`${panel} overflow-hidden`}><div className="grid gap-3 border-b p-4 md:grid-cols-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari Artikel / Description" className="h-10 rounded-xl border px-3"/><select value={stockerFilter} onChange={e=>setStockerFilter(e.target.value)} className="h-10 rounded-xl border px-3"><option value="ALL">Semua Stocker</option>{stockers.map(([name])=><option key={name} value={name}>{name}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-sm"><thead><tr><th className="px-3 py-3 text-left">No</th><th className="px-3 py-3 text-left">Stocker</th><th className="px-3 py-3 text-left">Artikel</th><th className="px-3 py-3 text-left">Description</th><th className="px-3 py-3 text-right">Total Stock</th><th className="px-3 py-3">Backroom</th><th className="px-3 py-3">Dropbox</th><th className="px-3 py-3">Floor</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.rowNumber} className="border-t"><td className="px-3 py-2">{i+1}</td><td className="px-3 py-2"><select value={r.stocker} disabled={working} onChange={e=>void override(r,e.target.value)} className="h-9 min-w-[160px] rounded-lg border px-2 text-xs font-semibold"><option value={r.stocker}>{r.stocker}</option>{data.staff.filter(x=>x.name!==r.stocker).map(x=><option key={x.id||x.name} value={x.name}>{x.name}</option>)}</select></td><td className="px-3 py-2 font-semibold">{r.article}</td><td className="px-3 py-2">{r.description}</td><td className="px-3 py-2 text-right font-bold">{num.format(r.totalStock)}</td><td className="px-3 py-2"></td><td className="px-3 py-2"></td><td className="px-3 py-2"></td></tr>)}</tbody></table></div></section>
  </>}
 </div>
}
