"use client";
import {useEffect,useMemo,useState} from "react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
const shortMoney=(v:number)=>{const a=Math.abs(v);if(a>=1_000_000_000)return `Rp ${(v/1_000_000_000).toLocaleString("id-ID",{maximumFractionDigits:2})} M`;if(a>=1_000_000)return `Rp ${(v/1_000_000).toLocaleString("id-ID",{maximumFractionDigits:0})} Jt`;return money.format(v)};
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const monthName=(period:string)=>new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(`${period}-01T00:00:00`));
const months=Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,"0")}`);
type Progress={key:string;label:string;actual:number;target:number;achievement:number};
type Lob={name:string;qty:number;target:number;achievement:number;vsLastWeek:number};
type Daily={date:string;day:number;actual:number;target:number};
type Payload={period:string;store:string;target:{amount:number;device:number;accessories:number;vas:number};actual:{amount:number;device:number;accessories:number;vas:number};achievement:number;remaining:number;remainingDays:number;needPerDay:number;daily:Daily[];today:{label:string;date:string;sales:number;target:number;achievement:number};projected:number;projectedAchievement:number;kpi:{lfl:number;mtm:number;cvr:number;upt:number;atv:number};progress:Progress[];lob:Lob[];insight:string;error?:string};
function tone(v:number){if(v>=100)return{bar:"bg-emerald-500",text:"text-emerald-600"};if(v>=90)return{bar:"bg-blue-500",text:"text-blue-600"};if(v>=80)return{bar:"bg-amber-400",text:"text-amber-600"};return{bar:"bg-rose-500",text:"text-rose-600"}}
function Delta({value,suffix="%"}:{value:number;suffix?:string}){const up=value>=0;return <span className={`font-black ${up?"text-emerald-600":"text-rose-600"}`}>{up?"▲":"▼"} {Math.abs(value).toLocaleString("id-ID",{maximumFractionDigits:1})}{suffix}</span>}
function SummaryCard({label,value,sub,accent=false}:{label:string;value:string;sub?:string;accent?:boolean}){return <article className={`rounded-2xl border p-5 shadow-sm ${accent?"border-blue-100 bg-blue-50/60 dark:border-blue-900/40 dark:bg-blue-950/20":"bg-white dark:bg-slate-950"}`}><p className="text-xs font-black uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-3 text-2xl font-black tracking-[-.04em] text-slate-950 dark:text-white">{value}</p>{sub&&<p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{sub}</p>}</article>}
function ProgressRow({row}:{row:Progress}){const t=tone(row.achievement);return <div><div className="mb-2 flex items-center justify-between gap-4"><div><p className="font-bold">{row.label}</p><p className="text-xs text-slate-400">{shortMoney(row.actual)} / {shortMoney(row.target)}</p></div><b className={t.text}>{pct(row.achievement)}</b></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className={`h-full rounded-full ${t.bar}`} style={{width:`${Math.min(100,row.achievement)}%`}}/></div></div>}
function DailyChart({rows}:{rows:Daily[]}){const width=Math.max(720,rows.length*34),height=220,max=Math.max(1,...rows.flatMap(r=>[r.actual,r.target])),x=(i:number)=>28+i*((width-56)/Math.max(1,rows.length-1)),y=(v:number)=>height-36-(v/max)*(height-70),points=rows.map((r,i)=>`${x(i)},${y(r.target)}`).join(" ");return <div className="overflow-x-auto"><svg width={width} height={height} role="img" aria-label="Actual vs Target harian"><line x1="28" y1={height-36} x2={width-28} y2={height-36} stroke="currentColor" opacity=".12"/><polyline points={points} fill="none" stroke="#94a3b8" strokeWidth="2" strokeDasharray="6 5"/>{rows.map((r,i)=>{const bx=x(i)-7,by=y(r.actual),bh=height-36-by;return <g key={r.date}><rect x={bx} y={by} width="14" height={Math.max(0,bh)} rx="5" fill="#2563eb" opacity=".9"/><circle cx={x(i)} cy={y(r.target)} r="3" fill="#64748b"/><text x={x(i)} y={height-16} textAnchor="middle" fontSize="10" fill="currentColor" opacity=".55">{r.day}</text></g>})}</svg><div className="mt-1 flex gap-5 text-xs text-slate-500"><span><i className="mr-1 inline-block size-2 rounded-sm bg-blue-600"/>Actual</span><span><i className="mr-1 inline-block h-[2px] w-4 align-middle bg-slate-400"/>Target</span></div></div>}
export default function StoreAchievementPage(){const[period,setPeriod]=useState(today().slice(0,7)),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let active=true;setLoading(true);fetch(`/api/store-achievement?period=${period}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()).then(j=>{if(active)setData(j)}).catch(()=>{if(active)setData(null)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[period]);const salesProgress=useMemo(()=>data?.progress.find(x=>x.key==="amount"),[data]);if(loading&&!data)return <div className="rounded-2xl border bg-white p-8 text-center text-slate-500 shadow-sm dark:bg-slate-950">Memuat Pencapaian Store…</div>;if(!data||data.error)return <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 font-bold text-rose-700">{data?.error||"Data Pencapaian Store belum tersedia."}</div>;return <div className="space-y-5"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-blue-600">M238 PIM 2</p><h1 className="mt-1 text-3xl font-black tracking-[-.04em]">Pencapaian Store</h1><p className="mt-1 text-sm text-slate-500">Ringkasan pencapaian store • {monthName(period)}</p></div><label className="w-full sm:w-56"><span className="mb-1 block text-[11px] font-black uppercase tracking-[.12em] text-slate-400">Bulan & Tahun</span><select value={period} onChange={e=>setPeriod(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 text-sm font-bold outline-none dark:bg-slate-950">{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label></header>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard accent label="Sales Achievement" value={`${shortMoney(data.actual.amount)} / ${shortMoney(data.target.amount)}`} sub={pct(data.achievement)}/><SummaryCard label="Sisa Target" value={shortMoney(data.remaining)}/><SummaryCard label="Sisa Hari" value={`${data.remainingDays} Hari`}/><SummaryCard label="Need / Day" value={shortMoney(data.needPerDay)}/></section>
<section className="grid gap-5 xl:grid-cols-[.9fr_1.4fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="mb-5"><h2 className="text-lg font-black">Progress Target</h2><p className="mt-1 text-sm text-slate-500">Achievement bulan terpilih</p></div><div className="space-y-5">{data.progress.map(r=><ProgressRow key={r.key} row={r}/>)}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="mb-3"><h2 className="text-lg font-black">Daily Performance</h2><p className="mt-1 text-sm text-slate-500">Actual vs target sales per hari</p></div><DailyChart rows={data.daily}/><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[[`${data.today.label} Sales`,shortMoney(data.today.sales)],[`${data.today.label} Target`,shortMoney(data.today.target)],[`${data.today.label} Achievement`,pct(data.today.achievement)],["Projected Closing",shortMoney(data.projected)],["Projected Achievement",pct(data.projectedAchievement)]].map(([l,v])=><div key={l} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><p className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">{l}</p><p className="mt-1 font-black">{v}</p></div>)}</div></article></section>
<section className="grid gap-5 xl:grid-cols-[.9fr_1.4fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="text-lg font-black">KPI Store</h2><p className="mt-1 text-sm text-slate-500">KPI utama tanpa traffic & transaction card</p><div className="mt-5 divide-y dark:divide-slate-800">{[["LFL",<Delta value={data.kpi.lfl}/>,"vs periode yang sama tahun lalu"],["MTM",<Delta value={data.kpi.mtm}/>,"vs bulan sebelumnya"],["CVR",<b>{pct(data.kpi.cvr)}</b>,"Conversion Rate"],["UPT",<b>{data.kpi.upt.toLocaleString("id-ID",{maximumFractionDigits:1})}</b>,"Unit per transaction"],["ATV",<b>{shortMoney(data.kpi.atv)}</b>,"Average transaction value"]].map(([l,v,s])=><div key={String(l)} className="flex items-center justify-between gap-4 py-3"><div><p className="font-black">{l}</p><p className="text-xs text-slate-400">{s}</p></div><div className="text-right text-lg">{v}</div></div>)}</div></article><article className="rounded-2xl border bg-white shadow-sm dark:bg-slate-950"><div className="border-b px-5 py-4 dark:border-slate-800"><h2 className="text-lg font-black">LOB Performance</h2><p className="mt-1 text-sm text-slate-500">Qty bulanan, target dan pergerakan last week</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-slate-400"><th className="px-5 py-3 text-left">LOB</th><th className="px-4 py-3 text-right">Sales / Qty</th><th className="px-4 py-3 text-right">Target</th><th className="px-4 py-3 text-right">Achievement</th><th className="px-5 py-3 text-right">vs Last Week</th></tr></thead><tbody>{data.lob.map(r=><tr key={r.name} className="border-t dark:border-slate-800"><td className="px-5 py-3 font-black">{r.name}</td><td className="px-4 py-3 text-right">{r.qty} pcs</td><td className="px-4 py-3 text-right">{r.target||"—"}</td><td className="px-4 py-3 text-right font-bold">{r.target?pct(r.achievement):"—"}</td><td className={`px-5 py-3 text-right font-black ${r.vsLastWeek>=0?"text-emerald-600":"text-rose-600"}`}>{r.vsLastWeek>=0?"+":""}{pct(r.vsLastWeek)}</td></tr>)}</tbody></table></div></article></section>
<section className="rounded-2xl border border-blue-100 bg-blue-50/60 px-5 py-4 shadow-sm dark:border-blue-900/40 dark:bg-blue-950/20"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:gap-4"><b className="shrink-0 text-blue-700 dark:text-blue-300">Store Insight</b><p className="text-sm leading-6 text-slate-700 dark:text-slate-300">{data.insight}</p></div></section></div>}
