"use client";

import {useEffect,useMemo,useState} from "react";

type FilterMode="week"|"month"|"range";
type StaffShare={id?:string;name:string;position?:string;share:number};
type ProviderStaff={name:string;qty:number;value:number;deviceQty:number;deviceValue:number;ar:number};
type Provider={name:string;qty:number;value:number;staff:ProviderStaff[]};
type Payload={periodLabel?:string;week?:string;month?:string;from?:string;to?:string;availableWeeks?:string[];availableMonths?:string[];vas?:{providers?:Provider[];total?:{qty?:number;value?:number}}};
type TargetMap=Record<string,number>;

const VAS=["Qoala","Telkomsel","XL","Indosat"] as const;
const num=new Intl.NumberFormat("id-ID");
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const toNum=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
const monthName=(v:string)=>{if(!/^\d{4}-\d{2}$/.test(v))return v;const[y,m]=v.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))};
const panel="m238-soft-card rounded-2xl border";
function achStatus(ach:number,target:number){const p=target>0?ach/target*100:0;return p>=100?"Achieve":p>=80?"Need Push":"Critical"}
function arStatus(ar:number){return ar>=40?"Achieve":ar>=30?"Need Push":"Critical"}
function badgeClass(s:string){return s==="Achieve"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300":s==="Need Push"?"bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300":"bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300"}

export default function VasFocusPage(){
 const now=today(),initialMonth=now.slice(0,7);
 const[filterMode,setFilterMode]=useState<FilterMode>("week"),[week,setWeek]=useState(""),[month,setMonth]=useState(initialMonth),[from,setFrom]=useState(`${initialMonth}-01`),[to,setTo]=useState(now);
 const[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[activeVAS,setActiveVAS]=useState<string>("Qoala");
 const[targetOpen,setTargetOpen]=useState(false),[valueTargets,setValueTargets]=useState<TargetMap>({}),[valueDraft,setValueDraft]=useState<TargetMap>({}),[staffShares,setStaffShares]=useState<StaffShare[]>([]),[saving,setSaving]=useState(false),[message,setMessage]=useState("");

 useEffect(()=>{
  let alive=true;const q=new URLSearchParams({mode:filterMode});if(filterMode==="week"&&week)q.set("week",week);if(filterMode==="month")q.set("month",month);if(filterMode==="range"){q.set("from",from);q.set("to",to)}
  setLoading(true);setError("");
  fetch(`/api/target-focus?${q.toString()}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j?.error||"Gagal membaca data VAS Fokus");return j}).then((j:Payload)=>{if(!alive)return;setData(j||{});if(!week&&j?.week)setWeek(j.week);if(!month&&j?.month)setMonth(j.month)}).catch(e=>{if(!alive)return;setData({});setError(e instanceof Error?e.message:"Gagal membaca data VAS Fokus")}).finally(()=>{if(alive)setLoading(false)});
  return()=>{alive=false};
 },[filterMode,week,month,from,to]);

 const targetScope=filterMode==="week"?"weekly":filterMode==="month"?"monthly":"range";
 const targetPeriod=filterMode==="week"?(data?.week||week):filterMode==="month"?month:`${from}|${to}`;
 useEffect(()=>{
  if(!targetPeriod)return;let alive=true;
  fetch(`/api/manual-target?scope=${targetScope}&period=${encodeURIComponent(targetPeriod)}&group=vas-focus-value&t=${Date.now()}`,{cache:"no-store"})
   .then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j?.error||"Gagal membaca target Value");return j})
   .then(j=>{if(!alive)return;const v:TargetMap={};for(const name of VAS)v[name]=Math.max(0,toNum(j?.targets?.[name]?.target));setValueTargets(v);setValueDraft(v);setStaffShares(Array.isArray(j?.staff)?j.staff:[])})
   .catch(()=>{if(!alive)return;const v:TargetMap={};for(const name of VAS)v[name]=0;setValueTargets(v);setValueDraft(v);setStaffShares([])});
  return()=>{alive=false};
 },[targetScope,targetPeriod]);

 const rawProviders=Array.isArray(data?.vas?.providers)?data!.vas!.providers!:[];
 const providerMap=useMemo(()=>new Map(rawProviders.map(p=>[String(p?.name||"").trim().toUpperCase(),p])),[rawProviders]);
 const providers=useMemo(()=>VAS.map(name=>{const p=providerMap.get(name.toUpperCase());return{name,qty:toNum(p?.qty),value:toNum(p?.value),staff:Array.isArray(p?.staff)?p!.staff:[] as ProviderStaff[]}}),[providerMap]);
 const active=useMemo(()=>providers.find(p=>p.name===activeVAS)??providers[0]??{name:"Qoala",qty:0,value:0,staff:[] as ProviderStaff[]},[providers,activeVAS]);
 const activeTarget=toNum(valueTargets[active.name]),activeValue=toNum(active.value),activeQty=toNum(active.qty),activePct=activeTarget?activeValue/activeTarget*100:0,activeGap=Math.max(0,activeTarget-activeValue),activeStatus=achStatus(activeValue,activeTarget);
 const totalTarget=VAS.reduce((a,v)=>a+toNum(valueTargets[v]),0),totalValue=providers.reduce((a,p)=>a+p.value,0),totalQty=providers.reduce((a,p)=>a+p.qty,0),overall=totalTarget?totalValue/totalTarget*100:0,totalGap=Math.max(0,totalTarget-totalValue);
 const shareByName=useMemo(()=>new Map((staffShares||[]).map(s=>[String(s?.name||"").trim().toUpperCase(),Math.max(0,toNum(s?.share))])),[staffShares]);
 const staffRows=useMemo(()=>{const sales=new Map((Array.isArray(active?.staff)?active.staff:[]).map(r=>[String(r?.name||"").trim().toUpperCase(),r]));const names=new Map<string,string>();for(const r of active?.staff||[]){const n=String(r?.name||"").trim();if(n)names.set(n.toUpperCase(),n)}for(const r of staffShares||[]){const n=String(r?.name||"").trim();if(n)names.set(n.toUpperCase(),n)}return[...names.entries()].map(([key,name])=>{const r=sales.get(key);const qty=toNum(r?.qty),value=toNum(r?.value),deviceQty=toNum(r?.deviceQty),ar=toNum(r?.ar),share=shareByName.get(key)||0,valueTarget=Math.round(activeTarget*share),valueGap=Math.max(0,valueTarget-value),status=active.name==="Qoala"?arStatus(ar):achStatus(value,valueTarget);return{name,qty,value,deviceQty,ar,valueTarget,valueGap,status}}).sort((a,b)=>b.value-a.value||b.qty-a.qty||a.name.localeCompare(b.name))},[active,staffShares,shareByName,activeTarget]);

 const save=async()=>{setSaving(true);setMessage("");try{const body:TargetMap={};for(const v of VAS)body[v]=Math.max(0,Math.floor(toNum(valueDraft[v])));const res=await fetch("/api/manual-target",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:targetScope,period:targetPeriod,group:"vas-focus-value",targets:body})});const j=await res.json();if(!res.ok){setMessage(j?.error||"Gagal menyimpan target Value");return}setValueTargets(body);setValueDraft(body);setStaffShares(Array.isArray(j?.staff)?j.staff:staffShares);setTargetOpen(false)}catch{setMessage("Koneksi gagal saat menyimpan target.")}finally{setSaving(false)}};

 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600 dark:text-blue-400">M238 • Target Fokus</p><h2 className="mt-1 text-3xl font-black">VAS Fokus</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Pilih provider untuk melihat detail. Target utama menggunakan Value.</p></div>
  <section className={`${panel} p-4`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{(["week","month","range"] as FilterMode[]).map(f=><button key={f} onClick={()=>setFilterMode(f)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filterMode===f?"bg-blue-600 text-white":"bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"}`}>{f==="week"?"Week":f==="month"?"Bulan":"Range Tanggal"}</button>)}</div><button onClick={()=>{setValueDraft({...valueTargets});setMessage("");setTargetOpen(true)}} className="rounded-xl border px-4 py-2 text-sm font-black">Set Target VAS</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{filterMode==="week"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Apple Week</span><select value={week} onChange={e=>setWeek(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableWeeks??[]).map(w=><option key={w} value={w}>{w}</option>)}</select></label>}{filterMode==="month"&&<label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Filter Bulan</span><select value={month} onChange={e=>setMonth(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold">{(data?.availableMonths??[]).map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></label>}{filterMode==="range"&&<><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Dari Tanggal</span><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label><label><span className="mb-1 block text-[11px] font-bold uppercase text-slate-500">Sampai Tanggal</span><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border px-3 font-semibold"/></label></>}</div><p className="mt-3 text-xs text-slate-500">Periode aktif: <b>{data?.periodLabel||targetPeriod||"-"}</b></p></section>
  {loading?<div className={`${panel} p-8 text-center text-slate-500`}>Memuat VAS Fokus…</div>:<>{error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-700">Data VAS belum dapat dibaca: {error}</div>}
   <section className={`${panel} p-4`}><div className="flex flex-wrap gap-x-6 gap-y-2 text-sm"><span><b>Total Target:</b> {money.format(totalTarget)}</span><span><b>Achievement:</b> {money.format(totalValue)} ({pct(overall)})</span><span><b>Gap:</b> {money.format(totalGap)}</span><span><b>Actual Qty:</b> {num.format(totalQty)} unit</span></div></section>
   <section className={`${panel} p-3`}><div className="overflow-x-auto"><div className="flex min-w-max gap-2">{providers.map(p=>{const target=toNum(valueTargets[p.name]),pc=target?p.value/target*100:0,selected=activeVAS===p.name;return <button key={p.name} onClick={()=>setActiveVAS(p.name)} className={`rounded-xl border px-4 py-2 text-left ${selected?"border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/30":"bg-white text-slate-700 dark:bg-slate-900 dark:text-slate-200"}`}><div className="text-sm font-black">{p.name}</div><div className="mt-0.5 text-[11px] opacity-70">{pct(pc)}</div></button>})}</div></div></section>
   <section className={`${panel} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Provider Dipilih</p><h3 className="mt-1 text-2xl font-black">{active.name}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-black ${badgeClass(activeStatus)}`}>{activeStatus}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-4"><div><p className="text-xs text-slate-400">Target Value</p><p className="mt-1 text-xl font-black">{money.format(activeTarget)}</p></div><div><p className="text-xs text-slate-400">Achievement</p><p className="mt-1 text-xl font-black">{money.format(activeValue)}</p><p className="text-xs text-slate-500">{pct(activePct)}</p></div><div><p className="text-xs text-slate-400">Gap Value</p><p className="mt-1 text-xl font-black">{money.format(activeGap)}</p></div><div><p className="text-xs text-slate-400">Actual Qty</p><p className="mt-1 text-xl font-black">{num.format(activeQty)} unit</p></div></div></section>
   <section className={`${panel} overflow-hidden`}><div className="border-b px-5 py-4"><h3 className="font-black">Penjualan Staff • {active.name}</h3><p className="mt-1 text-sm text-slate-500">Detail hanya untuk provider yang sedang dipilih.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead><tr><th className="px-4 py-3 text-left">Staff</th><th className="px-3 py-3 text-right">Target Value</th><th className="px-3 py-3 text-right">Value</th><th className="px-3 py-3 text-right">Gap</th><th className="px-3 py-3 text-right">Qty</th><th className="px-3 py-3 text-right">Device Qty</th><th className="px-3 py-3 text-right">AR</th><th className="px-3 py-3 text-left">Status</th></tr></thead><tbody>{staffRows.map(r=><tr key={`${active.name}-${r.name}`} className="border-t"><td className="px-4 py-3 font-bold">{r.name}</td><td className="px-3 py-3 text-right">{money.format(r.valueTarget)}</td><td className="px-3 py-3 text-right font-black">{money.format(r.value)}</td><td className="px-3 py-3 text-right">{money.format(r.valueGap)}</td><td className="px-3 py-3 text-right">{num.format(r.qty)}</td><td className="px-3 py-3 text-right">{num.format(r.deviceQty)}</td><td className="px-3 py-3 text-right font-black">{pct(r.ar)}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-black ${badgeClass(r.status)}`}>{r.status}</span></td></tr>)}</tbody></table></div></section>
  </>}
  {targetOpen&&<div className="fixed inset-0 z-[140] grid place-items-center bg-black/35 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setTargetOpen(false)}}><div className="m238-soft-card max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-2xl border bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Set Target VAS</p><h3 className="mt-1 text-xl font-black">{data?.periodLabel||targetPeriod||"-"}</h3></div><button onClick={()=>setTargetOpen(false)} className="rounded-lg border px-3 py-1.5 text-sm font-bold">Tutup</button></div><div className="mt-4 space-y-3">{VAS.map(v=><label key={v} className="block rounded-xl border p-3"><span className="font-black">{v}</span><span className="mt-2 block text-xs font-bold text-slate-500">Target Value</span><input type="number" min="0" step="1000" value={valueDraft[v]??0} onChange={e=>setValueDraft(x=>({...x,[v]:Math.max(0,Math.floor(toNum(e.target.value)))}))} className="mt-2 h-10 w-full rounded-xl border px-3 text-right font-black"/><span className="mt-1 block text-[11px] text-slate-500">{money.format(valueDraft[v]||0)}</span></label>)}</div><div className="mt-4 border-t pt-4 text-sm"><b>Total Target Value:</b> {money.format(VAS.reduce((a,v)=>a+toNum(valueDraft[v]),0))}</div>{message&&<p className="mt-3 text-sm font-bold text-rose-600">{message}</p>}<div className="mt-5 flex justify-end gap-2"><button onClick={()=>setTargetOpen(false)} className="rounded-xl border px-4 py-2 text-sm font-bold">Batal</button><button disabled={saving} onClick={save} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-black text-white disabled:opacity-50">{saving?"Menyimpan…":"Simpan Target"}</button></div></div></div>}
 </div>;
}
