"use client";

import {useCallback,useEffect,useMemo,useState} from "react";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
type Agg={qty:number;amount:number};
type Analysis={review:string;actionPlan:string;target:number;achievement:number;gap:number};
type Weekly={labelA:string;labelB:string;periodA:{start:string;end:string};periodB:{start:string;end:string};availableWeeks:string[];a:{scheme:Record<string,Agg>;lob:Record<string,Record<string,Agg>>};b:{scheme:Record<string,Agg>;lob:Record<string,Record<string,Agg>>};analysis:Record<string,Analysis>;feedbackSummary:string;targets:{lob:Record<string,number>};error?:string};
type Daily={total:{amount:number;qty:number;invoices:number}};
const lobOrder:[[string,string]]|any=[["AIRPODS","AIRPODS"],["APPLE WATCH","APPLE WATCH"],["IPAD","IPAD"],["IPHONE","IPHONE"],["MAC","MACBOOK"]];
function total(values:Record<string,Agg>={}){return Object.values(values).reduce((a,r)=>({qty:a.qty+(r.qty||0),amount:a.amount+(r.amount||0)}),{qty:0,amount:0})}
function dates(start:string,end:string){const out:string[]=[];if(!start||!end)return out;const d=new Date(`${start}T00:00:00Z`),e=new Date(`${end}T00:00:00Z`);while(d<=e){out.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1)}return out}
async function dailySummary(start:string,end:string){const ds=dates(start,end),rows=await Promise.all(ds.map(async date=>{const r=await fetch(`/api/daily?date=${date}`,{cache:"no-store"});return await r.json() as Daily}));return rows.reduce((a,r)=>({amount:a.amount+(r.total?.amount||0),qty:a.qty+(r.total?.qty||0),invoices:a.invoices+(r.total?.invoices||0)}),{amount:0,qty:0,invoices:0})}

export default function WeeklyReasonPage(){
 const[data,setData]=useState<Weekly|null>(null),[from,setFrom]=useState(""),[to,setTo]=useState(""),[trafficA,setTrafficA]=useState(0),[trafficB,setTrafficB]=useState(0),[dailyA,setDailyA]=useState({amount:0,qty:0,invoices:0}),[dailyB,setDailyB]=useState({amount:0,qty:0,invoices:0}),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const q=from&&to?`?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`:"",w=await fetch(`/api/weekly${q}`,{cache:"no-store"}).then(r=>r.json()) as Weekly;setData(w);if(!from)setFrom(w.labelA||"");if(!to)setTo(w.labelB||"");if(w.periodA?.start&&w.periodB?.start){const[ta,tb,da,db]=await Promise.all([fetch(`/api/traffic?from=${w.periodA.start}&to=${w.periodA.end}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/traffic?from=${w.periodB.start}&to=${w.periodB.end}`,{cache:"no-store"}).then(r=>r.json()),dailySummary(w.periodA.start,w.periodA.end),dailySummary(w.periodB.start,w.periodB.end)]);setTrafficA(Number(ta.total||0));setTrafficB(Number(tb.total||0));setDailyA(da);setDailyB(db)}}finally{setLoading(false)}},[from,to]);
 useEffect(()=>{void load()},[]);
 const salesGrowth=dailyA.amount?(dailyB.amount-dailyA.amount)/dailyA.amount*100:0,trafficGrowth=trafficA?(trafficB-trafficA)/trafficA*100:0,cvrA=trafficA?dailyA.invoices/trafficA*100:0,cvrB=trafficB?dailyB.invoices/trafficB*100:0,uptA=dailyA.invoices?dailyA.qty/dailyA.invoices:0,uptB=dailyB.invoices?dailyB.qty/dailyB.invoices:0;
 const options=data?.availableWeeks||[];
 return <div className="space-y-5">
  <div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">M238 Reporting</p><h1 className="mt-1 text-3xl font-black">Weekly Reason</h1><p className="mt-1 text-sm text-slate-500">Format reason mingguan mengikuti contoh: sales, traffic, conversion, feedback LOB, target dan action plan.</p></div>
  <section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1 block text-xs font-black uppercase tracking-wide text-slate-400">Compare Week</span><select value={from} onChange={e=>setFrom(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900">{options.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="mb-1 block text-xs font-black uppercase tracking-wide text-slate-400">Current Week</span><select value={to} onChange={e=>setTo(e.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900">{options.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>void load()} disabled={loading} className="self-end rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Memuat…":"Buat Reason"}</button></div></section>
  {data&&<>
   <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="text-xl font-black">M238 DIGIMAP PIM 2</h2><h3 className="mt-1 text-lg font-black">{data.labelB}</h3><p className="mt-4 leading-7">Penjualan {data.labelB} mencapai <b>{money.format(dailyB.amount)}</b>, {salesGrowth>=0?"naik":"turun"} <b>{pct(Math.abs(salesGrowth))}</b> dibanding {data.labelA} sebesar <b>{money.format(dailyA.amount)}</b>.</p></section>
   <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Traffic</h3><p className="mt-3">{data.labelA}: <b>{num.format(trafficA)}</b></p><p>{data.labelB}: <b>{num.format(trafficB)}</b></p><p className={`mt-2 font-black ${trafficGrowth>=0?"text-emerald-600":"text-rose-600"}`}>Growth: {trafficGrowth>=0?"+":""}{pct(trafficGrowth)}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Conversion</h3><div className="mt-3 grid grid-cols-2 gap-4"><div><b>{data.labelA}</b><p>{num.format(dailyA.invoices)} transaksi</p><p>CVR {pct(cvrA)}</p><p>UPT {uptA.toFixed(1)}</p></div><div><b>{data.labelB}</b><p>{num.format(dailyB.invoices)} transaksi</p><p>CVR {pct(cvrB)}</p><p>UPT {uptB.toFixed(1)}</p></div></div></div></section>
   <section className="rounded-2xl border bg-blue-50/60 p-5 dark:bg-blue-950/20"><h3 className="font-black">Feedback Team</h3><p className="mt-2 leading-7">{data.feedbackSummary}</p></section>
   {lobOrder.map(([key,label]:[string,string])=>{const a=total(data.a?.lob?.[key]),b=total(data.b?.lob?.[key]),g=a.qty?(b.qty-a.qty)/a.qty*100:0,an=data.analysis?.[key];return <section key={key} className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="text-lg font-black">LOB {label}</h3><p className="mt-3">Penjualan {label} week ini {g>=0?"mengalami kenaikan":"mengalami penurunan"} <b>{g>=0?"+":""}{pct(g)}</b> dan menjual sebanyak <b>{num.format(b.qty)} unit</b>.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><b>{data.labelA}</b><p>{num.format(a.qty)} unit</p><p>{money.format(a.amount)}</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><b>{data.labelB}</b><p>{num.format(b.qty)} unit</p><p>{money.format(b.amount)}</p></div></div><div className="mt-4"><b>Feedback</b><p className="mt-1 leading-7">{an?.review||"Belum ada reason."}</p></div><div className="mt-4"><b>Achievement</b><p className={an?.gap>=0?"text-emerald-600":"text-rose-600"}>{an?.target?`Target: ${an.gap>=0?"+":"-"}${Math.abs(an.gap)} unit • ${pct(an.achievement)}`:"Target belum tersedia"}</p></div><div className="mt-4"><b>Action Plan</b><p className="mt-1 leading-7">{an?.actionPlan||"Monitoring opportunity dan follow up customer potensial."}</p></div></section>})}
  </>}
 </div>
}
