"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {exportReportPdf} from "@/lib/dashboard-export";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(v)}%`;
type Agg={qty:number;amount:number};
type Analysis={review:string;actionPlan:string;target:number;achievement:number;gap:number};
type Weekly={labelA:string;labelB:string;availableWeeks:string[];a:{scheme:Record<string,Agg>;lob:Record<string,Record<string,Agg>>};b:{scheme:Record<string,Agg>;lob:Record<string,Record<string,Agg>>};analysis:Record<string,Analysis>;feedbackSummary:string;error?:string};
type Side={label:string;period:{start:string;end:string};traffic:number;transactions:number;qty:number;upt:number;sales:number};
type Product={article:string;description:string;type:string;lob:string;prevQty:number;currQty:number;stockQty:number};
type Metrics={a:Side;b:Side;products:Product[];error?:string};
type Saved={data?:Weekly;snapshot?:{data?:Weekly};found?:boolean};
const lobOrder:[string,string][]=[["AIRPODS","AirPods"],["APPLE WATCH","Apple Watch"],["IPAD","iPad"],["IPHONE","iPhone"],["MAC","MacBook"]];
const rank=(label:string)=>{const m=label.match(/Week\s*(\d+)\s*Q(\d+)/i);return Number(m?.[2]||0)*100+Number(m?.[1]||0)};
const previousWeek=(weeks:string[],week:string)=>{const sorted=[...weeks].sort((a,b)=>rank(a)-rank(b)),i=sorted.indexOf(week);return i>0?sorted[i-1]:(sorted[0]||week)};
const growth=(a:number,b:number)=>a?(b-a)/a*100:0;
const downProducts=(products:Product[],lob:string)=>products.filter(p=>p.lob===lob&&p.currQty<p.prevQty).sort((a,b)=>(b.prevQty-b.currQty)-(a.prevQty-a.currQty));
function stockSentence(items:Product[]){if(!items.length)return"";return items.slice(0,3).map(p=>`${p.description||p.type} turun ${p.prevQty-p.currQty} unit (${p.prevQty} → ${p.currQty}), SOH ${p.stockQty} unit`).join("; ")}
function planFor(lob:string,analysis:Analysis|undefined,downs:Product[]){const text=(analysis?.review||"").toLowerCase(),out:string[]=[];if(downs.some(p=>p.stockQty<=0))out.push("prioritaskan konsolidasi stok untuk tipe/warna yang kosong dan siapkan alternatif terdekat");else if(downs.length)out.push("fokuskan selling ke tipe/warna yang turun walaupun stok masih tersedia");if(/harga|promo|compare|kompetitor|budget/.test(text))out.push("maksimalkan promo aktif dan opsi cicilan/BNPL saat customer masih compare");if(/follow|belum closing|menunggu/.test(text))out.push("follow up kembali customer yang belum closing dan simpan opportunity per tipe");if(/traffic|sepi/.test(text))out.push("maksimalkan conversion dari setiap traffic yang masuk");if(lob==="AIRPODS")out.unshift("jalankan AirPods Try On, voucher Rp250 ribu, dan attachment ke penjualan device");if(lob==="MAC")out.unshift("jalankan MacBook Try On, voucher Rp600 ribu, dan demo sesuai use case customer");if(lob==="IPAD")out.unshift("jalankan iPad Try On, voucher Rp600 ribu, serta attachment Pencil/keyboard");if(lob==="IPHONE"&&/iphone\s*18/.test(text))out.unshift("buat list customer yang menunggu iPhone 18 dan follow up terjadwal, sambil tawarkan opsi yang tersedia bila kebutuhannya tidak bisa menunggu");if(lob==="APPLE WATCH")out.unshift("demo fitur health/fitness dan arahkan ke ukuran/warna yang stoknya tersedia");return [...new Set(out)].slice(0,3).join("; ")+"."}

export default function WeeklyReasonLivePage(){
 const reportRef=useRef<HTMLDivElement>(null),[weeks,setWeeks]=useState<string[]>([]),[selected,setSelected]=useState(""),[weekly,setWeekly]=useState<Weekly|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[source,setSource]=useState(""),[busy,setBusy]=useState("");
 const latest=weeks.length?[...weeks].sort((a,b)=>rank(a)-rank(b)).at(-1)||"":"";
 const load=useCallback(async(week:string,force=false,knownWeeks?:string[])=>{if(!week)return;setLoading(true);setError("");try{const list=knownWeeks||weeks,compare=previousWeek(list,week),isCurrent=week===(list.length?[...list].sort((a,b)=>rank(a)-rank(b)).at(-1):week);let reason:Weekly|null=null;if(!isCurrent&&!force){const saved=await fetch(`/api/weekly-reason-snapshot?week=${encodeURIComponent(week)}`,{cache:"no-store"}).then(r=>r.json()) as Saved;reason=(saved.snapshot?.data||saved.data||null) as Weekly|null;if(reason)setSource("Reason tersimpan • angka performa tetap membaca data terbaru")}if(!reason){reason=await fetch(`/api/weekly?from=${encodeURIComponent(compare)}&to=${encodeURIComponent(week)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Weekly;setSource(isCurrent?"Week berjalan • live":"Reason diperbarui dari data terbaru")}if(reason.error)throw new Error(reason.error);const m=await fetch(`/api/weekly-reason-metrics?from=${encodeURIComponent(compare)}&to=${encodeURIComponent(week)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Metrics;if(m.error)throw new Error(m.error);setWeekly(reason);setMetrics(m);if(force||isCurrent){await fetch("/api/weekly-reason-snapshot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({week:reason.labelB,compareWeek:reason.labelA,snapshot:{data:reason,trafficA:m.a.traffic,trafficB:m.b.traffic,dailyA:{qty:m.a.qty,invoices:m.a.transactions},dailyB:{qty:m.b.qty,invoices:m.b.transactions},savedAt:new Date().toISOString()}})}).catch(()=>{})}}catch(e){setError(e instanceof Error?e.message:"Weekly Reason gagal dibaca")}finally{setLoading(false)}},[weeks]);
 useEffect(()=>{void(async()=>{try{const w=await fetch(`/api/weekly?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Weekly;if(w.error)throw new Error(w.error);const list=[...(w.availableWeeks||[])].sort((a,b)=>rank(a)-rank(b));setWeeks(list);const current=w.labelB||list.at(-1)||"";setSelected(current);await load(current,false,list)}catch(e){setError(e instanceof Error?e.message:"Weekly Reason gagal dibuka");setLoading(false)}})()},[]);
 useEffect(()=>{if(!selected||selected!==latest)return;const id=setInterval(()=>void load(selected,false),60000);return()=>clearInterval(id)},[selected,latest,load]);
 const cvrA=metrics?.a.traffic?metrics.a.transactions/metrics.a.traffic*100:0,cvrB=metrics?.b.traffic?metrics.b.transactions/metrics.b.traffic*100:0,salesGrowth=metrics?growth(metrics.a.sales,metrics.b.sales):0,trafficGrowth=metrics?growth(metrics.a.traffic,metrics.b.traffic):0;
 const reasonBlocks=useMemo(()=>lobOrder.map(([key,label])=>{const a=weekly?.a?.lob?.[key]||{},b=weekly?.b?.lob?.[key]||{},aq=Object.values(a).reduce((x,r)=>x+(r.qty||0),0),bq=Object.values(b).reduce((x,r)=>x+(r.qty||0),0),g=growth(aq,bq),analysis=weekly?.analysis?.[key],downs=downProducts(metrics?.products||[],key),detail=stockSentence(downs);return{key,label,aq,bq,g,analysis,downs,detail,plan:planFor(key,analysis,downs)}}),[weekly,metrics]);
 const text=()=>{if(!weekly||!metrics)return"";const lines=[`*M238 DIGIMAP PIM 2*`,`*${weekly.labelB}*`,``,`Total Sales: ${money.format(metrics.b.sales)} (${salesGrowth>=0?"naik":"turun"} ${pct(Math.abs(salesGrowth))} vs ${weekly.labelA} ${money.format(metrics.a.sales)})`,``,`Traffic ${weekly.labelA}: ${num.format(metrics.a.traffic)}`,`Traffic ${weekly.labelB}: ${num.format(metrics.b.traffic)} (${trafficGrowth>=0?"+":""}${pct(trafficGrowth)})`,``,`Conversion ${weekly.labelA}: ${num.format(metrics.a.transactions)} transaksi | CVR ${pct(cvrA)} | UPT ${metrics.a.upt.toFixed(1)}`,`Conversion ${weekly.labelB}: ${num.format(metrics.b.transactions)} transaksi | CVR ${pct(cvrB)} | UPT ${metrics.b.upt.toFixed(1)}`,``,`*Compile Reason Staff*`,weekly.feedbackSummary||"Belum ada feedback team."];for(const x of reasonBlocks){lines.push("",`*${x.label}*`,`${x.label} ${weekly.labelB} ${x.g>=0?"naik":"turun"} ${pct(Math.abs(x.g))} dengan total ${x.bq} unit, dibanding ${weekly.labelA} ${x.aq} unit.`,`Reason: ${x.analysis?.review||"Pergerakan mengikuti data week-to-week."}${x.detail?` Data tipe/warna: ${x.detail}.`:""}`,`Action Plan: ${x.plan}`)}return lines.join("\n")};
 const pdf=async()=>{if(!reportRef.current||!weekly)return;setBusy("PDF");try{await exportReportPdf(reportRef.current,`M238-Weekly-Reason-${weekly.labelB}`)}finally{setBusy("")}};const share=async()=>{const t=text();if(!t)return;setBusy("TEXT");try{if(navigator.share)await navigator.share({title:`M238 Weekly Reason ${weekly?.labelB||""}`,text:t});else{await navigator.clipboard.writeText(t);alert("Weekly Reason sudah disalin.")}}finally{setBusy("")}};const wa=()=>{const t=text();if(t)window.open(`https://wa.me/?text=${encodeURIComponent(t)}`,"_blank","noopener,noreferrer")};
 return <div className="space-y-5">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">M238 Reporting</p><h1 className="mt-1 text-3xl font-black">Weekly Reason</h1><p className="mt-1 text-sm text-slate-500">Data week-to-week, traffic, conversion, feedback team, type/warna yang turun, dan SOH.</p></div>{weekly&&<div className="export-hide flex flex-wrap gap-2"><button onClick={()=>void pdf()} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white">{busy==="PDF"?"Membuat...":"Unduh PDF"}</button><button onClick={()=>void share()} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-black">Share Text</button><button onClick={wa} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Share WhatsApp</button></div>}</div>
  <section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Pilih Week</span><select value={selected} onChange={e=>{setSelected(e.target.value);void load(e.target.value,false)}} className="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900">{weeks.map(w=><option key={w}>{w}</option>)}</select></label><div className="rounded-xl border bg-slate-50 px-4 py-2 dark:bg-slate-900"><span className="text-xs font-black uppercase text-slate-400">Compare</span><p className="mt-1 font-black">{selected?previousWeek(weeks,selected):"—"}</p></div><button onClick={()=>void load(selected,true)} disabled={loading} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Memuat…":"Update Reason"}</button></div><p className="mt-3 text-xs font-semibold text-slate-500">{source}{selected===latest?" • otomatis refresh 60 detik":""}</p></section>
  {error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
  {weekly&&metrics&&<div ref={reportRef} className="space-y-5 bg-slate-50 p-1 dark:bg-slate-900">
   <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="text-xl font-black">M238 DIGIMAP PIM 2</h2><h3 className="mt-1 text-lg font-black">{weekly.labelB}</h3><p className="mt-4 leading-7">Total sales <b>{money.format(metrics.b.sales)}</b>, {salesGrowth>=0?"naik":"turun"} <b>{pct(Math.abs(salesGrowth))}</b> dibanding {weekly.labelA} <b>{money.format(metrics.a.sales)}</b>.</p><p className="mt-2 text-xs text-slate-500">Sumber: Data Copas yang sama dengan Weekly Report → Sales Summary.</p></section>
   <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Traffic</h3><div className="mt-3 grid grid-cols-2 gap-4"><div><b>{weekly.labelA}</b><p className="text-xl">{num.format(metrics.a.traffic)}</p><small>{metrics.a.period.start} s/d {metrics.a.period.end}</small></div><div><b>{weekly.labelB}</b><p className="text-xl">{num.format(metrics.b.traffic)}</p><small>{metrics.b.period.start} s/d {metrics.b.period.end}</small></div></div><p className={`mt-3 font-black ${trafficGrowth>=0?"text-emerald-600":"text-rose-600"}`}>Growth {trafficGrowth>=0?"+":""}{pct(trafficGrowth)}</p></div>
   <div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Conversion</h3><div className="mt-3 grid grid-cols-2 gap-4"><div><b>{weekly.labelA}</b><p>Transaksi {num.format(metrics.a.transactions)}</p><p>CVR {pct(cvrA)}</p><p>UPT {metrics.a.upt.toFixed(1)}</p></div><div><b>{weekly.labelB}</b><p>Transaksi {num.format(metrics.b.transactions)}</p><p>CVR {pct(cvrB)}</p><p>UPT {metrics.b.upt.toFixed(1)}</p></div></div><p className="mt-3 text-xs text-slate-500">Transaksi = invoice unik • UPT = total qty ÷ invoice unik • CVR = invoice unik ÷ traffic.</p></div></section>
   <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Compile Reason Staff</h3><p className="mt-3 whitespace-pre-line text-sm leading-7">{weekly.feedbackSummary||"Belum ada feedback team."}</p></section>
   {reasonBlocks.map(x=><section key={x.key} className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-black">{x.label}</h3><span className={`rounded-full px-3 py-1 text-xs font-black ${x.g>=0?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{x.g>=0?"+":""}{pct(x.g)}</span></div><p className="mt-3">{weekly.labelA}: <b>{x.aq} unit</b> → {weekly.labelB}: <b>{x.bq} unit</b></p><p className="mt-3 text-sm leading-7"><b>Reason:</b> {x.analysis?.review||"Pergerakan mengikuti data week-to-week."}</p>{x.detail&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm leading-6 text-amber-950"><b>Type / warna & SOH:</b> {x.detail}.</p>}<p className="mt-3 text-sm leading-7"><b>Action Plan:</b> {x.plan}</p></section>)}
  </div>}
 </div>
}
