"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {exportReportPdf} from "@/lib/dashboard-export";

const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const num=new Intl.NumberFormat("id-ID");
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
type Agg={qty:number;amount:number};
type Analysis={review:string;actionPlan:string;target:number;achievement:number;gap:number};
type Weekly={labelA:string;labelB:string;availableWeeks:string[];a:{lob:Record<string,Record<string,Agg>>};b:{lob:Record<string,Record<string,Agg>>};analysis:Record<string,Analysis>;feedbackSummary:string;error?:string};
type Side={label:string;period:{start:string;end:string};traffic:number;transactions:number;qty:number;upt:number;sales:number};
type Product={article:string;description:string;type:string;lob:string;prevQty:number;currQty:number;stockQty:number};
type Metrics={a:Side;b:Side;products:Product[];error?:string};
type Theme={key:string;count:number};
type Lost={label:string;qty:number;status:string};
type LobContext={feedbackCount:number;themes:Theme[];lostStock:Lost[];stockClaimAvailable:number;sohAvailable:boolean};
type Context={byLob:Record<string,LobContext>;feedbackCount:number;error?:string};
type Saved={data?:Weekly;snapshot?:{data?:Weekly};found?:boolean};
const lobOrder:[string,string][]=[["AIRPODS","AirPods"],["APPLE WATCH","Apple Watch"],["IPAD","iPad"],["IPHONE","iPhone"],["MAC","MacBook"]];
const rank=(label:string)=>{const m=label.match(/Week\s*(\d+)\s*Q(\d+)/i);return Number(m?.[2]||0)*100+Number(m?.[1]||0)};
const previousWeek=(weeks:string[],week:string)=>{const sorted=[...weeks].sort((a,b)=>rank(a)-rank(b)),i=sorted.indexOf(week);return i>0?sorted[i-1]:(sorted[0]||week)};
const growth=(a:number,b:number)=>a?(b-a)/a*100:0;
const sum=(r:Record<string,Agg>={})=>Object.values(r).reduce((a,x)=>({qty:a.qty+(x.qty||0),amount:a.amount+(x.amount||0)}),{qty:0,amount:0});
function movers(a:Record<string,Agg>={},b:Record<string,Agg>={}){return [...new Set([...Object.keys(a),...Object.keys(b)])].map(name=>({name,diff:(b[name]?.qty||0)-(a[name]?.qty||0)})).filter(x=>x.diff!==0).sort((x,y)=>Math.abs(y.diff)-Math.abs(x.diff))}
function reviewFor(label:string,a:Record<string,Agg>,b:Record<string,Agg>,ctx:LobContext|undefined){const A=sum(a),B=sum(b),qg=growth(A.qty,B.qty),ag=growth(A.amount,B.amount),mv=movers(a,b),down=mv.filter(x=>x.diff<0).slice(0,2),up=mv.filter(x=>x.diff>0).slice(0,2);let text=`Penjualan ${label} week ini ${B.qty>A.qty?"mengalami kenaikan":B.qty<A.qty?"mengalami penurunan":"stabil"} ${B.qty===A.qty?"0%":`${qg>=0?"+":""}${pct(qg)}`} dibanding week sebelumnya, dari ${A.qty} menjadi ${B.qty} unit.`;if(A.amount)text+=` Secara amount ${ag>=0?"naik":"turun"} ${pct(Math.abs(ag))}.`;if(B.qty<A.qty&&down.length)text+=` Penurunan terbesar terjadi pada ${down.map(x=>x.name).join(" dan ")}.`;else if(B.qty>A.qty&&up.length)text+=` Kenaikan terbesar terbantu oleh ${up.map(x=>x.name).join(" dan ")}.`;else if(up.length&&down.length)text+=` ${up[0].name} naik ${up[0].diff} unit, namun tertahan penurunan ${down[0].name} ${Math.abs(down[0].diff)} unit.`;if(ctx?.lostStock?.length)text+=" Dari reason staff, beberapa lost terjadi pada varian yang stoknya habis atau terbatas.";return text}
function reasonLines(g:number,ctx:LobContext|undefined){if(!ctx)return[];const keys=new Set((ctx.themes||[]).map(x=>x.key)),out:string[]=[];if(keys.has("price"))out.push("Beberapa customer masih compare harga atau penawaran sebelum closing.");if(keys.has("survey"))out.push("Beberapa customer masih survey dan belum menentukan pembelian.");if(keys.has("shifting"))out.push("Ada customer yang beralih ke type atau product alternatif.");if(keys.has("waiting"))out.push("Sebagian customer masih menunggu promo atau product yang dituju.");if(keys.has("installment"))out.push("Opsi cicilan atau metode pembayaran menjadi pertimbangan sebagian customer.");if(keys.has("traffic"))out.push("Opportunity dari traffic masih terbatas pada week ini.");if(g>=0&&keys.has("promo"))out.push("Promo yang berjalan ikut membantu closing.");if(g>=0&&keys.has("tryon"))out.push("Try on atau demo membantu customer lebih yakin dengan produk.");if(g>=0&&keys.has("bundling"))out.push("Bundling membantu menambah closing pada product terkait.");if(!out.length&&ctx.stockClaimAvailable>0)out.push("Reason staff sempat menyebut stok, namun varian yang dicari masih tersedia dan belum ada kendala lain yang dominan.");if(!out.length&&ctx.feedbackCount>0)out.push("Reason staff belum menunjukkan satu kendala yang dominan pada LOB ini.");return out.slice(0,3)}
function planFor(g:number,ctx:LobContext|undefined){const keys=new Set((ctx?.themes||[]).map(x=>x.key)),out:string[]=[];if(ctx?.lostStock?.length){out.push("Request dan konsolidasi antar store untuk varian yang stoknya habis atau terbatas.","Follow up customer yang sebelumnya lost karena stok.","Arahkan customer ke alternatif warna atau kapasitas yang masih tersedia.")}else if(keys.has("price")){out.push("Maksimalkan promo bank atau cicilan yang sedang berjalan.","Highlight benefit pembelian di Digimap saat customer compare.","Follow up customer yang masih membandingkan penawaran.")}else if(keys.has("survey")){out.push("Perkuat probing kebutuhan customer.","Maksimalkan demo atau try on untuk membantu customer menentukan pilihan.","Follow up customer yang sudah menunjukkan buying signal.")}else if(keys.has("shifting")){out.push("Identifikasi type yang paling sering menjadi alternatif.","Maksimalkan upselling atau downselling sesuai kebutuhan customer.","Pastikan staff memahami perbedaan benefit antar type.")}else if(g>=0&&(keys.has("promo")||keys.has("tryon")||keys.has("bundling"))){if(keys.has("tryon"))out.push("Pertahankan try on atau demo pada type yang paling berkontribusi.");if(keys.has("promo"))out.push("Pertahankan penyampaian promo yang terbukti membantu closing.");if(keys.has("bundling"))out.push("Maksimalkan bundling pada customer device yang relevan.")}else if(keys.has("waiting")){out.push("Follow up customer saat promo atau product yang ditunggu sudah tersedia.","Tawarkan alternatif yang paling dekat dengan kebutuhan customer saat ini.")}else if(keys.has("installment")){out.push("Pastikan staff menawarkan opsi cicilan yang sesuai kebutuhan customer.","Jelaskan benefit tenor dan metode pembayaran secara sederhana sebelum closing.")}else if(keys.has("traffic")){out.push("Maksimalkan conversion dari setiap traffic yang masuk.","Perkuat probing agar opportunity yang masuk tidak terlewat.")}else out.push("Monitoring type yang paling turun dan perkuat probing untuk mengetahui kendala customer berikutnya.");return out.slice(0,3)}

export default function WeeklyReasonLivePageV2(){
 const reportRef=useRef<HTMLDivElement>(null),[weeks,setWeeks]=useState<string[]>([]),[selected,setSelected]=useState(""),[weekly,setWeekly]=useState<Weekly|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[context,setContext]=useState<Context|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[source,setSource]=useState(""),[busy,setBusy]=useState("");
 const latest=weeks.length?[...weeks].sort((a,b)=>rank(a)-rank(b)).at(-1)||"":"";
 const load=useCallback(async(week:string,force=false,knownWeeks?:string[])=>{if(!week)return;setLoading(true);setError("");try{const list=knownWeeks||weeks,compare=previousWeek(list,week),isCurrent=week===(list.length?[...list].sort((a,b)=>rank(a)-rank(b)).at(-1):week);let reason:Weekly|null=null;if(!isCurrent&&!force){const saved=await fetch(`/api/weekly-reason-snapshot?week=${encodeURIComponent(week)}`,{cache:"no-store"}).then(r=>r.json()) as Saved;reason=(saved.snapshot?.data||saved.data||null) as Weekly|null;if(reason)setSource("Reason tersimpan • angka performa tetap membaca data terbaru")}if(!reason){reason=await fetch(`/api/weekly?from=${encodeURIComponent(compare)}&to=${encodeURIComponent(week)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Weekly;setSource(isCurrent?"Week berjalan • live":"Reason diperbarui dari data terbaru")}if(reason.error)throw new Error(reason.error);const [m,c]=await Promise.all([fetch(`/api/weekly-reason-metrics?from=${encodeURIComponent(compare)}&to=${encodeURIComponent(week)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Promise<Metrics>,fetch(`/api/weekly-reason-context?week=${encodeURIComponent(week)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Promise<Context>]);if(m.error)throw new Error(m.error);setWeekly(reason);setMetrics(m);setContext(c.error?{byLob:{},feedbackCount:0}:c);if(force||isCurrent)await fetch("/api/weekly-reason-snapshot",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({week:reason.labelB,compareWeek:reason.labelA,snapshot:{data:reason,trafficA:m.a.traffic,trafficB:m.b.traffic,dailyA:{qty:m.a.qty,invoices:m.a.transactions},dailyB:{qty:m.b.qty,invoices:m.b.transactions},savedAt:new Date().toISOString()}})}).catch(()=>{})}catch(e){setError(e instanceof Error?e.message:"Weekly Reason gagal dibaca")}finally{setLoading(false)}},[weeks]);
 useEffect(()=>{void(async()=>{try{const w=await fetch(`/api/weekly?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()) as Weekly;if(w.error)throw new Error(w.error);const list=[...(w.availableWeeks||[])].sort((a,b)=>rank(a)-rank(b));setWeeks(list);const current=w.labelB||list.at(-1)||"";setSelected(current);await load(current,false,list)}catch(e){setError(e instanceof Error?e.message:"Weekly Reason gagal dibuka");setLoading(false)}})()},[]);
 useEffect(()=>{if(!selected||selected!==latest)return;const id=setInterval(()=>void load(selected,false),60000);return()=>clearInterval(id)},[selected,latest,load]);
 const cvrA=metrics?.a.traffic?metrics.a.transactions/metrics.a.traffic*100:0,cvrB=metrics?.b.traffic?metrics.b.transactions/metrics.b.traffic*100:0,salesGrowth=metrics?growth(metrics.a.sales,metrics.b.sales):0,trafficGrowth=metrics?growth(metrics.a.traffic,metrics.b.traffic):0;
 const blocks=useMemo(()=>lobOrder.map(([key,label])=>{const a=weekly?.a?.lob?.[key]||{},b=weekly?.b?.lob?.[key]||{},A=sum(a),B=sum(b),g=growth(A.qty,B.qty),ctx=context?.byLob?.[key],review=reviewFor(label,a,b,ctx),reasons=reasonLines(g,ctx),plans=planFor(g,ctx);return{key,label,A,B,g,ctx,review,reasons,plans}}),[weekly,context]);
 const text=()=>{if(!weekly||!metrics)return"";const lines=[`*M238 DIGIMAP PIM 2*`,`*${weekly.labelB}*`,``,`Total Sales: ${money.format(metrics.b.sales)} (${salesGrowth>=0?"naik":"turun"} ${pct(Math.abs(salesGrowth))} vs ${weekly.labelA})`];for(const x of blocks){lines.push("",`*${x.label}*`,`Weekly Review: ${x.review}`);if(x.ctx?.lostStock?.length){lines.push("Lost Stock");for(const l of x.ctx.lostStock)lines.push(`- ${l.label} — ${l.status}`)}if(x.reasons.length){lines.push(x.g>=0?"Reason":"Kendala");for(const r of x.reasons)lines.push(`- ${r}`)}lines.push("Action Plan");for(const p of x.plans)lines.push(`- ${p}`)}return lines.join("\n")};
 const pdf=async()=>{if(!reportRef.current||!weekly)return;setBusy("PDF");try{await exportReportPdf(reportRef.current,`M238-Weekly-Reason-${weekly.labelB}`)}finally{setBusy("")}};const share=async()=>{const t=text();if(!t)return;setBusy("TEXT");try{if(navigator.share)await navigator.share({title:`M238 Weekly Reason ${weekly?.labelB||""}`,text:t});else{await navigator.clipboard.writeText(t);alert("Weekly Reason sudah disalin.")}}finally{setBusy("")}};const wa=()=>{const t=text();if(t)window.open(`https://wa.me/?text=${encodeURIComponent(t)}`,"_blank","noopener,noreferrer")};
 return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">M238 Reporting</p><h1 className="mt-1 text-3xl font-black">Weekly Reason</h1><p className="mt-1 text-sm text-slate-500">Weekly sales actual, reason staff, product movement dan kondisi SOH.</p></div>{weekly&&<div className="export-hide flex flex-wrap gap-2"><button onClick={()=>void pdf()} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-black text-white">{busy==="PDF"?"Membuat...":"Unduh PDF"}</button><button onClick={()=>void share()} className="rounded-xl border bg-white px-4 py-2.5 text-sm font-black">Share Text</button><button onClick={wa} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white">Share WhatsApp</button></div>}</div>
 <section className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-slate-950"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1 block text-xs font-black uppercase text-slate-400">Pilih Week</span><select value={selected} onChange={e=>{setSelected(e.target.value);void load(e.target.value,false)}} className="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900">{weeks.map(w=><option key={w}>{w}</option>)}</select></label><div className="rounded-xl border bg-slate-50 px-4 py-2 dark:bg-slate-900"><span className="text-xs font-black uppercase text-slate-400">Compare</span><p className="mt-1 font-black">{selected?previousWeek(weeks,selected):"—"}</p></div><button onClick={()=>void load(selected,true)} disabled={loading} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{loading?"Memuat…":"Update Reason"}</button></div><p className="mt-3 text-xs font-semibold text-slate-500">{source}{selected===latest?" • otomatis refresh 60 detik":""}</p></section>
 {error&&<div className="rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</div>}
 {weekly&&metrics&&<div ref={reportRef} className="space-y-5 bg-slate-50 p-1 dark:bg-slate-900"><section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h2 className="text-xl font-black">M238 DIGIMAP PIM 2</h2><h3 className="mt-1 text-lg font-black">{weekly.labelB}</h3><p className="mt-4 leading-7">Total sales <b>{money.format(metrics.b.sales)}</b>, {salesGrowth>=0?"naik":"turun"} <b>{pct(Math.abs(salesGrowth))}</b> dibanding {weekly.labelA} <b>{money.format(metrics.a.sales)}</b>.</p></section>
 <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Traffic</h3><div className="mt-3 grid grid-cols-2 gap-4"><div><b>{weekly.labelA}</b><p className="text-xl">{num.format(metrics.a.traffic)}</p></div><div><b>{weekly.labelB}</b><p className="text-xl">{num.format(metrics.b.traffic)}</p></div></div><p className={`mt-3 font-black ${trafficGrowth>=0?"text-emerald-600":"text-rose-600"}`}>Growth {trafficGrowth>=0?"+":""}{pct(trafficGrowth)}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Conversion</h3><div className="mt-3 grid grid-cols-2 gap-4"><div><b>{weekly.labelA}</b><p>Transaksi {num.format(metrics.a.transactions)}</p><p>CVR {pct(cvrA)}</p><p>UPT {metrics.a.upt.toFixed(1)}</p></div><div><b>{weekly.labelB}</b><p>Transaksi {num.format(metrics.b.transactions)}</p><p>CVR {pct(cvrB)}</p><p>UPT {metrics.b.upt.toFixed(1)}</p></div></div></div></section>
 <section className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><h3 className="font-black">Compile Reason Staff</h3><p className="mt-3 whitespace-pre-line text-sm leading-7">{weekly.feedbackSummary||"Belum ada feedback team."}</p></section>
 {blocks.map(x=><section key={x.key} className="rounded-2xl border bg-white p-5 shadow-sm dark:bg-slate-950"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-black">{x.label}</h3><span className={`rounded-full px-3 py-1 text-xs font-black ${x.g>=0?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{x.g>=0?"+":""}{pct(x.g)}</span></div><div className="mt-4"><p className="text-sm font-black">Weekly Review</p><p className="mt-1 text-sm leading-7">{x.review}</p></div>{x.ctx?.lostStock?.length?<div className="mt-4"><p className="text-sm font-black">Lost Stock</p><ul className="mt-1 space-y-1 text-sm leading-6">{x.ctx.lostStock.map((l,i)=><li key={`${l.label}-${i}`}>• {l.label} — {l.status}</li>)}</ul></div>:null}{x.reasons.length?<div className="mt-4"><p className="text-sm font-black">{x.g>=0?"Reason":"Kendala"}</p><ul className="mt-1 space-y-1 text-sm leading-6">{x.reasons.map((r,i)=><li key={i}>• {r}</li>)}</ul></div>:null}<div className="mt-4"><p className="text-sm font-black">Action Plan</p><ul className="mt-1 space-y-1 text-sm leading-6">{x.plans.map((p,i)=><li key={i}>• {p}</li>)}</ul></div></section>)}</div>}
 </div>
}
