"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Agg={qty:number;amount:number};
type Weekly={labelA:string;labelB:string;a:{lob:Record<string,Record<string,Agg>>};b:{lob:Record<string,Record<string,Agg>>}};
type Lost={label:string;qty:number;status:string};
type Theme={key:string;count:number};
type LobContext={feedbackCount:number;themes:Theme[];lostStock:Lost[];stockClaimAvailable:number;sohAvailable:boolean};
type Context={byLob:Record<string,LobContext>};
const lobOrder:[string,string][]=[["AIRPODS","AirPods"],["IPHONE","iPhone"],["MAC","MacBook"],["IPAD","iPad"],["APPLE WATCH","Watch"]];
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:1}).format(Number.isFinite(v)?v:0)}%`;
const money=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const growth=(a:number,b:number)=>a?(b-a)/a*100:0;
const total=(r:Record<string,Agg>={})=>Object.values(r).reduce((x,v)=>({qty:x.qty+(v?.qty||0),amount:x.amount+(v?.amount||0)}),{qty:0,amount:0});
function movement(a:Record<string,Agg>={},b:Record<string,Agg>={}){return [...new Set([...Object.keys(a),...Object.keys(b)])].map(name=>({name,diff:(b[name]?.qty||0)-(a[name]?.qty||0)})).filter(x=>x.diff!==0)}
const themeText:Record<string,string>={price:"Beberapa customer masih compare harga atau menyesuaikan budget",survey:"Beberapa customer masih survey dan belum closing",shifting:"Ada customer yang shifting ke product/type lain",waiting:"Ada customer yang masih menunggu product atau periode promo berikutnya",installment:"Ada kendala pada opsi cicilan atau pembayaran",traffic:"Opportunity customer masih terbatas karena traffic",promo:"Promo membantu closing pada beberapa opportunity",tryon:"Try on/demo membantu customer lebih yakin",bundling:"Bundling membantu meningkatkan closing atau attachment",followup:"Masih ada customer yang masuk tahap follow up"};
function build(lob:string,label:string,w:Weekly,c:Context|null){const a=w.a?.lob?.[lob]||{},b=w.b?.lob?.[lob]||{},ta=total(a),tb=total(b),qg=growth(ta.qty,tb.qty),ag=growth(ta.amount,tb.amount),moves=movement(a,b),up=moves.filter(x=>x.diff>0).sort((x,y)=>y.diff-x.diff),down=moves.filter(x=>x.diff<0).sort((x,y)=>x.diff-y.diff),ctx=c?.byLob?.[lob]||{feedbackCount:0,themes:[],lostStock:[],stockClaimAvailable:0,sohAvailable:false},themes=(ctx.themes||[]).filter(t=>t.key!=="stock"),themeKeys=new Set(themes.map(t=>t.key));let review=`Penjualan ${label} week ini ${qg>=0?"mengalami kenaikan":"mengalami penurunan"} ${qg>=0?"+":"-"}${pct(Math.abs(qg))} dibanding ${w.labelA}, dari ${ta.qty} unit menjadi ${tb.qty} unit.`;if(ta.amount||tb.amount)review+=` Secara amount ${ag>=0?"naik":"turun"} ${ag>=0?"+":"-"}${pct(Math.abs(ag))}, dari ${money.format(ta.amount)} menjadi ${money.format(tb.amount)}.`;if(qg<0&&down.length)review+=` Penurunan terbesar terjadi pada ${down.slice(0,2).map(x=>`${x.name} (${Math.abs(x.diff)} unit)`).join(" dan ")}.`;else if(qg>0&&up.length)review+=` Kenaikan terbesar didukung oleh ${up.slice(0,2).map(x=>`${x.name} (+${x.diff} unit)`).join(" dan ")}.`;if(qg>=0&&down.length)review+=` Di sisi lain, ${down[0].name} masih turun ${Math.abs(down[0].diff)} unit.`;
 const issues:string[]=[];for(const t of themes){const txt=themeText[t.key];if(txt&&!issues.includes(txt))issues.push(txt)}if(!ctx.lostStock?.length&&qg<0&&!issues.length)issues.push(ctx.feedbackCount?"Reason staff pada week ini belum menunjukkan satu kendala yang dominan":"Reason staff belum cukup untuk menentukan penyebab utama, sementara pergerakan weekly tetap perlu dimonitor");
 const actions:string[]=[];if(ctx.lostStock?.length)actions.push("Request dan konsolidasi antar store untuk varian yang stoknya habis atau terbatas","Follow up customer yang sebelumnya lost karena stok","Arahkan customer ke alternatif warna atau kapasitas yang masih tersedia");if(themeKeys.has("price")||themeKeys.has("installment"))actions.push("Maksimalkan promo bank/cicilan yang sedang berjalan dan highlight benefit pembelian di Digimap","Follow up customer yang masih compare");if(themeKeys.has("survey"))actions.push("Perkuat probing kebutuhan customer dan maksimalkan demo/try on","Fokus closing customer yang sudah menunjukkan buying signal");if(themeKeys.has("shifting"))actions.push("Identifikasi type yang paling banyak menjadi alternatif dan arahkan upselling/downselling sesuai kebutuhan","Pastikan staff memahami perbedaan benefit antar type");if(themeKeys.has("waiting"))actions.push("Buat list customer yang masih menunggu dan lakukan follow up terjadwal");if(themeKeys.has("traffic"))actions.push("Maksimalkan conversion dari setiap traffic yang masuk");if(qg>0&&themeKeys.has("tryon"))actions.push("Pertahankan try on/demo pada product yang mendorong kenaikan");if(qg>0&&themeKeys.has("promo"))actions.push("Pertahankan komunikasi promo yang terbukti membantu closing");if(qg>0&&themeKeys.has("bundling"))actions.push("Pertahankan bundling pada opportunity yang relevan");if(!actions.length)actions.push(qg<0?"Monitor type yang turun dan perkuat probing untuk menangkap kendala customer yang paling dominan":"Pertahankan momentum pada type yang naik dan monitor availability product utamanya");return{lob,label,review,lost:ctx.lostStock||[],issues,actions:[...new Set(actions)].slice(0,4)}}

export default function WeeklyReportReasonLive(){const[host,setHost]=useState<HTMLElement|null>(null),[weekly,setWeekly]=useState<Weekly|null>(null),[context,setContext]=useState<Context|null>(null),[range,setRange]=useState<{from:string;to:string}|null>(null);
 useEffect(()=>{let raf=0;const sync=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const page=document.querySelector(".weekly-report-page") as HTMLElement|null;if(!page){setHost(null);return}const heading=[...page.querySelectorAll("h3")].find(x=>x.textContent?.trim()==="Reason Weekly per LOB") as HTMLElement|undefined;if(!heading)return;const section=heading.closest("div.mt-6.border-t.pt-5") as HTMLElement|null;if(!section)return;const selects=[...page.querySelectorAll("select")] as HTMLSelectElement[];const from=selects[0]?.value||"",to=selects[1]?.value||"";if(from&&to)setRange(r=>r?.from===from&&r?.to===to?r:{from,to});let h=section.querySelector("[data-weekly-reason-live-host]") as HTMLElement|null;if(!h){h=document.createElement("div");h.dataset.weeklyReasonLiveHost="1";h.className="mt-4";section.appendChild(h)}const oldGrid=[...section.children].find(el=>el!==h&&(el as HTMLElement).classList.contains("grid")) as HTMLElement|undefined;if(oldGrid)oldGrid.style.display="none";setHost(x=>x===h?x:h)})};sync();const obs=new MutationObserver(sync);obs.observe(document.body,{childList:true,subtree:true});document.addEventListener("change",sync,true);return()=>{obs.disconnect();document.removeEventListener("change",sync,true);if(raf)cancelAnimationFrame(raf)}},[]);
 useEffect(()=>{if(!range)return;let alive=true;(async()=>{try{const[w,c]=await Promise.all([fetch(`/api/weekly?from=${encodeURIComponent(range.from)}&to=${encodeURIComponent(range.to)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json()),fetch(`/api/weekly-reason-context?week=${encodeURIComponent(range.to)}&t=${Date.now()}`,{cache:"no-store"}).then(r=>r.json())]);if(!alive)return;setWeekly(w?.error?null:w);setContext(c?.error?null:c)}catch{if(alive){setWeekly(null);setContext(null)}}})();return()=>{alive=false}},[range]);
 const blocks=useMemo(()=>weekly?lobOrder.map(([k,l])=>build(k,l,weekly,context)):[],[weekly,context]);if(!host)return null;return createPortal(<div className="grid gap-4 lg:grid-cols-2">{blocks.map(x=><article key={x.lob} className="rounded-2xl border bg-slate-50 p-4 dark:bg-slate-900"><h4 className="font-black text-blue-600">{x.label}</h4><div className="mt-3 space-y-3 text-sm leading-6"><div><b>Weekly Review</b><p className="mt-1 text-slate-600 dark:text-slate-300">{x.review}</p></div>{x.lost.length>0&&<div><b>Lost Stock</b><ul className="mt-1 space-y-1 text-slate-600 dark:text-slate-300">{x.lost.map((s,i)=><li key={`${s.label}-${i}`}>• {s.label} — {s.status}</li>)}</ul></div>}{x.issues.length>0&&<div><b>Kendala</b><ul className="mt-1 space-y-1 text-slate-600 dark:text-slate-300">{x.issues.map((s,i)=><li key={i}>• {s}</li>)}</ul></div>}<div className="rounded-xl bg-blue-50 p-3 dark:bg-blue-950/30"><b className="text-blue-700 dark:text-blue-300">Action Plan</b><ul className="mt-1 space-y-1 text-slate-700 dark:text-slate-200">{x.actions.map((s,i)=><li key={i}>• {s}</li>)}</ul></div></div></article>)}</div>,host)}
