import {NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const SHEET_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const s=v=>String(v??"").trim(),up=v=>s(v).toUpperCase(),n=v=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
function iso(v){const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""}
function kind(r){const scheme=up(r[12]),text=`${up(r[6])} ${up(r[9])} ${up(r[5])}`;if(scheme==="VAS")return"vas";if(scheme==="ACCESSORIES")return"accessories";if(scheme==="DEVICES")return"device";if(/IPHONE|IPAD|MAC|APPLE WATCH/.test(text))return"device";return"other"}
function lob(r){if(up(r[10])!=="APPLE")return"";const scheme=up(r[12]),text=`${up(r[6])} ${up(r[9])} ${up(r[5])}`;if(scheme==="ACCESSORIES"&&/AIRPODS/.test(text))return"airpods";if(scheme!=="DEVICES")return"";if(/IPHONE/.test(text))return"iphone";if(/MAC/.test(text))return"mac";if(/IPAD/.test(text))return"ipad";if(/APPLE WATCH|\bWATCH\b/.test(text))return"watch";return""}
function vasType(r){const t=`${up(r[4])} ${up(r[10])} ${up(r[13])} ${up(r[5])}`;if(t.includes("QOALA")||t.includes("KLA"))return"qoala";if(t.includes("TELKOMSEL")||t.includes("TSL"))return"telkomsel";if(t.includes("INDOSAT")||t.includes("IDT"))return"indosat";if(/(^|\s)XL(\s|$)|XXL/.test(t))return"xl";return""}
export async function GET(req){const period=req.nextUrl.searchParams.get("period")||"",staffId=req.nextUrl.searchParams.get("staffId")||"";if(!/^2026-\d{2}$/.test(period)||!staffId)return NextResponse.json({error:"period dan staffId wajib"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const[rows]=await getSheetRanges(SHEET_ID,["'Data Copas'!A2:S50000"],email,key);const selected=rows.filter(r=>iso(r[0]).startsWith(period)&&s(r[1])===staffId&&up(r[15])==="M238"&&up(r[12])!=="VOUCHER"&&!up(r[5]).includes("VOUCHER"));const byDate=new Map();for(const r of selected){const d=iso(r[0]);if(!d)continue;const arr=byDate.get(d)||[];arr.push(r);byDate.set(d,arr)}const dim=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate(),today=new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date()),limit=period===today.slice(0,7)?Number(today.slice(8,10)):dim,daily=[];let accessoriesQty=0;for(let day=1;day<=limit;day++){const date=`${period}-${String(day).padStart(2,"0")}`,mine=byDate.get(date)||[],invoices=new Set(mine.map(r=>s(r[3])).filter(Boolean)),sales=mine.reduce((a,r)=>a+n(r[8]),0),qty=mine.reduce((a,r)=>a+n(r[7]),0),device=mine.filter(r=>kind(r)==="device").reduce((a,r)=>a+n(r[7]),0),accRows=mine.filter(r=>kind(r)==="accessories"),accessories=accRows.reduce((a,r)=>a+n(r[8]),0),accQty=accRows.reduce((a,r)=>a+n(r[7]),0),vas=mine.filter(r=>kind(r)==="vas").reduce((a,r)=>a+n(r[8]),0);accessoriesQty+=accQty;daily.push({date,sales,trx:invoices.size,device,accessories,accessoriesQty:accQty,vas,qty,upt:invoices.size?qty/invoices.size:0,atv:invoices.size?sales/invoices.size:0})}const lobTotal={iphone:0,mac:0,ipad:0,watch:0,airpods:0},vasTotal={qoala:{qty:0,value:0},telkomsel:{qty:0,value:0},xl:{qty:0,value:0},indosat:{qty:0,value:0}};for(const r of selected){const l=lob(r);if(l)lobTotal[l]+=n(r[7]);if(kind(r)==="vas"){const v=vasType(r);if(v){vasTotal[v].qty+=n(r[7]);vasTotal[v].value+=n(r[8])}}}return NextResponse.json({period,staffId,daily,accessoriesQty,lob:lobTotal,vas:vasTotal},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca staff detail"},{status:500})}}
