const TOKEN_URL="https://oauth2.googleapis.com/token"
const SCOPE="https://www.googleapis.com/auth/spreadsheets"
const TOKEN_TTL=50*60*1000
const READ_CACHE_TTL=20*1000
const STALE_CACHE_TTL=2*60*1000
const META_CACHE_TTL=10*60*1000

type TokenCache={email:string;accessToken:string;expiresAt:number}
type ReadCache={at:number;values:unknown[][][]}
type MetaCache={at:number;titles:Set<string>}
let tokenCache:TokenCache|undefined
let tokenRequest:Promise<string>|undefined
let sheetApiRequestCount=0
const readCache=new Map<string,ReadCache>()
const readInflight=new Map<string,Promise<unknown[][][]>>()
const metaCache=new Map<string,MetaCache>()

export function getGoogleSheetRequestCount(){return sheetApiRequestCount}

function base64Url(input:string|Uint8Array){const raw=typeof input==="string"?new TextEncoder().encode(input):input;let binary="";raw.forEach(byte=>{binary+=String.fromCharCode(byte)});return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function pemBuffer(pem:string){const clean=pem.replace(/\\n/g,"\n").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");const binary=atob(clean);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function readKey(id:string,ranges:string[]){return `${id}::${ranges.join("||")}`}
function clearReadCacheForSheet(id:string){for(const key of readCache.keys())if(key.startsWith(`${id}::`))readCache.delete(key)}
async function requestWithRetry(input:RequestInfo|URL,init?:RequestInit){let response:Response|undefined;const waits=[1000,2000,4000,8000],url=String(input);for(let attempt=0;attempt<=waits.length;attempt++){if(url.includes("sheets.googleapis.com"))sheetApiRequestCount++;response=await fetch(input,init);if(response.ok)return response;const retryable=response.status===429||response.status>=500;if(!retryable||attempt===waits.length)return response;await sleep(waits[attempt]+Math.floor(Math.random()*250))}return response!}

async function requestToken(email:string,privateKey:string){const now=Math.floor(Date.now()/1000);const header=base64Url(JSON.stringify({alg:"RS256",typ:"JWT"}));const claims=base64Url(JSON.stringify({iss:email,scope:SCOPE,aud:TOKEN_URL,exp:now+3600,iat:now}));const unsigned=`${header}.${claims}`;const key=await crypto.subtle.importKey("pkcs8",pemBuffer(privateKey),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned));const assertion=`${unsigned}.${base64Url(new Uint8Array(signature))}`;const common={method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"}} as RequestInit;let response=await requestWithRetry(TOKEN_URL,{...common,body:new URLSearchParams({grant_type:"urn:ietf:params:oauth2:token-exchange",assertion})});if(!response.ok)response=await requestWithRetry(TOKEN_URL,{...common,body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});if(!response.ok)throw new Error(`Google OAuth gagal (${response.status})`);return((await response.json())as{access_token:string}).access_token}

async function token(email:string,privateKey:string){const now=Date.now();if(tokenCache?.email===email&&tokenCache.expiresAt>now)return tokenCache.accessToken;if(tokenRequest)return tokenRequest;tokenRequest=requestToken(email,privateKey).then(accessToken=>{tokenCache={email,accessToken,expiresAt:Date.now()+TOKEN_TTL};return accessToken}).finally(()=>{tokenRequest=undefined});return tokenRequest}

async function fetchSheetRanges(id:string,ranges:string[],email:string,privateKey:string){const access=await token(email,privateKey),url=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values:batchGet`);ranges.forEach(range=>url.searchParams.append("ranges",range));url.searchParams.set("valueRenderOption","UNFORMATTED_VALUE");const response=await requestWithRetry(url,{headers:{authorization:`Bearer ${access}`},cache:"no-store"});if(!response.ok)throw new Error(`Google Sheets gagal (${response.status})`);const json=await response.json()as{valueRanges?:Array<{values?:unknown[][]}>};return(json.valueRanges??[]).map(x=>x.values??[])}

export async function getSheetRanges(id:string,ranges:string[],email:string,privateKey:string){const key=readKey(id,ranges),now=Date.now(),cached=readCache.get(key);if(cached&&now-cached.at<READ_CACHE_TTL)return cached.values;const active=readInflight.get(key);if(active)return active;const request=fetchSheetRanges(id,ranges,email,privateKey).then(values=>{readCache.set(key,{at:Date.now(),values});return values}).catch(error=>{const stale=readCache.get(key);if(stale&&Date.now()-stale.at<STALE_CACHE_TTL)return stale.values;throw error}).finally(()=>{readInflight.delete(key)});readInflight.set(key,request);return request}

export async function clearAndWrite(id:string,clearRange:string|null,writeRange:string,values:unknown[][],email:string,privateKey:string,valueInputOption:"RAW"|"USER_ENTERED"="USER_ENTERED"){const access=await token(email,privateKey),headers={authorization:`Bearer ${access}`,"content-type":"application/json"};if(clearRange){const cleared=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(clearRange)}:clear`,{method:"POST",headers,body:"{}"});if(!cleared.ok)throw new Error(`Gagal membersihkan data lama (${cleared.status})`)}const written=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(writeRange)}?valueInputOption=${valueInputOption}`,{method:"PUT",headers,body:JSON.stringify({range:writeRange,majorDimension:"ROWS",values})});if(!written.ok)throw new Error(`Gagal menulis Google Sheet (${written.status})`);clearReadCacheForSheet(id);return written.json()}

export async function batchClearRanges(id:string,ranges:string[],email:string,privateKey:string){if(!ranges.length)return;const access=await token(email,privateKey);const response=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values:batchClear`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({ranges})});if(!response.ok)throw new Error(`Gagal membersihkan data (${response.status})`);clearReadCacheForSheet(id)}

export async function batchWriteRanges(id:string,data:Array<{range:string;values:unknown[][]}>,email:string,privateKey:string,valueInputOption:"RAW"|"USER_ENTERED"="RAW"){if(!data.length)return;const access=await token(email,privateKey);const response=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values:batchUpdate`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({valueInputOption,data:data.map(x=>({range:x.range,majorDimension:"ROWS",values:x.values}))})});if(!response.ok)throw new Error(`Gagal menulis batch data (${response.status})`);clearReadCacheForSheet(id);return response.json()}

export async function appendSheetValues(id:string,range:string,values:unknown[][],email:string,privateKey:string){const access=await token(email,privateKey);const response=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({range,majorDimension:"ROWS",values})});if(!response.ok)throw new Error(`Gagal menyimpan data (${response.status})`);clearReadCacheForSheet(id);return response.json()}

async function readTitles(id:string,access:string){const now=Date.now(),cached=metaCache.get(id);if(cached&&now-cached.at<META_CACHE_TTL)return cached.titles;const response=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=sheets.properties.title`,{headers:{authorization:`Bearer ${access}`},cache:"no-store"});if(!response.ok)throw new Error(`Gagal membaca struktur Google Sheet (${response.status})`);const json=await response.json()as{sheets?:Array<{properties?:{title?:string}}>} ;const titles=new Set((json.sheets??[]).map(x=>x.properties?.title||"").filter(Boolean));metaCache.set(id,{at:Date.now(),titles});return titles}

export async function ensureSheets(id:string,sheets:Array<{title:string;headers:string[]}>,email:string,privateKey:string){const access=await token(email,privateKey);let titles=await readTitles(id,access);const missing=sheets.filter(x=>![...titles].some(t=>t.trim().toLowerCase()===x.title.trim().toLowerCase()));if(missing.length){const add=await requestWithRetry(`https://sheets.googleapis.com/v4/spreadsheets/${id}:batchUpdate`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({requests:missing.map(x=>({addSheet:{properties:{title:x.title}}}))})});if(!add.ok&&add.status!==400)throw new Error(`Gagal membuat tab fast sales (${add.status})`);metaCache.delete(id);titles=await readTitles(id,access)}const headerWrites:Array<{range:string;values:unknown[][]}>=[];for(const sheet of sheets){const actual=[...titles].find(t=>t.trim().toLowerCase()===sheet.title.trim().toLowerCase())||sheet.title;const [row]=await getSheetRanges(id,[`'${actual}'!A1:${columnLetter(sheet.headers.length)}1`],email,privateKey);if(!(row?.[0]?.length))headerWrites.push({range:`'${actual}'!A1`,values:[sheet.headers]})}if(headerWrites.length)await batchWriteRanges(id,headerWrites,email,privateKey,"RAW")}

function columnLetter(n:number){let s="";for(let x=n;x>0;x=Math.floor((x-1)/26))s=String.fromCharCode(65+((x-1)%26))+s;return s}

export async function ensureSheet(id:string,title:string,headers:string[],email:string,privateKey:string){await ensureSheets(id,[{title,headers}],email,privateKey)}
