const TOKEN_URL="https://oauth2.googleapis.com/token"
const SCOPE="https://www.googleapis.com/auth/spreadsheets"
const TOKEN_TTL=50*60*1000
const READ_CACHE_TTL=20*1000
const STALE_CACHE_TTL=2*60*1000

type TokenCache={email:string;accessToken:string;expiresAt:number}
type ReadCache={at:number;values:unknown[][][]}
let tokenCache:TokenCache|undefined
let tokenRequest:Promise<string>|undefined
const readCache=new Map<string,ReadCache>()
const readInflight=new Map<string,Promise<unknown[][][]>>()

function base64Url(input:string|Uint8Array){const raw=typeof input==="string"?new TextEncoder().encode(input):input;let binary="";raw.forEach(byte=>{binary+=String.fromCharCode(byte)});return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function pemBuffer(pem:string){const clean=pem.replace(/\\n/g,"\n").replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");const binary=atob(clean);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer}
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function readKey(id:string,ranges:string[]){return `${id}::${ranges.join("||")}`}
function clearReadCacheForSheet(id:string){for(const key of readCache.keys())if(key.startsWith(`${id}::`))readCache.delete(key)}

async function requestToken(email:string,privateKey:string){const now=Math.floor(Date.now()/1000);const header=base64Url(JSON.stringify({alg:"RS256",typ:"JWT"}));const claims=base64Url(JSON.stringify({iss:email,scope:SCOPE,aud:TOKEN_URL,exp:now+3600,iat:now}));const unsigned=`${header}.${claims}`;const key=await crypto.subtle.importKey("pkcs8",pemBuffer(privateKey),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned));const assertion=`${unsigned}.${base64Url(new Uint8Array(signature))}`;const response=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth2:token-exchange",assertion})});if(!response.ok){const fallback=await fetch(TOKEN_URL,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});if(!fallback.ok)throw new Error(`Google OAuth gagal (${fallback.status})`);return((await fallback.json())as{access_token:string}).access_token}return((await response.json())as{access_token:string}).access_token}

async function token(email:string,privateKey:string){const now=Date.now();if(tokenCache?.email===email&&tokenCache.expiresAt>now)return tokenCache.accessToken;if(tokenRequest)return tokenRequest;tokenRequest=requestToken(email,privateKey).then(accessToken=>{tokenCache={email,accessToken,expiresAt:Date.now()+TOKEN_TTL};return accessToken}).finally(()=>{tokenRequest=undefined});return tokenRequest}

async function fetchSheetRanges(id:string,ranges:string[],email:string,privateKey:string){const access=await token(email,privateKey),url=new URL(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values:batchGet`);ranges.forEach(range=>url.searchParams.append("ranges",range));url.searchParams.set("valueRenderOption","UNFORMATTED_VALUE");let response:Response|undefined;for(let attempt=0;attempt<3;attempt++){response=await fetch(url,{headers:{authorization:`Bearer ${access}`},cache:"no-store"});if(response.ok)break;if(response.status!==429&&response.status<500)break;if(attempt<2)await sleep((attempt+1)*400+Math.floor(Math.random()*150))}if(!response?.ok)throw new Error(`Google Sheets gagal (${response?.status??"unknown"})`);const json=await response.json()as{valueRanges?:Array<{values?:unknown[][]}>};return(json.valueRanges??[]).map(x=>x.values??[])}

export async function getSheetRanges(id:string,ranges:string[],email:string,privateKey:string){const key=readKey(id,ranges),now=Date.now(),cached=readCache.get(key);if(cached&&now-cached.at<READ_CACHE_TTL)return cached.values;const active=readInflight.get(key);if(active)return active;const request=fetchSheetRanges(id,ranges,email,privateKey).then(values=>{readCache.set(key,{at:Date.now(),values});return values}).catch(error=>{const stale=readCache.get(key);if(stale&&Date.now()-stale.at<STALE_CACHE_TTL)return stale.values;throw error}).finally(()=>{readInflight.delete(key)});readInflight.set(key,request);return request}

export async function clearAndWrite(id:string,clearRange:string|null,writeRange:string,values:unknown[][],email:string,privateKey:string,valueInputOption:"RAW"|"USER_ENTERED"="USER_ENTERED"){const access=await token(email,privateKey),headers={authorization:`Bearer ${access}`,"content-type":"application/json"};const clearRequest=clearRange?fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(clearRange)}:clear`,{method:"POST",headers,body:"{}"}):Promise.resolve(null);const writeRequest=fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(writeRange)}?valueInputOption=${valueInputOption}`,{method:"PUT",headers,body:JSON.stringify({range:writeRange,majorDimension:"ROWS",values})});const[cleared,written]=await Promise.all([clearRequest,writeRequest]);if(cleared&&!cleared.ok)throw new Error(`Gagal membersihkan data lama (${cleared.status})`);if(!written.ok)throw new Error(`Gagal menulis Google Sheet (${written.status})`);clearReadCacheForSheet(id);return written.json()}

export async function appendSheetValues(id:string,range:string,values:unknown[][],email:string,privateKey:string){const access=await token(email,privateKey);const response=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({range,majorDimension:"ROWS",values})});if(!response.ok)throw new Error(`Gagal menyimpan data (${response.status})`);clearReadCacheForSheet(id);return response.json()}

export async function ensureSheet(id:string,title:string,headers:string[],email:string,privateKey:string){const access=await token(email,privateKey);const metaUrl=`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=sheets.properties.title`;const readMeta=async()=>{const response=await fetch(metaUrl,{headers:{authorization:`Bearer ${access}`},cache:"no-store"});if(!response.ok)throw new Error(`Gagal membaca struktur Google Sheet (${response.status})`);return response.json()as Promise<{sheets?:Array<{properties?:{title?:string}}>} >};let json=await readMeta();const wanted=title.trim().toLocaleLowerCase();let actualTitle=json.sheets?.map(x=>x.properties?.title||"").find(x=>x.trim().toLocaleLowerCase()===wanted)||"";if(!actualTitle){const add=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}:batchUpdate`,{method:"POST",headers:{authorization:`Bearer ${access}`,"content-type":"application/json"},body:JSON.stringify({requests:[{addSheet:{properties:{title}}}]})});if(!add.ok){if(add.status!==400)throw new Error(`Gagal membuat tab ${title} (${add.status})`);json=await readMeta();actualTitle=json.sheets?.map(x=>x.properties?.title||"").find(x=>x.trim().toLocaleLowerCase()===wanted)||"";if(!actualTitle)throw new Error(`Gagal membuat tab ${title} (${add.status})`)}else{actualTitle=title;clearReadCacheForSheet(id)}}const rangeTitle=actualTitle||title;const existing=await getSheetRanges(id,[`'${rangeTitle}'!A1:${String.fromCharCode(64+Math.min(headers.length,26))}1`],email,privateKey);if(!(existing[0]?.[0]?.length)){await clearAndWrite(id,null,`'${rangeTitle}'!A1`,[headers],email,privateKey,"RAW")}}
