export type SalesRow={date:string;id:string;name:string;invoice:string;article:string;description:string;type:string;qty:number;amount:number;category:string;brand:string;core:string;scheme:string;vendor:string;store:string};

const s=(v:unknown)=>String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim();
const up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
export function isoDate(v:unknown){const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""}
export function parseSalesRow(r:unknown[]):SalesRow{return{date:isoDate(r[0]),id:s(r[1]),name:s(r[2]),invoice:s(r[3]),article:s(r[4]),description:s(r[5]),type:s(r[6]),qty:n(r[7]),amount:n(r[8]),category:up(r[9]),brand:up(r[10]),core:up(r[11]),scheme:up(r[12]),vendor:up(r[13]),store:up(r[15])}}
export function isVoucher(r:SalesRow){const text=up(`${r.scheme} ${r.article} ${r.description} ${r.type} ${r.category} ${r.brand} ${r.core} ${r.vendor}`);return /\bVOUCHER\b|E-?VOUCHER|GIFT\s*CARD/.test(text)}
export function isValidSale(r:SalesRow,requireStore=true){return!!(r.date&&r.id)&&(!requireStore||!r.store||r.store==="M238")&&!isVoucher(r)}
export function saleKind(r:SalesRow){const text=up(`${r.category} ${r.type} ${r.description}`);if(/HALO\s*IPHONE|HALOIPHONE|\bHALO\b/.test(text))return"vas";if(r.scheme==="VAS")return"vas";if(r.scheme==="ACCESSORIES")return"accessories";if(r.scheme==="DEVICES")return"device";if(/IPHONE|IPAD|MAC|APPLE WATCH|AIRPODS/.test(text))return"device";return"other"}
export function productKey(r:SalesRow){const text=up(`${r.category} ${r.type} ${r.description}`);if(r.brand==="APPLE"&&text.includes("AIRPODS"))return"airpods";if(saleKind(r)!=="device"||r.brand!=="APPLE")return"other";if(r.category==="IPHONE"||text.includes("IPHONE"))return"iphone";if(r.category==="MAC"||r.category==="MACBOOK"||text.includes("MACBOOK"))return"mac";if(r.category==="IPAD"||text.includes("IPAD"))return"ipad";if(r.category==="APPLE WATCH"||r.category==="WATCH"||text.includes("APPLE WATCH"))return"watch";return"other"}
export function vasKey(r:SalesRow){const text=up(`${r.article} ${r.brand} ${r.vendor} ${r.type} ${r.category} ${r.description}`);if(text.includes("QOALA")||text.includes("KLA"))return"qoala";if(text.includes("TELKOMSEL")||text.includes("TSL")||text.includes("HALO IPHONE")||text.includes("HALOIPHONE")||/\bHALO\b/.test(text))return"telkomsel";if(text.includes("INDOSAT")||text.includes("IDT"))return"indosat";if(/(^|\s)XL(\s|$)|XXL/.test(text))return"xl";return""}
export function aggregateSales(rows:SalesRow[]){const clean=rows.filter(r=>isValidSale(r,false));const invoices=new Set(clean.map(r=>r.invoice).filter(Boolean));const lob={iphone:0,mac:0,ipad:0,watch:0,airpods:0};const vasDetail={qoala:{qty:0,value:0},telkomsel:{qty:0,value:0},xl:{qty:0,value:0},indosat:{qty:0,value:0}};let amount=0,device=0,accessories=0,vas=0,qty=0;for(const r of clean){amount+=r.amount;qty+=r.qty;const kind=saleKind(r);if(kind==="device")device+=r.amount;else if(kind==="accessories")accessories+=r.amount;else if(kind==="vas")vas+=r.amount;const p=productKey(r);if(p in lob)lob[p as keyof typeof lob]+=r.qty;if(kind==="vas"){const v=vasKey(r);if(v){vasDetail[v as keyof typeof vasDetail].qty+=r.qty;vasDetail[v as keyof typeof vasDetail].value+=r.amount}}}return{amount,device,accessories,vas,qty,invoices:invoices.size,upt:invoices.size?qty/invoices.size:0,atv:invoices.size?amount/invoices.size:0,lob,vasDetail}}
