import {batchClearRanges,batchWriteRanges,ensureSheets,getSheetRanges} from "@/lib/google-sheets";
import type {FastSalesRow} from "@/lib/m238-fast-sales";

const MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk",SOURCE_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0",STORE="M238";
const CACHE="DAILY SUMMARY FOCUS CACHE",SOURCE_INDEX="DAILY SUMMARY SOURCE INDEX",ACTIVE="SALES DASHBOARD DATA",CLASS="FAST SALES CLASSIFICATION",LIMIT=900;
export const focusCacheHeaders=["Store","Date","Types JSON","VAS JSON","Updated At","Source"];
type Credentials={email:string;key:string};
type Vas={qoalaQty:number;qoalaValue:number;telkomselQty:number;telkomselValue:number;xlQty:number;xlValue:number;indosatQty:number;indosatValue:number};
type TypeDaily={productKey:string;productName:string;lob:string;qty:number};
type FocusDaily={store:string;date:string;types:TypeDaily[];vas:Vas;updatedAt:string;source:"SPW"|"CACHE_REFRESH"};
export type FocusType={productKey:string;productName:string;lob:string;target:number|null;achievement:number;order:number;configured:boolean};
export type FocusResponse={lob:{iphone:{target:number|null;achievement:number};macbook:{target:number|null;achievement:number};ipad:{target:number|null;achievement:number};appleWatch:{target:number|null;achievement:number};allDevice:{target:number|null;achievement:number}};types:FocusType[];configuredFocusKeys:string[];vasByDate:Record<string,Vas>;cache:string;sourceRows:number};
const s=(v:unknown)=>String(v??"").replace(/\u00a0/g," ").replace(/\s+/g," ").trim(),up=(v:unknown)=>s(v).toUpperCase(),n=(v:unknown)=>typeof v==="number"?v:Number(s(v).replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
const iso=(v:unknown)=>{if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);const m=x.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""};
const keyPart=(v:string)=>up(v).replace(/[^A-Z0-9]+/g,"-").replace(/^-|-$/g,""),productKey=(name:string,lob:string)=>`${keyPart(lob)}:${keyPart(name)}`;
const emptyVas=():Vas=>({qoalaQty:0,qoalaValue:0,telkomselQty:0,telkomselValue:0,xlQty:0,xlValue:0,indosatQty:0,indosatValue:0});
function lobOf(category:string,type:string,scheme:string){const c=up(category),t=up(type),sc=up(scheme);if(sc==="ACCESSORIES"&&/AIRPODS/.test(`${c} ${t}`))return"AirPods";if(sc!=="DEVICES")return"";if(/IPHONE/.test(c)||/^IPHONE\b/.test(t))return"iPhone";if(/^(MAC|MACBOOK|MAC BOOK)$/.test(c)||/MACBOOK|MAC MINI|IMAC/.test(t))return"MacBook";if(/IPAD/.test(c)||/^IPAD\b/.test(t))return"iPad";if(/APPLE WATCH|SMARTWATCH|WATCH/.test(c)||/APPLE WATCH|WATCH SERIES|WATCH SE|WATCH ULTRA/.test(t))return"Apple Watch";return""}
function providerOf(r:FastSalesRow){if(up(r.scheme)!=="VAS")return"";const t=up(`${r.article} ${r.category} ${r.brand} ${r.vendor} ${r.description}`);if(t.includes("QOALA")||/(^|\s)KLA/.test(t)||t.includes("PROTEKSI"))return"qoala";if(t.includes("TELKOMSEL")||/(^|\s)TSL(\s|$)/.test(t))return"telkomsel";if(t.includes("INDOSAT")||/(^|\s)IDT(\s|$)/.test(t))return"indosat";if(/(^|\s)XL(\s|$)|XXL/.test(t))return"xl";return""}
function displayType(type:string,category:string,description:string,lob:string){if(s(type))return s(type);return s(description).replace(/\b\d{2,4}GB\b/ig,"").replace(/\b(BLACK|WHITE|BLUE|PINK|GREEN|YELLOW|SILVER|GOLD|PURPLE|ORANGE|STARLIGHT|MIDNIGHT)\b/ig,"").replace(/\s+/g," ").trim()||s(category)||lob}
export function buildDailyFocusRows(rows:FastSalesRow[],source:"SPW"|"CACHE_REFRESH"="SPW"){
 const grouped=new Map<string,{types:Map<string,TypeDaily>;vas:Vas}>();for(const r of rows){if(r.store!==STORE||!r.date||r.qty<=0||/VOUCHER|DEMO/i.test(`${r.scheme} ${r.description} ${r.type}`))continue;let g=grouped.get(r.date);if(!g){g={types:new Map(),vas:emptyVas()};grouped.set(r.date,g)}const lob=lobOf(r.category,r.type,r.scheme);if(lob){const name=displayType(r.type,r.category,r.description,lob),key=productKey(name,lob),old=g.types.get(key)||{productKey:key,productName:name,lob,qty:0};old.qty+=r.qty;g.types.set(key,old)}const p=providerOf(r),q=r.qty,v=r.amount;if(p==="qoala"){g.vas.qoalaQty+=q;g.vas.qoalaValue+=v}else if(p==="telkomsel"){g.vas.telkomselQty+=q;g.vas.telkomselValue+=v}else if(p==="xl"){g.vas.xlQty+=q;g.vas.xlValue+=v}else if(p==="indosat"){g.vas.indosatQty+=q;g.vas.indosatValue+=v}}
 const now=new Date().toISOString();return[...grouped].map(([date,g]):FocusDaily=>({store:STORE,date,types:[...g.types.values()],vas:g.vas,updatedAt:now,source}))}
function toValues(r:FocusDaily){return[r.store,r.date,JSON.stringify(r.types),JSON.stringify(r.vas),r.updatedAt,r.source]}
function fromValues(r:unknown[]):FocusDaily|null{const date=iso(r[1]);if(up(r[0])!==STORE||!date)return null;try{return{store:STORE,date,types:JSON.parse(s(r[2])||"[]"),vas:{...emptyVas(),...JSON.parse(s(r[3])||"{}")},updatedAt:s(r[4]),source:(s(r[5])||"CACHE_REFRESH") as FocusDaily["source"]}}catch{return null}}
async function ensure(credentials:Credentials){await ensureSheets(MASTER_ID,[{title:CACHE,headers:focusCacheHeaders}],credentials.email,credentials.key)}
async function persist(rows:FocusDaily[],credentials:Credentials){const sorted=[...rows].sort((a,b)=>a.date.localeCompare(b.date));await batchClearRanges(MASTER_ID,[`'${CACHE}'!A2:F${LIMIT}`],credentials.email,credentials.key);if(sorted.length)await batchWriteRanges(MASTER_ID,[{range:`'${CACHE}'!A2`,values:sorted.map(toValues)}],credentials.email,credentials.key,"RAW")}
export async function upsertDailyFocusRows(incoming:FocusDaily[],credentials:Credentials){if(!incoming.length)return;await ensure(credentials);const[v]=await getSheetRanges(MASTER_ID,[`'${CACHE}'!A2:F${LIMIT}`],credentials.email,credentials.key),map=new Map((v||[]).map(fromValues).filter((x):x is FocusDaily=>Boolean(x)).map(r=>[r.date,r]));for(const r of incoming)map.set(r.date,r);await persist([...map.values()],credentials)}
export async function clearActiveSpwFocusRows(credentials:Credentials){await ensure(credentials);const[v]=await getSheetRanges(MASTER_ID,[`'${CACHE}'!A2:F${LIMIT}`],credentials.email,credentials.key),rows=(v||[]).map(fromValues).filter((x):x is FocusDaily=>Boolean(x)).filter(r=>r.source!=="SPW");await persist(rows,credentials)}
function rawRow(r:unknown[]):FastSalesRow|null{const date=iso(r[0]),id=s(r[1]),article=up(r[4]),store=up(r[15]);if(!date||!id||!article||store!==STORE)return null;return{date,id,name:s(r[2]),invoice:s(r[3]),article,description:s(r[5]),type:s(r[6]),qty:n(r[7]),amount:n(r[8]),category:up(r[9]),brand:up(r[10]),core:up(r[11]),scheme:up(r[12]),vendor:up(r[13]),week:s(r[14]),store,key:`${store}|${date}|${s(r[3])}|${article}|${id}`}}
function activeRow(r:unknown[]):FastSalesRow|null{const date=iso(r[0]),id=s(r[1]),article=up(r[4]),store=up(r[15])||STORE;if(!date||!id||!article)return null;return{date,id,name:s(r[2]),invoice:s(r[3]),article,description:s(r[5]),type:s(r[6]),qty:n(r[7]),amount:n(r[8]),category:up(r[9]),brand:up(r[10]),core:up(r[11]),scheme:up(r[12]),vendor:up(r[13]),week:s(r[14]),store,key:s(r[16])||`${store}|${date}|${s(r[3])}|${article}|${id}`}}
function periods(from:string,to:string){const out:string[]=[];let[y,m]=from.slice(0,7).split("-").map(Number);const end=to.slice(0,7);while(out.length<36){const p=`${y}-${String(m).padStart(2,"0")}`;out.push(p);if(p===end)break;if(++m>12){m=1;y++}}return out}
function monthLabel(period:string){const[y,m]=period.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(Date.UTC(y,m-1,1)))}
function currentDate(){return new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date())}
function parseTargets(config:unknown[][],from:string,to:string){const period=from.slice(0,7),fullMonth=from===`${period}-01`&&(to===`${period}-${String(new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate()).padStart(2,"0")}`||(period===currentDate().slice(0,7)&&to===currentDate())),label=up(monthLabel(period)),lobTargets=new Map<string,number>(),focusTargets=new Map<string,{name:string;target:number;order:number}>(),configured:string[]=[],periodWeeks=new Set<string>();
 if(fullMonth)for(let r=0;r<config.length-1;r++)for(let c=0;c<(config[r]?.length||0);c++){if(up(config[r][c])!=="LOB TARGET")continue;const h=config[r+1]||[],mi=h.findIndex(v=>up(v)==="MONTHLY"),wi=h.findIndex(v=>up(v)==="WEEKLY");if(mi<0)continue;for(let rr=r+2;rr<Math.min(config.length,r+24);rr++){if(up(config[rr]?.[mi])!==label)continue;if(wi>=0&&/^W\d+$/.test(up(config[rr]?.[wi])))periodWeeks.add(up(config[rr][wi]));if(wi<0)for(let cc=mi+1;cc<h.length;cc++){const k=up(h[cc]);if(["MACBOOK","IPHONE","IPAD","APPLE WATCH","AIRPODS"].includes(k)&&s(config[rr]?.[cc])!=="")lobTargets.set(k,n(config[rr][cc]))}}}
 for(let r=0;r<config.length-1;r++)for(let c=0;c<(config[r]?.length||0);c++){if(up(config[r][c])!=="LOB FOKUS WEEKLY")continue;const h=config[r+1]||[],wi=h.findIndex(v=>up(v)==="WEEKLY");if(wi<0)continue;for(let cc=wi+1;cc<h.length;cc++){const name=s(h[cc]);if(!name)continue;const lob=lobOf(name,name,"DEVICES");if(!lob)continue;const key=productKey(name,lob);configured.push(key);let total=0,has=false;if(fullMonth)for(let rr=r+2;rr<Math.min(config.length,r+30);rr++){const wk=up(config[rr]?.[wi]);if(!periodWeeks.has(wk))continue;if(s(config[rr]?.[cc])!==""){total+=n(config[rr][cc]);has=true}}if(has)focusTargets.set(key,{name,target:total,order:cc-wi-1})}}
 return{lobTargets,focusTargets,configured:[...new Set(configured)]}}
export async function getDailySummaryFocus(from:string,to:string,credentials:Credentials){const started=Date.now();await ensure(credentials);const[focusRaw,activeRaw,classRows,indexRaw]=await getSheetRanges(MASTER_ID,[`'${CACHE}'!A2:F${LIMIT}`,`'${ACTIVE}'!A2:Q50000`,`'${CLASS}'!A2:I20000`,`'${SOURCE_INDEX}'!A2:F300`],credentials.email,credentials.key),stored=(focusRaw||[]).map(fromValues).filter((x):x is FocusDaily=>Boolean(x)),map=new Map(stored.map(r=>[r.date,r])),wanted=periods(from,to),hasHistorical=wanted.every(p=>stored.some(r=>r.source==="CACHE_REFRESH"&&r.date.startsWith(p)));let sourceRows=0,cache="HIT";
 if(!hasHistorical){const entries=(indexRaw||[]).map(r=>({store:up(r[0]),period:s(r[1]),sheet:s(r[2]),start:n(r[3]),end:n(r[4])})).filter(e=>e.store===STORE&&wanted.includes(e.period)&&e.start>=2&&e.end>=e.start),bySheet=new Map<string,typeof entries>();for(const e of entries){const list=bySheet.get(e.sheet)||[];list.push(e);bySheet.set(e.sheet,list)}const sales:FastSalesRow[]=[];for(const[sheet,list]of bySheet){const blocks=await getSheetRanges(SOURCE_ID,list.map(e=>`'${sheet}'!A${e.start}:S${e.end}`),credentials.email,credentials.key);for(const block of blocks)for(const r of block){const x=rawRow(r);if(x&&x.date>=from&&x.date<=to)sales.push(x)}}sourceRows+=sales.length;for(const r of buildDailyFocusRows(sales,"CACHE_REFRESH"))map.set(r.date,r);cache="MISS_BUILT"}
 const active=(activeRaw||[]).map(activeRow).filter((x):x is FastSalesRow=>Boolean(x)).filter(r=>r.date>=from&&r.date<=to);sourceRows+=active.length;for(const r of buildDailyFocusRows(active,"SPW"))map.set(r.date,r);if(cache==="MISS_BUILT"||active.length)await persist([...map.values()],credentials);
 const range=[...map.values()].filter(r=>r.date>=from&&r.date<=to),[config]=await getSheetRanges(SOURCE_ID,["Config!A1:AZ120"],credentials.email,credentials.key),targets=parseTargets(config||[],from,to),typeMap=new Map<string,FocusType>(),vasByDate:Record<string,Vas>={};for(const r of range){vasByDate[r.date]=r.vas;for(const t of r.types){const old=typeMap.get(t.productKey)||{...t,target:null,achievement:0,order:999,configured:false};old.achievement+=t.qty;typeMap.set(t.productKey,old)}}
 for(const r of classRows||[]){const type=s(r[1]),cat=up(r[2]),brand=up(r[3]),scheme=up(r[5]);if(brand!=="APPLE"||!type)continue;const lob=lobOf(cat,type,scheme);if(!lob)continue;const key=productKey(type,lob);if(!typeMap.has(key))typeMap.set(key,{productKey:key,productName:type,lob,target:null,achievement:0,order:999,configured:false})}
 for(const[key,t]of targets.focusTargets){const old=typeMap.get(key)||{productKey:key,productName:t.name,lob:lobOf(t.name,t.name,"DEVICES")||"Device",target:null,achievement:0,order:t.order,configured:true};old.target=t.target;old.order=t.order;old.configured=true;typeMap.set(key,old)}for(const key of targets.configured){const x=typeMap.get(key);if(x)x.configured=true}
 const sums={iphone:0,macbook:0,ipad:0,appleWatch:0};for(const t of typeMap.values()){if(t.lob==="iPhone")sums.iphone+=t.achievement;else if(t.lob==="MacBook")sums.macbook+=t.achievement;else if(t.lob==="iPad")sums.ipad+=t.achievement;else if(t.lob==="Apple Watch")sums.appleWatch+=t.achievement}const target=(k:string)=>targets.lobTargets.has(k)?targets.lobTargets.get(k)!:null,targets4=[target("IPHONE"),target("MACBOOK"),target("IPAD"),target("APPLE WATCH")],allTarget=targets4.every(v=>v!==null)?targets4.reduce<number>((a,v)=>a+(v??0),0):null;
 const data:FocusResponse={lob:{iphone:{target:target("IPHONE"),achievement:sums.iphone},macbook:{target:target("MACBOOK"),achievement:sums.macbook},ipad:{target:target("IPAD"),achievement:sums.ipad},appleWatch:{target:target("APPLE WATCH"),achievement:sums.appleWatch},allDevice:{target:allTarget,achievement:sums.iphone+sums.macbook+sums.ipad+sums.appleWatch}},types:[...typeMap.values()].sort((a,b)=>a.order-b.order||a.productName.localeCompare(b.productName)),configuredFocusKeys:targets.configured,vasByDate,cache,sourceRows};return{data,timing:{focusTotal:Date.now()-started,focusSourceRows:sourceRows}}}
