import {NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const txt=(v:unknown)=>String(v??"").trim();
const num=(v:unknown)=>typeof v==="number"?v:Number(txt(v).replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
function iso(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=txt(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);return""}
type M={period:string;amount:number;device:number;accessories:number;vas:number;qty:number;invoices:Set<string>};
function blank(y:number,m:number):M{return{period:`${y}-${String(m).padStart(2,"0")}`,amount:0,device:0,accessories:0,vas:0,qty:0,invoices:new Set()}}
function build(rows:unknown[][],year:number){const out=Array.from({length:12},(_,i)=>blank(year,i+1));for(const r of rows){const d=iso(r[0]);if(!d.startsWith(`${year}-`))continue;const mi=Number(d.slice(5,7))-1;if(mi<0||mi>11)continue;const x=out[mi],qty=num(r[7]),amount=num(r[8]),category=txt(r[9]).toUpperCase(),brand=txt(r[10]).toUpperCase(),core=txt(r[11]).toUpperCase(),scheme=txt(r[12]).toUpperCase(),invoice=txt(r[3]);if(category==="VOUCHER"||core==="VOUCHER"||brand==="VOUCHER")continue;x.amount+=amount;x.qty+=qty;if(invoice)x.invoices.add(invoice);if(scheme==="DEVICES")x.device+=amount;else if(scheme==="VAS")x.vas+=amount;else if(scheme==="ACCESSORIES")x.accessories+=amount}return out.map(x=>({period:x.period,amount:x.amount,device:x.device,accessories:x.accessories,vas:x.vas,qty:x.qty,invoices:x.invoices.size,upt:x.invoices.size?x.qty/x.invoices.size:0}))}
export async function GET(){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const[r26,r25]=await getSheetRanges(ID,["'Data Copas'!A2:M50000","'Data Copas Archive 2025'!A2:M32755"],email,key);const y2025=build(r25,2025),y2026=build(r26,2026);const total=(rows:ReturnType<typeof build>)=>rows.reduce((a,r)=>({amount:a.amount+r.amount,device:a.device+r.device,accessories:a.accessories+r.accessories,vas:a.vas+r.vas,qty:a.qty+r.qty,invoices:a.invoices+r.invoices}),{amount:0,device:0,accessories:0,vas:0,qty:0,invoices:0});return NextResponse.json({years:{"2025":y2025,"2026":y2026},totals:{"2025":total(y2025),"2026":total(y2026)}},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca detail tahunan"},{status:500})}}
