"use client";
import {useRef,useState} from "react";
const card="m238-soft-card rounded-2xl border p-5 shadow-sm";
const field="h-11 w-full rounded-xl border bg-white px-3 dark:bg-slate-900";
const today=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
type Notice={type:"success"|"error";title:string;text:string}|null;
type Preview={date:string;staffId:string;staff:string;invoice:string;article:string;description:string;qty:number;amount:number};
type SpwProgress=""|"Uploading SPW..."|"Processing Sales..."|"Updating Daily Sales..."|"Ready";
export default function Page(){
 const spw=useRef<HTMLInputElement>(null),soh=useRef<HTMLInputElement>(null);
 const[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(""),[pin,setPin]=useState(""),[spwProgress,setSpwProgress]=useState<SpwProgress>(""),[confirmClearSpw,setConfirmClearSpw]=useState(false);
 const[cutMode,setCutMode]=useState<"date"|"month">("date"),[cutValue,setCutValue]=useState(today());
 const[invoice,setInvoice]=useState(""),[noExchange,setNoExchange]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[existingExchange,setExistingExchange]=useState("");
 const show=(type:"success"|"error",title:string,text:string)=>setNotice({type,title,text:`${text} • ${new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}`});
 const upload=async(kind:"spw"|"soh")=>{const input=(kind==="spw"?spw:soh).current,f=input?.files?.[0];if(!f)return show("error",`Upload ${kind.toUpperCase()} belum dijalankan`,`Pilih file Excel ${kind.toUpperCase()} terlebih dahulu.`);setBusy(`upload-${kind}`);setNotice(null);let timer1:number|undefined,timer2:number|undefined;if(kind==="spw"){setSpwProgress("Uploading SPW...");timer1=window.setTimeout(()=>setSpwProgress("Processing Sales..."),500);timer2=window.setTimeout(()=>setSpwProgress("Updating Daily Sales..."),1300)}try{const body=new FormData();body.append("file",f);const r=await fetch(kind==="spw"?"/api/upload-spw":"/api/upload-soh",{method:"POST",body,cache:"no-store"}),j=await r.json();if(!r.ok){show("error",`Upload ${kind.toUpperCase()} gagal`,j.error||"Periksa file lalu coba kembali.");if(kind==="spw")setSpwProgress("")}else if(kind==="spw"){if(j.fast?.ok){setSpwProgress("Ready");const ms=Number(j.processingMs||0),secs=ms?`${(ms/1000).toFixed(1)} dtk`:"—",warning=j.fast?.warning?` • ${j.fast.warning}`:"";show("success","SPW berhasil diupload dan Daily Sales sudah diperbarui.",`${j.processedRows??j.rows} row diproses • ${j.newRows??j.processedRows??0} processed • ${j.duplicateSkipped??0} duplicate digabung • ${secs}${warning}`)}else{setSpwProgress("");show("error","SPW berhasil diupload, tetapi Fast Daily Sales gagal diproses.",`${j.fast?.error||"Fast processing gagal"} Data existing tetap aman.`)}if(input)input.value=""}else{show("success",`Upload ${kind.toUpperCase()} berhasil`,`${f.name} • ${j.rows} baris tersimpan di MASTER DATA M238.`);if(input)input.value=""}}catch{show("error",`Upload ${kind.toUpperCase()} gagal`,"Koneksi terputus atau server tidak merespons.");if(kind==="spw")setSpwProgress("")}finally{if(timer1)window.clearTimeout(timer1);if(timer2)window.clearTimeout(timer2);setBusy("")}};
 const cutoff=async()=>{if(!cutValue)return show("error","Cut Off Gagal","Pilih tanggal/periode cut off terlebih dahulu.");if(!confirm(`Jalankan Cut Off ${cutMode==="date"?"tanggal":"bulan"} ${cutValue}? Data akan di-append ke Data Copas.`))return;setBusy("cutoff");setNotice(null);try{const r=await fetch("/api/data-upload-ops",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"cutoff",mode:cutMode,value:cutValue}),cache:"no-store"}),j=await r.json();if(!r.ok)show("error","Cut Off Gagal",j.error||"Cut Off tidak dapat diselesaikan.");else show("success","Cut Off Berhasil",`${j.rows} baris ditambahkan ke Data Copas.`)}catch{show("error","Cut Off Gagal","Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const searchInvoice=async()=>{const q=invoice.trim();if(!q)return show("error","Pencarian Invoice","Masukkan No Invoice terlebih dahulu.");setBusy("find-invoice");setPreview(null);setExistingExchange("");setNotice(null);try{const r=await fetch(`/api/data-upload-ops?invoice=${encodeURIComponent(q)}`,{cache:"no-store"}),j=await r.json();if(!r.ok)return show("error","Invoice tidak ditemukan",j.error||"Invoice tidak ditemukan.");setPreview(j.preview||null);setExistingExchange(String(j.existingNoExchange||""));if(j.existingNoExchange)show("error","No Exchange invoice ini sudah terisi",String(j.existingNoExchange));else show("success","Invoice ditemukan","Periksa preview transaksi lalu isi No Exchange.")}catch{show("error","Pencarian Invoice gagal","Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const saveExchange=async()=>{if(!preview||preview.invoice.trim().toUpperCase()!==invoice.trim().toUpperCase())return show("error","No Exchange belum disimpan","Cari invoice dan periksa preview terlebih dahulu.");if(existingExchange)return show("error","No Exchange invoice ini sudah terisi",existingExchange);if(!noExchange.trim())return show("error","No Exchange belum diisi","Masukkan No Exchange terlebih dahulu.");setBusy("save-exchange");setNotice(null);try{const r=await fetch("/api/data-upload-ops",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"exchange",invoice:invoice.trim(),noExchange:noExchange.trim()}),cache:"no-store"}),j=await r.json();if(!r.ok)return show("error","No Exchange gagal disimpan",j.error||"Operasi tidak dapat diselesaikan.");show("success","No Exchange berhasil disimpan",noExchange.trim());setExistingExchange(noExchange.trim());setNoExchange("")}catch{show("error","No Exchange gagal disimpan","Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const performClear=async(kind:"spw"|"soh")=>{setBusy(`clear-${kind}`);setNotice(null);try{const r=await fetch("/api/data-tools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:`clear-${kind}`,passcode:pin}),cache:"no-store"}),j=await r.json();if(!r.ok)show("error",`Clear ${kind.toUpperCase()} gagal`,j.error||"Operasi tidak dapat diselesaikan.");else{show("success",`Clear ${kind.toUpperCase()} berhasil`,j.message||"Data master sudah dibersihkan.");if(kind==="spw")setSpwProgress("")}}catch{show("error",`Clear ${kind.toUpperCase()} gagal`,"Koneksi terputus atau server tidak merespons.")}finally{setBusy("");setConfirmClearSpw(false)}};
 const clear=async(kind:"spw"|"soh")=>{if(!pin)return show("error","Admin Clear dikunci","Masukkan Passcode Admin terlebih dahulu.");if(kind==="spw"){setConfirmClearSpw(true);return}if(!confirm("Yakin ingin Clear SOH di MASTER DATA M238?"))return;await performClear(kind)};
 const btn=(key:string)=>busy===key?"Memproses...":null;
 return <div className="w-full space-y-5"><div><h2 className="text-2xl font-black text-slate-900 dark:text-slate-100">Data Upload</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">SPW dan SOH disimpan di MASTER DATA M238. Cut Off dan No Exchange menggunakan RAW Salesperson.</p></div>{notice&&<div role="alert" className={`rounded-2xl border p-4 ${notice.type==="success"?"border-emerald-300/70 bg-emerald-50 text-emerald-800 dark:border-emerald-700/60 dark:bg-emerald-950/25 dark:text-emerald-200":"border-rose-300/70 bg-rose-50 text-rose-800 dark:border-rose-700/60 dark:bg-rose-950/25 dark:text-rose-200"}`}><div className="font-black">{notice.type==="success"?"✓ ":"⚠ "}{notice.title}</div><div className="mt-1 text-sm font-semibold">{notice.text}</div></div>}
 <div className="grid gap-5 md:grid-cols-2"><section className={card}><h3 className="text-lg font-black">Upload SPW</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Excel SPW → MASTER DATA M238 / SPW.</p><input ref={spw} type="file" accept=".xlsx,.xls" className="mt-4 w-full rounded-xl border p-2"/><button disabled={!!busy} onClick={()=>upload("spw")} className="mt-3 w-full rounded-xl bg-blue-600/90 px-5 py-3 font-bold text-white disabled:opacity-50">{busy==="upload-spw"?(spwProgress||"Uploading SPW..."):"Upload SPW"}</button>{spwProgress&&<div className="mt-3 text-xs font-bold text-slate-500">{spwProgress}</div>}</section>
 <section className={card}><h3 className="text-lg font-black">Upload SOH</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Excel SOH → MASTER DATA M238 / SOH.</p><input ref={soh} type="file" accept=".xlsx,.xls" className="mt-4 w-full rounded-xl border p-2"/><button disabled={!!busy} onClick={()=>upload("soh")} className="mt-3 w-full rounded-xl bg-emerald-600/90 px-5 py-3 font-bold text-white disabled:opacity-50">{btn("upload-soh")||"Upload SOH"}</button></section></div>
 <div className="grid gap-5 md:grid-cols-2"><section className={card}><h3 className="text-lg font-black">Cut Off Data</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">RAW Salesperson AB:AR → append ke Data Copas. Data existing tidak dihapus.</p><div className="mt-4 grid gap-3 sm:grid-cols-[150px_1fr]"><select value={cutMode} onChange={e=>{const m=e.target.value as "date"|"month";setCutMode(m);setCutValue(m==="date"?today():today().slice(0,7))}} className={field}><option value="date">Tanggal</option><option value="month">Bulan</option></select><input type={cutMode==="date"?"date":"month"} value={cutValue} onChange={e=>setCutValue(e.target.value)} className={field}/></div><p className="mt-3 text-xs text-slate-400">Duplicate dicek dari isi 17 kolom yang sudah tersimpan di Data Copas, jadi tetap terdeteksi setelah refresh/login ulang.</p><button disabled={!!busy} onClick={cutoff} className="mt-3 w-full rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-50">{btn("cutoff")||"Jalankan Cut Off"}</button></section>
 <section className={card}><h3 className="text-lg font-black">No Exchange Invoice</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Cari invoice di RAW Salesperson lalu isi hanya kolom Y jika masih kosong.</p><div className="mt-4 flex gap-2"><input value={invoice} onChange={e=>{setInvoice(e.target.value);setPreview(null);setExistingExchange("")}} placeholder="No Invoice" className={field}/><button disabled={!!busy||!invoice.trim()} onClick={searchInvoice} className="shrink-0 rounded-xl border px-4 font-bold disabled:opacity-50">{busy==="find-invoice"?"Mencari...":"Cari"}</button></div>{preview&&<div className="mt-3 rounded-xl border bg-slate-50 p-3 text-sm dark:bg-slate-900"><div className="font-black">{preview.invoice}</div><div className="mt-1 text-slate-500">{preview.date||"—"} • {preview.staff||preview.staffId||"—"}</div><div className="mt-1 text-xs text-slate-500">{preview.article||"—"} • {preview.description||"—"} • Qty {preview.qty}</div>{existingExchange&&<div className="mt-2 font-bold text-amber-600">No Exchange: {existingExchange}</div>}</div>}<input value={noExchange} onChange={e=>setNoExchange(e.target.value)} placeholder="No Exchange" disabled={!preview||!!existingExchange} className={`${field} mt-3 disabled:opacity-50`}/><button disabled={!!busy||!preview||!!existingExchange||!noExchange.trim()} onClick={saveExchange} className="mt-3 w-full rounded-xl bg-slate-900 px-5 py-3 font-bold text-white disabled:opacity-40 dark:bg-white dark:text-slate-900">{btn("save-exchange")||"Simpan No Exchange"}</button></section></div>
 <section className={`${card} border-rose-200/70 dark:border-rose-800/50`}><h3 className="text-lg font-black">Admin Clear MASTER DATA</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Clear SPW juga mengosongkan SALES DASHBOARD DATA dan DAILY SALES CACHE aktif. Data Copas, hasil Cut Off, No Exchange, SOH, Config, dan history tetap aman.</p><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Passcode Admin" className="mt-4 h-11 w-full rounded-xl border px-3"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><button disabled={!!busy||!pin} onClick={()=>clear("spw")} className="rounded-xl bg-rose-600/90 px-4 py-3 font-bold text-white disabled:opacity-40">{btn("clear-spw")||"Clear SPW"}</button><button disabled={!!busy||!pin} onClick={()=>clear("soh")} className="rounded-xl bg-rose-600/90 px-4 py-3 font-bold text-white disabled:opacity-40">{btn("clear-soh")||"Clear SOH"}</button></div></section>
 {confirmClearSpw&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-950"><h3 className="text-lg font-black">Clear SPW aktif?</h3><p className="mt-2 text-sm text-slate-500">Yakin ingin clear SPW aktif? Data upload aktif dan cache Daily Sales akan dikosongkan. Data Cut Off/history tetap aman.</p><div className="mt-5 grid grid-cols-2 gap-3"><button disabled={!!busy} onClick={()=>setConfirmClearSpw(false)} className="rounded-xl border px-4 py-3 font-bold">Batal</button><button disabled={!!busy} onClick={()=>performClear("spw")} className="rounded-xl bg-rose-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy==="clear-spw"?"Memproses...":"Ya, Clear"}</button></div></div></div>}
 </div>;
}
