"use client";
import {useEffect,useRef,useState} from "react";
import ScheduleImageConverter from "@/components/schedule-image-converter";
const card="m238-soft-card rounded-2xl border p-5 shadow-sm";
type Notice={type:"success"|"error";title:string;text:string}|null;
type Log={period:string;fileName:string;uploadedAt:string;type:string;remark:string;parsedRows:number;status:string};
const currentPeriod=()=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());
export default function Page(){
 const spw=useRef<HTMLInputElement>(null),soh=useRef<HTMLInputElement>(null),schedule=useRef<HTMLInputElement>(null),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(""),[pin,setPin]=useState(""),[schedulePeriod,setSchedulePeriod]=useState(currentPeriod()),[remark,setRemark]=useState(""),[logs,setLogs]=useState<Log[]>([]);
 const loadLogs=()=>fetch("/api/upload-schedule",{cache:"no-store"}).then(r=>r.json()).then(j=>setLogs(j.rows||[])).catch(()=>{});useEffect(()=>{void loadLogs()},[]);
 const show=(type:"success"|"error",title:string,text:string)=>setNotice({type,title,text:`${text} • ${new Date().toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}`});
 const upload=async(kind:"spw"|"soh")=>{const input=(kind==="spw"?spw:soh).current,f=input?.files?.[0];if(!f)return show("error",`Upload ${kind.toUpperCase()} belum dijalankan`,`Pilih file Excel ${kind.toUpperCase()} terlebih dahulu.`);setBusy(`upload-${kind}`);setNotice(null);try{const body=new FormData();body.append("file",f);const r=await fetch(kind==="spw"?"/api/upload-spw":"/api/upload-soh",{method:"POST",body,cache:"no-store"}),j=await r.json();if(!r.ok)show("error",`Upload ${kind.toUpperCase()} gagal`,j.error||"Periksa file lalu coba kembali.");else{show("success",`Upload ${kind.toUpperCase()} berhasil`,`${f.name} • ${j.rows} baris masuk ke MASTER DATA M238 dan sinkron ke dashboard.`);if(input)input.value=""}}catch{show("error",`Upload ${kind.toUpperCase()} gagal`,"Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const uploadSchedule=async()=>{const input=schedule.current,f=input?.files?.[0];if(!pin)return show("error","Upload Schedule dikunci","Masukkan Passcode Admin yang sama dengan Admin Clear.");if(!f)return show("error","Upload Schedule belum dijalankan","Pilih file schedule terlebih dahulu.");setBusy("upload-schedule");setNotice(null);try{const body=new FormData();body.append("file",f);body.append("period",schedulePeriod);body.append("remark",remark);body.append("passcode",pin);const r=await fetch("/api/upload-schedule",{method:"POST",body,cache:"no-store"}),j=await r.json();if(!r.ok)show("error","Upload Schedule gagal",j.error||"Schedule tidak dapat disimpan.");else{show("success","Upload Schedule berhasil",j.message||`${f.name} berhasil dicatat.`);if(input)input.value="";setRemark("");void loadLogs()}}catch{show("error","Upload Schedule gagal","Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const action=async(a:string)=>{const label=a==="cutoff-spw"?"Cut Off SPW":a==="clear-spw"?"Clear SPW":a==="clear-soh"?"Clear SOH":"Buka MASTER DATA M238";if(a==="cutoff-spw"&&!confirm("Lanjut Cut Off SPW? Data hasil RAW SalesPerson AB–AR akan ditambahkan ke Data Copas."))return;if(a.startsWith("clear")&&!confirm(`Yakin ingin ${label}? Data sumber di MASTER DATA M238 dan mirror dashboard akan dibersihkan.`))return;setBusy(a);setNotice(null);try{const r=await fetch("/api/data-tools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:a,passcode:pin}),cache:"no-store"}),j=await r.json();if(!r.ok)show("error",`${label} gagal`,j.error||"Operasi tidak dapat diselesaikan.");else if(a==="open-master"&&j.url){window.open(j.url,"_blank","noopener,noreferrer");show("success","MASTER DATA M238 terbuka","Akses admin berhasil diverifikasi.")}else show("success",`${label} berhasil`,j.message||`${label} selesai diproses.`)}catch{show("error",`${label} gagal`,"Koneksi terputus atau server tidak merespons.")}finally{setBusy("")}};
 const btn=(key:string)=>busy===key?"Memproses...":null;
 return <><div className="w-full space-y-5"><div><h2 className="text-2xl font-black text-slate-900 dark:text-slate-100">Data Upload & Cut Off</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">SPW, SOH, dan Schedule tersimpan terstruktur di MASTER DATA M238.</p></div>{notice&&<div role="alert" className={`rounded-2xl border p-4 ${notice.type==="success"?"border-emerald-300/70 bg-emerald-50 text-emerald-800 dark:border-emerald-700/60 dark:bg-emerald-950/25 dark:text-emerald-200":"border-rose-300/70 bg-rose-50 text-rose-800 dark:border-rose-700/60 dark:bg-rose-950/25 dark:text-rose-200"}`}><div className="font-black">{notice.type==="success"?"✓ ":"⚠ "}{notice.title}</div><div className="mt-1 text-sm font-semibold">{notice.text}</div></div>}
 <div className="grid gap-5 md:grid-cols-2"><section className={card}><h3 className="text-lg font-black">Upload SPW</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Excel SPW → MASTER DATA M238 / SPW → RAW SalesPerson R–T.</p><input ref={spw} type="file" accept=".xlsx,.xls" className="mt-4 w-full rounded-xl border p-2"/><button disabled={!!busy} onClick={()=>upload("spw")} className="mt-3 w-full rounded-xl bg-blue-600/90 px-5 py-3 font-bold text-white disabled:opacity-50">{btn("upload-spw")||"Upload SPW"}</button></section>
 <section className={card}><h3 className="text-lg font-black">Cut Off SPW</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Menambahkan hasil AB–AR ke Data Copas tanpa menimpa histori.</p><button disabled={!!busy} onClick={()=>action("cutoff-spw")} className="mt-6 w-full rounded-xl bg-slate-700 px-5 py-3 font-bold text-white dark:bg-slate-600 disabled:opacity-50">{btn("cutoff-spw")||"Cut Off SPW"}</button></section>
 <section className={card}><h3 className="text-lg font-black">Upload SOH</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Excel SOH → MASTER DATA M238 / SOH → RAW StockPosition F–N.</p><input ref={soh} type="file" accept=".xlsx,.xls" className="mt-4 w-full rounded-xl border p-2"/><button disabled={!!busy} onClick={()=>upload("soh")} className="mt-3 w-full rounded-xl bg-emerald-600/90 px-5 py-3 font-bold text-white disabled:opacity-50">{btn("upload-soh")||"Upload SOH"}</button></section>
 <section className={`${card} border-violet-200/70 dark:border-violet-700/40`}><div className="flex items-center justify-between gap-3"><div><h3 className="text-lg font-black">Upload Schedule</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Khusus admin • password sama dengan Admin Clear.</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-black text-violet-700 dark:bg-violet-950/40 dark:text-violet-300">LOCKED</span></div><label className="mt-4 block"><span className="mb-1 block text-xs font-bold text-slate-500">Passcode Admin</span><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Masukkan passcode" className="h-11 w-full rounded-xl border px-3"/></label><label className="mt-3 block"><span className="mb-1 block text-xs font-bold text-slate-500">Periode Schedule</span><input type="month" value={schedulePeriod} onChange={e=>setSchedulePeriod(e.target.value)} className="h-11 w-full rounded-xl border px-3"/></label><input ref={schedule} type="file" accept=".jpg,.jpeg,.png,.pdf,.heic,.xls,.xlsx" className="mt-3 w-full rounded-xl border p-2"/><textarea value={remark} onChange={e=>setRemark(e.target.value)} rows={3} placeholder="Remark manual jika ada perubahan mendadak / pergantian schedule" className="mt-3 w-full rounded-xl border p-3"/><button disabled={!!busy||!pin} onClick={uploadSchedule} className="mt-3 w-full rounded-xl bg-violet-600/90 px-5 py-3 font-bold text-white disabled:opacity-40">{btn("upload-schedule")||"Upload Schedule"}</button><div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-800 dark:border-blue-800/60 dark:bg-blue-950/25 dark:text-blue-200"><b>Foto/screenshot/PDF:</b> setelah file dipilih, sistem akan membaca schedule dan menampilkan preview. Setelah preview benar, tekan <b>Gunakan Hasil Ini untuk Upload Schedule</b>, lalu tekan <b>Upload Schedule</b>.</div></section>
 <section className={`${card} border-amber-200/70 dark:border-amber-700/40`}><h3 className="text-lg font-black">Admin / MASTER DATA</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Passcode yang sama digunakan untuk Upload Schedule, membuka MASTER DATA M238, dan Admin Clear.</p><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Passcode Admin" className="mt-4 h-11 w-full rounded-xl border px-3"/><button disabled={!!busy||!pin} onClick={()=>action("open-master")} className="mt-3 w-full rounded-xl bg-amber-500/90 px-4 py-3 font-black text-slate-950 disabled:opacity-40">{btn("open-master")||"Buka MASTER DATA M238"}</button><div className="mt-3 grid grid-cols-2 gap-3"><button disabled={!!busy||!pin} onClick={()=>action("clear-spw")} className="rounded-xl bg-rose-600/90 px-4 py-3 font-bold text-white disabled:opacity-40">{btn("clear-spw")||"Clear SPW"}</button><button disabled={!!busy||!pin} onClick={()=>action("clear-soh")} className="rounded-xl bg-rose-600/90 px-4 py-3 font-bold text-white disabled:opacity-40">{btn("clear-soh")||"Clear SOH"}</button></div></section></div>
 <section className={`${card} overflow-hidden`}><h3 className="text-lg font-black">Riwayat Upload Schedule</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Schedule aktif yang sudah terbaca tidak akan ditimpa.</p><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th className="px-3 py-3 text-left">Periode</th><th className="px-3 py-3 text-left">File</th><th className="px-3 py-3 text-left">Upload</th><th className="px-3 py-3 text-left">Status</th><th className="px-3 py-3 text-left">Remark</th></tr></thead><tbody>{logs.length?logs.map((r,i)=><tr key={`${r.period}-${i}`} className="border-t"><td className="px-3 py-3 font-bold">{r.period}</td><td className="px-3 py-3">{r.fileName}</td><td className="px-3 py-3">{r.uploadedAt?new Date(r.uploadedAt).toLocaleString("id-ID"):"-"}</td><td className="px-3 py-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{r.status}</span></td><td className="px-3 py-3">{r.remark||"-"}</td></tr>):<tr><td colSpan={5} className="p-6 text-center text-slate-400">Belum ada schedule yang di-upload.</td></tr>}</tbody></table></div></section></div><ScheduleImageConverter/></>;
}