import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const s=(v:unknown)=>String(v??"").trim();
const up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
function iso(v:unknown){const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return""}
type Tot={qty:number;value:number};const fresh=():Tot=>({qty:0,value:0});const add=(t:Tot,q:number,v:number)=>{t.qty+=q;t.value+=v};
function lob(type:string,category:string,desc:string){const x=`${type} ${category} ${desc}`.toUpperCase();if(/IPHONE/.test(x))return"iPhone";if(/MACBOOK|MAC BOOK|MBA |MBP /.test(x))return"MacBook";if(/IPAD/.test(x))return"iPad";if(/APPLE WATCH|WATCH |\bAW\b/.test(x))return"Watch";if(/AIRPODS/.test(x))return"AirPods";return""}
function vas(article:string,brand:string,vendor:string,desc:string){const a=up(article),b=up(brand),v=up(vendor),d=up(desc);if(b==="QOALA"||a.startsWith("KLA")||v.includes("QOALA"))return"Qoala";if(b==="TELKOMSEL"||a.startsWith("TSL")||v.includes("TELKOMSEL"))return"Telkomsel";if(b==="XL"||b==="XXL"||a.startsWith("XXL")||v==="XL")return"XL";if(b.includes("INDOSAT")||a.startsWith("IDT")||v.includes("INDOSAT")||d.includes("INDOSAT"))return"Indosat";return""}
export async function GET(req:NextRequest){const period=req.nextUrl.searchParams.get("period")||"2026-09";if(!/^202[56]-\d{2}$/.test(period))return NextResponse.json({error:"Period hanya mendukung 2025 atau 2026"},{status:400});const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const year=period.slice(0,4),range=year==="2026"?"'Data Copas'!A2:S50000":"'Data Copas Archive 2025'!A2:M32755",[rows]=await getSheetRanges(ID,[range],email,key);const selected=rows.filter(r=>iso(r[0]).startsWith(period)&&(year==="2025"||up(r[15])==="M238"));const staff=new Map<string,number>(),lobs:Record<string,Tot>={iPhone:fresh(),MacBook:fresh(),iPad:fresh(),Watch:fresh(),AirPods:fresh()},providers:Record<string,Tot>={Qoala:fresh(),Telkomsel:fresh(),XL:fresh(),Indosat:fresh()};let total=0,qty=0,invoices=new Set<string>();for(const r of selected){const name=s(r[2])||"Tanpa Nama",article=s(r[4]),desc=s(r[5]),type=s(r[6]),q=n(r[7]),value=n(r[8]),category=s(r[9]),brand=s(r[10]),scheme=up(r[12]),vendor=year==="2026"?s(r[13]):"";if(up(type)==="VOUCHER"||up(category)==="VOUCHER"||up(article).startsWith("ZZZMAP"))continue;total+=value;qty+=q;staff.set(name,(staff.get(name)||0)+value);if(s(r[3]))invoices.add(s(r[3]));const l=lob(type,category,desc);if(l&&lobs[l])add(lobs[l],q,value);if(scheme==="VAS"){const p=vas(article,brand,vendor,desc);if(p)add(providers[p],q,value)}}return NextResponse.json({period,year,total,qty,invoices:invoices.size,staff:[...staff.entries()].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value),lob:Object.entries(lobs).map(([name,t])=>({name,...t})),vas:Object.entries(providers).map(([name,t])=>({name,...t}))},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca detail bulan"},{status:500})}}
