import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const STORE="M238";
const DEVICE_LOBS=["iPhone","iPad","Mac","Apple Watch","AirPods"] as const;
const n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
const s=(v:unknown)=>String(v??"").trim();
const up=(v:unknown)=>s(v).toUpperCase();
function iso(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);const m=x.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""}
function jakartaToday(){return new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date())}
function monthLabel(period:string){return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${period}-01T00:00:00Z`))}
function valid(r:unknown[]){return up(r[12])!=="VOUCHER"&&!up(r[5]).includes("VOUCHER")}
function rowText(r:unknown[]){return `${up(r[6])} ${up(r[9])} ${up(r[5])}`}
function kind(r:unknown[]){const scheme=up(r[12]),text=rowText(r);if(scheme==="VAS")return"vas";if(scheme==="ACCESSORIES")return"accessories";if(scheme==="DEVICES")return"device";if(/IPHONE|IPAD|MAC|APPLE WATCH|AIRPODS/.test(text))return"device";return"other"}
function deviceLob(r:unknown[]){const text=rowText(r);if(text.includes("IPHONE"))return"iPhone";if(text.includes("IPAD"))return"iPad";if(text.includes("MAC"))return"Mac";if(text.includes("APPLE WATCH")||/\bWATCH\b/.test(text))return"Apple Watch";if(text.includes("AIRPODS"))return"AirPods";return"Other Device"}
function scoped(rows:unknown[][],period?:string){return rows.filter(r=>{const d=iso(r[0]);if(!d||!valid(r))return false;if(period&&!d.startsWith(period))return false;return up(r[15])===STORE})}
function archiveScoped(rows:unknown[][]){const hasStore=rows.some(r=>up(r[15])===STORE);return rows.filter(r=>{const d=iso(r[0]);if(!d||!d.startsWith("2025-")||!valid(r))return false;return hasStore?up(r[15])===STORE:true})}
function sumByKind(rows:unknown[][],k:string){return rows.filter(r=>kind(r)===k).reduce((a,r)=>a+n(r[8]),0)}
function sumAmount(rows:unknown[][]){return rows.reduce((a,r)=>a+n(r[8]),0)}
function sumQty(rows:unknown[][]){return rows.reduce((a,r)=>a+n(r[7]),0)}
function monthSeries(rows:unknown[][],year:number){return Array.from({length:12},(_,i)=>{const period=`${year}-${String(i+1).padStart(2,"0")}`,rr=rows.filter(r=>iso(r[0]).startsWith(period)),devices=rr.filter(r=>kind(r)==="device"),lobs:Record<string,{amount:number;qty:number}>={};for(const lob of DEVICE_LOBS)lobs[lob]={amount:0,qty:0};lobs["Other Device"]={amount:0,qty:0};for(const r of devices){const lob=deviceLob(r),cur=lobs[lob]||{amount:0,qty:0};lobs[lob]={amount:cur.amount+n(r[8]),qty:cur.qty+n(r[7])}}return{period,amount:sumAmount(rr),qty:sumQty(rr),device:sumAmount(devices),deviceQty:sumQty(devices),lobs}})}

export async function GET(req:NextRequest){
 const period=req.nextUrl.searchParams.get("period")||jakartaToday().slice(0,7);
 if(!/^2026-\d{2}$/.test(period))return NextResponse.json({error:"Period harus format YYYY-MM"},{status:400});
 const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;
 if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});
 try{
  const[rows2026,rows2025,config]=await getSheetRanges(ID,["'Data Copas'!A2:S50000","'Data Copas Archive 2025'!A2:S32755","Config!A1:AZ120"],email,key);
  const monthRows=scoped(rows2026||[],period),all2026=scoped(rows2026||[]),all2025=archiveScoped(rows2025||[]);
  const label=monthLabel(period).toLowerCase(),targetRow=(config||[]).find(r=>s(r[16]).toLowerCase()===label),target={amount:n(targetRow?.[17]),device:n(targetRow?.[18]),accessories:n(targetRow?.[19]),vas:n(targetRow?.[20])};
  const shareById=new Map<string,number>();for(const r of (config||[]).slice(27,55)){const id=s(r[8]);if(id)shareById.set(id,n(r[11]))}
  const byStaff=new Map<string,unknown[][]>();for(const r of monthRows){const id=s(r[1]);if(!id)continue;const arr=byStaff.get(id)||[];arr.push(r);byStaff.set(id,arr)}
  const staff=[...byStaff.entries()].map(([id,rr])=>{const names=rr.map(r=>s(r[2])).filter(Boolean),name=names.at(-1)||id,invoices=new Set(rr.map(r=>s(r[3])).filter(Boolean)),qty=sumQty(rr),amount=sumAmount(rr),device=sumByKind(rr,"device"),accessories=sumByKind(rr,"accessories"),vas=sumByKind(rr,"vas"),share=Math.max(0,shareById.get(id)||0),staffTarget=target.amount*share,achievement=staffTarget?amount/staffTarget*100:null;let status="Productive";if(achievement!==null)status=achievement>=100?"Productive":achievement>=80?"Need Push":"Low Activity";return{id,name,amount,device,accessories,vas,qty,invoices:invoices.size,upt:invoices.size?qty/invoices.size:0,atv:invoices.size?amount/invoices.size:0,target:staffTarget,achievement,gap:staffTarget?Math.max(0,staffTarget-amount):0,status}}).sort((a,b)=>b.amount-a.amount);
  const invoices=new Set(monthRows.map(r=>s(r[3])).filter(Boolean)),qty=sumQty(monthRows),amount=sumAmount(monthRows),device=sumByKind(monthRows,"device"),accessories=sumByKind(monthRows,"accessories"),vas=sumByKind(monthRows,"vas");
  const dates=[...new Set(monthRows.map(r=>iso(r[0])).filter(Boolean))].sort(),daily=dates.map(date=>({date,amount:sumAmount(monthRows.filter(r=>iso(r[0])===date))}));
  const today=jakartaToday(),current=today.slice(0,7),dim=new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate(),elapsed=period<current?dim:period>current?0:Math.min(Number(today.slice(8,10)),dim),pace=dim?elapsed/dim*100:0,achievement=target.amount?amount/target.amount*100:0,gap=Math.max(0,target.amount-amount),status=target.amount?(achievement>=100?"Achieve":achievement>=pace?"On Track":"Need Push"):"Target belum ada";
  const projectionFactor=elapsed>0?dim/elapsed:0;
  const estimate={amount:period<current?amount:period>current?0:amount*projectionFactor,device:period<current?device:period>current?0:device*projectionFactor,accessories:period<current?accessories:period>current?0:accessories*projectionFactor,vas:period<current?vas:period>current?0:vas*projectionFactor};
  const pointDevice=Math.min(target.device?device/target.device*60:0,60),pointAccessories=Math.min(target.accessories?accessories/target.accessories*30:0,30),pointVas=Math.min(target.vas?vas/target.vas*10:0,10),point={total:pointDevice+pointAccessories+pointVas,device:pointDevice,accessories:pointAccessories,vas:pointVas};
  const series2025=monthSeries(all2025,2025),series2026=monthSeries(all2026,2026),currentMonth=Number(current.slice(5,7));
  const compare=series2025.map((x,i)=>{const y=series2026[i],started=i+1<=currentMonth||y.amount>0,diff=started?y.amount-x.amount:null,growth=started&&x.amount?((y.amount-x.amount)/x.amount)*100:null,qtyDiff=started?y.qty-x.qty:null,qtyGrowth=started&&x.qty?((y.qty-x.qty)/x.qty)*100:null,deviceDiff=started?y.device-x.device:null,deviceGrowth=started&&x.device?((y.device-x.device)/x.device)*100:null,deviceQtyDiff=started?y.deviceQty-x.deviceQty:null,deviceQtyGrowth=started&&x.deviceQty?((y.deviceQty-x.deviceQty)/x.deviceQty)*100:null;const lobs=Object.keys({...x.lobs,...y.lobs}).map(lob=>{const a=x.lobs[lob]||{amount:0,qty:0},b=y.lobs[lob]||{amount:0,qty:0},amount2026=started?b.amount:null,qty2026=started?b.qty:null,lobDiff=started?(amount2026||0)-a.amount:null,lobGrowth=started&&a.amount?(((amount2026||0)-a.amount)/a.amount)*100:null,lobQtyDiff=started?(qty2026||0)-a.qty:null,lobQtyGrowth=started&&a.qty?(((qty2026||0)-a.qty)/a.qty)*100:null;return{lob,amount2025:a.amount,amount2026,qty2025:a.qty,qty2026,diff:lobDiff,growth:lobGrowth,qtyDiff:lobQtyDiff,qtyGrowth:lobQtyGrowth}});return{month:i+1,period2025:x.period,period2026:y.period,amount2025:x.amount,amount2026:started?y.amount:null,qty2025:x.qty,qty2026:started?y.qty:null,diff,growth,qtyDiff,qtyGrowth,device2025:x.device,device2026:started?y.device:null,deviceQty2025:x.deviceQty,deviceQty2026:started?y.deviceQty:null,deviceDiff,deviceGrowth,deviceQtyDiff,deviceQtyGrowth,lobs,started}});
  const ytdRows=compare.filter(x=>x.month<=currentMonth),sum=(key:string)=>ytdRows.reduce((a,x)=>a+Number((x as unknown as Record<string,unknown>)[key]||0),0),ytd2025=sum("amount2025"),ytd2026=sum("amount2026"),ytdQty2025=sum("qty2025"),ytdQty2026=sum("qty2026"),ytdDevice2025=sum("device2025"),ytdDevice2026=sum("device2026"),ytdDeviceQty2025=sum("deviceQty2025"),ytdDeviceQty2026=sum("deviceQty2026");
  const ytdLobs=DEVICE_LOBS.map(lob=>{const amount2025=ytdRows.reduce((a,r)=>a+(r.lobs.find(x=>x.lob===lob)?.amount2025||0),0),amount2026=ytdRows.reduce((a,r)=>a+(r.lobs.find(x=>x.lob===lob)?.amount2026||0),0),qty2025=ytdRows.reduce((a,r)=>a+(r.lobs.find(x=>x.lob===lob)?.qty2025||0),0),qty2026=ytdRows.reduce((a,r)=>a+(r.lobs.find(x=>x.lob===lob)?.qty2026||0),0);return{lob,amount2025,amount2026,qty2025,qty2026,diff:amount2026-amount2025,growth:amount2025?(amount2026-amount2025)/amount2025*100:null,qtyDiff:qty2026-qty2025,qtyGrowth:qty2025?(qty2026-qty2025)/qty2025*100:null}});
  const selectedMonth=Number(period.slice(5,7)),lfl=compare[selectedMonth-1]||null;
  return NextResponse.json({period,label:monthLabel(period),target,summary:{amount,device,accessories,vas,invoices:invoices.size,qty,upt:invoices.size?qty/invoices.size:0,atv:invoices.size?amount/invoices.size:0,achievement,gap,pace,status,estimate,point},staff,daily,team:{total:staff.length,productive:staff.filter(x=>x.status==="Productive").length,needPush:staff.filter(x=>x.status!=="Productive").length,totalTransactions:invoices.size,avgUpt:invoices.size?qty/invoices.size:0,avgAtv:invoices.size?amount/invoices.size:0},lfl,compare,ytd:{amount2025:ytd2025,amount2026:ytd2026,qty2025:ytdQty2025,qty2026:ytdQty2026,diff:ytd2026-ytd2025,growth:ytd2025?(ytd2026-ytd2025)/ytd2025*100:0,qtyDiff:ytdQty2026-ytdQty2025,qtyGrowth:ytdQty2025?(ytdQty2026-ytdQty2025)/ytdQty2025*100:0,device2025:ytdDevice2025,device2026:ytdDevice2026,deviceQty2025:ytdDeviceQty2025,deviceQty2026:ytdDeviceQty2026,deviceDiff:ytdDevice2026-ytdDevice2025,deviceGrowth:ytdDevice2025?(ytdDevice2026-ytdDevice2025)/ytdDevice2025*100:0,deviceQtyDiff:ytdDeviceQty2026-ytdDeviceQty2025,deviceQtyGrowth:ytdDeviceQty2025?(ytdDeviceQty2026-ytdDeviceQty2025)/ytdDeviceQty2025*100:0,lobs:ytdLobs,throughMonth:currentMonth}},{headers:{"cache-control":"no-store"}})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca Overview"},{status:500})}
}
