import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
import {cacheFromValues} from "@/lib/m238-fast-sales";
import {GET as legacyDailyGET} from "@/app/api/daily/route";

const SOURCE_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0",MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk",STORE="M238",CACHE="DAILY SALES CACHE",SNAPSHOT="Dashboard Schedule Snapshot";
const s=(v:unknown)=>String(v??"").trim(),up=(v:unknown)=>s(v).toUpperCase(),n=(v:unknown)=>typeof v==="number"?v:Number(String(v??"").replace(/[^0-9.-]/g,""))||0;
function iso(v:unknown){const x=s(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);return""}
function today(){return new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date())}
function weekday(date:string){return new Intl.DateTimeFormat("id-ID",{weekday:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00Z`)).toLowerCase()}
function unavailable(v:string){return/OFF|CUTI|TRAINING|MEETING|\bRO\b|SAKIT|SICK|LEAVE/i.test(v)}
function isSupervisor(v:string){return/SUPERVISOR|\bSPV\b/i.test(v)}
function isOnline(v:string){return/DIGIMAP\s*\.?\s*CO\s*\.?\s*ID/i.test(v)}
function shareValue(v:unknown){const x=n(v);return x>1?x/100:Math.max(0,x)}
function neutral(v:string){const x=up(v);if(/OFF/.test(x))return"OFF";if(/CUTI|LEAVE/.test(x))return"Cuti";if(/TRAINING/.test(x))return"Training";if(/MEETING/.test(x))return"Meeting";if(/SAKIT|SICK/.test(x))return"Sakit";if(/\bRO\b/.test(x))return"RO";return s(v)||"IN"}
const SHIFT:Record<string,{start:number;end:number}>={D047:{start:540,end:1020},D072:{start:660,end:1140},D083:{start:720,end:1200},D093:{start:780,end:1260},D103:{start:840,end:1320}};
function nowMinutes(){const p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Jakarta",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date());return Number(p.find(x=>x.type==="hour")?.value||0)*60+Number(p.find(x=>x.type==="minute")?.value||0)}
function liveMeta(date:string,status:string,amount:number,target:number){if(unavailable(status))return{liveStatus:neutral(status),statusTone:"neutral",shiftStart:"",shiftEnd:"",shiftProgress:0,paceTarget:0};const shift=SHIFT[up(status)];if(!shift)return{liveStatus:amount>=target&&target>0?"Achieve":amount>0?"Need Push":"Belum Produktif",statusTone:amount>=target&&target>0?"green":amount>0?"yellow":"neutral",shiftStart:"",shiftEnd:"",shiftProgress:0,paceTarget:0};const hh=(v:number)=>`${String(Math.floor(v/60)).padStart(2,"0")}.${String(v%60).padStart(2,"0")}`;if(date!==today()){const ok=target>0&&amount>=target;return{liveStatus:ok?"Achieve":amount>0?"Need Push":"Belum Produktif",statusTone:ok?"green":amount>0?"yellow":"red",shiftStart:hh(shift.start),shiftEnd:hh(shift.end),shiftProgress:1,paceTarget:target}}const now=nowMinutes();if(now<shift.start)return{liveStatus:"Belum Masuk Shift",statusTone:"neutral",shiftStart:hh(shift.start),shiftEnd:hh(shift.end),shiftProgress:0,paceTarget:0};const elapsed=Math.min(Math.max(0,now-shift.start),shift.end-shift.start),progress=Math.min(1,elapsed/(shift.end-shift.start)),pace=target*progress;if(target>0&&amount>=pace)return{liveStatus:"Achieve",statusTone:"green",shiftStart:hh(shift.start),shiftEnd:hh(shift.end),shiftProgress:progress,paceTarget:pace};if(amount>0)return{liveStatus:"Need Push",statusTone:"yellow",shiftStart:hh(shift.start),shiftEnd:hh(shift.end),shiftProgress:progress,paceTarget:pace};return{liveStatus:elapsed<120?"Belum Produktif":"Need Push",statusTone:elapsed<120?"neutral":"yellow",shiftStart:hh(shift.start),shiftEnd:hh(shift.end),shiftProgress:progress,paceTarget:pace}}

type StaffBase={id:string;name:string;position:string;share:number;status:string;configShare?:number};
const MONTHS:Record<string,number>={JANUARI:1,FEBRUARI:2,MARET:3,APRIL:4,MEI:5,JUNI:6,JULI:7,AGUSTUS:8,SEPTEMBER:9,OKTOBER:10,NOVEMBER:11,DESEMBER:12};
function monthFromRow(r:unknown[]){for(const c of r.slice(0,3)){const m=MONTHS[up(c)];if(m)return m}return 0}function pad(v:number){return String(v).padStart(2,"0")}
function scheduleIndex(date:string,month:number,days:number[]){const[y,m,d]=date.split("-").map(Number);if(!month||!days.includes(d))return-1;const wrap=days.findIndex((v,i)=>i<days.length-1&&v>days[i+1]);for(let i=0;i<days.length;i++){if(days[i]!==d)continue;let cm=month;if(wrap>=0&&i<=wrap)cm=month===1?12:month-1;let cy=y;if(month===1&&cm===12)cy=y-1;if(cm===m&&`${cy}-${pad(cm)}-${pad(d)}`===date)return i}return-1}
function carry(r:unknown[],idx:number){const value=up(r[3+idx]);if(value)return value;for(let i=idx-1;i>=0;i--){const prev=up(r[3+i]);if(!prev)continue;if(/TRAINING|MEETING|CUTI|SAKIT|SICK|LEAVE|\bRO\b/.test(prev))return prev;break}return"IN"}
async function scheduleFor(date:string,email:string,key:string,cacheRows:ReturnType<typeof cacheFromValues>[]):Promise<StaffBase[]>{const[weekly,snaps]=await getSheetRanges(MASTER_ID,["'Schedule weekly'!A1:Q600",`'${SNAPSHOT}'!A2:G5000`],email,key);const nameToId=new Map(cacheRows.map(r=>[up(r.name),r.id]));for(let r=0;r<weekly.length-2;r++){const month=monthFromRow(weekly[r]);if(!month)continue;const days=weekly[r].slice(3,10).map(v=>n(v)).filter(v=>v>0&&v<=31);if(days.length!==7)continue;const di=scheduleIndex(date,month,days);if(di<0)continue;let h=r+1;if(up(weekly[h]?.[1])!=="NAME"&&up(weekly[h]?.[0])!=="NIK")h=r+2;if(up(weekly[h]?.[1])!=="NAME"&&up(weekly[h]?.[0])!=="NIK")continue;const staff:StaffBase[]=[];for(let i=h+1;i<Math.min(weekly.length,h+24);i++){const row=weekly[i],name=s(row?.[1]);if(!name)continue;const first=up(row?.[0]);if(/^D0\d{2}|FULL|OFF|CUTI/.test(first)||/^D0\d{2}|FULL|OFF|CUTI/.test(up(name)))break;const position=s(row?.[2])||"Sales Assistant";let id=s(row?.[0]);if(!/^\d{6,10}$/.test(id))id=nameToId.get(up(name))||"";if(id)staff.push({id,name,position,share:0,status:carry(row,di)})}if(staff.length)return staff}const locked=snaps.filter(r=>iso(r[0])===date).map(r=>({id:s(r[1]),name:s(r[2]),position:s(r[3])||"Sales Assistant",share:0,status:up(r[5])||"IN"})).filter(r=>r.id);if(locked.length)return locked;return cacheRows.map(r=>({id:r.id,name:r.name,position:"Sales Assistant",share:0,status:"IN"}))}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Koneksi Google Sheets belum tersedia"},{status:500});const date=req.nextUrl.searchParams.get("date")||today();try{const[cacheRaw,config]=await Promise.all([getSheetRanges(MASTER_ID,[`'${CACHE}'!A2:Z20000`],email,key).then(x=>x[0]||[]),getSheetRanges(SOURCE_ID,["Config!A1:AZ120"],email,key).then(x=>x[0]||[])]),cleared=cacheRaw.some(r=>up(r[25])==="CLEARED"),fast=cacheRaw.map(cacheFromValues).filter(r=>r.date===date&&r.store===STORE);if(!fast.length&&!cleared)return legacyDailyGET(req);const hasMismatch=fast.some(r=>r.validation==="MISMATCH");if(hasMismatch){console.warn("Fast processing mismatch detected",date);const legacy=await legacyDailyGET(req),json=await legacy.json();return NextResponse.json({...json,fastSource:"legacy-fallback",fastWarning:"Fast processing mismatch detected"},{status:legacy.status,headers:{"cache-control":"no-store"}})}
 const schedule=await scheduleFor(date,email,key,fast),shareById=new Map<string,number>(),shareByName=new Map<string,number>();for(const r of config.slice(27,55)){if(up(r[7])!==STORE||!s(r[8])||!s(r[9])||isSupervisor(s(r[10])))continue;const sh=shareValue(r[11]);shareById.set(s(r[8]),sh);shareByName.set(up(r[9]),sh)}const dailyTargetRow=config.find(r=>s(r[22]).toLowerCase()===weekday(date)),target={amount:n(dailyTargetRow?.[23]),accessories:n(dailyTargetRow?.[24]),vas:n(dailyTargetRow?.[25])};const scheduled=schedule.filter(p=>!isSupervisor(p.position)).map(p=>({...p,configShare:shareById.get(p.id)??shareByName.get(up(p.name))??0})),eligible=scheduled.filter(p=>!unavailable(p.status)&&p.configShare!>0),sumShare=eligible.reduce((a,p)=>a+(p.configShare||0),0),withShares=scheduled.map(p=>({...p,share:!unavailable(p.status)&&sumShare>0?(p.configShare||0)/sumShare:0})),fastById=new Map(fast.map(r=>[r.id,r]));
 const make=(p:StaffBase)=>{const c=fastById.get(p.id),targets={amount:target.amount*p.share,accessories:target.accessories*p.share,vas:target.vas*p.share},base={...p,amount:c?.amount||0,accessories:c?.accessories||0,vas:c?.vas||0,qty:c?.qty||0,invoices:c?.invoices||0,upt:c?.upt||0,atv:c?.atv||0,targets,lob:{iphone:c?.iphone||0,mac:c?.mac||0,ipad:c?.ipad||0,watch:c?.watch||0,airpods:c?.airpods||0},vasDetail:{qoala:{qty:c?.qoalaQty||0,value:c?.qoalaValue||0},telkomsel:{qty:c?.telkomselQty||0,value:c?.telkomselValue||0},xl:{qty:c?.xlQty||0,value:c?.xlValue||0},indosat:{qty:c?.indosatQty||0,value:c?.indosatValue||0}}};return{...base,...liveMeta(date,p.status,base.amount,targets.amount)}};
 const staff=withShares.filter(p=>!unavailable(p.status)).map(make),ids=new Set(staff.map(x=>x.id));for(const c of fast){if(ids.has(c.id))continue;staff.push(make({id:c.id,name:c.name,position:isOnline(c.name)?"Online Sales":"Sales (non-schedule)",share:0,status:isOnline(c.name)?"ONLINE":"EXTRA"}))}
 const total=staff.reduce((a,r)=>({amount:a.amount+r.amount,accessories:a.accessories+r.accessories,vas:a.vas+r.vas,qty:a.qty+r.qty,invoices:a.invoices+r.invoices}),{amount:0,accessories:0,vas:0,qty:0,invoices:0}),warning=fast.some(r=>r.validation!=="MATCH")?fast.map(r=>r.validation).find(v=>v!=="MATCH")||"PENDING":"";return NextResponse.json({date,staff,total:{...total,target:target.amount,accTarget:target.accessories,vasTarget:target.vas,upt:total.invoices?total.qty/total.invoices:0},snapshotLocked:date<=today(),targetSnapshotLocked:date<=today(),salesSnapshotLocked:!cleared,scheduleSource:"MASTER DATA M238 → Schedule weekly",scheduleRemark:cleared?"SPW aktif sudah di-clear. Menunggu upload SPW baru.":"Daily Sales memakai fast processed source; schedule dan target tetap logic existing.",targetSource:"Config W:Z daily target + Config L28:L staff share",storage:"MASTER DATA M238 → DAILY SALES CACHE",fastSource:cleared?"cleared":"primary",fastWarning:cleared?"Menunggu upload SPW baru":warning||undefined,fastUpdatedAt:fast[0]?.updatedAt},{headers:{"cache-control":"no-store"}})}catch(e){console.error("daily-fast",e);return legacyDailyGET(req)}}
