import {NextRequest,NextResponse} from "next/server";
import {ensureSheet,getSheetRanges} from "@/lib/google-sheets";

const SALES:Record<string,string>={
  "2025":"1NnRW70VyrtV8c89_M08gTnOGbtzeldSy8gL-gm4GjJ0",
  "2026":"151Qfrz3RZnDMgZjKOPt5s_aS-zscSiOTCWodbUDWM1k"
};
const OPS="1BjLDXdi_5BgZCUUJAKba-xYRFf0RDmRTT0FW1be03WE";
const STORE_CODES=["M117","M118","M124","M127","M217","M227","M238","M255","M264"] as const;
const STORE_NAMES:Record<string,string>={
 M117:"DIGIMAP PLAZA SENAYAN",M118:"Digimap Pondok Indah Mall 3",M124:"DIGIMAP PACIFICPLACE",M127:"DIGIMAP APP Lotte Avenue",M217:"DIGIMAP BLOK - M PLAZA",M227:"Digimap Aeon Tanjung Barat",M238:"Digimap AAR Pondok Indah Mall 2",M255:"Digimap Antasari Place",M264:"Digimap Plaza Semanggi"
};
const MONTHS=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const PROMO_HEADERS=["Active","Title","Description","Period","Scope","Updated At"];
type Row=unknown[];
type WeekAgg={key:string;label:string;start:string;end:string;store:string;achievement:number;device:number;acc:number;vas:number;qty:number;transactions:Set<string>;iphone:number;macbook:number;ipad:number;watch:number;airpods:number;qoala:number};
let cache=new Map<string,{at:number,data:unknown}>();
const CACHE_MS=5*60*1000;

function n(v:unknown){if(typeof v==="number")return Number.isFinite(v)?v:0;const s=String(v??"").trim();if(!s)return 0;const cleaned=s.replace(/\s/g,"").replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",",".").replace(/[^0-9.-]/g,"");const x=Number(cleaned);return Number.isFinite(x)?x:0}
function dateKey(v:unknown){if(typeof v==="number"&&v>20000){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return d.toISOString().slice(0,10)}const s=String(v??"").trim();let m=s.match(/^(\d{2})[-/](\d{2})[-/](\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:""}
function containsVoucher(row:Row){return row.some(v=>String(v??"").toUpperCase().includes("VOUCHER"))}
function emptyFocus(){return{iphone17promax:0,iphone17pro:0,iphone17:0,iphone15:0,iphone16:0,iphoneAir:0,macbookAirM5:0,macbookNeo:0,ipad11:0,awSe3:0}}
function addFocus(f:ReturnType<typeof emptyFocus>,desc:string,qty:number){const q=Math.max(0,qty),d=desc.replace(/\s+/g," ");if(/IPHONE 17 PRO\s*MAX|IPHONE 17 PROMAX/.test(d))f.iphone17promax+=q;else if(/IPHONE 17 PRO/.test(d))f.iphone17pro+=q;else if(/IPHONE 17(?!\s*(PRO|AIR))/.test(d))f.iphone17+=q;if(/IPHONE 15/.test(d))f.iphone15+=q;if(/IPHONE 16/.test(d))f.iphone16+=q;if(/IPHONE\s+AIR/.test(d))f.iphoneAir+=q;if(/MACBOOK AIR/.test(d)&&/M5/.test(d))f.macbookAirM5+=q;if(/MACBOOK NEO/.test(d))f.macbookNeo+=q;if(/IPAD\s+11/.test(d))f.ipad11+=q;if(/(APPLE\s+WATCH|AW).*SE\s*3|WATCH\s+SE\s*3/.test(d))f.awSe3+=q}
function emptyStore(code:string){return{code,name:STORE_NAMES[code],target:{amount:0,device:0,acc:0,vas:0},achievement:0,device:0,acc:0,vas:0,qty:0,transactions:0,traffic:0,cvr:0,upt:0,atv:0,nps:null as number|null,point:0,focus:emptyFocus()}}
function parseTargets(rows:Row[],monthName:string){const out:Record<string,{amount:number;device:number;acc:number;vas:number}>={};let active=false;for(const row of rows){const first=String(row[0]??"").trim();if(MONTHS.some(m=>m.toLowerCase()===first.toLowerCase())){active=first.toLowerCase()===monthName.toLowerCase();continue}if(!active)continue;if(String(row[1]??"").trim().toLowerCase()==="total")break;if(STORE_CODES.includes(first as any))out[first]={amount:n(row[3]),device:n(row[4]),acc:n(row[5]),vas:n(row[6])}}return out}
function parseNps(rows:Row[],monthIdx:number){const out:Record<string,number|null>={};for(const row of rows.slice(2)){const label=String(row[0]??"");const code=STORE_CODES.find(c=>label.includes(c));if(code){const v=row[monthIdx+1];out[code]=v===undefined||v===null||v===""?null:n(v)}}return out}
function parseStaffMaster(rows:Row[]){const out:Record<string,{id:string;name:string;store:string;position:string;share:number}>={};for(const row of rows.slice(1)){const store=String(row[0]??"").trim();if(!STORE_CODES.includes(store as any))continue;const id=String(row[1]??"").replace(/\.0$/,"").trim(),name=String(row[2]??"").trim(),position=String(row[3]??"").trim(),share=n(row[4]);if(name){const key=id||`${store}|${name.toUpperCase()}`;out[key]={id:key,name,store,position,share}}}return out}
function parseTraffic(rows:Row[],period:string){const month:Record<string,number>=Object.fromEntries(STORE_CODES.map(c=>[c,0]));const daily:Record<string,Record<string,number>>={};const header=rows[0]??[];const cols=Object.fromEntries(STORE_CODES.map(code=>[code,header.findIndex(v=>String(v??"").includes(code))]));for(const row of rows.slice(1)){const d=dateKey(row[0]);if(!d||!d.startsWith(period))continue;daily[d]=daily[d]??{};for(const code of STORE_CODES){const value=cols[code]>=0?n(row[cols[code]]):0;daily[d][code]=value;month[code]+=value}}return{month,daily}}
function parsePromos(rows:Row[]){return rows.slice(1).map((r,i)=>({id:String(i+1),active:String(r[0]??"").trim().toLowerCase(),title:String(r[1]??"").trim(),description:String(r[2]??"").trim(),period:String(r[3]??"").trim(),scope:String(r[4]??"").trim(),updatedAt:String(r[5]??"").trim()})).filter(x=>x.title&&!["false","0","no","inactive"].includes(x.active))}
function accessoryIncentive(unitAmount:number){return unitAmount<1315000?15000:30000}
function qoalaIncentive(unitAmount:number){return unitAmount<1315000?15000:50000}
function weekInfo(date:string){const d=new Date(`${date}T00:00:00Z`),anchor=new Date("2026-06-28T00:00:00Z"),days=Math.floor((d.getTime()-anchor.getTime())/86400000),weekIndex=Math.floor(days/7);let qIndex=Math.floor(weekIndex/13),w=((weekIndex%13)+13)%13+1;let q=4+qIndex;while(q<1)q+=4;while(q>4)q-=4;const start=new Date(anchor.getTime()+(weekIndex*7)*86400000),end=new Date(start.getTime()+6*86400000);return{key:`${start.toISOString().slice(0,10)}`,label:`Week ${w} Q${q}`,start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}}

export async function GET(req:NextRequest){
 const period=req.nextUrl.searchParams.get("period")||"2026-09";
 if(!/^(2025|2026)-(0[1-9]|1[0-2])$/.test(period))return NextResponse.json({error:"Periode tidak valid"},{status:400});
 const year=period.slice(0,4),salesId=SALES[year];if(!salesId)return NextResponse.json({error:"Source tahun tidak tersedia"},{status:400});
 const force=req.nextUrl.searchParams.has("refresh")||req.nextUrl.searchParams.has("t");const cached=cache.get(period);if(!force&&cached&&Date.now()-cached.at<CACHE_MS)return NextResponse.json(cached.data,{headers:{"x-jakarta1-cache":"HIT"}});
 const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});
 try{
  await ensureSheet(OPS,"Promo Board",PROMO_HEADERS,email,key);
  const [salesRangesData,ops]=await Promise.all([
   getSheetRanges(salesId,STORE_CODES.map(c=>`'${c}'!A:O`),email,key),
   getSheetRanges(OPS,["'Master Data'!Y1:AE160","'Master Data'!S1:X130","'Data Nps'!A:M","'Data Traffic'!A:J","'Promo Board'!A:F"],email,key)
  ]);
  const monthIdx=Number(period.slice(5,7))-1,monthName=MONTHS[monthIdx],targets=year==="2026"?parseTargets(ops[0]??[],monthName):{},staffMaster=parseStaffMaster(ops[1]??[]),nps=year==="2026"?parseNps(ops[2]??[],monthIdx):{},traffic=year==="2026"?parseTraffic(ops[3]??[],period):{month:Object.fromEntries(STORE_CODES.map(c=>[c,0])),daily:{}};
  const stores=Object.fromEntries(STORE_CODES.map(c=>[c,emptyStore(c)])) as Record<string,ReturnType<typeof emptyStore>>;
  const storeTx:Record<string,Set<string>>=Object.fromEntries(STORE_CODES.map(c=>[c,new Set<string>()]));
  const daily:Record<string,Record<string,any>>={},monthly:Record<string,Record<string,number>>={},weeks=new Map<string,WeekAgg>();
  const staffAgg:Record<string,any>={};
  const daysInMonth=new Date(Number(year),monthIdx+1,0).getDate();
  for(let si=0;si<STORE_CODES.length;si++){
   const code=STORE_CODES[si],rows=(salesRangesData[si]??[]) as Row[],store=stores[code];store.target=targets[code]??store.target;store.nps=nps[code]??null;
   for(const row of rows.slice(1)){
    const d=dateKey(row[1]);if(!d||!d.startsWith(`${year}-`))continue;
    if(containsVoucher(row))continue;
    const staffId=String(row[4]??"").replace(/\.0$/,"").trim(),staffName=String(row[5]??"").trim(),cat=String(row[6]??"").toUpperCase(),group=String(row[8]??"").toUpperCase(),desc=String(row[10]??"").toUpperCase(),qty=n(row[11]),amount=n(row[13]),txn=String(row[14]??"").trim();
    const ym=d.slice(0,7);monthly[ym]=monthly[ym]??Object.fromEntries(STORE_CODES.map(c=>[c,0]));monthly[ym][code]+=amount;
    const wi=weekInfo(d),wkKey=`${wi.key}|${code}`,wk=weeks.get(wkKey)??{...wi,store:code,achievement:0,device:0,acc:0,vas:0,qty:0,transactions:new Set<string>(),iphone:0,macbook:0,ipad:0,watch:0,airpods:0,qoala:0};weeks.set(wkKey,wk);wk.achievement+=amount;wk.qty+=qty;if(txn)wk.transactions.add(`${code}|${txn}`);if(group==="DEVICES")wk.device+=amount;else if(group==="ACCESSORIES")wk.acc+=amount;else if(group==="VAS")wk.vas+=amount;if(cat.includes("IPHONE"))wk.iphone+=qty;else if(cat==="MAC"||cat.includes("MACBOOK"))wk.macbook+=qty;else if(cat.includes("IPAD"))wk.ipad+=qty;else if(cat.includes("WATCH"))wk.watch+=qty;else if(cat.includes("AIRPODS"))wk.airpods+=qty;if(cat.includes("PROTEKSI")||desc.includes("QOALA"))wk.qoala+=amount;
    if(!d.startsWith(period))continue;
    store.achievement+=amount;store.qty+=qty;if(txn)storeTx[code].add(`${code}|${txn}`);if(group==="DEVICES")store.device+=amount;else if(group==="ACCESSORIES")store.acc+=amount;else if(group==="VAS")store.vas+=amount;addFocus(store.focus,desc,qty);
    daily[d]=daily[d]??{};const dr=daily[d][code]??{date:d,store:code,target:(store.target.amount||0)/daysInMonth,achievement:0,vas:0,qty:0,transactions:new Set<string>(),iphone:0,macbook:0,ipad:0,watch:0,airpods:0,qoala:0,telkomsel:0,xl:0,indosat:0};daily[d][code]=dr;dr.achievement+=amount;dr.qty+=qty;if(txn)dr.transactions.add(`${code}|${txn}`);if(group==="VAS")dr.vas+=amount;if(cat.includes("IPHONE"))dr.iphone+=qty;else if(cat==="MAC"||cat.includes("MACBOOK"))dr.macbook+=qty;else if(cat.includes("IPAD"))dr.ipad+=qty;else if(cat.includes("WATCH"))dr.watch+=qty;else if(cat.includes("AIRPODS"))dr.airpods+=qty;if(cat.includes("PROTEKSI")||desc.includes("QOALA"))dr.qoala+=amount;if(desc.includes("TELKOMSEL")||desc.includes("HALO"))dr.telkomsel+=amount;if(desc.includes("XL")||desc.includes("MYPRIO"))dr.xl+=amount;if(desc.includes("INDOSAT")||desc.includes("IM3"))dr.indosat+=amount;
    const master=staffMaster[staffId]||Object.values(staffMaster).find(s=>s.store===code&&s.name.trim().toUpperCase()===staffName.toUpperCase());if(master){const sk=master.id,sa=staffAgg[sk]??{...master,amount:0,qty:0,tx:new Set<string>(),iphone:0,macbook:0,ipad:0,watch:0,qoala:0,incentive:{iphone:0,macbook:0,ipad:0,watch:0,accessories:0,qoala:0}};staffAgg[sk]=sa;sa.amount+=amount;sa.qty+=qty;if(txn)sa.tx.add(`${code}|${txn}`);if(cat.includes("IPHONE")){sa.iphone+=qty;sa.incentive.iphone+=Math.max(0,qty)*15000}else if(cat==="MAC"||cat.includes("MACBOOK")){sa.macbook+=qty;sa.incentive.macbook+=Math.max(0,qty)*30000}else if(cat.includes("IPAD")){sa.ipad+=qty;sa.incentive.ipad+=Math.max(0,qty)*10000}else if(cat.includes("WATCH")){sa.watch+=qty;sa.incentive.watch+=Math.max(0,qty)*10000}if(group==="ACCESSORIES"&&qty>0){const unit=amount/qty;sa.incentive.accessories+=accessoryIncentive(unit)*qty}if((cat.includes("PROTEKSI")||desc.includes("QOALA"))&&qty>0){sa.qoala+=amount;const unit=amount/qty;sa.incentive.qoala+=qoalaIncentive(unit)*qty}}
   }
  }
  STORE_CODES.forEach(code=>{const s=stores[code];s.transactions=storeTx[code].size;s.traffic=traffic.month[code]??0;s.cvr=s.traffic?s.transactions/s.traffic*100:0;s.upt=s.transactions?s.qty/s.transactions:0;s.atv=s.transactions?s.achievement/s.transactions:0;s.point=s.target.amount?s.achievement/s.target.amount*100:0});
  const storeList=STORE_CODES.map(c=>stores[c]),areaTarget=storeList.reduce((a,s)=>({amount:a.amount+s.target.amount,device:a.device+s.target.device,acc:a.acc+s.target.acc,vas:a.vas+s.target.vas}),{amount:0,device:0,acc:0,vas:0}),area=storeList.reduce((a,s)=>({achievement:a.achievement+s.achievement,device:a.device+s.device,acc:a.acc+s.acc,vas:a.vas+s.vas,qty:a.qty+s.qty,transactions:a.transactions+s.transactions,traffic:a.traffic+s.traffic}),{achievement:0,device:0,acc:0,vas:0,qty:0,transactions:0,traffic:0});const validNps=storeList.map(s=>s.nps).filter((v):v is number=>typeof v==="number");
  const allDates=Array.from({length:daysInMonth},(_,i)=>`${period}-${String(i+1).padStart(2,"0")}`),dailyRows=allDates.flatMap(date=>STORE_CODES.map(code=>{const r=daily[date]?.[code],target=(stores[code].target.amount||0)/daysInMonth,tx=r?.transactions.size??0,tr=(traffic.daily as any)[date]?.[code]??0;return{date,store:code,target,achievement:r?.achievement??0,vas:r?.vas??0,upt:tx?(r?.qty??0)/tx:0,traffic:tr,transactions:tx,cvr:tr?tx/tr*100:0,iphone:r?.iphone??0,macbook:r?.macbook??0,ipad:r?.ipad??0,watch:r?.watch??0,airpods:r?.airpods??0,qoala:r?.qoala??0,telkomsel:r?.telkomsel??0,xl:r?.xl??0,indosat:r?.indosat??0}}));
  const staff=Object.values(staffAgg).map((s:any)=>{const target=(targets[s.store]?.amount??0)*s.share,upt=s.tx.size?s.qty/s.tx.size:0,point=target?s.amount/target*100:0,total=Object.values(s.incentive).reduce((a:number,b:any)=>a+n(b),0);return{id:s.id,name:s.name,store:s.store,position:s.position,target,achievement:s.amount,iphone:s.iphone,macbook:s.macbook,ipad:s.ipad,watch:s.watch,qoala:s.qoala,upt,point,status:point>=100?"Achieved":point>=80?"On Track":"Need Push",incentive:{...s.incentive,total}}}).sort((a:any,b:any)=>b.achievement-a.achievement);
  const weekly=[...weeks.values()].map(w=>({key:w.key,label:w.label,start:w.start,end:w.end,store:w.store,achievement:w.achievement,device:w.device,acc:w.acc,vas:w.vas,qty:w.qty,transactions:w.transactions.size,upt:w.transactions.size?w.qty/w.transactions.size:0,iphone:w.iphone,macbook:w.macbook,ipad:w.ipad,watch:w.watch,airpods:w.airpods,qoala:w.qoala})).sort((a,b)=>a.start.localeCompare(b.start));
  const monthComparison=Array.from({length:12},(_,i)=>{const p=`${year}-${String(i+1).padStart(2,"0")}`,r=monthly[p]??{};return{period:p,total:STORE_CODES.reduce((a,c)=>a+(r[c]??0),0),stores:Object.fromEntries(STORE_CODES.map(c=>[c,r[c]??0]))}});
  const promos=parsePromos(ops[4]??[]);
  const result={period,year,monthName,stores:storeList,area:{target:areaTarget,...area,cvr:area.traffic?area.transactions/area.traffic*100:0,achievementPct:areaTarget.amount?area.achievement/areaTarget.amount*100:0,upt:area.transactions?area.qty/area.transactions:0,atv:area.transactions?area.achievement/area.transactions:0,nps:validNps.length?validNps.reduce((a,b)=>a+b,0)/validNps.length:null},daily:dailyRows,staff,weekly,monthComparison,promos,meta:{storeCodes:STORE_CODES,storeNames:STORE_NAMES,salesSource:`Data Compile ${year} per Store Code`,incentiveRules:{accessories:"< Rp1.315.000 = Rp15.000/item; >= Rp1.315.000 = Rp30.000/item",qoala:"< Rp1.315.000 = Rp15.000/policy; >= Rp1.315.000 = Rp50.000/policy"}}};
  cache.set(period,{at:Date.now(),data:result});return NextResponse.json(result,{headers:{"cache-control":"public, max-age=60, stale-while-revalidate=240","x-jakarta1-cache":"MISS"}})
 }catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca data Jakarta 1"},{status:500})}
}
