import {NextRequest,NextResponse} from "next/server";
import * as XLSX from "xlsx";
import {appendSheetValues,clearAndWrite,getSheetRanges} from "@/lib/google-sheets";

const DASHBOARD_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk";
type Cell=string|number|boolean;
function cleanText(v:unknown){return String(v??"").replace(/\u00a0/g," ").replace(/[\u0000-\u001f\u007f]+/g," ").replace(/\s+/g," ").trim()}
function normalizeCell(cell:XLSX.CellObject|undefined):Cell{if(!cell||cell.v===undefined||cell.v===null)return "";if(cell.t==="d"&&cell.v instanceof Date){const d=cell.v;return `${String(d.getUTCDate()).padStart(2,"0")}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${d.getUTCFullYear()}`}if(cell.t==="n"&&cell.z&&XLSX.SSF.is_date(cell.z))return XLSX.SSF.format("dd-mm-yyyy",Number(cell.v));if(cell.t==="n")return Number(cell.v);if(cell.t==="b")return Boolean(cell.v);return cleanText(cell.v)}
function rowsFromSheet(ws:XLSX.WorkSheet){if(!ws["!ref"])return [] as Cell[][];const range=XLSX.utils.decode_range(ws["!ref"]),rows:Cell[][]=[];for(let r=range.s.r;r<=range.e.r;r++){const row=Array.from({length:9},(_,i)=>normalizeCell(ws[XLSX.utils.encode_cell({r,c:range.s.c+i})]));if(row.some(v=>String(v).trim()))rows.push(row)}return rows}
function score(rows:Cell[][]){const flat=rows.flat().map(v=>String(v)),stockTitle=flat.some(v=>/Stock Position Report/i.test(v)),store=flat.some(v=>/Store\s*:/i.test(v)),productRows=rows.filter(r=>typeof r[6]==="number"&&typeof r[7]==="number"&&typeof r[8]==="number").length;return(stockTitle?1000:0)+(store?300:0)+productRows*3+Math.min(rows.length,500)}
export async function POST(req:NextRequest){const e=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,k=process.env.GOOGLE_PRIVATE_KEY;if(!e||!k)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const f=(await req.formData()).get("file");if(!(f instanceof File)||!/\.xlsx?$/i.test(f.name))return NextResponse.json({error:"Pilih file SOH Excel .xlsx/.xls"},{status:400});const wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true,cellNF:true,raw:true}),candidates=wb.SheetNames.map(name=>({name,rows:rowsFromSheet(wb.Sheets[name])})).filter(x=>x.rows.length).map(x=>({...x,score:score(x.rows)})).sort((a,b)=>b.score-a.score),report=candidates[0];if(!report)return NextResponse.json({error:"File SOH kosong"},{status:400});if(report.score<300)return NextResponse.json({error:"Format SOH tidak dikenali. Pastikan file adalah Stock Position Report asli."},{status:400});if(report.rows.length>10000)return NextResponse.json({error:"Data SOH melebihi 10.000 baris"},{status:400});await clearAndWrite(MASTER_ID,"'SOH'!A1:I10000","'SOH'!A1",report.rows,e,k,"RAW");const[masterRows]=await getSheetRanges(MASTER_ID,[`'SOH'!A1:I${Math.max(1,report.rows.length)}`],e,k),numericProductRows=masterRows.filter(row=>typeof row[6]==="number"&&typeof row[7]==="number"&&typeof row[8]==="number").length;if(numericProductRows===0)return NextResponse.json({error:"MASTER DATA M238 menerima file SOH, tetapi Price/Qty/Total tidak terbaca sebagai angka. Data dashboard lama tidak diubah."},{status:422});await clearAndWrite(DASHBOARD_ID,"'RAW StockPosition'!F:N","'RAW StockPosition'!F1",masterRows,e,k,"RAW");const ts=new Date().toISOString();await appendSheetValues(MASTER_ID,"'UPLOAD LOG'!A:H",[[ts,"SOH",f.name,report.rows.length,"","","SUCCESS",report.name]],e,k);return NextResponse.json({ok:true,rows:report.rows.length,sheet:report.name,uploadedAt:ts,numericProductRows,masterSheet:"MASTER DATA M238 / SOH",storage:"master-google-sheets-native-values",message:`SOH berhasil dikonversi ke MASTER DATA M238 lalu disinkronkan ke dashboard (${report.rows.length} baris).`})}catch(err){return NextResponse.json({error:err instanceof Error?err.message:"Upload SOH gagal"},{status:500})}}
