import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";
const ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const txt=(v:unknown)=>String(v??"").trim();
const num=(v:unknown)=>typeof v==="number"?v:Number(txt(v).replace(/\./g,"").replace(/,/g,".").replace(/[^0-9.-]/g,""))||0;
function iso(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=txt(v);if(/^\d{2}-\d{2}-\d{4}$/.test(x)){const[d,m,y]=x.split("-");return`${y}-${m}-${d}`}if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);return""}
type T={qty:number;value:number};const fresh=():T=>({qty:0,value:0});const add=(t:T,q:number,v:number)=>{t.qty+=q;t.value+=v};
function lob(category:string,scheme:string,brand:string){const c=category.toUpperCase(),s=scheme.toUpperCase(),b=brand.toUpperCase();if(s==="DEVICES"){if(c==="IPHONE")return"iphone";if(c==="MAC")return"mac";if(c==="IPAD")return"ipad";if(c==="APPLE WATCH")return"watch"}if(s==="ACCESSORIES"&&c==="AIRPODS"&&b==="APPLE")return"airpods";return""}
export async function GET(req:NextRequest){const date=req.nextUrl.searchParams.get("date")||new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).format(new Date());const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY;if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});try{const[rows]=await getSheetRanges(ID,["'Data Copas'!A2:M50000"],email,key);const map=new Map<string,{id:string;name:string;amount:number;qty:number;lob:Record<string,T>}>();for(const r of rows){if(iso(r[0])!==date)continue;const id=txt(r[1]),name=txt(r[2]),scheme=txt(r[12]),category=txt(r[9]),brand=txt(r[10]);if(!name)continue;const q=num(r[7]),v=num(r[8]);let rec=map.get(id||name);if(!rec){rec={id:id||name,name,amount:0,qty:0,lob:{iphone:fresh(),mac:fresh(),ipad:fresh(),watch:fresh(),airpods:fresh()}};map.set(id||name,rec)}rec.amount+=v;rec.qty+=q;const k=lob(category,scheme,brand);if(k)add(rec.lob[k],q,v)}return NextResponse.json({date,staff:[...map.values()]},{headers:{"Cache-Control":"no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal membaca Daily LOB"},{status:500})}}
