"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
const today=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const monthName=(p:string)=>{const[y,m]=p.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(y,m-1,1))};
const dateLabel=(d:string)=>{const[y,m,x]=d.split("-").map(Number);return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(y,m-1,x))};
export default function Page(){
 const[date,setDate]=useState(today()),[period,setPeriod]=useState(today().slice(0,7)),[staff,setStaff]=useState<any[]>([]),[dailyRows,setDailyRows]=useState<any[]>([]),[monthRows,setMonthRows]=useState<any[]>([]),[staffId,setStaffId]=useState(""),[cx,setCx]=useState(0),[member,setMember]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{const[d,day,month]=await Promise.all([fetch(`/api/data?period=${date.slice(0,7)}`).then(r=>r.json()),fetch(`/api/cx-member?period=${date.slice(0,7)}&date=${date}`).then(r=>r.json()),fetch(`/api/cx-member?period=${period}`).then(r=>r.json())]);setStaff(d.staff||[]);setDailyRows(day.rows||[]);setMonthRows(month.rows||[])},[date,period]);
 useEffect(()=>{void load()},[load]);
 const recap=useMemo(()=>{const map=new Map<string,{date:string;cx:number;member:number;staff:number}>();for(const r of monthRows){const v=map.get(r.date)||{date:r.date,cx:0,member:0,staff:0};v.cx+=Number(r.cx)||0;v.member+=Number(r.member)||0;v.staff+=1;map.set(r.date,v)}return [...map.values()].sort((a,b)=>b.date.localeCompare(a.date))},[monthRows]);
 const totals=useMemo(()=>recap.reduce((a,r)=>({cx:a.cx+r.cx,member:a.member+r.member}),{cx:0,member:0}),[recap]);
 const save=async()=>{const p=staff.find(x=>x.id===staffId);if(!p)return;setBusy(true);setNotice("");try{const r=await fetch("/api/cx-member",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date,staffId:p.id,name:p.name,cx,member})}),j=await r.json();if(!r.ok){setNotice(j.error||"Data gagal disimpan.");return}setCx(0);setMember(0);setStaffId("");setPeriod(date.slice(0,7));setNotice("Data CX & New Member berhasil disimpan.");await load()}finally{setBusy(false)}};
 return <main className="min-h-screen bg-slate-50 p-5 sm:p-8"><a href="/" className="font-bold text-blue-600">← Dashboard</a><div className="mx-auto mt-6 max-w-6xl space-y-5"><div><h1 className="text-3xl font-black">NPS / CX & Member</h1><p className="text-slate-500">Input harian dan rekap pencapaian CX & New Member per bulan.</p></div>{notice&&<div className="rounded-xl border bg-white p-3 font-bold">{notice}</div>}
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label><b className="mb-2 block text-sm">Tanggal</b><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-12 w-full rounded-xl border px-3"/></label><label><b className="mb-2 block text-sm">Nama Staff</b><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="h-12 w-full rounded-xl border px-3"><option value="">Pilih Staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="rounded-2xl border-2 border-blue-200 bg-blue-50 p-5"><span className="text-xs font-black uppercase tracking-wider text-blue-600">CATEGORY: CX</span><b className="mt-2 block text-lg">Jumlah CX Hari Ini</b><input type="number" min={0} value={cx} onChange={e=>setCx(+e.target.value)} className="mt-3 h-14 w-full rounded-xl border bg-white px-4 text-xl font-black"/></label><label className="rounded-2xl border-2 border-emerald-200 bg-emerald-50 p-5"><span className="text-xs font-black uppercase tracking-wider text-emerald-600">CATEGORY: NEW MEMBER</span><b className="mt-2 block text-lg">Jumlah New Member Hari Ini</b><input type="number" min={0} value={member} onChange={e=>setMember(+e.target.value)} className="mt-3 h-14 w-full rounded-xl border bg-white px-4 text-xl font-black"/></label></div><button disabled={!staffId||busy} onClick={save} className="mt-5 w-full rounded-xl bg-blue-600 py-3 font-bold text-white disabled:opacity-40">{busy?"Menyimpan...":"Simpan CX & New Member"}</button></section>
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-black">Rekap Bulanan</h2><p className="text-sm text-slate-500">Pencapaian seluruh staff per hari.</p></div><label><b className="mb-1 block text-xs uppercase text-slate-500">Filter Bulan</b><input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="h-11 rounded-xl border px-3"/></label></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-100 p-4"><span className="text-xs font-bold text-slate-500">PERIODE</span><b className="mt-1 block">{monthName(period)}</b></div><div className="rounded-xl bg-blue-50 p-4"><span className="text-xs font-bold text-blue-600">TOTAL CX</span><b className="mt-1 block text-2xl">{totals.cx}</b></div><div className="rounded-xl bg-emerald-50 p-4"><span className="text-xs font-bold text-emerald-600">TOTAL NEW MEMBER</span><b className="mt-1 block text-2xl">{totals.member}</b></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Tanggal</th><th className="p-3 text-right">Staff Input</th><th className="p-3 text-right">CX</th><th className="p-3 text-right">New Member</th></tr></thead><tbody>{recap.length?recap.map(r=><tr className="border-t" key={r.date}><td className="p-3 font-bold">{dateLabel(r.date)}</td><td className="p-3 text-right">{r.staff}</td><td className="p-3 text-right font-bold">{r.cx}</td><td className="p-3 text-right font-bold">{r.member}</td></tr>):<tr><td colSpan={4} className="p-6 text-center text-slate-400">Belum ada data pada bulan ini.</td></tr>}</tbody><tfoot><tr className="border-t-2 bg-slate-50 font-black"><td className="p-3">TOTAL BULAN</td><td></td><td className="p-3 text-right">{totals.cx}</td><td className="p-3 text-right">{totals.member}</td></tr></tfoot></table></div></section>
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">Detail Staff • {dateLabel(date)}</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Nama Staff</th><th className="text-right">CX</th><th className="text-right">New Member</th></tr></thead><tbody>{dailyRows.length?dailyRows.map((r,i)=><tr className="border-t" key={i}><td className="p-2 font-bold">{r.name}</td><td className="text-right">{r.cx}</td><td className="text-right">{r.member}</td></tr>):<tr><td colSpan={3} className="p-5 text-center text-slate-400">Belum ada input pada tanggal ini.</td></tr>}</tbody></table></div></section></div></main>;
}