import {NextRequest,NextResponse} from "next/server";
import {getSheetRanges} from "@/lib/google-sheets";

const SOURCE_ID="160_eV8tgT_eXH7dm8pHP8Ym2mHPyHhlFpKWf1bpxEP0";
const MASTER_ID="1v479QFSArfDb-vt_YRGcw0o4RhYxCzFlNOCH6VMvCSk";
const s=(v:unknown)=>String(v??"").trim();
const up=(v:unknown)=>s(v).toUpperCase();
const n=(v:unknown)=>typeof v==="number"?v:Number(s(v).replace(/[^0-9.-]/g,""))||0;
function iso(v:unknown){if(typeof v==="number")return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);const x=s(v);if(/^\d{4}-\d{2}-\d{2}/.test(x))return x.slice(0,10);if(/^\d{1,2}[/-]\d{1,2}[/-]\d{4}$/.test(x)){const[d,m,y]=x.split(/[/-]/);return`${y}-${m.padStart(2,"0")}-${d.padStart(2,"0")}`}return""}
function addDays(date:string,days:number){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function diffDays(a:string,b:string){return Math.max(1,Math.round((new Date(`${b}T00:00:00Z`).getTime()-new Date(`${a}T00:00:00Z`).getTime())/86400000)+1)}
function weekday(date:string){return new Intl.DateTimeFormat("id-ID",{weekday:"long",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00Z`)).toLowerCase()}
type Row={date:string;invoice:string;description:string;type:string;qty:number;amount:number;category:string;brand:string;scheme:string;vendor:string;article:string};
function parse(r:unknown[]):Row{return{date:iso(r[0]),invoice:s(r[3]),article:s(r[4]),description:s(r[5]),type:s(r[6]),qty:n(r[7]),amount:n(r[8]),category:up(r[9]),brand:up(r[10]),scheme:up(r[12]),vendor:up(r[13])}}
function valid(r:Row){return !!r.date&&r.scheme!=="VOUCHER"&&!up(`${r.article} ${r.description}`).includes("VOUCHER")}
function kind(r:Row){if(r.scheme==="VAS")return"vas";if(r.scheme==="ACCESSORIES")return"accessories";if(r.scheme==="DEVICES")return"device";return"other"}
function product(r:Row){if(r.brand!=="APPLE")return"";if(r.scheme==="ACCESSORIES"&&r.category==="AIRPODS")return"airpods";if(r.scheme!=="DEVICES")return"";if(r.category==="IPHONE")return"iphone";if(r.category==="MAC"||r.category==="MACBOOK")return"mac";if(r.category==="IPAD")return"ipad";if(r.category==="APPLE WATCH"||r.category==="WATCH")return"watch";return""}
function vasType(r:Row){const t=up(`${r.article} ${r.brand} ${r.vendor} ${r.description}`);if(t.includes("QOALA")||t.includes("KLA"))return"qoala";if(t.includes("TELKOMSEL")||t.includes("TSL"))return"telkomsel";if(t.includes("INDOSAT")||t.includes("IDT"))return"indosat";if(/(^|\s)XL(\s|$)|XXL/.test(t))return"xl";return""}
function aggregate(rows:Row[],date:string,target:number,traffic:number){const day=rows.filter(r=>r.date===date&&valid(r)),invoices=new Set(day.map(r=>r.invoice).filter(Boolean));let amount=0,device=0,accessories=0,vas=0,qty=0,mac=0,ipad=0,iphone=0,watch=0,airpods=0,qoala=0,telkomsel=0,indosat=0,xl=0;for(const r of day){amount+=r.amount;qty+=r.qty;const k=kind(r);if(k==="device")device+=r.amount;else if(k==="accessories")accessories+=r.amount;else if(k==="vas")vas+=r.amount;const p=product(r);if(p==="mac")mac+=r.qty;else if(p==="ipad")ipad+=r.qty;else if(p==="iphone")iphone+=r.qty;else if(p==="watch")watch+=r.qty;else if(p==="airpods")airpods+=r.qty;if(k==="vas"){const v=vasType(r);if(v==="qoala")qoala+=r.amount;else if(v==="telkomsel")telkomsel+=r.amount;else if(v==="indosat")indosat+=r.amount;else if(v==="xl")xl+=r.amount}}const inv=invoices.size,upt=inv?qty/inv:0,atv=inv?amount/inv:0,cvr=traffic?inv/traffic*100:0;return{date,amount,target,device,accessories,vas,invoices:inv,qty,upt,atv,cvr,traffic,mac,ipad,iphone,watch,airpods,qoala,telkomsel,indosat,xl}}

export async function GET(req:NextRequest){const email=process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key=process.env.GOOGLE_PRIVATE_KEY,from=req.nextUrl.searchParams.get("from")||"",to=req.nextUrl.searchParams.get("to")||"";if(!email||!key)return NextResponse.json({error:"Google Sheets belum dikonfigurasi"},{status:503});if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return NextResponse.json({error:"Range tanggal tidak valid"},{status:400});try{const days=diffDays(from,to),prevEnd=addDays(from,-1),prevStart=addDays(prevEnd,-days+1);const trafficPromise=getSheetRanges(MASTER_ID,["'Traffic'!A2:B1000"],email,key);const[config,dateRows]=await getSheetRanges(SOURCE_ID,["Config!A1:AZ120","'Data Copas'!A2:A50000"],email,key);const indexes:number[]=[];for(let i=0;i<dateRows.length;i++){const d=iso(dateRows[i]?.[0]);if(d&&d>=prevStart&&d<=to)indexes.push(i+2)}let parsed:Row[]=[];if(indexes.length){const[first,last]=[Math.min(...indexes),Math.max(...indexes)];const[detail]=await getSheetRanges(SOURCE_ID,[`'Data Copas'!A${first}:S${last}`],email,key);parsed=(detail||[]).map(parse).filter(r=>r.date>=prevStart&&r.date<=to&&valid(r))}const[trafficRows]=await trafficPromise,trafficMap=new Map<string,number>();for(const r of trafficRows||[]){const d=iso(r[0]);if(d)trafficMap.set(d,n(r[1]))}const dates=[...new Set(parsed.filter(r=>r.date>=from&&r.date<=to).map(r=>r.date))].sort();const rows=dates.map(date=>{const targetRow=config.find(r=>s(r[22]).toLowerCase()===weekday(date));return aggregate(parsed,date,n(targetRow?.[23]),trafficMap.get(date)||0)});const previousTotal=parsed.filter(r=>r.date>=prevStart&&r.date<=prevEnd).reduce((a,r)=>a+r.amount,0);return NextResponse.json({from,to,rows,previousTotal,generatedAt:new Date().toISOString(),source:"Data Copas + Config + Traffic"},{headers:{"cache-control":"private, max-age=20, stale-while-revalidate=40"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Gagal memuat Daily Summary"},{status:500,headers:{"cache-control":"no-store"}})}}
